### ISSUE TITLE
Able to generate entity bundles with unmet dependencies

### ISSUE THREAD

**Issue by allgood2386** [hechoendrupal/drupal-console#1067]
https://gist.github.com/allgood2386/4e9191af141de235088b

That is my usage. Should console allow you to generate configuration that has unmet dependencies? As far as I can tell in d8 the behavior is that modules don't get enabled unless they are defined in the module.yml file. So creating a content type with the defaults in a minimal install will build you a content type that can't be enabled.

**Comment by enzolutions** [comment]
@allgood2386 could you try enabling your module with latest version of Drupal console

```
$ drupal module:install testmodule
```

To check what error you get if you get an error.

**Comment by enzolutions** [comment]
We cannot reproduce the error with current version
