### ISSUE TITLE
Generate logger channels?

### ISSUE THREAD

**Issue by wizonesolutions** [hechoendrupal/drupal-console#1075]
https://www.drupal.org/node/2270941#specific-channel

Similar to `generate:service`, but no `class` — only a `parent`. I don't think the service questionnaire allows this right now.

**Comment by jmolivas** [comment]
We currently do not have this generator, but this feature can be added.

**Comment by darol100** [comment]
:+1:  For this feature been implemented.

**Comment by LOBsTerr** [comment]
PR https://github.com/hechoendrupal/drupal-console/pull/3841
PR for translation https://github.com/hechoendrupal/drupal-console-en/pull/196

**Comment by LOBsTerr** [comment]
Merged
