### ISSUE TITLE
Integrate with PhpStorm's Command Line Tool

### ISSUE THREAD

**Issue by tsvenson** [hechoendrupal/drupal-console#1079]
After I got Composer and Drush working from the built in Command Line Tool (CLI/Shell) in PhpStorm I got blown away with the workflow and productivity improvements it resulted in.

Looking at the list of out-of-box support in the screenshot below, my guestimate is that most of what Drupal Console need to integrate already _should_ be there. To start with, the code generation features in Drupal Console would feels like top of the list of benefits this would have.

![phpstorm_cli](https://cloud.githubusercontent.com/assets/444455/10582633/11027086-7689-11e5-9be1-15dc4c98cfc6.png)

[Enabling a Command Line Tool](https://www.jetbrains.com/phpstorm/help/enabling-a-command-line-tool.html) is a good starting point for information about how to create new Command Line Tools for PhpStorm.

I'm going to try making this work, but have still a lot of learning and configuration to do before my setup is ready for a serious attempts.

One thing I would like to test if it is possible is if it is possible to take advantage of Drupal Console directly from the "File/New Project...", "File/New..." (files and folders) and "Code/Generate..." features without having to go via the terminal. That would be something...

If anyone else is interested of collaborating on this, let me know and we can have a talk about it.

**Comment by danielrose28** [comment]
@tsvenson I love PhpStorm as well as DrupalConsole, so anything I can do to help with integration testing, let me know and I'd be happy to. I'm somewhat of a newbie with D8 and its code but I'm always willing to learn and help whenever I can.

**Comment by tsvenson** [comment]
@danielrose28, thanks for showing interest in this idea. I'm a newbie too, however we can certainly work something out together.

Some is already working, try the following:

1. Open Settings/Tools/Command Line Tool Support
2. Click the + to add a new tool
3. ![selection_004](https://cloud.githubusercontent.com/assets/444455/10652901/87f3f93a-785a-11e5-85cd-0eb83ba54abf.png)
4. ![selection_005](https://cloud.githubusercontent.com/assets/444455/10652949/f22e45bc-785a-11e5-9d65-f96d3518f507.png)

My installation is following the instructions on [Drupal Console](http://drupalconsole.com/) website.

When I did the above PhpStorm found 17 commands, same as when running "drupal list" in the terminal outside a drupal site installation, and automatically generated an editable .xml file:

![selection_006](https://cloud.githubusercontent.com/assets/444455/10653020/a4dd1b0c-785b-11e5-94e1-73c36bbd345a.png)

You need to Apply before the .xml can be opened.

I haven't done much testing how well this works yet, but this is a good start.

**Comment by tsvenson** [comment]
Oh, and Drupal Console does work just fine from the integrated terminal, including generating code and stuff, without any special configuration needs. Just as in a OS shell.

At least on my Ubuntu 14.04 desktop.

**Comment by danielrose28** [comment]
Sounds good. I'll try this out and see how it works on my Mac. I'm running El Capitan.

**Comment by darol100** [comment]
I think this issue should be part of phpStorm forum ? So they might be able to support DrupalConsole out-box ?

**Comment by tsvenson** [comment]
@darol100 Have been thinking about that too and down the line I'm sure they are open for making that happen.

However, that does also puts some constraints on the development to maintain compatibility with the code needed in PhpStorm to make Drupal Console integration simplified for users. Thus that call is @jmolivas to make.

**Comment by tsvenson** [comment]
@darol100 @jmolivas 

I did have a look over at the Jetbrains devnet community and found [Command Line Tools Support](https://devnet.jetbrains.com/docs/DOC-1230) with lots of interesting information, however the doc is from 2011 so I can't really tell how current it is.

I'm going to spend a little tile later to research their resources and see what I can come up with. My main goal is to find information about how to give Drupal Console the current project path so it can recognize the drupal site being worked on. That feels like the most important obstacle to solf first.

**Comment by tsvenson** [comment]
FYI: I've created [Improve Drupal Console integration with PhpStorm Command Line Tool](https://devnet.jetbrains.com/thread/473800) over at Jetbrains discussion forum asking for pointers to documentation and tutorials for how to develop Command Line Tool integration, specifically for how to give Drupal Console the current project path.

**Comment by tsvenson** [comment]
Done some digging, but can only find bits and pieces so it will take some time for a n00b like me to get the full picture.

I did stumble on [PhpStormSupportBundle](https://github.com/marphi/PhpStormSupportBundle] and in [GenerateCommandToolsConfigCommand.php](https://github.com/marphi/PhpStormSupportBundle/blob/master/Command/GenerateCommandToolsConfigCommand.php) there are some code that might help us get the missing commands generated. The project is four years old though...

**Comment by danielrose28** [comment]
@tsvenson Just wanted to clarify, I'm able to run Drupal Console from within the built-in terminal in PhpStorm. I ran 'drupal generate:module' and created a test module. After module was created I was able to see the new directory and files in the project tree. I'm assuming that there is some more configuration that you are trying to set up, other than just being able to run DrupalConsole from the terminal? 

I saw your post on the jetbrains site as well. I'll copy this over there so we can get some chatter going on that forum as well.

This is awesome though. Just being able to run DrupalConsole from within PhpStorm, along with Drush. This is making my day. :)

**Comment by tsvenson** [comment]
@danielrose28 Saw that, replied too.

From what I learned so far the built-in terminal and CLT are to very different things, the terminal in practice being an embedded shell.

**Comment by danielrose28** [comment]
Hope that was ok to post there as well? I might not keep posting to both places though. Just wanted it to get some traffic to see if others would chime in as well. 

That makes sense. I guess I hadn't thought of that.

**Comment by tsvenson** [comment]
@danielrose28 Sure, I don't mind. If fact, I enjoy the collaboration as it is nice to know you're keen on getting this working too.

For two newbies like us, this is a great learning experience as well :)

**Comment by danielrose28** [comment]
@tsvenson My apologies, I just realized you had already confirmed this in an earlier comment:

"Oh, and Drupal Console does work just fine from the integrated terminal, including generating code and stuff, without any special configuration needs. Just as in a OS shell."

**Comment by tsvenson** [comment]
Sorry for being quiet about progress on this issue, just that there is so much I still have to learn to comprehend everything. Some of the "magic" is beginning to make sense and I have a proposal plan for how to address this.

After going over the source code in PhpStormSupportBundle linked to in [this comment](https://github.com/hechoendrupal/DrupalConsole/issues/1079#issuecomment-150727237) I'm going to use it to create a test-project on my account with it as model. I think that is a better approach than a pull request to here as PhpStorm 10 is announced and I also have a feeling Jetbrain will be positive to the idea of creating bundled support like for Drush. Thus a separate codebase seems logical for now.

As I'm still aspiring to reach rookie-level a timeframe for this happening is impossible, but I will post here when I have a sensible codebase committed.

**Comment by enzolutions** [comment]
@tsvenson that will be awesome when you acomplish this goal

**Comment by tsvenson** [comment]
@enzolutions Think I took on more than I could chew here. Am still working hard on learning OOP, D8 API and more gaps in coding skills I have to overcome.

If anyone want to jump in and help out/take over to make this feature happen feel free :)

**Comment by enzolutions** [comment]
@tsvenson don't worry I guess that is the current situation for any Drupal developer nowadays. in order to find more colaborators for this task. Do you think you can document and share the current status of this task?

**Comment by tsvenson** [comment]
@enzolutions Sure, give me the weekend to go over my findings. Should I update the OP or in a comment like this?

**Comment by enzolutions** [comment]
Hi @tsvenson is this comment is OK, I don't understand what you mean with OP.

**Comment by tsvenson** [comment]
@enzolutions Oh, I suppose OP is a drupal.org thing. It stands for Original Post. Basically I wonder if I should update the initial issue text (the OP) at the top with the current information or in a comment to it like this one.

**Comment by enzolutions** [comment]
Just is a comment, I will try to help you from your latest status

**Comment by tsvenson** [comment]
Great stuff, I'll get something up Monday latest as I got a few things going on in the weekend. Thanks.

**Comment by darol100** [comment]
:+1:  for this been implemented. @tsvenson any new updates on with this feature ?

**Comment by jmolivas** [comment]
@darol100 I will take info from this issue and create a doc page to make people aware of this feature.

**Comment by tsvenson** [comment]
I'm so sorry guys, had completely forgot about this as I am currently consumed by other things.

In short, the [ PhpStormSupportBundle](https://github.com/hechoendrupal/DrupalConsole/issues/1079#issuecomment-150727237) is the best source I have found, it does for Symfony what we want for Drupal. As I see it, the only better option would be to develop a proper PhpStorm plugin to host at Jetbrains and that later can be made into bundled support.

Hope this helps, otherwise please ask specifics and I'll answer with what I know. Fine pinging me on IRC too, where I am usually logged in.

**Comment by Saphyel** [comment]
I have an error on the last version of PHPStorm using the dev version of console.
```
Failed to parse command output Details
```
in Details there is only a big xml... @tsvenson  when you have time would you mind to update your 1st comment in this issue?

**Comment by mikeshiyan** [comment]
Just to add to previous comment: Parsing fails because of [extra warning message after XML structure](https://github.com/hechoendrupal/DrupalConsole/blob/1.0.0-beta2/src/Application.php#L237). It prevents parsing the output of the "list" command. I've opened an issue: #2442 

To add to whole issue: From my experience with integrated Drush CLT I can say that it too does not provide project-specific commands for auto-completion, only global ones - declared by Drush itself and provided by globally installed drush extensions (like in ~/.drush/). No matter whether I add the tool for global or project visibility.

So it's the issue of CLT support in common - it should gather project-specific commands too in some way.
Guess this issue can be closed(

**Comment by tsvenson** [comment]
@Saphyel I haven't really looked at this since my last comment Dec 6, so not really sure what to update in the OP. Sorry.

**Comment by Glisa060** [comment]
You can integrate drupal console in the following way. I will use cmder from Laragon wamp.
Go to phpstorm setting/tools/terminal.

Set start directory as C:\laragon\www\drupal\vendor\bin

Shell path: choose you shell. Can be cmd from windows, git bash or anything else really. 

These setting are not global so it will not affect your other projects.
