### ISSUE TITLE
Move generated entity interfaces from src/ to src/Entity

### ISSUE THREAD

**Issue by bojanz** [hechoendrupal/drupal-console#1088]
I've had a number of conversations in Barcelona and elsewhere about correct namespacing.
One of the ideas that came out of them is to move the entity interfaces from src/ to src/Entity. 
It's much more logical to have the interface next to the implementing class, and it follows alexpott's idea that src/ should have as little files as possible.

Commerce, Address, Profile already do this. Making Console follow as well would truly establish the standard.

Give me a +1 and I'll send a PR.

**Comment by omero** [comment]
:+1: :D

**Comment by jmolivas** [comment]
:+1:  I Like the idea of grouping classes on a common `src/Entity` namespace.

**Comment by enzolutions** [comment]
@jmolivas this is different to the work I did moving all command to their own namespace?

**Comment by darol100** [comment]
This issue is for `generate:entity:config` command ?

@bojanz , Any updates on your PR ?

:+1:

**Comment by AaronMcHale** [comment]
Not that I'm a fan of dragging up old closed issues, but this is the first time I've used Drupal Console, and it's great, already saved me a bunch of time, but I was surprised at first to see it putting entity interfaces under the Entity namespace.  A lot of core modules (such as User and Node) along with the guides and docs on Drupal.org all indicate that Interfaces in general are meant to live under src, and in a way I can see the logic to doing that, so would it not make more sense for Drupal Console to follow those same conventions?

**Comment by LOBsTerr** [comment]
@AaronMcHale I agree it is better to follow common standards 

https://github.com/hechoendrupal/drupal-console/pull/3960

**Comment by LOBsTerr** [comment]
Merged
