### ISSUE TITLE
[translate] Drupal Console into Samuel Jackson Language 

### ISSUE THREAD

**Issue by darol100** [hechoendrupal/drupal-console#1106]
## Problem / Motivation

We should translate Drupal Console to Samuel Jackson language. This will help us to demonstrate how easy can be to translate languages in Drupal console.  
## Solution

We should use http://slipsum.com/ to use some of his common sentences and  translate console.

We can also use this video as part of the translation https://www.youtube.com/watch?v=c0LBi1MHoaU

**Comment by omero** [comment]
jajaja it will be awesome :+1: XD

**Comment by darol100** [comment]
@omero I started working on it, on a fork https://github.com/darol100/drupalconsole

**Comment by seanr** [comment]
+1 for "I am sick of these motherfucking modules in this motherfucking application"  ROFL!

**Comment by phenaproxima** [comment]
Thank you! That's one of mine :)

**Comment by phenaproxima** [comment]
So, serious point for a sec -- the problem with using slipsum.com is that a) those are pretty much completely random sentences that SLJ has said in his various movies and cannot be meaningfully connected to Drupal Console, and b) slipsum.com only generates about 4 distinct paragraphs, yet Console has a LOT more text than that.

Personally, I think that Console should still be useful, if hopped-up on attitude, under an SLJ translation. Maybe we all ought to mainline SLJ movies until we have a collection of one-liners (watch them with your IDEs open!) that we can integrate into Console and, more to the point, translate them into strings that *sound* like SLJ, even if he didn't actually say them.

I'm totally on board with this. ;-)

**Comment by jmolivas** [comment]
Closing this one, @phenaproxima thanks for the idea of separating the languages.
