### ISSUE TITLE
[generate:entity:content] Ask if entity forms are needed for entity

### ISSUE THREAD

**Issue by wizonesolutions** [hechoendrupal/drupal-console#1120]
I just made an entity that is more of an internal entity than one the end user needs to administer. I noticed that Drupal Console generated entity forms and permissions automatically, so I needed to remove those manually in order not to use them.

Would be great if there was a "Generate entity forms? [Yes/No]" step, default could still be yes.

**Comment by darol100** [comment]
:+1:
