### ISSUE TITLE
The base url isn't setup

### ISSUE THREAD

**Issue by bojanz** [hechoendrupal/drupal-console#1171]
Generating a link:
$link = $container->get('url_generator')->generate('entity.commerce_store.edit_form', ['commerce_store' => $store->id()], TRUE); 
gives me a relative url because for some reason the $base_url isn't known when running inside Console.

The same thing works fine in the web UI.

**Comment by LOBsTerr** [comment]
@bojanz Tried to reproduce. It looks like it works now as it should. Can you confirm ?

**Comment by harold20** [comment]
Hi @bojanz How can I reproduce it?
