### ISSUE TITLE
[php:interactive] PHP interactive session

### ISSUE THREAD

**Issue by g3r4** [hechoendrupal/drupal-console#1359]
Dear drupal console team:

Is is possible to have a command that would allow us to run an interactive session with our Drupal 8 site bootstrapped ?

Thanks

**Comment by enzolutions** [comment]
@g3r4 could you provide more details about what is an interactive session?

**Comment by darol100** [comment]
@enzolutions this is the same functionality as drush as with this command  `core-cli (php)` "Open an interactive shell on a Drupal site."

**Comment by jmolivas** [comment]
The `shell` command provides this functionality 
![drupal-shell-sandcamp](https://user-images.githubusercontent.com/366275/28761235-06ef29a2-7562-11e7-8b41-962571a65423.png)
