### ISSUE TITLE
[container:debug] add a `--tag` option

### ISSUE THREAD

**Issue by gido** [hechoendrupal/drupal-console#1386]
It would be really helpful to get a list of services tagged with a specific tag. Like the symfony console had.

Here is would be my last real world usage:

```
$ drupal container:debug --tag=twig
$ drupal container:debug --tag=breadcrumb_builder
$ drupal container:debug --tag=event_subscriber
```

I started looking for a way to achieve this:
1. But it's roughly hard to get an instance of the `ContainerBuilder` (that contain tags information).
2. Then I tried something with [DrupalKernelInterface::getCachedContainerDefinition()](https://api.drupal.org/api/drupal/core%21lib%21Drupal%21Core%21DrupalKernelInterface.php/function/DrupalKernelInterface%3A%3AgetCachedContainerDefinition/8) but [OptimizedPhpArrayDumper](https://api.drupal.org/api/drupal/core%21lib%21Drupal%21Component%21DependencyInjection%21Dumper%21OptimizedPhpArrayDumper.php/8) and [PhpArrayDumper](https://api.drupal.org/api/drupal/core%21lib%21Drupal%21Component%21DependencyInjection%21Dumper%21PhpArrayDumper.php/class/PhpArrayDumper/8) don't include tags informations (for good reason, tag is not useful for compiled Container).

What do you think about this feature ?
Maybe one of you have an idea or a hint to get this done ?

**Comment by jmolivas** [comment]
I do totally :+1: on this feature.

We can probably take a look a this old PR https://github.com/hechoendrupal/DrupalConsole/pull/60 and if make sense try to resurrect it.

I will take a look at this and also ask at IRC if there is way to achieve this.

**Comment by egulias** [comment]
Hi There.
I've been looking for ways on doing this within Drupal 8 DIC and I've failed to find a way to do it. Drupal's DIC implementation does not makes easy nor accessible to find the "dump" of the container necessary for the inspection. More over I've heard rumours of Drupal working on a DIC that will not generate any files.
If at any given point you find a way to have the DIC dump for inspection take a look at [TagDebug](https://github.com/egulias/TagDebug), a small lib for filtering DIC tags (which is used by the ListenersDebugCommand)

**Comment by gido** [comment]
Hi @egulias,

Thanks for your feedback!
I looked at your PR and the lib and stuck at the same place than you.

About the rumours, I heard the same and find https://www.drupal.org/node/2497243

**Comment by egulias** [comment]
So maybe the definitions are now accessible from the DB using `API changes

* Introduces DrupalKernel::getCachedContainerDefinition() as new public method.`?

**Comment by jmolivas** [comment]
@egulias @gido We can access the `getCachedContainerDefinition` from a `ContainerAwareCommand` Command class by using:
```
$kernelHelper = $this->getKernelHelper(); 
$kernel = $kernelHelper->getKernel();
$kernel->getCachedContainerDefinition();
```

**Comment by egulias** [comment]
Amazing!!
I've not looked at the code yet. But, can I mock that to test it without
whole Drupal?

**Comment by gido** [comment]
@jmolivas @egulias I tried `DrupalKernel::getCachedContainerDefinition()` but sadly the serialized data don't include service tags informations.

**Comment by LOBsTerr** [comment]
it was already implemented. Closing this issue. Feel free to reopen it.
