### ISSUE TITLE
[generate:entity:content] Add prompt questions to enable bundle support and more

### ISSUE THREAD

**Issue by smalot** [hechoendrupal/drupal-console#1390]
Current entity keys supported are : 

```
 *   entity_keys = {
 *     "id" = "id",
 *     "label" = "name",
 *     "uuid" = "uuid"
 *   },
```

Compared to those supported by `node` entity : 

```
 *   entity_keys = {
 *     "id" = "nid",
 *     "revision" = "vid",
 *     "bundle" = "type",
 *     "label" = "title",
 *     "langcode" = "langcode",
 *     "uuid" = "uuid",
 *     "status" = "status",
 *     "uid" = "uid",
 *   },
```

It should be very interesting to ask for : 
- do you want to support `versioning` ?
- do you want to support `bundle` ?

**Comment by smalot** [comment]
My fault, I didn't see the "--has-bundles" option.
Versioning is still a need

**Comment by UnbekanntesPferd** [comment]
So you can enable bundle support for a custom entity, but - correct me if I'm wrong - you can't create a bundle via console. generate:entity:bundle is only used for node bundles, correct?

**Comment by LOBsTerr** [comment]
@UnbekanntesPferd This issue we will handle in this ticket https://github.com/hechoendrupal/drupal-console/issues/3418

**Comment by LOBsTerr** [comment]
I'm closing the tickets, because the current implementation allow to generate bundles and revisions. Feel free to reopen it.
