### ISSUE TITLE
[config:edit] Respect the $EDITOR environment variable

### ISSUE THREAD

**Issue by cburschka** [hechoendrupal/drupal-console#1401]
I'm getting vim even though $EDITOR is set to nano. Even removing the line from the config file doesn't help, because it's hard-coded via `$config->get('application.editor', 'vi');`. That's probably kinda silly because it means the part of the code that's supposed to use the environment variable is unreachable.

``` php
        $editor = $config->get('application.editor', 'vi');

        if ($editor != '') {
            return trim($editor);
        }
       // this will never be reached:
        $processBuilder = new ProcessBuilder(array('bash'));
        $process = $processBuilder->getProcess();
        $process->setCommandLine('echo ${EDITOR:-${VISUAL:-vi}}');
```

**Comment by enzolutions** [comment]
Hi @cburschka 

Drupa Console editor configures in your file ~/.console/config.yml if you don't have this file just run

```
drupal init
```
