### ISSUE TITLE
[generate:composer] Composer.json Stand Alone

### ISSUE THREAD

**Issue by darol100** [hechoendrupal/drupal-console#1417]
### Problem / Motivation

`composer.json` can only be generate in DrupalConsole if the user needs to generate a new module, using the generate:module. However, we need to be able generate `composer.json` on an existing module without need of generate a module. In addition we should provide more options on writing the `composer.json`. Right now, the generation of `composer.json` assume many things instead of asking. The generation of composer.json assume all these without asking:

```
  "keywords": ["Drupal"],
  "homepage": "http://drupal.org/project/test2_module",
  "minimum-stability": "dev",
  "support": {
    "issues": "http://drupal.org/project/issues/test2_module",
    "source": "http://cgit.drupalcode.org/test2_module"
  }
```

All these things needs to be ask before the generate the `composer.json`.
### Solution
- We need to be able generate composer.json
- homepage, support, issues, irc, source, minimum-stability should not be assume because they might change base on where the user is been hosting or providing support.
- We need to be able to add the Authors (maintainers of the project)
-  We need to be able to add search and add under required libraries from packagist.org
- And the composer.json should looks something like this:

```
{
  "name": "drupal/mobile_detect",
  "description": "Mobile_Detect is a lightweight PHP class for detecting mobile devices.",
  "type": "drupal-module",
  "homepage": "http://drupal.org/project/mobile_detect",
  "authors": [
    {
      "name": "Matthew Donadio (mpdonadio)",
      "homepage": "https://www.drupal.org/u/mpdonadio",
      "role": "Maintainer"
    },
    {
      "name": "Darryl Norris (darol100)",
      "email": "admin@darrylnorris.com",
      "homepage": "https://www.drupal.org/u/darol100",
      "role": "Co-maintainer"
    }
  ],
  "support": {
    "issues": "http://drupal.org/project/mobile_detect",
    "irc": "irc://irc.freenode.org/drupal-contribute",
    "source": "http://cgit.drupalcode.org/mobile_detect"
  },
  "license": "GPL-2.0+",
  "minimum-stability": "dev",
  "require": {
    "mobiledetect/mobiledetectlib": "~2.8"
  }
}

```

**Comment by edutrul** [comment]
I am going to be working on this, please @jmolivas let's discuss a bit for this before I start the implementation

**Comment by novia713** [comment]
not my business, but ...
if we want so detailed composer.json generation ...
why not skip doing that with DC and 
let the user do a simple & effective «_composer init_»?

i doubt it worth the work to mimic exactly the behaviour of a _composer init_
that command already exists, we are not providing something now (in case of imitate it)

**Comment by edutrul** [comment]
I like the idea, What do you think @jmolivas ?

**Comment by darol100** [comment]
I was not aware of the `composer init`. 👍  for closing this issue and let user use composer instead.

**Comment by jmolivas** [comment]
the advantage of DC is because add values related to the module is been generated.

**Comment by novia713** [comment]
just to simplify...
what about passing the module info as arguments to «composer init»?
https://getcomposer.org/doc/03-cli.md#init

**Comment by jmolivas** [comment]
This is a really simple generator it just collect information already ask on the module generation and pass to this template => https://github.com/hechoendrupal/DrupalConsole/blob/master/templates/module/composer.json.twig

**Comment by jmolivas** [comment]
For this command you only need ask for module name, read description from Drupal Core and pass it to the same Twig template.

**Comment by darol100** [comment]
What about the `authors`,  `license` , `require` information ?

**Comment by jmolivas** [comment]
* `license` is already added to the template as `GPL-2.0+` 
* `require` is added as empty 
* `authors` we are missing this one on the template

**Comment by LOBsTerr** [comment]
Merged
