### ISSUE TITLE
hook_theme command

### ISSUE THREAD

**Issue by itsdarrylnorris** [hechoendrupal/drupal-console#1423]
### Problem / Motivation
#1422 I propose to remove hook_theme from `generate:module` because is an empty function. By removing this from the `generate:module` we need to add the ability of the user to generate hook_theme.
### Solution
- We need to be able to generate hook_theme on a stand a lone command.
- If there is an exiting hook_theme, this command should hook_theme instead of generating another hook_theme. Otherwise we will be running to the same issue as #1562 .

**Comment by enzolutions** [comment]
Closing this issue, because was fixed and recently tested with issue https://github.com/hechoendrupal/drupal-console/issues/1562
