### ISSUE TITLE
[generate:theme] Generate a library while generating a theme

### ISSUE THREAD

**Issue by darol100** [hechoendrupal/drupal-console#1433]
### Problem / Motivation

99.99% of the time if you are working on themes you will need to add the css/js to your project. That been said, I think once #1432 is been solve we should bundle that command with generate:theme.
### Solution

We need to be able to generate libraries when we are generating a theme.

**Comment by marcvangend** [comment]
This would be really nice to have indeed. In fact, when I first used generate:theme, I had a bit of a WTF moment when the .libraries.yml file wasn't there. I guess was expecting it to exist because generate:theme explicitly prompts `Enter the global styling library name [global-styling]:`.

**Comment by LOBsTerr** [comment]
It looks this task is out-of-date I have checked everything is properly generated. If you need something else please reopen it
