### ISSUE TITLE
[router:debug] should take a pattern as an argument

### ISSUE THREAD

**Issue by simesy** [hechoendrupal/drupal-console#1479]
The process of debugging a route can start with a URL...

`console router:debug --pattern=/admin/structure/migrate`

**Comment by jmolivas** [comment]
Like this idea :+1:

**Comment by simesy** [comment]
I may or may not be able to do a PR for this. I'm still getting my bearings with D8/Symfony.

**Comment by jmolivas** [comment]
I am more than glad to help you on creating the PR if you like.

**Comment by simesy** [comment]
This is what i have so far.

Looking in [DebugCommand.php](https://github.com/hechoendrupal/DrupalConsole/blob/master/src/Command/Router/DebugCommand.php) the `[router:debug]` command leans on `getRouteByNames()`, and this calls on `getRoutesByNames()` in core's [RouteProvider.php](https://api.drupal.org/api/drupal/core%21lib%21Drupal%21Core%21Routing%21RouteProvider.php/8).

RouteProvider.php also has another method called [getRoutesByPath()](https://api.drupal.org/api/drupal/core%21lib%21Drupal%21Core%21Routing%21RouteProvider.php/function/RouteProvider%3A%3AgetRoutesByPath/8), and this is what could be used to resolve a route path first.

**Comment by LOBsTerr** [comment]
PR https://github.com/hechoendrupal/drupal-console/pull/3913
PR Translation - https://github.com/hechoendrupal/drupal-console-en/pull/212
