### ISSUE TITLE
[router:debug] Should provide routename enhancer info

### ISSUE THREAD

**Issue by simesy** [hechoendrupal/drupal-console#1481]
Normally router:debug (eg `console router:debug views.ajax`) will show information about the controller. But the controller for many routes is defined in an enhancer.

Something like `console router:debug  entity.migration_group.list` should be able inspect the `route_enhancer.entity` and it's enhance method and list its defaults.

Hope this makes sense.

**Comment by jmolivas** [comment]
@simesy:  Do you have a link on the docs or a place in core where we can take a look how this is done.

**Comment by simesy** [comment]
No, I've only traced it visually through the code so far. I'll certainly provide that info as i come across it.

**Comment by LOBsTerr** [comment]
@simesy I tried to investigate this issue. I can't understand how this information can be used
Normally Enhancer provides the standard routes for entities, in your case:
```
 entity.migration_group.add_form -  /admin/structure/migrate/add                                                                                             
 entity.migration_group.delete_form - /admin/structure/migrate/manage/{migration_group}/delete                                                                 
 entity.migration_group.edit_form - /admin/structure/migrate/manage/{migration_group}                                                                        
 entity.migration_group.list - /admin/structure/migrate  
```
Is this what you expected to see here ?
Honestly, I can't think of a use case when you will need this information. Can you please shade some light here ?

**Comment by LOBsTerr** [comment]
I'm closing the issue, feel free to reopen it if you find more information
