### ISSUE TITLE
Allow plug-in generation for install profiles

### ISSUE THREAD

**Issue by krlucas** [hechoendrupal/drupal-console#1515]
In D8 install profiles have all the power of modules so in Drupal Console they should be available as an option for generate:plugin:*.

**Comment by darol100** [comment]
@krlucas , Can you provide an code example of how it should looks like ?

**Comment by krlucas** [comment]
@darol100,

Sure. Here's an install profile that provides a block plug-in. 
http://cgit.drupalcode.org/sandbox-krlucas-2637020/tree/

The plug-in structure is exactly the same as it is for modules.

**Comment by pfrenssen** [comment]
I need this too, we're building an install profile with custom code. I provided a fix in PR #1886.

**Comment by LOBsTerr** [comment]
@jmolivas we can closed. It was fixed

**Comment by jmolivas** [comment]
Closing this one. Feel free to re-open if still happening after updating to the latest version.
