### ISSUE TITLE
[drupal:list] Injecting the Drupal Aliases the list command

### ISSUE THREAD

**Issue by darol100** [hechoendrupal/drupal-console#1519]
### Problem / Motivation

The easier way to teach users how to use the aliases is going to be to providing them when they are looking for the commands. In Drupal Console we use the `drupal list` command to search all command where I think we should added the alias so the user can get uses to use them.

For instance `drupal cache:build (cr)`. 
### Solution
- We need to add the ability of injecting the aliases at the end of the each command example. Link this.... 

```
module
  module:download (md)    Download module or modules in application
 site
  site:debug(sd)         List all known local and remote sites.
  site:install(si)       Install a Drupal project
  site:new(sn)           Create a new Drupal project
```

**Comment by mikecrittenden** [comment]
+1 I was just looking at the help page for the `list` command to see if there was an option to show the alias for each command.

**Comment by jmolivas** [comment]
+1 on that format @darol100

**Comment by jmolivas** [comment]
Alias are shown now 
![drupal-list-alias-1](https://user-images.githubusercontent.com/366275/28761183-ae97a522-7561-11e7-8a12-46e1b3b23bf4.png)
![drupal-list-alias-2](https://user-images.githubusercontent.com/366275/28761182-ae9701b2-7561-11e7-934a-594f33943637.png)
