### ISSUE TITLE
[console] --db-prefix not optional

### ISSUE THREAD

**Issue by xendk** [hechoendrupal/drupal-console#1544]
Experimented with migrate but couldn't set up the migration as console insisted on an non-empty db-prefix.

![selection_129](https://cloud.githubusercontent.com/assets/229422/11925840/af676f1c-a7bf-11e5-845b-01531b11d45a.png)

Seems like the problem might stem from https://github.com/hechoendrupal/DrupalConsole/commit/b7597874bbc66c8db0c6460ae357b71536c87ffc which begs the question how many other commands might be broken.

**Comment by jmolivas** [comment]
@xendk: Which Drupal Console version are you currently using ?. 

We already fixed this, may you try latest version v0.9.10

**Comment by xendk** [comment]
```
~/s/x/web~>> drupal list
Drupal Console version 0.9.10
...
```

Installed just yesterday. The project is based on https://github.com/drupal-composer/drupal-project which installs 0.9.9, but I assume that it doesn't try to use that when I run the phar.

**Comment by jmolivas** [comment]
I tried `drupal/composer`and after `composer install` and running `vendor/bin/console` I have 0.9.10

**Comment by xendk** [comment]
Yeah, but when I'm running the phar version I installed in $HOME/bin, it should use that version (0.9.10), no?

**Comment by jmolivas** [comment]
Do you mind to paste the command + arguments and options `drupal migrate:setup` to tested locally.

**Comment by xendk** [comment]
I tried with:

```
drupal migrate:setup --db-type=mysql --db-host=xen8_database_1.docker --db-name=legacy --db-user=root --db-pass=root
```

But it kept asking for prefix anyway, so I tried to find some way of supplying an empty prefix.

**Comment by darol100** [comment]
I believe this issue was fixed already.

**Comment by xendk** [comment]
So I tried upgrading the console installed by drupal-composer to 0.9.10, and now it'll at least take an empty string when it asks.

So apparently, even though I'm using the phar I have installed in ~/bin, it manages to pull in commands defined by the console installed in the site (which is pulled in by the Drupal autoloader I suspect). This is unfortunate as it opens up for all kind of weird bugs due to mismatched versions, not to mention that users will report bugs mentioning the version of the global command, while the real buggy version is hidden. 

Secondly, is it really on purpose that it asks for parameters that have quite sensible default? 

Thirdly, I haven't been able to define the empty prefix using a command line argument. I'm aware of the `-n` switch, but it can't be right that you have to supply a switch on random commands to avoid interactive questions on commands that already have multiple arguments.

**Comment by jmolivas** [comment]
@xendk: I am aware of `drupal-composer/drupal-project` and I will give another try next week to check what you mentioned about the mismatched versions.

We add the option to allow empty string as you noticed.

The interactive mode asks for values for the not provided inline and as you noticed you can use `-n` alias of `--no-interact` option.

I saw you on the image you try using `--db-prefix=''` I will see if there is anything we can do related to that.

**Comment by jmolivas** [comment]
@xendk: I am aware of `drupal-composer/drupal-project` and I will give another try next week to check what you mentioned about the mismatched versions.

We add the option to allow empty string as you noticed.

The interactive mode asks for values for the not provided inline and as you noticed you can use `-n` alias of `--no-interact` option.

I saw you on the image you try using `--db-prefix=''` I will see if there is anything we can do related to that.

**Comment by LOBsTerr** [comment]
@jmolivas Is it still relevant or we can close it?

**Comment by jmolivas** [comment]
That option is optional 
https://github.com/hechoendrupal/drupal-console/blob/master/src/Command/Migrate/SetupCommand.php#L93-L98

Closing this one. Feel free to re-open if still happening after updating to the latest version.
