### ISSUE TITLE
[generate:entity:content] returns '[ERROR] Value "<modulename>" is invalid' for all input

### ISSUE THREAD

**Issue by lhridley** [hechoendrupal/drupal-console#1573]
<img width="1280" alt="screen shot 2015-12-23 at 9 26 15 am" src="https://cloud.githubusercontent.com/assets/153297/11978167/544c9582-a957-11e5-8f46-c959050699c0.png">
Running Drupal Console version 0.10.0, on DrupalVM.
Host machine runs Mac OS X Yosemite 10.10.5
Same error occurred on Debian Jessie VM running php 5.6.

System Info
 Drupal                         8.0.0-dev  
 Access to update.php           Protected  
 Configuration files            Protected  
 Cron maintenance tasks         Last run 1 hour 38 minutes ago  
 Database system                MySQL, MariaDB, Percona Server, or equivalent  
 Database system version        5.5.46-0ubuntu0.14.04.2-log  
 Database updates               Up to date  
 Drupal core update status      <a href="/admin/reports/updates">Unknown release date (version 8.0.1 available)</a>  
 Entity/field definitions       Up to date  
 File system                    Writable (<em>public</em> download method)  
 GD library                     2.1.1-dev  
 GD library PNG support         2.1.1-dev  
 Image toolkit                  gd  
 Module and theme update status <a href="/admin/reports/updates">No available releases found</a>  
 Node Access Permissions        Disabled  
 PHP                            5.6.16-2+deb.sury.org~trusty+1 (<a href="/admin/reports/status/php">more information</a>) 
 PHP extensions                 Enabled  
 PHP memory limit               -1 (Unlimited)  
 PHP OPcode caching             Not enabled  
 Search index progress          100% (0 remaining)  
 Trusted Host Settings          Not enabled  
 Twig C extension               Not available  
 Unicode library                PHP Mbstring Extension  
 Update notifications           Enabled  
 Upload progress                Not enabled  
 Web server  
 Hash salt                      9EGfY5za6zMzD1WKbEKmXcGuq_r8iQPUPTJzTI4K1KH2kNI266yXCuB6_NsWYclVIqQ6vypmbg  
 Drupal Console                 0.10.0                                                                                    

 Database connection
 Driver              mysql  
 Host                localhost  
 Database connection drupal  
 Port  
 Username            drupal  
 Password            drupal  
 Connection          mysql//drupal:drupal@localhost/drupal 

 Themes
 theme_default bartik 
 theme_admin   seven  

 Directories
 Site root directory      /var/www/drupalvm/drupal 
 Site temporary directory /tmp  
 Default theme directory  /core/themes/bartik  
 Admin theme directory    /core/themes/seven      

Drupal Console was running fine until running self-update to upgrade to verson 0.10.0.

**Comment by mnico** [comment]
Hi @lhridley, first you need to create the module with generate:module. The generate:entity:content command will not generate a new module but instead it would work with a module already created. 
Regards

**Comment by jmolivas** [comment]
@lhridley: yes @mnico is correct you must select a valid module name. 

If you want to generate a new module, you must use the `generate:module` command first.

I do believe we can improve this by:
- Updating message instead of `Enter the module name` use `Select module name from list:`
- Update error message `Invalid module selected`

**Comment by lhridley** [comment]
Thank you for responding, that explains the issue much more clearly.  Suggestion:  An update to the documentation would be great, to make it more clear that you must have a module created first.

**Comment by zkent** [comment]
I was confused by this also but I guess it makes sense in a way.  A single module may have X entities defined in it.  However, better docs/error message would be helpful.

**Comment by MajdiZ** [comment]
I think will be better if the message says pick module to generate the entity in or something like this

**Comment by LOBsTerr** [comment]
I think this issue can be closed, because it is quite old, We have updated the code. Now we use the autocomplete and if a user will pass parameter using options there will be error like this 
```
  There aren't any releases for module "module_name" 
```
