### ISSUE TITLE
[config:export:single] config-name into an array

### ISSUE THREAD

**Issue by darol100** [hechoendrupal/drupal-console#1707]
### Problem / Motivation

It will be nice we add the ability of supporting an array when with the chain command so when there are multiple export single it can be a little bit more clean. For instance...

Currently is like this 

![screen shot 2016-01-12 at 12 15 40 am](https://cloud.githubusercontent.com/assets/6808460/12258202/b402b6cc-b8c1-11e5-8576-f5d3c0821de5.png)

And instead it will be nice like this ...

![screen shot 2016-01-12 at 12 17 18 am](https://cloud.githubusercontent.com/assets/6808460/12258227/e08c103a-b8c1-11e5-83f3-a835b04561fa.png)
### Solution
- Add the ability of supporting multiple config-name so we can download multiples singles at the same time.

**Comment by jmolivas** [comment]
@darol100 :+1:  I will take of this.

**Comment by acbramley** [comment]
+1 for this feature.

**Comment by darol100** [comment]
@jmolivas Do you have a PR for this issue ?

**Comment by jmolivas** [comment]
I do have a branch, need to send the PR and I will by the end of this week.

**Comment by jmolivas** [comment]
We have been delaying this for long time, lets take care about it during DrupalCon New Orleans sprints.

**Comment by darol100** [comment]
@jmolivas Do you still have this PR ? If so can you upload it so I can look at it and maybe even work on it.

**Comment by jmolivas** [comment]
@darol100 seems could coordinate with @bpresles tha is working on a similar feature https://github.com/hechoendrupal/DrupalConsole/pull/2965

**Comment by harold20** [comment]
This is already implemented in the current version 1.8.0
