### ISSUE TITLE
[generate:entity:config] Throws fatal error after trying to create entity

### ISSUE THREAD

**Issue by tamerzg** [hechoendrupal/drupal-console#1719]
Use generate:entity:config to create new config entity, clear the cache, go to /admin/structure/{your_new_config_entity} and try to save it. This will throw fatal error

Drupal\Component\Plugin\Exception\PluginNotFoundException: The "" entity type does not exist. in Drupal\Core\Entity\EntityTypeManager->getDefinition() (line 130 of /Library/WebServer/Documents/drupal-8.0.1/core/lib/Drupal/Core/Entity/EntityTypeManager.php).

**Comment by darol100** [comment]
@tamerzg , What version of Drupal Console? And I'm assuming that you are running Drupal 8.0.1?

**Comment by tamerzg** [comment]
Its reproducable with both 8.0.1 and 8.0.2. I am using latest version of Drupal Console v0.10.3

**Comment by darol100** [comment]
I'm running a git version of DrupalConsole few hours from the release 0.10.3 (which, we should be running the same version). And I did the following steps and could not replicate your issue.

- [generate:module] and use all default questions
- [generate:entity:config] and use all default questions
- Enable the module
- Clear Cache

Then I go to `/admin/structure/default_entity`

And everything seem to be right ...

<img width="435" alt="screen shot 2016-01-13 at 8 30 23 am" src="https://cloud.githubusercontent.com/assets/6808460/12300351/ebe688de-b9cf-11e5-8382-c11df125b3c2.png">

I try this out on 8.0.1 and 8.0.2 both are working fine for me.

There is something that I was missing from the steps to reproduce ?

**Comment by tamerzg** [comment]
Have you tried clicking Add Default entity. After saving it, then you will get error.

**Comment by darol100** [comment]
After adding the default entity and saving it. I was able to replicate this issue.

**Comment by hotlevel4** [comment]
Same error is seen when attempting to delete an added entity.

**Comment by kevinquillen** [comment]
I also get the same error - I am adding a config entity to an existing module (no need to generate the module first).

**Comment by zugec** [comment]
I think I've found the bug.

The config entity is always extending the `ConfigEntityBundleBase` base class. This base class should only be used for config entities which are used as bundles.

If you want to use a config entity as basic configuration you need to extend `ConfigEntityBase` instead.

The if statement in the following line of code doesn't seem to work: 
https://github.com/hechoendrupal/DrupalConsole/blob/master/templates/module/src/Entity/entity.php.twig#L57

To fix the issue just change `ConfigEntityBundleBase` where your config entity is defined and extend `ConfigEntityBase` instead.
