### ISSUE TITLE
[helper] - Add typehinting to ContainerAwareCommand

### ISSUE THREAD

**Issue by eyaldofinity** [hechoendrupal/drupal-console#1750]
## Motivation

Many methods of ContainerAwareCommand don't have type hinting (see getModuleInstaller(), getEntityQuery(), getModuleHandler(), ...)

The missing type hinting forces programmers to add type hinting on the received values which is redundant.

**Comment by LOBsTerr** [comment]
@jmolivas I think it can be closed, we already provide this in many commands

**Comment by jmolivas** [comment]
Closing this one. Feel free to re-open if still happening after updating to the latest version.
