### ISSUE TITLE
Chain command does not pick up the templates folder for custom module commands.

### ISSUE THREAD

**Issue by Jaesin** [hechoendrupal/drupal-console#1816]
While creating a command for a custom module I was using chain to automate things but my templates weren't being found.

**Comment by darol100** [comment]
@Jaesin , Can you explain your current module directory ? where do you have your templates ? Are you running the chain from your Drupal root directory ? What DrupalConsole version are you running and what Drupal 8 version are you running ?

**Comment by Jaesin** [comment]
Hello @darol100 It's here: https://github.com/Jaesin/content_entity_base/tree/console-ceb/console_ceb

**Comment by Jaesin** [comment]
Drupal latest, Console latest (from git).
I believe I was running the command from the site root.

**Comment by jmolivas** [comment]
@Jaesin May you try using latest release 0.10.8? if the issue persist can you please elaborate how to replicate it?

**Comment by harold20** [comment]
Hi @Jaesin sorry for the late response.

Since 2016, the Drupal Console has changed a lot, so now to create custom commands, generators and templates are a bit different, We are updating our docs so if you wish, you can ping me in the drupal console slack.
