### ISSUE TITLE
Chain command helper doesn't respect --uri option passed in

### ISSUE THREAD

**Issue by acbramley** [hechoendrupal/drupal-console#1854]
I have a command that uses the chain command helper to set some site specific input options. One of which is the `--uri` option which as important for url translations.

If I run my command directly with --uri, and dump the result of the following code, the correct absolute url is output:

```
$site = Url::fromRoute('<front>', array(), array('absolute' => TRUE))->toString();
```

But when passing --uri through the chain command like this:

```
    // Export the block content.
    $input = [
      '--uri' => 'http://mysite.local/',
    ];
    $this->getHelper('chain')->addCommand('entity_pilot_git:import', $input);
```

The url that outputs is simply a single "/" character, even though if I dump:

```
$input->getOption('uri');
```

It shows the correct string.

It seems like the chain command isn't respecting the option early enough, or something? I'm going to try to look into how normal commands use the `--uri` option now.

**Comment by jmolivas** [comment]
@acbramley I will be taking a look at this, ping me at https://gitter.im/hechoendrupal/DrupalConsole if you are available.

**Comment by jmolivas** [comment]
@acbramley: The chain helper does not re-boot drupal, it shared the booted drupal. 

I did some code changes. PR https://github.com/hechoendrupal/DrupalConsole/pull/1855 this code detects if `--uri`, `--target` or `--root` options were passed and send an ouput message.

Still missing to re-boot drupal this must require a change on the `Application` class but I think is a valid use case.

**Comment by acbramley** [comment]
@jmolivas excellent, that looks like a good start.
