### ISSUE TITLE
Inconsequent parameter separators for module:install and module:uninstall commands

### ISSUE THREAD

**Issue by balagan73** [hechoendrupal/drupal-console#1872]
The module:install command expects parameters separated by space, while the module:uninstall commands expects parameters separated by comma. These should be consequent. I prefer spaces, they are easier to type. ;-)

**Comment by darol100** [comment]
I think we should be supporting both spaces and commands.

**Comment by balagan73** [comment]
Yeah, that's even better

**Comment by harold20** [comment]
@balagan73 we use the array mode in the module argument, by default, the modules to uninstall or install need a space. I fixed the translation.
