### ISSUE TITLE
Documentation Examples/Context

### ISSUE THREAD

**Issue by justinlevi** [hechoendrupal/drupal-console#1878]
Would be great to see some additional help on each of the command documentation pages so we can get some context about each command. 

Probably don't want to teach people everything about drupal but as an example on the 
`generate:controller` documentation page, would be nice to see some information about what a controller is and why I'd want to run this. 

Links to more info would be really helpful too. Any information that would tell me what I'm going to get before I run the command would be helpful. 

Even listing the files that would be affected and what scaffolding would get added could be very helpful.

**Comment by LOBsTerr** [comment]
@jmolivas it was fixed here https://github.com/hechoendrupal/drupal-console/issues/2306

**Comment by jmolivas** [comment]
Closing this one. Feel free to re-open if still happening after updating to the latest version.
