### ISSUE TITLE
site:new fails with --no-interaction when version argument is missing

### ISSUE THREAD

**Issue by kentr** [hechoendrupal/drupal-console#1889]
### Problem

Though the `version` argument is optional for the `site:new` command, when when using `--no-interaction`, there is no prompt to select the version.  Consequently, an empty version is passed to `ProjectDownloadTrait::downloadProject()`.  

While the underlying `DrupalApiHelper::downloadProjectRelease()` defaults to the latest version, `NewCommand::execute()` gets an incorrect `$downloadPath`, and fails at the rename step.
### Proposed resolution

Provide a default to the latest version, and a new method in `DrupalApiHelper` which `NewCommand::execute()` can use to get the latest release when `$version` is empty.  Something like this:

``` php
protected function execute(InputInterface $input, OutputInterface $output)
{
    $io = new DrupalStyle($input, $output);
    $directory = $input->getArgument('directory');
    $version = $input->getArgument('version');
    if (empty($version)) {
        $version = $this->getDrupalApi()->getCurrentVersion('core');
    }
```

If you agree to this solution, I can probably provide a pull request for it.

**Comment by harold20** [comment]
Hi @kentr, sorry for the late response.

That command doesn't belong to drupal console, now it's a chain command that calls an exec command to create a new drupal site.
