### ISSUE TITLE
You have requested a non-existent service "cache.backend.null", to run drupal cr all

### ISSUE THREAD

**Issue by igasi** [hechoendrupal/drupal-console#1895]
```
drupal cr all


  [Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException]                                                                                     
  You have requested a non-existent service "cache.backend.null". Did you mean one of these: "cache.backend.memory", "cache.backend.apcu", "cache.backend.php"?  


cache:rebuild [--learning] [--] [<cache>]
```

This is in relation to this Drupal core issue
https://www.drupal.org/node/2348219

Rebuilding the container will resolve this problem.

**Comment by miguel303** [comment]
I can not reproduce the issue 
I just execute drupal cr all , using 
Drupal Console (1.0.0-beta3) version  and works as expected 

@igasi  can you try again please

**Comment by jmolivas** [comment]
Closing this one. Feel free to re-open if still happening after updating to the latest version.

**Comment by nvaken** [comment]
We're experiencing this issue as well. I've personally had this a little while back (last week?) but a colleague experiences this ATM, not sure why this is happening, he's running a pretty clean and new project.

**Comment by jmolivas** [comment]
Is your colleague using latest DC that should be fixed on 1.1.0

**Comment by 43n79w** [comment]
@jmolivas this just started happening to me after upgrading to DC 1.1.1 from 1.0.2. Reverting back to 1.0.2 makes the error go away.

**Comment by nvaken** [comment]
@jmolivas He's using Drupal Console Launcher `1.1.0` and installed in the projects he's working on is Drupal Console `1.1.0`.

**Comment by jmolivas** [comment]
This PR https://github.com/hechoendrupal/drupal-console/pull/3590 addresses and fixed this issue 

Use it is as a patch https://patch-diff.githubusercontent.com/raw/hechoendrupal/drupal-console/pull/3590.patch
