### ISSUE TITLE
Block plugin generation error messages are not helpful

### ISSUE THREAD

**Issue by chx** [hechoendrupal/drupal-console#1897]
drupal-console generate:plugin:block 

 // Welcome to the Drupal Plugin Block generator
 Enter the module name [block_class]:

> smartsheet_user_widget

 [ERROR] Value "smartsheet_user_widget" is invalid       

Turns out I do not yet have this module. I thought it'll be autogenerated. Or, if not, told at least what's the problem. If you go to the command line and enter a nonexisting module name you will end up with a PHP Fatal error:  Call to a member function getPath() on null in phar:///usr/local/bin/drupal-console/src/Helper/SiteHelper.php on line 178

After I generated and enabled the module:

➜  html git:(master) ✗ drush en -y sc_user_widget
The following extensions will be enabled: sc_user_widget
Do you really want to continue? (y/n): y
sc_user_widget was enabled successfully.                                                                                                                            [ok]
➜  html git:(master) ✗ drupal-console generate:plugin:block --module==sc_user_widget --class=ScUserWidget  --plugin-id=sc_user_widget --theme-region=sidebar --root=.  -y -n
PHP Fatal error:  Call to a member function getPath() on null in phar:///usr/local/bin/drupal-console/src/Helper/SiteHelper.php on line 178

Hint: I accidentally typed two equal signs after module. An error saying `can't find the module =sc_user_widget` would be helpful in all of these cases.

Once I figured it out the generated plugin is helpful, thanks!

**Comment by franfran** [comment]
Same case here.
I was trying to generate rest api using drupal generate:plugin:rest:resource
And I got the error

> PHP Fatal error:  Call to a member function getPath() on a non-object in phar:///usr/local/Cellar/drupalconsole/0.10.12/bin/drupal/src/Helper/SiteHelper.php on line 178


Spent couple of hours, cannot figure it out and until I found this git issue.

So the getPath() error means the module is not found and we simply need to create it first

`drupal generate:module
`

btw, DrupalConsole is a great work.

Thank you very much!!

**Comment by ao2** [comment]
I ran into this today. And I think I already experienced the issue in the past and then forgot that the plugin generation commands expect the module to exist already.

Maybe the issue can be solved at the documentation level: the description of the `--module` option of the **plugin** generation commands could state that the module is supposed to exist already.

**Comment by LOBsTerr** [comment]
@jmolivas we have fixed with moduleOption.

**Comment by jmolivas** [comment]
Closing this one. Feel free to re-open if still happening after updating to the latest version.
