### ISSUE TITLE
[site:install] places settings.php file outside of sites/default directory

### ISSUE THREAD

**Issue by Eyal-Shalev** [hechoendrupal/drupal-console#1958]
# Problem

Calling site:install places settings.php file outside of sites/default directory.
# Reproduce
## Details
- Drupal version 8.0.3
- Console version 0.10.12
## Steps
1. Delete your settings.php file
2. `drupal site:install [profile] --langcode="en" --db-type="mysql" --db-host="localhost" --db-name="[db_name]" --db-user="root" --db-port="2201" --site-name="[site_name]" --site-mail="admin@[site_name].com" --account-name="admin" --account-mail="admin@[site_name].com" --account-pass="[site_name]"`

**Comment by roberto-butti** [comment]
Question: if you run this command in interactive way, you don't have this issue... is it right?

**Comment by Eyal-Shalev** [comment]
@roberto-butti The issue persists.

Could it be related to my custom profile???

**Comment by LOBsTerr** [comment]
@Eyal-Shalev Do you still experience this issue? I checked the installation with different combinations and I never had this issue

**Comment by LOBsTerr** [comment]
Closing the issue, because it is old and I didn't receive any response. Feel free to reopen it.
