### ISSUE TITLE
[site:install] sqlite, db-type and db-file

### ISSUE THREAD

**Issue by roberto-butti** [hechoendrupal/drupal-console#1960]
Software version:

```
Drupal Console (0.10.12) | Drupal (8.0.3)
```

Command executed:

```
drupal site:install --langcode=it --db-type=sqlite --db-file=sites/default/files/.ht.sqlite standard
```

When you need sqlite and in command line you specify db-type and db-file the command in interactive mode asks you also db host.

I think that the problem is in the "if" at line number 165 of InstallCommand.php file.

https://github.com/hechoendrupal/DrupalConsole/blob/0.10.12/src/Command/Site/InstallCommand.php#L165

I think that I fix the problem in my local copy of sources. I'm checking if there is some side effects in this "fix".

```
            // --db-file option
        $dbFile = $input->getOption('db-file');
        if ($dbType == 'sqlite' && !$dbFile) {
            $dbFile = $this->dbFileQuestion($io);
            $input->setOption('db-file', $dbFile);
        }
        if ($dbType != 'sqlite') {
```

I will try to make a pull request.

**Comment by mortenson** [comment]
I'm also having troubles installing with SQLite - I can't get it to work for new installs or re-installs at all. Running:

```
drupal site:install minimal --force --no-interaction --db-type=sqlite --db-file=sites/default/files/.ht.sqlite
```

**Comment by mortenson** [comment]
I filed #3980 which fixes SQLite install problems for me.

**Comment by harold20** [comment]
Hi @roberto-butti. This is already fixed in the current version.
