### ISSUE TITLE
[chain] not install drupal

### ISSUE THREAD

**Issue by vacho** [hechoendrupal/drupal-console#1971]
I execute 
$ drupal chain --file=~/.console/chain/quick-start.yml

Then the d8 has been downloaded but don't installed
This messages appear:

// site:new
 Downloading drupal 8.0.3  
 [OK] Drupal 8.0.3 was downloaded in directory /var/www/html/drupal8.dev                                                

 // site:install
 Starting Drupal 8 install process  
 [ERROR] Class  does not exist                                                                                          

 // server  
 /usr/bin/php5 -S 127.0.0.1:8088 /home/vacho/.console/router.php                                                        

 [OK] Executing php from /usr/bin/php5.

**Comment by vacho** [comment]
I use ubuntu 14.04 and I execute as root user.

**Comment by jmolivas** [comment]
@vacho try running and look for missing sqlite dependency
```
drupal check
```

**Comment by miloskroulik** [comment]
I have the same problem in the same environment. I have run `drupal check` and its output was:

```
                                                                                                                        
 [OK] Checks passed.                                                                                                    
                                                                                                                        

 // settings:set

                                                                                                                        
 [OK] Setting checked was set to true 
```

Also, I'm running Symfony Demo app on the same system, which also requires sqlite and it works fine.

My console version is 1.0.0-alpha2

**Comment by kgaut** [comment]
In my case it was the sqlite3 extension that was missing.

**Comment by harold20** [comment]
Hi @vacho Sorry for the late response.

This (command)[https://github.com/hechoendrupal/drupal-console-core/blob/master/config/chain/quick-start.yml] chain was moved to the core repository.

How to run it:

```
drupal quick:start
```

When the command ask for a directory, provide an absolute path ex: `/absolute-path/dir-name`
