### ISSUE TITLE
[site:install] webpage on front without styles and permissions problems

### ISSUE THREAD

**Issue by vacho** [hechoendrupal/drupal-console#1972]
After run
$ drupal site:install

The comand install d8 perfectly but after the webpage was without styles and with permissions problems.
The website let login as admin and in this scenario show styles perfectly

**Comment by darol100** [comment]
@vacho , Which version of Drupal Console  and Drupal core are you running ?

**Comment by vacho** [comment]
hi @darol100 I use console 0.10.12 version over ubuntu 14.04 and I execute the command with root user account.

**Comment by vacho** [comment]
Afeter exectute 

$ chmod 777 sites/default/files/
$ drupal cache:rebuild

styles works fine...
(with 775 perms fail ???)

**Comment by vacho** [comment]
Executing this commands after install and the site run (ubuntu)
$ chown www-data:www-data -R sites/default/files/
$ chmod 755 -R sites/default/files/
$ drupal cache:rebuild

The definitive solution is add this excecutions to the command.

**Comment by harold20** [comment]
I can't reproduce this issue with the current version of drupal console 1.8.0
