### ISSUE TITLE
[drupal g:p:fieldwidget] Call to undefined method Drupal\Console\Helper\SiteHelper::getProfile()

### ISSUE THREAD

**Issue by greg606** [hechoendrupal/drupal-console#2008]
```
Error: Call to undefined method Drupal\Console\Helper\SiteHelper::getProfile() in /var/www/xxx/vendor/drupal/console/src/Command/ModuleTrait.php on line 29
Error: Call to undefined method Drupal\Console\Helper\SiteHelper::getProfile() in Drupal\Console\Command\Generate\PluginFieldWidgetCommand->moduleQuestion() (line 29 of /var/www/xxx/vendor/drupal/console/src/Command/ModuleTrait.php).
```

php 7
drupal 8.0.5

**Comment by darol100** [comment]
@greg606 , What command did you run ?

**Comment by greg606** [comment]
@darol100 I put it in the title ;)
it's drupal g:p:fieldwidget

**Comment by VeggieMeat** [comment]
This also happens with generate:form:config.

**Comment by almare** [comment]
Same happens for generate:entity:config

**Comment by jmolivas** [comment]
@VeggieMeat @almare are you also running `php 7`?

**Comment by almare** [comment]
No, I am running PHP 5.5.9-1. I found out that the last working version is tagged with 0.10.12. All Versions behind that tag throw this error.

**Comment by jmolivas** [comment]
@almare thanks for the info.

**Comment by almare** [comment]
@jmolivas you are welcome.

**Comment by andrewbelcher** [comment]
I'm getting the same. Did a little debugging and it is trying to use the site helper from a globally installed drupal console but calling from a copy in /vendor (have installed using drupal-composer/drupal-project). The global version was older and presumably didn't have the method - updating to the latest drupal console globally has fixed it.

**Comment by james-nesbitt** [comment]
A quick comment.  In most cases, composer is failing you if you get this error.  You may have global libraries that are the wrong version for console.

It is recommended to install console with your project, not globally, and use the version specific to your project.  In such a case, it makes sense to make an alias pointing to the console from your project, and specifying the root path, and url.

If your project doesn't yet have composer, or if you want to install somewhere else
````
  $/> composer init
````
Then add console to your project
````
  $/> composer require "drupal/console": "~0.11"
  $/> alias drupal-myProject="$(pwd)/vendor/bin/drupal --root=${MYPROJECTWEBROOT}"
````

**Comment by harold20** [comment]
This is no longer present in the current version 1.8.0
