### ISSUE TITLE
config:export:view export view that contains only 'false'

### ISSUE THREAD

**Issue by balagan73** [hechoendrupal/drupal-console#2021]
When running drupal console 0.10.12 on Windows with the config:export:view option, the exported view contains a single word 'false'.

**Comment by enzolutions** [comment]
Could you try again with latest version @balagan73 ?

**Comment by enzolutions** [comment]
Due no further information, this issue will be close

**Comment by balagan73** [comment]
Sorry for replying so late, but I was really busy for the last couple of weeks. The export works with the current version (0.10.14), but it only accepted the default module name, so after checking it again I will open an issue for that.

**Comment by kenorb** [comment]
Same with 1.8.0

**Comment by LOBsTerr** [comment]
I have investigated the issue. There is only one case when I got file with "false" content, when I pass the wrong name of the view. For example:
```
drupal cev sdhfjhsdjfhsdjfk
```
but when I pass a real name of the view 
```
drupal cev files
```
We need to add additional check, when we don't use interactive mode.

**Comment by LOBsTerr** [comment]
PR - https://github.com/hechoendrupal/drupal-console/pull/3911
Translation - https://github.com/hechoendrupal/drupal-console-en/pull/211

**Comment by LOBsTerr** [comment]
Merged
