### ISSUE TITLE
[console] No commands defined after global composer install.

### ISSUE THREAD

**Issue by socketwench** [hechoendrupal/drupal-console#2064]
From the following repo & branch: https://github.com/socketwench/dropwhale/tree/switchToDrupalConsole

Install Drupal Console using the following commands:

`composer global require drupal/console:@stable && \
    ln -s /root/.composer/vendor/bin/drupal /usr/bin/drupal`

Then attempt to use any command. A command such as site:install will print usage information in markdown format. 

When attempting to enable a module, the following error is displayed:

`[Symfony\Component\Console\Exception\CommandNotFoundException]  
  Command "module:install" is not defined.                        
  Did you mean one of these?                                      
      site:install                                                
      module:download`

When installing from the *.phar, Console behaves as expected.

**Comment by skippednote** [comment]
I'm facing the same issue. After installing using Composer `composer global require drupal/console:@stable`, I still don't see any `drupal` binary in my `~/.composer/vendor/bin`.

**Comment by harold20** [comment]
For global executions it  is better to use the [launcher](https://docs.drupalconsole.com/en/getting/launcher.html)
