### ISSUE TITLE
[translation] Use double quotes when %s is used it.

### ISSUE THREAD

**Issue by darol100** [hechoendrupal/drupal-console#2071]
### Problem / Motivation

There is been some inconsistency between commands, where some of them use `%s` and some of them use `"%s"` at the translation level.
### Solution

Rename `%s` to `"%s"`.

**Comment by jmolivas** [comment]
We should define a standard and make change on the all of the for translation files, are we using?
* Single quotes
* Double quotes

How about languages that contain single quotes within the translation text should we use `''` to avoid invalid YAML files.

Translation file `config/translations/ca/cache.rebuild.yml`
```
generate-chain: 'Imprimir les opcions d''execució i els arguments com una sortida YAML per ser utilitzats amb el comandament "chain".'
```

**Comment by LOBsTerr** [comment]
@jmolivas I have passed through English translation files and wrapped %s with double quotes
PR https://github.com/hechoendrupal/drupal-console-en/pull/164

**Comment by LOBsTerr** [comment]
Close the issue, feel free to reopen, if you find other cases
