### ISSUE TITLE
[generate:plugin:ckeditorbutton] Warning: No such file or directory in _locale_parse_js_file()

### ISSUE THREAD

**Issue by darol100** [hechoendrupal/drupal-console#2078]
### Problem / Motivation

In one of the modules that use by the generator, I got reported this bug https://www.drupal.org/node/2695025#comment-11017805. Which for some reason if the JS file is not there is going to throw an error. This seem to be like a fairly common issue across other modules. An easy fix will be to added `files_exits` before we get any file.

I will be fixing this issue at the module level. However, I reported back to the Drupal Console module because it can apply at the generator level.
### Solution
- We need to added the `files_exits` at any place where is trying to get a file. From the code that is generating.

**Comment by dabito** [comment]
@darol100,

have you found any specific places where you think this validation should happen?

I ran a project-wide search for file_get_contents() and only the EntityContentGenerator seems to be using it. I also wonder if a specific file not found warning should be triggered if validation fails. 

Thanks for the pointers!

**Comment by serundeputy** [comment]
@dabito looks to me like on line 159 of `EntityContentGenerator.php`:

```php
$module_file_contents = file_get_contents($module_filename);
```

we could check if that file exists perhaps on or before line 147, but it is tricky to test since the file you are getting the contents of is most likely the thing trying to get the `js` file(s).

The best thing I can think of is to try to generate a plugin `generate:plugin:ckeditorbutton` then make your `file_exists` checks and see if you can avoid the bug in the OP or at least warn the user about it.

~Geoff

**Comment by darol100** [comment]
This issue does not have to do anything with `EntityContentGenerator.php`. This issue occurs with the code that is been generate by this command, which is `templates/module/src/Plugin/CKEditorPlugin/ckeditorbutton.php.twig`

I think the issue is at ` return drupal_get_path('module', '{{ module }}') . '/js/plugins/{{ plugin_id }}/plugin.js';` when is trying to get js and if not there is going to throw an error. What we should be doing is add a 
````
if (file_exist($file)){
    return drupal_get_path('module', '{{ module }}') . '/js/plugins/{{ plugin_id }}/plugin.js';
}
```

If guys want to truly test download - [CKEditor Smiley](https://www.drupal.org/project/ckeditor_smiley), see if you can replicate and add the if statement around the return.

**Comment by serundeputy** [comment]
@darol100 that makes sense that is where it is actually looking for the `js` file; thanks for the clarification.

**Comment by dabito** [comment]
Thanks guys... I'll give it a shot this week :)

**Comment by dabito** [comment]
WIP 746e0f4 don't know how to build phar :see_no_evil: so I couldn't test it yet.

**Comment by mxr576** [comment]
There is no return value when the file does not exists. Is it intended? 
As I [can see](https://api.drupal.org/api/drupal/core!modules!ckeditor!src!CKEditorPluginInterface.php/function/CKEditorPluginInterface%3A%3AgetFile/8), this method should return the file path or FALSE.

So a `return file_exist($file);` would not be better, instead of the `if` condition?

**Comment by darol100** [comment]
@mxr576 , I agree with you. @dabito Can you change it to `return file_exist($file);` its a lot more clean.

**Comment by dabito** [comment]
sure thing... any pointers on building the phar?

**Comment by jmolivas** [comment]
@dabito ping me on gitter I can tell you how to do that.

**Comment by dabito** [comment]
@darol100 @mxr576 I did apply the change you guys suggested, but reading the documentation it indicates that it should only return FALSE if the plugin is internal (meaning it's part of Drupal core, so I dont think that's a use case we should prepare for, feel free to tell me if you disagree).

Also, file_exists returns TRUE if it finds the file and not the file path, which would completely break the getFile functionallity.

It seems to me that the best solution is returning a drupal_get_path as it was in the begginning (and closing this issue as wont fix)

**Comment by enzolutions** [comment]
@darol100 are you close to close this issue?

**Comment by LOBsTerr** [comment]
dabito is right. We can't return false here.
/core/modules/ckeditor/src/Plugin/Editor/CKEditor.php (line 193). It should be fixed in the core.
I'm closing the issue. Feel free to reopen it, if you find new information
