### ISSUE TITLE
A bit baffled by config:export

### ISSUE THREAD

**Issue by iainhouston** [hechoendrupal/drupal-console#2088]
```
 $ drupal config:export --target=ba.dev --directory=config.test
 [OK] The configuration was exported at:                                                                                
config.test
// settings:set
[OK] Setting checked was set to true    
```

but `config.test` is empty on both remote `b.dev` and local
nor is `config.test` created if it doesn't already exist

Where is `config.test` supposed to be? local or remote?

**Comment by jmolivas** [comment]
@iainhouston Thanks a lot for filing this issue! We'll take a look at it as soon as possible!

**Comment by harold20** [comment]
I can't reproduce this issues with the DrupalConsole 1.9.0 dev
