### ISSUE TITLE
[generate:plugin:derivative] New command 

### ISSUE THREAD

**Issue by igasi** [hechoendrupal/drupal-console#2117]
Implements https://www.drupal.org/node/1653226 to block plug in.

Derivatives provide a simple way to expand a single plugin so that it can represent itself as multiple plugins in the user interface.

**Comment by igasi** [comment]
Speaking with @jmolivas and @dmouse , which define how the Derivative Plugin must be integrated to Block Plugin.

- How derivative plugin is a plugin that helps iterate any other plugin. 
- A Derivative plugin should always be accompanied to another plugin.
- So I think we should integrate it as a question more in the flow of creation per each plugin. 
- At the beginning by the Block Plugin.
- At the current flow is could add:
  
`` `
Do you want to generate a Derivative Plugin (yes / no) [no]:
> yes

 // Welcome to the Drupal Plugin Derivative generator
 Enter the module name [derivativesdev]:
 > derivativesdev

 Plugin class name [DefaultDerivative]:
 >

 Plugin label [Default derivative]:
 >

 Plugin id [default_derivative]:
 >

 Derivative Array Ids to Iterations [array_derivative_ids]:
 >

 Do you want to load from the container services (yes / no) [no]:
 > yes

Type the service name or use keyup or keydown.
This is optional, press enter to continue

 Enter your service []:
 > entity.manager
 Enter your service []:
 > config.manager
 Enter your service []:
 >

Do you confirm generation? (Yes / no) [yes]:
 >

`` `

**Comment by enzolutions** [comment]
Implemented with PR https://github.com/hechoendrupal/drupal-console/pull/4173 , will be included in release 1.9.4
