### ISSUE TITLE
Add additional information for generate a form structure in each new added field type.

### ISSUE THREAD

**Issue by igasi** [hechoendrupal/drupal-console#2123]
**Problem/Motivation**
When it generate a form structure, per each field added is some confusing understand if the type is a argument of previous field or if a new field type.

**How to reproduce**
In my case this appears when I run generate:plugin:block and added a form structure. But I suppose that happens in others commands that can add a form structure.

**Propose solution** 
Add additional information, to clarify this confusion, with a little message before of new field type.

![selection_003](https://cloud.githubusercontent.com/assets/3912749/14413058/03829f0a-ff35-11e5-8f26-4414c5b436d3.png)

**Comment by darol100** [comment]
@igasi , There are few commands like that... Also, there are commands that said things like.... "Click Enter whenever you are done", which to me is a little bit confusing.

Do you have any specify solution that you suggest to solve this issue ?

**Comment by LOBsTerr** [comment]
@jmolivas It is a duplication of this issue: https://github.com/hechoendrupal/drupal-console/issues/1991
Let's close this one.

I have added the fix there

**Comment by jmolivas** [comment]
Duplicated
