### ISSUE TITLE
[database:restore] - Add drop option / Remove container awareness / ...

### ISSUE THREAD

**Issue by Eyal-Shalev** [hechoendrupal/drupal-console#2174]
# Problems
1. Restoring the database without dropping it caused problems because of zombie tables.
2. Removing the database without hidding the $database line in settings.php resulted in drupal errors (tried to load non-existing tables)
3. Removing the $database line from settings.php removed the database:restore option.
# Suggestions
- Add a --replace option to [database:restore] command.
  That will remove the database prior to performing the import.
- Expose the [database:restore] command to uninitialized drupal sites.

**Comment by jmolivas** [comment]
Looking at this

**Comment by marcelovani** [comment]
I think this PR will also help with https://github.com/hechoendrupal/drupal-console/issues/3097

**Comment by enzolutions** [comment]
Solved with https://github.com/hechoendrupal/drupal-console/pull/4037 thanks @marcelovani
