### ISSUE TITLE
[module:download] DownloadCommand command should use $io->ask() method instead to allow enter any value.

### ISSUE THREAD

**Issue by naveenvalecha** [hechoendrupal/drupal-console#2212]
Copy from https://github.com/hechoendrupal/DrupalConsole/issues/2198#issuecomment-216443257

This is a different issue but since you will be touching the DownloadCommand class
The interactive method is using the <code>modulesQuestion</code> 

<pre><code>        if (!$module) {
            $module = $this-&gt;modulesQuestion($io);

            $input-&gt;setArgument('module', $module);
        }
</code></pre>

This is not working since that method validates the entered value for the module to be an available module on the system, this should be using <code>$io-&gt;ask()</code> method instead to allow enter any value.

<pre><code>        if (!$module) {
            $module = $io-&gt;ask('Enter modules, separated by coma');

            $input-&gt;setArgument('module', $module);
        }
</code></pre>

That value must be validated by the execution instead.

**Comment by LOBsTerr** [comment]
@jmolivas I think, it can be closed. The code has been replaced by modulesQuestion
