### ISSUE TITLE
Windows problem

### ISSUE THREAD

**Issue by divined** [hechoendrupal/drupal-console#2214]
tar.exe has bug: Cannot connect to C: resolve failed

to fix:

Add --force-local.

"tar.exe" "--extract" "--file=%user%\AppData\Local\Temp/drupal.tar.gz" "--overwrite-dir" "--overwrite" "--gzip" "--directory" "%targetdir%" "--force-local"

**Comment by heyyoyo** [comment]
Hi, I also have this bug, did you find a way to insert this parameter **--force-local** in all calls to tar ?

**Comment by divined** [comment]
Use Drupal Scaffold v.2+

**Comment by nequeteme** [comment]
Hi @divined, I have the command tar using Cmder, this is the link to download https://cmder.net and if you look this it´s the Console emulator for Windows recommended on https://hechoendrupal.gitbooks.io/drupal-console/content/en/getting/windows.html
