### ISSUE TITLE
 SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed:

### ISSUE THREAD

**Issue by llwoll** [hechoendrupal/drupal-console#2218]
### i install DrupalConsole by  following that

   `curl https://drupalconsole.com/installer -L -o drupal.phar`
  `php -r "readfile('https://drupalconsole.com/installer');" > drupal.phar`
  `php drupal.phar`
### but i got that :

`[PDOException]                                                               
  SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: nodena  
  me nor servname provided, or not known`

**Comment by LOBsTerr** [comment]
It looks issue with DNS or remote server configuration. I will close the ticket, because it is not related to Drupal console.
Anyway feel free to reopen it, if you still face the issue.

**Comment by retif** [comment]
Same issue here. And it is a problem of Drupal console, because it gives meaningless error that is not helps to find how to solve it. Where Drupal console read connection address from? which address is that? Where in the code this error is happens?

**Comment by enzolutions** [comment]
@retif as @LOBsTerr  mentioned looks like is not something we could fix inside Drupal Console, if you still think is something we should fix, could you do a little dig and pointing us the piece of code where the problem is.

Thanks for take care of Drupal Console Project

**Comment by sheanhoxie** [comment]
This happened to me as a result of my dev environment, Lando.

When trying to run 'drupal' on my local, I receive the error. Using the 'lando drupal' command results in success
