### ISSUE TITLE
[config:export] Exports config that's overridden in settings.php files

### ISSUE THREAD

**Issue by acbramley** [hechoendrupal/drupal-console#2243]
We have settings.*.php files to override config per environment.

The issue with using drupal console to export config with a set up like this is that the configuration overrides from settings.php are exported to the file system when using config:export. Drush doesn't have this problem presumably because it has a slightly smarter way of going about the export than using file_put_contents.

A configuration override looks like:

`
$config['system.performance']['js']['preprocess'] = TRUE;
`

**Comment by acbramley** [comment]
Hmm, I'm having trouble reproducing this now, not sure if it has been fixed with an update since.

**Comment by harold20** [comment]
I can't reproduce it with the current version 1.8.0 of Drupal Console
