### ISSUE TITLE
absolute path config:import

### ISSUE THREAD

**Issue by jefferyvincent** [hechoendrupal/drupal-console#2246]
Seeing the following:

[Exception]  
  Unable to open in read mode '~/Downloads/config.gz'

When doing this:

`drupal config:import --file=~/Downloads/config.gz`

Resolved by doing this:

`drupal config:import --file=/Users/jefferyvincent/Downloads/config.gz`

**Comment by harold20** [comment]
When the config to be imported is outside the project you must write the absolute path.

**Comment by harold20** [comment]
@jefferyvincent When the config to be imported is outside the project, you must write the absolute path.
