### ISSUE TITLE
[site:install] Allow re-install 

### ISSUE THREAD

**Issue by Saphyel** [hechoendrupal/drupal-console#2269]
At the moment if you already installed the site and you want to reinstall it, you'll have to drop the database, delete the mysql config in settings.php and finally you can install it....

Could be a way to simplify this? if you are working with profiles this is a **massive problem**...

**Comment by jmolivas** [comment]
👍  on this one

**Comment by Saphyel** [comment]
@jmolivas thanks! in Drush you are able to install it even if there is data in the DB.
I dunno if we should create a command for restore the settings, or allow install with a _dirty DB_ or the database:drop should also restore the settings..

**Comment by bradjones1** [comment]
The PR above was closed without explanation; any further thoughts on this?

**Comment by bradjones1** [comment]
In Drush, you may reinstall but it appears Drupal must be first able to bootstrap. I have a workflow where it would be nice to have the installer determine the database config from the existing `settings.php` file, while not requiring the database have any data/tables.

**Comment by jmolivas** [comment]
@bradjones1 this is a must have feature for the project I can test what @Saphyel was working on and resurrect the PR.

**Comment by Saphyel** [comment]
Well I closed it myself because I'm not longer working on it... If you have an idea @bradjones1 feel free to overtake it.

**Comment by jmolivas** [comment]
@bradjones1 @Saphyel this is done and will be included on upcoming release. 

This should be executed as 
```
drupal site:install --force --no-interaction
```

![drupal-site-install-force](https://cloud.githubusercontent.com/assets/366275/20788200/9b337e40-b764-11e6-847e-8e62c951cef5.png)

**Comment by jmolivas** [comment]
PR => https://github.com/hechoendrupal/DrupalConsole/pull/2984

**Comment by nvaken** [comment]
This seems merged? Is it not? Close?

**Comment by bradjones1** [comment]
@nvaken Yes it is and I've been using it per above, though I don't have permissions to close. Looks done.
