### ISSUE TITLE
Error when logging an error to watchdog from console command

### ISSUE THREAD

**Issue by yanniboi** [hechoendrupal/drupal-console#2277]
When logging an error in a drupal console command, if --uri is not specified, the log->location value is set to 'http://:/' which breaks when trying to view the watchdog error as it tries to resolve the url.

Could the default uri be something like http://default (similar to drush)?

**Comment by yanniboi** [comment]
#2276 would also be quite helpful in solving this.

**Comment by andrewbelcher** [comment]
This is fixed by #2680.

**Comment by LOBsTerr** [comment]
Closing the issue. Feel free to reopen if it is still the case
