### ISSUE TITLE
drupal module:download downloads to wrong directory

### ISSUE THREAD

**Issue by rkoberg** [hechoendrupal/drupal-console#2318]
The download command always downloads to a "module" directory regardless of using the default or entering a custom path. I have to manually move them or the modules will not install. For example:

```
Enter the contrib project Path [modules/contrib]:
 > modules
 One or more modules shopify are not available, running download process to get those modules
 Getting releases for module shopify
 Please select your favorite release:
  [0] 8.x-1.0-alpha3
  [1] 8.x-1.0-alpha2
  [2] 8.x-1.0-alpha1
  [3] 8.x-1.x-dev
 > 0
 Downloading module shopify release 8.x-1.0-alpha3
 [OK] Module shopify version 8.x-1.0-alpha3 was downloaded successfully at                                              
 /Users/rkoberg/Sites/fwi/drupal/module/shopify      
```

**Comment by jmolivas** [comment]
This is fixed and will be included on the next release.

**Comment by darol100** [comment]
Leaving open until next release....

**Comment by gilbertomangones** [comment]
Hi, I have tried this command ```$ drupal module:download``` it works fine, even, download the dependent modules and the modules are placed on path selected [modules/contrib].

**Details**
Drupal Console : 1.9.3
Drupal core : 8.7.7

**Results test**

![2019-09-26_2309](https://user-images.githubusercontent.com/6983125/65741758-e4dd0000-e0b2-11e9-81d5-2fa5f892983a.png)
