### ISSUE TITLE
[site:mode] option for disabling all caches

### ISSUE THREAD

**Issue by novia713** [hechoendrupal/drupal-console#2350]
_site:mode dev_ or perhaps with another option should disable by default all drupal caches (not only the Twig one, also _render cache_ and _Dynamic Page Cache_, for example) for developing mode.

all the steps are in https://www.drupal.org/node/2598914

as user, i would like to change with only one command all the required variables in
$config  & $settings in settings.php for disabling all the caches

**Comment by jameswilson** [comment]
Seems useful and pretty straightforward. Two questions:

1)  is there any precedent or ideal way console does the kinds of things needed to make this work?
E.g. 

* copy example file -- but don't copy if the file already exists.
* edit/replace/uncomment specific lines -- if lines already exist uncommented, reset their values to the needed value.
* deal with folder permissions -- if sites/default is 644 or 444, change accordingly before copying/editing files. 

2) you say you want to change `settings.php`, but the documentation at the link you provided talks about putting these settings in `settings.local.php`.  Wouldn't it be better to follow how core suggests doing this?

**Comment by novia713** [comment]
@jameswilson 
afaik, there is no recommendend way by DrupalConsole for working with settings.php .... maybe i'm wrong ....

1)
- i don't would simply copy the file, perhaps the user has a customized one
- i have a **rude sketch** at https://paste.fedoraproject.org/372711/62623614/ for inserting the lines, but i feel really dirty about it :smile:  should be a better way to do this
- my sketch already deals with permissions, besides maybe a problem anyway

2) 

i would check if `settings.local.php` exists first of all, yes. but DrupalConsole doesn't create it when installing a new site, so maybe it were `settings.php` ....
this is totally up to the user, besides we should take in consideration the best practice ...

**Comment by novia713** [comment]
related → https://www.drupal.org/project/settingsphp

**Comment by novia713** [comment]
i would do this like in my sketch but using http://symfony.com/doc/current/components/filesystem/introduction.html#dumpfile

**Comment by novia713** [comment]
got it working with `dumpFile`, example at → https://paste.fedoraproject.org/372732/63191314/

**Comment by jameswilson** [comment]
Your pastebin code looks wrong syntax:

```
$settings =["cache"]["bins"]["dynamic_page_cache"] = "cache.backend.null";
```

hope that was just quick sample pseudo code.

**Comment by novia713** [comment]
ups, i didn't noticed it :/
thanks for the warning @jameswilson :+1: 

it's late here, but surely i will have a PR for tomorrow handling all of this
it shall not be the code of my dreams, but i expect it does the job :octopus:

**Comment by FatherShawn** [comment]
`settings.local.php` is a pretty common place to put local dev settings.  If we wanted to fence this off even more, we could create a `settings.console.php`.  I would leave it up to the developer to add the appropriate include in `settings.php`.

What I like about this proposal is that `site:mode dev` is already managing `service.yml`

**Comment by novia713** [comment]
fuf, i got it working more or less in my machine,
but this is very far from being trivial ...

it's incredible how to simply add a few lines to an archive becomes a totally painful process if you want to do it programming.... the code is so complex i'm thinking about to transform it (the code) in a single command ...

more or less, the workflow i'm following is https://www.drupal.org/node/2348219#comment-9202547

as said above, i'm far from being proud of the way i have accomplished the target, i didn't do yet the opposite action [_site:mode prod_] :(

if someone can and want to lend me a hand i can do a preliminar PR in order to someone review it and   polish it in the best way he/she can :dart:

**Comment by jmolivas** [comment]
@novia713  I can help taking a look and reviewing once a PR is sent.

**Comment by novia713** [comment]
i'm very afraid of my code  ^^ 

to quickly overview it, i paste here

here they are the manoeuvres according to
https://www.drupal.org/node/2605652#comment-10728554
&
https://www.drupal.org/node/2348219#comment-9202547
<script src="https://gist.github.com/novia713/f7829369f17c06b44689b644557b049a.js"></script>

and this is the Settings service
<script src="https://gist.github.com/novia713/7a96e482f46d7c2de0409409613dc95b.js"></script>

**Comment by novia713** [comment]
folks, here it's the PR #2376 just in case someone wants to try it.
[test with caution, it can ruin your site ^^]

**Comment by novia713** [comment]
new clean PR at https://github.com/hechoendrupal/DrupalConsole/pull/2969

**Comment by jmolivas** [comment]
Closing this one. Feel free to re-open if still happening after updating to the latest version.
