### ISSUE TITLE
[list] Impossible to parse XML

### ISSUE THREAD

**Issue by mikeshiyan** [hechoendrupal/drupal-console#2442]
### Problem/Motivation

A warning message ["In order to list all of the available commands, you should run this inside a drupal root directory."](https://github.com/hechoendrupal/DrupalConsole/blob/1.0.0-beta2/src/Application.php#L237) prevents parsing XML output of `drupal list --format=xml` command.

An example when something needs to parse this XML is integration of Drupal Console in PhpStorm as a command line tool (for commands auto-completion as a major feature, etc).
### Proposed solution

I can't complain about other supported formats, but with --format=xml there should not be any data outside an XML structure, so the warning should be removed from there.

**Comment by jmolivas** [comment]
@mikeshiyan Nice catch, make sense removing the message when XML option format is passed to the command.

**Comment by enzolutions** [comment]
@mikeshiyan I am confuse, I see the output in xml, could you show me what in you opinion must to be removed from xml output, and how that will be use in PHPStorm?

**Comment by mikeshiyan** [comment]
@enzolutions Seems I forgot to mention that the warning message appears when running the command outside of drupal project.

PhpStorm has support for command line tools, and is able to provide auto-completion for commands. _There's a separate issue about integrating Drupal Console with it - #1079_

**Comment by jmolivas** [comment]
@mikeshiyan  I saw this and will take care of having it fixed.

**Comment by enzolutions** [comment]
@mikeshiyan you mean remove this message

```
[WARNING] In order to list all of the available commands, you should run this inside a drupal root directory.
```

**Comment by LOBsTerr** [comment]
@jmolivas is it finished or something should be done here?

**Comment by jmolivas** [comment]
@LOBsTerr fixed with this PR => https://github.com/hechoendrupal/drupal-console-core/pull/296
