### ISSUE TITLE
translations

### ISSUE THREAD

**Issue by Saphyel** [hechoendrupal/drupal-console#2482]
I was thinking that maybe we can move from our unique `commands.test.run.arguments.url` to `commands.question.path` because in this way we can avoid duplicate strings, is less effort in translation & I don't see any cons in this way...

**Comment by enzolutions** [comment]
What files?

**Comment by Saphyel** [comment]
So at the moment we have the file: `test.run.yml` with the strings of that command, so in this way every command has "unique" strings... but that's not the case, some commands uses sentences that are in other commands...
So my proposal is create something like `questions.yml` so if we want to ask the path of something or the name of the module is already there and we don't have to duplicate that string in different files...

**Comment by enzolutions** [comment]
Hi @Saphyel 

Sure why not if you can contribute that change, will be great go for it.
