### ISSUE TITLE
[generate:plugin:ckeditorbutton] Add the ability of entering multiples button

### ISSUE THREAD

**Issue by darol100** [hechoendrupal/drupal-console#2505]
### Problem / Motivation

There CKEditor plugins that contain multiples button and this generator only support one button.
### Solution
- Re-ask the user if want to add another button and add another button.

**Comment by LOBsTerr** [comment]
PR: https://github.com/hechoendrupal/drupal-console/pull/3770
PR for translations: https://github.com/hechoendrupal/drupal-console-en/pull/173

**Comment by jmolivas** [comment]
PR #3770 Merged
