### ISSUE TITLE
Possible naming clash for ~/.console/ folder and files in it

### ISSUE THREAD

**Issue by madalinignisca** [hechoendrupal/drupal-console#2534]
Is the folder something enforced by Symfony's Console or was this a decision regarding Drupal Console?

This folder name might cause problems with various other applications as it is too generic.

I would have a suggestion on  having it as

> ~/.drupalconsole/

to make sure we have our own _namespace_ for common settings.

**Comment by jmolivas** [comment]
@madalinignisca This was a decision for DrupalConsole project.

Make sense to rename is as `~/.drupalconsole/` to avid any possible conflict.

We are adding support to read config from modules and site root path if contains a directory we should keep the same name on all those places as well

**Comment by enzolutions** [comment]
Until now we survive with the current configuration, I will close this issue
