### ISSUE TITLE
[generate:entity:content] Allow revisionable entities

### ISSUE THREAD

**Issue by pdscti** [hechoendrupal/drupal-console#2537]
Added functionality (using the node module as a template) to allow the generation of revisionable entities.

https://github.com/hechoendrupal/DrupalConsole/pull/2536

**Comment by pdscti** [comment]
#https://github.com/hechoendrupal/DrupalConsole/pull/2536

**Comment by LOBsTerr** [comment]
@jmolivas It can be closed

**Comment by jmolivas** [comment]
Closing this one. Feel free to re-open if still happening after updating to the latest version.
