### ISSUE TITLE
[generate:entity:config] output has minor lint errors.

### ISSUE THREAD

**Issue by martinfrances107** [hechoendrupal/drupal-console#2538]
when I use 

drupal generate:entity:config

and then immediately I run 

phpcs --standard=Drupal .

I see that the templates have the same one trivial coding standard issue repeated all over the place .. it is very minor but I want to fix it

Here for example is the EntityListBuilder output

---
## PHPCBF CAN FIX THE 1 MARKED SNIFF VIOLATIONS AUTOMATICALLY

I am working on a pull request now...

**Comment by harold20** [comment]
This is already fixed in the next version 1.9.0
