### ISSUE TITLE
Translations/aliases not working for custom commands

### ISSUE THREAD

**Issue by andrewbelcher** [hechoendrupal/drupal-console#2539]
I have a custom command that makes use of translation, but for some reason the translation isn't happening and I am just getting the key outputted.

Similarly, aliases are never found...

It was working, so I'm not sure if it's something that has changed with an update or something? All the commands that come with console are working fine, just my custom ones that aren't. I wonder if it's to do with ~/.console as I think that has changed in an update?

My set up is using [drupal-composer](https://github.com/drupal-composer/drupal-project), so directories are:
- ~/.console/: Bits from `drupal init`
- ~/app/: Project route (git etc)
- ~/app/web/: Web route
- ~/app/vendor/: Composer vendor dir
- ~/app/vendor/drupal/console: Drupal console dir
- ~/app/modules/custom/my_module/: My module containing the commands.

Edit: Currently using 1.0.0-beta2.

**Comment by Jelle-S** [comment]
I'm having the same issues. My translations are not detected. Command was generated using drupal:generate:command

**Comment by jmolivas** [comment]
@acbramley @Jelle-S we are working on having this fix for RC-1.

**Comment by andrewbelcher** [comment]
@jmolivas let me know if there is anything I can do to help. Is there an issue describing what's actually going on/a pull request being worked on?

**Comment by LOBsTerr** [comment]
@jmolivas It looks like it has been fixed. Can I close it ?

**Comment by LOBsTerr** [comment]
Closed the issue, feel free to reopen it if it happens again
