### ISSUE TITLE
Does not work with private stream wrapper

### ISSUE THREAD

**Issue by Jelle-S** [hechoendrupal/drupal-console#2588]
`$realpath = $this->getDrupalService('file_system')->realpath('private://test');` returns nothing. 
`file_save_data('data', 'private://test.txt');` creates DRUPAL_ROOT/private:/test.txt in stead of DRUPAL_ROOT/sites/default/files/private/test.txt

**Comment by jmolivas** [comment]
@Jelle-S which version of Drupal and DrupalConsole and OS are you using?

**Comment by Jelle-S** [comment]
Drupal Console: 1.0.0-beta5
Drupal: 8.1.8
OS: Ubuntu 16.04 LTS (64 bit, in a virtualbox)

**Comment by LOBsTerr** [comment]
Closing the issue. Feel free to reopen it if it happens again.
