### ISSUE TITLE
conflict with metatag module?

### ISSUE THREAD

**Issue by verasativa** [hechoendrupal/drupal-console#2599]
Hi, I'm getting this:

``` bash
$ drupal status

Fatal error: Trait 'Drupal\Console\Command\ServicesTrait' not found in /Users/N/repositories/nahuel.me/_builds/last.www/modules/contrib/metatag/src/Command/GenerateGroupCommand.php on line 28
```

Looks like there is conflict with metatag, any ideas?

**Comment by jlbellido** [comment]
Hi! 

I think this is not related with the Console itself but with the implementation of the commands at the metatag module (https://www.drupal.org/node/2752239)

From my point of view, this should be closed since it's not related with the console project.

Thanks!

**Comment by nahueldotme** [comment]
Yep. I just noticed I subscribed to the issue on do. I'll close it when can
connect from desktop or if somebody do it before, even better.


Am Montag, 22. August 2016 schrieb Jose Luis :

**Comment by damienmckenna** [comment]
This was fixed with today's release of 8.x-1.0-beta10.

**Comment by jmolivas** [comment]
Yay @damienmckenna awesome

**Comment by damienmckenna** [comment]
FYI there's now a new issue:

https://github.com/drush-ops/drush/issues/2322

Any idea on how to fix this?

**Comment by jmolivas** [comment]
No idea why is drush loading DrupalConsole commands.

**Comment by cinekk** [comment]
```    
// We have to get the service command list from the container, because
// it is constructed in an indirect way during the container initialization.    
// The upshot is that the list of console commands is not available
// until after $kernel->boot() is called.
$container = \Drupal::getContainer();
$serviceCommandlist = $container->get('drush.service.consolecommands');
foreach ($serviceCommandlist->getCommandList() as $command) {
   if (!$this->commandIgnored($command, $ignored_modules)) {
      drush_log(dt('Add a command: !name', ['!name' => $command->getName()]), LogLevel::DEBUG);
      annotationcommand_adapter_cache_module_console_commands($command);
  }
}
```

inside `bootstrap_drupal_full` - that`s where drush loads the commands.  The only purpose to do that is to cache the commangs (which I think is the reason we use the `tags` option mentioned below).

It loads only the commands that have their service. Or - just the ones that have
```    
tags:
      - { name: console.command }
```
in their service definition.

What is this used for precisely? Does a normal console command require the tags set up? Or a service?

**Comment by jmolivas** [comment]
@cinekk yes DrupalConsole requires tag for commands, we used to register on the Drupal container and inject drupal services.

**Comment by gilbertomangones** [comment]
Hi, this command ```$ drupal status``` for the new version Drupal Console it is replaced by 

```$ drupal``` Display help about ```$ drupal site:status```
site:status (ss,st)                         View current Drupal Installation status

![2019-09-18_1931](https://user-images.githubusercontent.com/6983125/65199007-043cb300-da4b-11e9-8e2a-c2ee02ba2e55.png)

**Comment by enzolutions** [comment]
Working as expected

**Comment by harold20** [comment]
This issue is gone, but there is another issue related to the latest version of DC, but its need to fix it in the Metatag module, I already sent a [patch]
(https://www.drupal.org/project/metatag/issues/2841737#comment-13263681)

I will close this issue
