### ISSUE TITLE
archlinux drupalconsole multiple sites on a server

### ISSUE THREAD

**Issue by ikit-claw** [hechoendrupal/drupal-console#2602]
Okay I have been trying on and off for days now to figure out why this will not work.

I initially installed drush with root so I have also tried all of this as root user.

As far as I can tell console is installed it worked fine for my first site but for my second it does not want to work. So perhaps the issue lies with that ? the error I can not seem to fix is error occurred while renaming directory drupal-8.1.8

Any suggestions or advice at this would be much obliged

**Comment by jmolivas** [comment]
@ikit-claw  is this happening when executing a `site:new` command ?

**Comment by ikit-claw** [comment]
Yes but it also occurs with other commands too. 

drupal chain --file=~/.console/chain/quick-start.yml
drupal site:new drupal8.dev 
drupal site:new 

All give the same error.

**Comment by jmolivas** [comment]
@ikit-claw what is the error message?

**Comment by ikit-claw** [comment]
Drupal "8.1.8" was downloaded in directory "drupal-8.1.8" 

[ERROR] An error occurred while renaming directory as "[ERROR] An error occurred while renaming directory as"

**Comment by ikit-claw** [comment]
Where does it download it to ? it'd help if it told you.

**Comment by jmolivas** [comment]
@ikit-claw seems like the issue is while trying to untar the downloaded file.

**Comment by ikit-claw** [comment]
Yeah but I have no idea why it won't the user has full permissions.

**Comment by ikit-claw** [comment]
I even re tried it as root.

**Comment by jmolivas** [comment]
same result?

**Comment by ikit-claw** [comment]
100% same

**Comment by harold20** [comment]
I can't reproduce in the current version 1.8.0
