### ISSUE TITLE
[generate:entity:content] corrupts existing link.menu definitions

### ISSUE THREAD

**Issue by martinfrances107** [hechoendrupal/drupal-console#2634]
I found this while using 

drupal generate:entity:content   

I had existing entries in the links.menu.yml file

What I found was that a newline needs to inserted before the command adds new definitions to this file.

For example I found this in my *.links.menu.yml when I created an entity named "reservation" 

```
route_name: 'valid route name from existing definition' # Reservation entity menu items definition

entity.reservation_entity.collection:
  title: 'Reservation entity list'
```

The problem is in the comment text  

> # Reservation entity menu items definition

... the problem I saw was the the comment invalidates the line and the link vanishes.
everything returns to normal when I separate the comment

I am working on a patch now

**Comment by LOBsTerr** [comment]
@jmolivas it can be closed
