### ISSUE TITLE
Support Kalabox database credentials

### ISSUE THREAD

**Issue by jdleonard** [hechoendrupal/drupal-console#2678]
I use [Kalabox](http://www.kalabox.io/) as my local development environment for Pantheon-hosted sites.

When running `drupal list` from my D8 install's root directory, I receive the message:

> [WARNING] In order to list all of the available commands you should install drupal first.

My workaround was to add database credentials to `settings.local.php` (like Acquia Dev Desktop, Kalabox provides database credentials via environment variables).

It would be awesome if (similar to #920), Drupal Console checked for and used these environment variables:

> PANTHEON_DATABASE_HOST
> PANTHEON_DATABASE_PORT
> PANTHEON_DATABASE_USERNAME
> PANTHEON_DATABASE_PASSWORD
> PANTHEON_DATABASE_DATABASE

Note that, due to the use of a VM, the hostname and port here is from the VM's perspective (not that of the host machine). I'm not sure whether that will matter. The hostname and port from the perspective of the host machine can be obtained by inspecting the output of the command `kbox services`.

**Comment by jdleonard** [comment]
Actually my workaround didn't work. There's a Kalabox issue to implement a Drupal Console plugin that would resolve this: https://github.com/kalabox/kalabox/issues/581

**Comment by enzolutions** [comment]
Kalabox is deprecated
