### ISSUE TITLE
Dependencies for generated plugins should use Interfaces not their implementations

### ISSUE THREAD

**Issue by SchnWalter** [hechoendrupal/drupal-console#2758]
Currently if you generate a plugin that has some dependencies, the generated file references the implementations of the services not their interfaces.

It should not look like this:

``` php
<?php

use Drupal\Core\Extension\ModuleHandler;

/**
 * Class CoffeeActionsDiscoveryService.
 *
 * @package Drupal\coffee
 */
class CoffeeActionsDiscoveryService implements CoffeeActionsDiscoveryServiceInterface {

  /**
   * Drupal\Core\Extension\ModuleHandler definition.
   *
   * @var \Drupal\Core\Extension\ModuleHandler
   */
  protected $moduleHandler;

  /**
   * Constructor.
   */
  public function __construct(
    ModuleHandler $module_handler,
  ) {
    $this->moduleHandler = $module_handler;
  }

}
```

It should look like this:

``` php
<?php

use Drupal\Core\Extension\ModuleHandlerInterface;

/**
 * Class CoffeeActionsDiscoveryService.
 *
 * @package Drupal\coffee
 */
class CoffeeActionsDiscoveryService implements CoffeeActionsDiscoveryServiceInterface {

  /**
   * Drupal\Core\Extension\ModuleHandlerInterface definition.
   *
   * @var \Drupal\Core\Extension\ModuleHandlerInterface
   */
  protected $moduleHandler;

  /**
   * Constructor.
   */
  public function __construct(
    ModuleHandlerInterface $module_handler,
  ) {
    $this->moduleHandler = $module_handler;
  }

}
```

**Comment by jmolivas** [comment]
@SchnWalter totally agree on this, some services implement several interfaces and this could be challenging what we could improve is. 

When the generator ask for a service then this should show you the implemented interfaces as options to select one.

**Comment by acrosman** [comment]
+1 on this one, although it should be for all generated injections, not just plugins.  I ran into a problem with the recent Redirect 404 update that apparently swaps in its own LoggerFactory. The generated form constructor (that had been fine for a months) suddenly failed because it was expecting the core factory instead of a factory interface.

**Comment by LOBsTerr** [comment]
PR: https://github.com/hechoendrupal/drupal-console/pull/3777
I have added the code. It is not a perfect solution, because the class can implement many interfaces and it is impossible to understand which one is correct. I try to get it based on class name.
