### ISSUE TITLE
Can't execute drupal console commands in non-root directory.  1.0.0RC4

### ISSUE THREAD

**Issue by betoquiroga** [hechoendrupal/drupal-console#2774]
The commands only can execute in the root of a drupal project.  But it can't execute them inside another directories (e.g. sites, themes,  modules)

**Comment by alvarito75** [comment]
I have the same problem,  when I work inside my project's theme directory.

**Comment by sylus** [comment]
Think this is related to this bug? https://github.com/hechoendrupal/DrupalConsole/issues/2590

**Comment by PacificMorrowind** [comment]
As per https://docs.drupalconsole.com/en/using/project.html and the --root command isn't this by design? I suppose trying to find the webroot in parent folders could be done to make it that ux slightly friendlier.
