### ISSUE TITLE
Add support for REST module (drupal 8.2)

### ISSUE THREAD

**Issue by eyudkin** [hechoendrupal/drupal-console#2797]
Just wanted to request support in case of 'rest' module changes during Drupal 8.1-8.2 migration.
Looks like existing commands do not support this.
Also will be cool to implement something like "drupal rest:config:create" and etc. to create rest configurations from cli.

**Comment by enzolutions** [comment]
Hi @tensor146 

Thanks for you report, the rest commands where fixed for Drupal 8.2 since rc9

About your idea about new command rest:config:create could you provide more specific instructions about what that command will do?
