### ISSUE TITLE
[taxonomy:term:delete] Inject dependencies.

### ISSUE THREAD

**Issue by jmolivas** [hechoendrupal/drupal-console#2812]
Take advantage of DI and the service container injecting dependencies  

Service definition:
https://github.com/hechoendrupal/DrupalConsole/blob/master/config/services/drupal-console/taxonomy.yml

Command class:
https://github.com/hechoendrupal/DrupalConsole/blob/master/src/Command/Taxonomy/DeleteTermCommand.php

**Comment by nidble** [comment]
I'm working on it!

**Comment by nidble** [comment]
Hi @jmolivas whats do you think about my PR? Is there something not correct or wrong?

**Comment by jmolivas** [comment]
Thanks for the PR. I will be reviewing during BADCamp this week.

**Comment by jmolivas** [comment]
@nidble  Thanks for the PR. I will be reviewing during BADCamp this week.

**Comment by LOBsTerr** [comment]
@jmolivas It can be closed

**Comment by jmolivas** [comment]
Closing this one. Feel free to re-open if still happening after updating to the latest version.
