### ISSUE TITLE
Installation in non-base Drupal directory

### ISSUE THREAD

**Issue by eyudkin** [hechoendrupal/drupal-console#2816]
Hi all!
Just wanted to ask.
Now dependency to console is into composer.json into a base Drupal directory. It works OK but there is an issue: If I'll update my Drupal version, there will be conflicts in this json.
From this point of view is better to add console into some module or like so, but if I do this - it will not work.
Are there some ways to do this?

**Comment by jmolivas** [comment]
What are you trying to do?

**Comment by tensor146** [comment]
Add a drupal console into the custom module (docroot/modules/custom/something/composer.json)
