### ISSUE TITLE
generate:entity:content with revision = yes results in Fatal Error

### ISSUE THREAD

**Issue by marcusx** [hechoendrupal/drupal-console#2831]
`drupal generate:entity:content`
Answer `commands.generate.entity.content.questions.revisionable (yes/no) [yes]:` with yes

I get:

```
PHP Fatal error:  Call to undefined method Drupal\Console\Generator\EntityContentGenerator::getSite() in /Users/marcus/Projekte/.../vendor/drupal/console/src/Generator/EntityContentGenerator.php on line 183
```

Using Console: (1.0.0-rc6)
And: Drupal Core 8.2.1

**Comment by betoquiroga** [comment]
hi,   I have the same issue but with another error when I enable the module

`[ERROR] Drupal\test1\TestEntityStorage does not implement Drupal\Core\Entity\ContentEntityStorageInterface`

**Comment by jmolivas** [comment]
@marcusx @betoquiroga seems like the issue is this
https://github.com/hechoendrupal/DrupalConsole/blob/master/src/Generator/EntityContentGenerator.php#L180-L211
We need to replace this
```
$this->getSite()
```
with
``` 
$this->site
```

**Comment by marcusx** [comment]
@jmolivas here a PR
