### ISSUE TITLE
Display a user-friendly error message when a command is not available

### ISSUE THREAD

**Issue by xmacinfo** [hechoendrupal/drupal-console#2837]
For users reading the Available commands documentation [https://hechoendrupal.gitbooks.io/drupal-console/content/en/commands/available-commands.html], as they might try out commands not available, Drupal Console should display a user-friendly message when a command is not available.

Referencing: #2825

**Comment by jmolivas** [comment]
Fixed at DrupalConsoleCore repo https://github.com/hechoendrupal/drupal-console-core/pull/71

**Comment by LOBsTerr** [comment]
@jmolivas it can be closed

**Comment by jmolivas** [comment]
Closing this one. Feel free to re-open if still happening after updating to the latest version.
