### ISSUE TITLE
When installing Drupal console in a site, I get files called multiple times, causing errors

### ISSUE THREAD

**Issue by jamesmcb** [hechoendrupal/drupal-console#2838]
I installed the Drupal Console launcher (1.0.0-rc6) then installed it to my Drupal 8.2.1 site and then ran the 2 composer commands.   However when I try to execute "drupal" from my site root directory I get some errors (see below).  I surmise that the global drupal command is running and when it runs in vendor/bin/drupal, all the stuff has already been called from the first one.

PHP Notice:  Constant DRUPAL_CONSOLE_CORE already defined in /Users/mcpuddin/Sites/b2/vendor/drupal/console-core/src/constants.php on line 3
PHP Stack trace:
PHP   1. {main}() /usr/local/bin/drupal:0
PHP   2. require() /usr/local/bin/drupal:10
PHP   3. require() phar:///usr/local/bin/drupal/bin/drupal:3
PHP   4. Drupal\Console\Utils\Launcher->launch() phar:///usr/local/bin/drupal/bin/drupal.php:64
PHP   5. include_once() phar:///usr/local/bin/drupal/src/Utils/Launcher.php:32
PHP   6. include_once() /Users/mcpuddin/Sites/b2/vendor/drupal/console/bin/drupal.php:15
PHP   7. require() /Users/mcpuddin/Sites/b2/autoload.php:14
PHP   8. ComposerAutoloaderInitDrupal8::getLoader() /Users/mcpuddin/Sites/b2/vendor/autoload.php:7
PHP   9. composerRequireDrupal8() /Users/mcpuddin/Sites/b2/vendor/composer/autoload_real.php:45
PHP  10. require() /Users/mcpuddin/Sites/b2/vendor/composer/autoload_real.php:54
PHP  11. define() /Users/mcpuddin/Sites/b2/vendor/drupal/console-core/src/constants.php:3

Notice: Constant DRUPAL_CONSOLE_CORE already defined in /Users/mcpuddin/Sites/b2/vendor/drupal/console-core/src/constants.php on line 3

Call Stack:
    0.0002     225616   1. {main}() /usr/local/bin/drupal:0
    0.0021     632208   2. require('phar:///usr/local/bin/drupal/bin/drupal') /usr/local/bin/drupal:10
    0.0023     653640   3. require('phar:///usr/local/bin/drupal/bin/drupal.php') phar:///usr/local/bin/drupal/bin/drupal:3
    0.2459    5493032   4. Drupal\Console\Utils\Launcher->launch() phar:///usr/local/bin/drupal/bin/drupal.php:64
    0.2463    5509232   5. include_once('/Users/mcpuddin/Sites/b2/vendor/drupal/console/bin/drupal.php') phar:///usr/local/bin/drupal/src/Utils/Launcher.php:32
    0.2464    5510904   6. include_once('/Users/mcpuddin/Sites/b2/autoload.php') /Users/mcpuddin/Sites/b2/vendor/drupal/console/bin/drupal.php:15
    0.2465    5512576   7. require('/Users/mcpuddin/Sites/b2/vendor/autoload.php') /Users/mcpuddin/Sites/b2/autoload.php:14
    0.2466    5524208   8. ComposerAutoloaderInitDrupal8::getLoader() /Users/mcpuddin/Sites/b2/vendor/autoload.php:7
    0.2588    7344608   9. composerRequireDrupal8() /Users/mcpuddin/Sites/b2/vendor/composer/autoload_real.php:45
    0.2588    7347232  10. require('/Users/mcpuddin/Sites/b2/vendor/drupal/console-core/src/constants.php') /Users/mcpuddin/Sites/b2/vendor/composer/autoload_real.php:54
    0.2588    7347376  11. define() /Users/mcpuddin/Sites/b2/vendor/drupal/console-core/src/constants.php:3

PHP Notice:  Constant DRUPAL_CONSOLE_LAUNCHER already defined in /Users/mcpuddin/Sites/b2/vendor/drupal/console-core/src/constants.php on line 4
PHP Stack trace:
PHP   1. {main}() /usr/local/bin/drupal:0
PHP   2. require() /usr/local/bin/drupal:10
PHP   3. require() phar:///usr/local/bin/drupal/bin/drupal:3
PHP   4. Drupal\Console\Utils\Launcher->launch() phar:///usr/local/bin/drupal/bin/drupal.php:64
PHP   5. include_once() phar:///usr/local/bin/drupal/src/Utils/Launcher.php:32
PHP   6. include_once() /Users/mcpuddin/Sites/b2/vendor/drupal/console/bin/drupal.php:15
PHP   7. require() /Users/mcpuddin/Sites/b2/autoload.php:14
PHP   8. ComposerAutoloaderInitDrupal8::getLoader() /Users/mcpuddin/Sites/b2/vendor/autoload.php:7
PHP   9. composerRequireDrupal8() /Users/mcpuddin/Sites/b2/vendor/composer/autoload_real.php:45
PHP  10. require() /Users/mcpuddin/Sites/b2/vendor/composer/autoload_real.php:54
PHP  11. define() /Users/mcpuddin/Sites/b2/vendor/drupal/console-core/src/constants.php:4

Notice: Constant DRUPAL_CONSOLE_LAUNCHER already defined in /Users/mcpuddin/Sites/b2/vendor/drupal/console-core/src/constants.php on line 4

Call Stack:
    0.0002     225616   1. {main}() /usr/local/bin/drupal:0
    0.0021     632208   2. require('phar:///usr/local/bin/drupal/bin/drupal') /usr/local/bin/drupal:10
    0.0023     653640   3. require('phar:///usr/local/bin/drupal/bin/drupal.php') phar:///usr/local/bin/drupal/bin/drupal:3
    0.2459    5493032   4. Drupal\Console\Utils\Launcher->launch() phar:///usr/local/bin/drupal/bin/drupal.php:64
    0.2463    5509232   5. include_once('/Users/mcpuddin/Sites/b2/vendor/drupal/console/bin/drupal.php') phar:///usr/local/bin/drupal/src/Utils/Launcher.php:32
    0.2464    5510904   6. include_once('/Users/mcpuddin/Sites/b2/autoload.php') /Users/mcpuddin/Sites/b2/vendor/drupal/console/bin/drupal.php:15
    0.2465    5512576   7. require('/Users/mcpuddin/Sites/b2/vendor/autoload.php') /Users/mcpuddin/Sites/b2/autoload.php:14
    0.2466    5524208   8. ComposerAutoloaderInitDrupal8::getLoader() /Users/mcpuddin/Sites/b2/vendor/autoload.php:7
    0.2588    7344608   9. composerRequireDrupal8() /Users/mcpuddin/Sites/b2/vendor/composer/autoload_real.php:45
    0.2588    7347232  10. require('/Users/mcpuddin/Sites/b2/vendor/drupal/console-core/src/constants.php') /Users/mcpuddin/Sites/b2/vendor/composer/autoload_real.php:54
    0.2593    7347640  11. define() /Users/mcpuddin/Sites/b2/vendor/drupal/console-core/src/constants.php:4

PHP Notice:  Constant DRUPAL_CONSOLE already defined in /Users/mcpuddin/Sites/b2/vendor/drupal/console-core/src/constants.php on line 5
PHP Stack trace:
PHP   1. {main}() /usr/local/bin/drupal:0
PHP   2. require() /usr/local/bin/drupal:10
PHP   3. require() phar:///usr/local/bin/drupal/bin/drupal:3
PHP   4. Drupal\Console\Utils\Launcher->launch() phar:///usr/local/bin/drupal/bin/drupal.php:64
PHP   5. include_once() phar:///usr/local/bin/drupal/src/Utils/Launcher.php:32
PHP   6. include_once() /Users/mcpuddin/Sites/b2/vendor/drupal/console/bin/drupal.php:15
PHP   7. require() /Users/mcpuddin/Sites/b2/autoload.php:14
PHP   8. ComposerAutoloaderInitDrupal8::getLoader() /Users/mcpuddin/Sites/b2/vendor/autoload.php:7
PHP   9. composerRequireDrupal8() /Users/mcpuddin/Sites/b2/vendor/composer/autoload_real.php:45
PHP  10. require() /Users/mcpuddin/Sites/b2/vendor/composer/autoload_real.php:54
PHP  11. define() /Users/mcpuddin/Sites/b2/vendor/drupal/console-core/src/constants.php:5

Notice: Constant DRUPAL_CONSOLE already defined in /Users/mcpuddin/Sites/b2/vendor/drupal/console-core/src/constants.php on line 5

Call Stack:
    0.0002     225616   1. {main}() /usr/local/bin/drupal:0
    0.0021     632208   2. require('phar:///usr/local/bin/drupal/bin/drupal') /usr/local/bin/drupal:10
    0.0023     653640   3. require('phar:///usr/local/bin/drupal/bin/drupal.php') phar:///usr/local/bin/drupal/bin/drupal:3
    0.2459    5493032   4. Drupal\Console\Utils\Launcher->launch() phar:///usr/local/bin/drupal/bin/drupal.php:64
    0.2463    5509232   5. include_once('/Users/mcpuddin/Sites/b2/vendor/drupal/console/bin/drupal.php') phar:///usr/local/bin/drupal/src/Utils/Launcher.php:32
    0.2464    5510904   6. include_once('/Users/mcpuddin/Sites/b2/autoload.php') /Users/mcpuddin/Sites/b2/vendor/drupal/console/bin/drupal.php:15
    0.2465    5512576   7. require('/Users/mcpuddin/Sites/b2/vendor/autoload.php') /Users/mcpuddin/Sites/b2/autoload.php:14
    0.2466    5524208   8. ComposerAutoloaderInitDrupal8::getLoader() /Users/mcpuddin/Sites/b2/vendor/autoload.php:7
    0.2588    7344608   9. composerRequireDrupal8() /Users/mcpuddin/Sites/b2/vendor/composer/autoload_real.php:45
    0.2588    7347232  10. require('/Users/mcpuddin/Sites/b2/vendor/drupal/console-core/src/constants.php') /Users/mcpuddin/Sites/b2/vendor/composer/autoload_real.php:54
    0.2596    7347648  11. define() /Users/mcpuddin/Sites/b2/vendor/drupal/console-core/src/constants.php:5

PHP Notice:  Constant DRUPAL_CONSOLE_LANGUAGE already defined in /Users/mcpuddin/Sites/b2/vendor/drupal/console-core/src/constants.php on line 6
PHP Stack trace:
PHP   1. {main}() /usr/local/bin/drupal:0
PHP   2. require() /usr/local/bin/drupal:10
PHP   3. require() phar:///usr/local/bin/drupal/bin/drupal:3
PHP   4. Drupal\Console\Utils\Launcher->launch() phar:///usr/local/bin/drupal/bin/drupal.php:64
PHP   5. include_once() phar:///usr/local/bin/drupal/src/Utils/Launcher.php:32
PHP   6. include_once() /Users/mcpuddin/Sites/b2/vendor/drupal/console/bin/drupal.php:15
PHP   7. require() /Users/mcpuddin/Sites/b2/autoload.php:14
PHP   8. ComposerAutoloaderInitDrupal8::getLoader() /Users/mcpuddin/Sites/b2/vendor/autoload.php:7
PHP   9. composerRequireDrupal8() /Users/mcpuddin/Sites/b2/vendor/composer/autoload_real.php:45
PHP  10. require() /Users/mcpuddin/Sites/b2/vendor/composer/autoload_real.php:54
PHP  11. define() /Users/mcpuddin/Sites/b2/vendor/drupal/console-core/src/constants.php:6

Notice: Constant DRUPAL_CONSOLE_LANGUAGE already defined in /Users/mcpuddin/Sites/b2/vendor/drupal/console-core/src/constants.php on line 6

Call Stack:
    0.0002     225616   1. {main}() /usr/local/bin/drupal:0
    0.0021     632208   2. require('phar:///usr/local/bin/drupal/bin/drupal') /usr/local/bin/drupal:10
    0.0023     653640   3. require('phar:///usr/local/bin/drupal/bin/drupal.php') phar:///usr/local/bin/drupal/bin/drupal:3
    0.2459    5493032   4. Drupal\Console\Utils\Launcher->launch() phar:///usr/local/bin/drupal/bin/drupal.php:64
    0.2463    5509232   5. include_once('/Users/mcpuddin/Sites/b2/vendor/drupal/console/bin/drupal.php') phar:///usr/local/bin/drupal/src/Utils/Launcher.php:32
    0.2464    5510904   6. include_once('/Users/mcpuddin/Sites/b2/autoload.php') /Users/mcpuddin/Sites/b2/vendor/drupal/console/bin/drupal.php:15
    0.2465    5512576   7. require('/Users/mcpuddin/Sites/b2/vendor/autoload.php') /Users/mcpuddin/Sites/b2/autoload.php:14
    0.2466    5524208   8. ComposerAutoloaderInitDrupal8::getLoader() /Users/mcpuddin/Sites/b2/vendor/autoload.php:7
    0.2588    7344608   9. composerRequireDrupal8() /Users/mcpuddin/Sites/b2/vendor/composer/autoload_real.php:45
    0.2588    7347232  10. require('/Users/mcpuddin/Sites/b2/vendor/drupal/console-core/src/constants.php') /Users/mcpuddin/Sites/b2/vendor/composer/autoload_real.php:54
    0.2599    7347632  11. define() /Users/mcpuddin/Sites/b2/vendor/drupal/console-core/src/constants.php:6

PHP Fatal error:  Cannot redeclare calculateRealPath() (previously declared in phar:///usr/local/bin/drupal/vendor/drupal/console-core/src/functions.php:7) in /Users/mcpuddin/Sites/b2/vendor/drupal/console-core/src/functions.php on line 18
PHP Stack trace:
PHP   1. {main}() /usr/local/bin/drupal:0
PHP   2. require() /usr/local/bin/drupal:10
PHP   3. require() phar:///usr/local/bin/drupal/bin/drupal:3
PHP   4. Drupal\Console\Utils\Launcher->launch() phar:///usr/local/bin/drupal/bin/drupal.php:64
PHP   5. include_once() phar:///usr/local/bin/drupal/src/Utils/Launcher.php:32
PHP   6. include_once() /Users/mcpuddin/Sites/b2/vendor/drupal/console/bin/drupal.php:15
PHP   7. require() /Users/mcpuddin/Sites/b2/autoload.php:14
PHP   8. ComposerAutoloaderInitDrupal8::getLoader() /Users/mcpuddin/Sites/b2/vendor/autoload.php:7
PHP   9. composerRequireDrupal8() /Users/mcpuddin/Sites/b2/vendor/composer/autoload_real.php:45

Fatal error: Cannot redeclare calculateRealPath() (previously declared in phar:///usr/local/bin/drupal/vendor/drupal/console-core/src/functions.php:7) in /Users/mcpuddin/Sites/b2/vendor/drupal/console-core/src/functions.php on line 18

Call Stack:
    0.0002     225616   1. {main}() /usr/local/bin/drupal:0
    0.0021     632208   2. require('phar:///usr/local/bin/drupal/bin/drupal') /usr/local/bin/drupal:10
    0.0023     653640   3. require('phar:///usr/local/bin/drupal/bin/drupal.php') phar:///usr/local/bin/drupal/bin/drupal:3
    0.2459    5493032   4. Drupal\Console\Utils\Launcher->launch() phar:///usr/local/bin/drupal/bin/drupal.php:64
    0.2463    5509232   5. include_once('/Users/mcpuddin/Sites/b2/vendor/drupal/console/bin/drupal.php') phar:///usr/local/bin/drupal/src/Utils/Launcher.php:32
    0.2464    5510904   6. include_once('/Users/mcpuddin/Sites/b2/autoload.php') /Users/mcpuddin/Sites/b2/vendor/drupal/console/bin/drupal.php:15
    0.2465    5512576   7. require('/Users/mcpuddin/Sites/b2/vendor/autoload.php') /Users/mcpuddin/Sites/b2/autoload.php:14
    0.2466    5524208   8. ComposerAutoloaderInitDrupal8::getLoader() /Users/mcpuddin/Sites/b2/vendor/autoload.php:7
    0.2601    7345096   9. composerRequireDrupal8() /Users/mcpuddin/Sites/b2/vendor/composer/autoload_real.php:45

**Comment by ahoebeke** [comment]
I had the same problem just now. I installed drupalconsole, ran drupal init (and chose the option "without root folder" or something similar).
Then went to my Drupal root folder and tried to run "drupal init" again out of curiosity. It told me to execute two composer commands, which I did. Now I get the same error message when running "drupal init" again.

**Comment by medis** [comment]
same problem....

**Comment by adriangordon1231** [comment]
Any resolutions to this issue?

**Comment by adriangordon1231** [comment]
I was experiencing the issue because I ran composer commands using super user privileges. Once I ran them again, everything was fixed.
