### ISSUE TITLE
Failed opening required error with entity generated via generate:entity:content

### ISSUE THREAD

**Issue by clrockwell79** [hechoendrupal/drupal-console#2840]
Hello again! This is on rc6.  I have an error showing in my logs related to `$entityname.page.inc`: `Warning: include_once(): Failed opening '/some/web/modules/custom/projects/project_entity.page.inc`.  The generated file exists in `'/some/web/modules/custom/projects/src`.  I'm not sure if this is generator related _or_ if the generator is putting it where it should, and `entity-content.theme.php.twig` should include `path`.  If this is a bug, I'd just need a little push in the right direction and I'd be happy to put together a PR.

In the meantime, if someone else experiences this, the fix is simple: just add add the `path` to `my_module_theme()`.

**Comment by jmolivas** [comment]
@clrockwell79  feel free to send a PR.

**Comment by clrockwell79** [comment]
#2847

**Comment by harold20** [comment]
This is already implemented
