### ISSUE TITLE
[cache:rebuild] PHP Fatal error:  Call to undefined method Symfony\Component\DependencyInjection\Definition::setShared()

### ISSUE THREAD

**Issue by rogical** [hechoendrupal/drupal-console#2844]
xyhuang@gitlab:~/projects/companyx$ drupal cache:rebuild all

 Rebuilding cache(s), wait a moment please.
PHP Fatal error:  Call to undefined method Symfony\Component\DependencyInjection\Definition::setShared() in /srv/home/xyhuang/projects/companyx/core/lib/Drupal/Core/DependencyInjection/YamlFileLoader.php on line 168
xyhuang@gitlab:~/projects/companyx$ php -v; drupal -v; drupal site:status
PHP 5.5.9-1ubuntu4.14 (cli) (built: Oct 28 2015 01:34:46) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
    with Zend OPcache v7.0.3, Copyright (c) 1999-2014, by Zend Technologies
# Drupal Console (0.10.14) | Supports Drupal (8.0.x) | Current Drupal version (8.2.0)

Copy configuration files to user home directory.

   drupal init --override

Download, install and serve Drupal 8

   drupal chain --file=~/.console/chain/quick-start.yml

Create a new Drupal project

   drupal site:new drupal8.dev 8.0.x

Install a Drupal project

   drupal site:install

Lists all available commands

   drupal list
## Update project to the latest version.

   drupal self-update

 System Info
 戴文科技                           8.2.0  
 Access to update.php               Protected  
 Configuration files                Protected  
 Cron maintenance tasks             Last run 1 天 ago  
 Database system                    MySQL，MariaDB，Percona Server或类似的数据库  
 Database system version            5.5.41-0ubuntu0.14.04.1  
 Database updates                   已是最新  
 Drupal core update status          No update data available  
 Entity/field definitions           已是最新  
 File system                        Writable (<em>public</em> download method)  
 GD library                         2.1.1-dev  
 GD库PNG支持                        2.1.1-dev  
 PHP (multiple statement disabling) 5.5.9-1ubuntu4.14 (<a href="/admin/reports/status/php">more information</a>) 
 PHP extensions                     已启用  
 PHP memory limit                   -1 (Unlimited)  
 PHP OPcode caching                 已启用  
 Search index progress              100% (0 remaining)  
 Translation update status          缺失的翻译  
 Trusted Host Settings              未启用  
 Unicode库                          PHP Mbstring 扩展  
 Web server  
 上传进度                           未启用  
 图像工具包                         gd  
 更新通知                           已启用  
 节点的访问权限                     已禁用  
 Hash salt                          Yjs_7tlkRqn-X-HO4MlyU6J25JOoOmBviy3OeKwESZyyE72_utTkN-AHyPLYcSaeM7KxU0PT2A  
 Drupal Console                     0.10.14                                                                      

 Database connection
 Driver              mysql  
 Host                192.168.42.1                                               

 Themes
 theme_default drupal8_zymphonies_theme 
 theme_admin   seven                    

 Directories
 Site root directory      /srv/home/xyhuang/projects/companyx 
 Site temporary directory /tmp  
 Default theme directory  /themes/drupal8_zymphonies_theme  
 Admin theme directory    /core/themes/seven

**Comment by gilbertomangones** [comment]
Hi, applying the command ```$ drupal cache:rebuild all```or ```$ drupal cr all``` work.

![2019-09-18_1901](https://user-images.githubusercontent.com/6983125/65196904-b4f48380-da46-11e9-805a-94ae7b4d9f8e.png)

Details.

![2019-09-18_1725](https://user-images.githubusercontent.com/6983125/65198570-2f260780-da49-11e9-91b2-b04ec0739f06.png)

**Comment by enzolutions** [comment]
Looks like the error is solved at tested version 1.9.3
