### ISSUE TITLE
Clear all cache - main menu broken [RC6]

### ISSUE THREAD

**Issue by betoquiroga** [hechoendrupal/drupal-console#2852]
After running "drupal cache:rebuild all"  command, the main menu is broken. All link menus have /node as target.

If I run "Flush all caches" from UI  all menus are well.

Regards

**Comment by FabricioBedoya** [comment]
Same problem here!

**Comment by Jesmaster** [comment]
I have some more information on this one. Looks like "drupal cr all" and using the Clear all caches in the drupal 8 admin backend have differing effects in the menu_tree table.

If you have pages in the menu that are created using Views, the route_param_key and route_parameters columns should be blank. This is the correct functionality, see the screenshot below:

![dc_clear_all_caches_menu_tree](https://cloud.githubusercontent.com/assets/1197834/22520713/736aac8a-e883-11e6-8432-713b6da2767c.png)

When clearing the cache with the "drupal cr all" command, these blanks are filled in as if they were duplicate nodes, in my case they were all set as if they were the node I use for the homepage. This caused the menu to have the wrong active states. See the screenshot below:

![dc_cr_all_menu_tree](https://cloud.githubusercontent.com/assets/1197834/22520901/140ad156-e884-11e6-82ec-69b85a24e4ab.png)

It now thinks that the News and Whitepaper links are both node 196 when they are actually views pages.

Hopefully that will give you guys enough info to figure out the issue.

**Comment by delister** [comment]
Hi! I have same problem. I read comment to `DrupalApi::drupal_rebuild `method (Line 318):
> Rebuilds all caches even when Drupal itself does not work.

I so understand that so it should be.

I use `drush cache-rebuild` command.

**Comment by Jesmaster** [comment]
FYI, I just tested this again and it isn't happening anymore so maybe it was fixed in a newer update

**Comment by harold20** [comment]
This issue is not longer present in the current version 1.8.0
