### ISSUE TITLE
[database:dump] --optimize

### ISSUE THREAD

**Issue by novia713** [hechoendrupal/drupal-console#2892]
i think it would be nice if `database:dump` would perform some optimizing actions *before* doing the dump:
 * executing cron (optional)
 * rebuild cache
 * clearing logs
 * `mysqlcheck -u myuser -p --auto-repair --optimize ${db}`
 * perhaps `TRUNCATE` some tables

additionally i would add a `--no-data` option for dumping only the structure ....

i'm ok to work on this if it were of interest ...

**Comment by novia713** [comment]
I've been deeply thinking about this and i concluded the best solution for this is using **chain files**.
Focusing on using chain files lead us to develop short, concise & efficient commands.
Then chain them in chain files, for example like i do in https://paste.fedoraproject.org/476610/87292591/

A lateral idea of all of this would be to create a **repository of recipes** like https://deployer.org/recipes
I think it would be very useful and quite people would be happy to contribute :grinning:

**Comment by enzolutions** [comment]
@novia713 we can close this issue?

**Comment by novia713** [comment]
yes, i followed the path of chain files.
thanks!
