### ISSUE TITLE
generate:entity:content missing "Revision" methods on template

### ISSUE THREAD

**Issue by nahueldotme** [hechoendrupal/drupal-console#2928]
Looks like generate:entity:content is missing the "revision" methods on its template.

Steps to reproduce it:
1. Create a new virgin module with generate:module
2. Create a new generate:entity:content and be sure to make commands.generate.entity.content.questions.revisionable to yes.
3. You wont be able to install the module (trough module:install or web admin), because the revision methods are added to route, but no definition its found.

**Comment by GDrupal** [comment]
This could be covered by https://github.com/hechoendrupal/DrupalConsole/pull/3030 since it adds the RevisionLogInterface class.

**Comment by jmolivas** [comment]
PR merged
