### ISSUE TITLE
Views filter plugin is never invoked by Drupal

### ISSUE THREAD

**Issue by jepster** [hechoendrupal/drupal-console#2944]
I have generated a Views filter plugin:

> peter@computer ~/Websites/pbt-d8 $ drupal generate:plugin:type:yaml
> 
>  // Welcome to the Drupal Plugin Type generator
>  Enter the module name [devel]:
>  > permissions_by_term
> 
>  Plugin type class name [ExamplePlugin]:
>  > ViewsFilterPlugin
> 
>  Plugin type machine name [views_filter_plugin]:
>  > 
> 
>  Plugin file name [views.filter.plugin]:
>  > 
> 
> Generated or updated files
> 
>  1 - modules/permissions_by_term/src/ViewsFilterPluginManager.php
>  2 - modules/permissions_by_term/src/ViewsFilterPluginManagerInterface.php
>  3 - modules/permissions_by_term/permissions_by_term.services.yml
>  4 - modules/permissions_by_term/permissions_by_term.views.filter.plugin.yml
> peter@computer ~/Websites/pbt-d8 

Afterwards I have cleared all caches and set Xdebug breakpoints in the methods at modules/permissions_by_term/src/ViewsFilterPluginManager.php. The debugger never halts in any method - because it's just not invoked. The "permissions_by_term" module is definitely enabled.

What am I doing wrong?

**Comment by enzolutions** [comment]
Hi @jepster 

After following the instruction provided at [#2943]  in my local machine, I could say that you are doing an incorrect approach.

Using Drupal Console project I can get a list of plugin available, what you did was create a new plugin type YAML with a class named ViewFilter, not there is not related with views itself.

You could do that in your machine executing the command

```
drupal plugin:debug | grep views
```
You could get an output similar to below image,

![screen shot 2016-11-16 at 1 25 14 pm](https://cloud.githubusercontent.com/assets/907914/20362283/937a1688-ac00-11e6-835f-758188942df2.png)

What I think you are trying to do is an implementation of plugin **views.filter**

Please check and let me know.

**Comment by jepster** [comment]
I have created the filter in the following way:

> peter@DESKTOP-UNMGSSF:/mnt/c/Users/peter/Dev/pbt-d8/modules/permissions_by_term$ drupal generate:plugin:type:yaml

 // Welcome to the Drupal Plugin Type generator
 Enter the module name [permissions_by_term]:
 >

 Plugin type class name [ExamplePlugin]:
 > ViewsFilter

 Plugin type machine name [views_filter]:
 >

 Plugin file name [views.filter]:
 >

Generated or updated files

 1 - modules/permissions_by_term/src/ViewsFilterManager.php
 2 - modules/permissions_by_term/src/ViewsFilterManagerInterface.php
 3 - modules/permissions_by_term/permissions_by_term.services.yml
 4 - modules/permissions_by_term/permissions_by_term.views.filter.yml
peter@DESKTOP-UNMGSSF:/mnt/c/Users/peter/Dev/pbt-d8/modules/permissions_by_term$

Where do I implement the actual filtering then?

**Comment by harold20** [comment]
The command work as expected using 1.8.0
