### ISSUE TITLE
Drupal Console can no longer be installed on Drupal 8.3.x

### ISSUE THREAD

**Issue by davidbarratt** [hechoendrupal/drupal-console#2987]
I'm trying to install Console on Drupal 8.3.x and I get this error:
```
$ composer require drupal/console:^1.0.0-rc10
You are running composer with xdebug enabled. This has a major impact on runtime performance. See https://getcomposer.org/xdebug
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Can only install one of: symfony/http-foundation[2.8.x-dev, v3.1.7].
    - Can only install one of: symfony/http-foundation[v3.1.7, 2.8.x-dev].
    - Can only install one of: symfony/http-foundation[2.8.x-dev, v3.1.7].
    - drupal/console 1.0.0-rc10 requires symfony/http-foundation ~2.8 -> satisfiable by symfony/http-foundation[2.8.x-dev].
    - Installation request for drupal/console ^1.0.0-rc10 -> satisfiable by drupal/console[1.0.0-rc10].
    - Installation request for symfony/http-foundation (locked at v3.1.7, required as >=3.1.6 <4.0) -> satisfiable by symfony/http-foundation[v3.1.7].


Installation failed, reverting ./composer.json to its original content.
````

It looks like this is caused by https://www.drupal.org/node/2743809

**Comment by naveenvalecha** [comment]
Confirming that this is caused by https://www.drupal.org/node/2743809

**Comment by jmolivas** [comment]
@davidbarratt & @naveenvalecha correct my if I am wrong. Updating DrupalConsole dependencies to `"~2.8|~3.0"` should fix this?

**Comment by davidbarratt** [comment]
@jmolivas,

Assuming Drupal console works with Symfony 3.1 components, then yes, I believe that should resolve the issue. :)

**Comment by jmolivas** [comment]
Related PRs
https://github.com/hechoendrupal/DrupalConsole/pull/2988
https://github.com/hechoendrupal/drupal-console-core/pull/96

**Comment by hansfn** [comment]
Observation: Drupal core 8.2.4 installs 2.8.15 Symfony components and Drupal Console reuses these (if you don't install globally), and then adds some 3.1.8 Symfony components. I guess it is thanks to Symfony that this mixing of versions works?

**Comment by jmolivas** [comment]
You should not install DrupalConsole that can have unexpected behavior.

What you install global is the Launcher aka global executable.

**Comment by hansfn** [comment]
I'm using drupal-composer/drupal-project which includes Drupal Console (and I have installed the launcher globally). I just assumed that you also could have a global non-launcher installation ... 

Anyway, the purpose of my comment was to get some feedback on the mixing of Symfony versions. Is it safe because the Symfony people is ensuring that? I would have expected Drupal core and Drupal Console to be in sync when it comes to Symfony. 

PS! If this is obvious stuff/discussed earlier, feel free to post a link so I can read up on this. I'm clearly not a Symfony expert ;-)

**Comment by jmolivas** [comment]
I tested Drupal + Drupal Console with a mix of 2.8.x & 3.1.x while using `drupal-composer/drupal-project` and `acquia/lightning` and the sites works fine. Once I updated some components to 3.2.x then things start to break.

**Comment by hansfn** [comment]
Which is why I wonder if Drupal Console shouldn't follow Drupal core? Anyway, your testing indicates that such mixing doesn't work in general.

**Comment by jmolivas** [comment]
We are trying to follow Drupal core and sometimes mostly at the beginning of the release cycle used to feel like feels like this:

![alt tag](http://cdn.smosh.com/sites/default/files/2015/03/costume-run.gif)

DrupalConsole master and our release are in sync with Drupal core stable releases to try avoiding api breaks on every release.

I am planning to use the DrupalConsole development branch to sync with Drupal core dev like in this case 8.3.

**Comment by harold20** [comment]
This issue is not longer present in the current version 1.8.0
