### ISSUE TITLE
Translations for custom commands

### ISSUE THREAD

**Issue by ternary-Operator** [hechoendrupal/drupal-console#3010]
(Asked twice via gitter.im) Hoping for a reply now.

How and where is it possible to add translation files for custom commands?

The CommandGeneratorCommand adds a file to {module}/console/translation/en/xyz.yml, which seems to be wrong.

I've tried to use the "translation:" tasks with no outcome. I still get only the key back from the translation method.

**Comment by ergonlogic** [comment]
I'm seeing the same behaviour on a newly generated command.

**Comment by ergonlogic** [comment]
AFAICT, no CommandTrait::translator is being set, so we're just being returned the key as per: https://github.com/hechoendrupal/drupal-console-core/blob/master/src/Command/Shared/CommandTrait.php#L38.

**Comment by jmolivas** [comment]
@ergonlogic I will take a look at this.

**Comment by beltofte** [comment]
Any updates to this issue? Facing the same issue with custom console commands.

**Comment by jmolivas** [comment]
@ternary-Operator @ergonlogic @beltofte This is fixed and will be released on next version RC-13.

**Comment by jmolivas** [comment]
Since you mentioned you have custom commands you may want to take a look at this breaking change on the `drupal/console-core` namespace project. https://github.com/hechoendrupal/drupal-console/issues/3049 The how-to-fix is also included on the link.

**Comment by beltofte** [comment]
@jmolivas Thanks for the heads up. When are you planning to release RC13?

**Comment by jmolivas** [comment]
Fixed with https://github.com/hechoendrupal/drupal-console/releases/tag/1.0.0-rc13

Make sure your translation file is for a module named demo ie: 
* File name and location `demo/console/translations/en/demo.default.yml`
* Content
```
description: 'Drupal Console generated command.'
options: {}
arguments: {}
messages:
    success: 'I am a new generated command.'
```
* Command class code:
```
<?php

namespace Drupal\demo\Command;

use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Console\Command\Command;
use Drupal\Console\Core\Command\Shared\CommandTrait;
use Drupal\Console\Core\Style\DrupalStyle;
use Drupal\Console\Annotations\DrupalCommand;

/**
 * Class DefaultCommand.
 *
 * @package Drupal\demo
 *
 * @DrupalCommand (
 *     extension="demo",
 *     extensionType="module"
 * )
 */
class DefaultCommand extends Command {

  use CommandTrait;

  /**
   * {@inheritdoc}
   */
  protected function configure() {
    $this
      ->setName('demo:default')
      ->setDescription($this->trans('commands.demo.default.description'));
  }

  /**
   * {@inheritdoc}
   */
  protected function execute(InputInterface $input, OutputInterface $output) {
    $io = new DrupalStyle($input, $output);

    $io->info($this->trans('commands.demo.default.messages.success'));
  }
}

```
