### ISSUE TITLE
Exception with Drupal Console RC 11

### ISSUE THREAD

**Issue by bpresles** [hechoendrupal/drupal-console#3017]
I've the following exception when using Drupal Console RC 11:
```
TypeError: Argument 2 passed to Drupal\Console\Command\Chain\ChainCommand::__construct() must be an instance of Drupal\Console\Utils\ChainDiscovery, instance of Drupal\Console\Utils\ConfigurationManager given in /srv/www/drupal/src/vendor/drupal/console-core/src/Command/Chain/ChainCommand.php on line 49 #0 [internal function]: Drupal\Console\Command\Chain\ChainCommand->__construct(Object(Drupal\Console\Utils\ChainQueue), Object(Drupal\Console\Utils\ConfigurationManager), '/srv/www/drupal...', Object(Drupal\Console\Extension\Manager))
#1 /srv/www/drupal/src/vendor/symfony/dependency-injection/ContainerBuilder.php(928): ReflectionClass->newInstanceArgs(Array)
#2 /srv/www/drupal/src/vendor/symfony/dependency-injection/ContainerBuilder.php(468): Symfony\Component\DependencyInjection\ContainerBuilder->createService(Object(Symfony\Component\DependencyInjection\Definition), 'console.chain')
#3 /srv/www/drupal/src/vendor/drupal/console/src/Application.php(149): Symfony\Component\DependencyInjection\ContainerBuilder->get('console.chain')
#4 /srv/www/drupal/src/vendor/drupal/console/src/Application.php(39): Drupal\Console\Application->registerCommands()
#5 /srv/www/drupal/src/vendor/symfony/console/Application.php(124): Drupal\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /srv/www/drupal/src/vendor/drupal/console/bin/drupal.php(69): Symfony\Component\Console\Application->run()
#7 /srv/www/drupal/src/vendor/drupal/console/bin/drupal(4): require('/srv/www/drupal...')
#8 {main}
TypeError: Argument 2 passed to Drupal\Console\Command\Chain\ChainCommand::__construct() must be an instance of Drupal\Console\Utils\ChainDiscovery, instance of Drupal\Console\Utils\ConfigurationManager given in Drupal\Console\Command\Chain\ChainCommand->__construct() (line 49 of /srv/www/drupal/src/vendor/drupal/console-core/src/Command/Chain/ChainCommand.php).
```
I installed it from scratch using the follwing command:
```
composer require drupal/console:1.0.0-rc11 \
--prefer-dist \
--optimize-autoloader \
--sort-packages
```
Also I tried to do: 
composer update --with-dependencies

This didn't work.

Also I checked that the drupal/console-core and drupal/console-en dependencies are also 1.0.0-rc11 versions, which is the case.

Note that rc10 work fine (even though I need to force console-core and console-en to rc10 to make it working, which is logical after all).

**Comment by jmolivas** [comment]
@bpresles Are you using the Launcher aka global executable? if yes make sure you update it to latest RC-11 as well

**Comment by jmolivas** [comment]
@bpresles RC-12 was tagged and now including forcing dependencies to latest version.
https://github.com/hechoendrupal/DrupalConsole/blob/1.0.0-rc12/composer.json#L40

**Comment by jmolivas** [comment]
@bpresles can you confirm this issue continue to happening you after updating to RC12 ?

**Comment by bpresles** [comment]
On RC-12 I have a different Exception on Drupal\Console\Command\Site\DebugCommand::_construct() of console-core.

$ drupal list
TypeError: Argument 1 passed to Drupal\Console\Command\Site\DebugCommand::__construct() must be an instance of Drupal\Console\Utils\ConfigurationManager, instance of Drupal\Console\Utils\Site given in /srv/www/drupal/src/vendor/drupal/console-core/src/Command/Site/DebugCommand.php on line 37 #0 [internal function]: Drupal\Console\Command\Site\DebugCommand->__construct(Object(Drupal\Console\Utils\Site), Object(Drupal\Console\Utils\ConfigurationManager))
#1 /srv/www/drupal/src/vendor/symfony/dependency-injection/ContainerBuilder.php(928): ReflectionClass->newInstanceArgs(Array)
#2 /srv/www/drupal/src/vendor/symfony/dependency-injection/ContainerBuilder.php(468): Symfony\Component\DependencyInjection\ContainerBuilder->createService(Object(Symfony\Component\DependencyInjection\Definition), 'console.site_de...')
#3 /srv/www/drupal/src/vendor/drupal/console/src/Application.php(149): Symfony\Component\DependencyInjection\ContainerBuilder->get('console.site_de...')
#4 /srv/www/drupal/src/vendor/drupal/console/src/Application.php(39): Drupal\Console\Application->registerCommands()
#5 /srv/www/drupal/src/vendor/symfony/console/Application.php(124): Drupal\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /srv/www/drupal/src/vendor/drupal/console/bin/drupal.php(69): Symfony\Component\Console\Application->run()
#7 /srv/www/drupal/src/vendor/drupal/console/bin/drupal(4): require('/srv/www/drupal...')
#8 {main}
TypeError: Argument 1 passed to Drupal\Console\Command\Site\DebugCommand::__construct() must be an instance of Drupal\Console\Utils\ConfigurationManager, instance of Drupal\Console\Utils\Site given in Drupal\Console\Command\Site\DebugCommand->__construct() (line 37 of /srv/www/drupal/src/vendor/drupal/console-core/src/Command/Site/DebugCommand.php).

I've tried to remove the vendor/ folder completely and clear the composer cache, than executed a "composer update --with-dependencies" and still it gives this exception.

**Comment by jmolivas** [comment]
@bpresles did you update the Launcher to the latest RC-12. You can do this by executing outside of your drupal site directory.

```
drupal self-update
```

**Comment by bpresles** [comment]
I'm not using the launcher. I just installed Drupal Console through composer adding the following line to my composer.json require section and with the vendor/.bin folder in my PATH:

"drupal/console": "1.0.0-rc12"

Than running "composer update --with-dependencies"

Also I tried removing the vendor/ folder completely and running the "composer update --with-dependencies" again.
In both cases I get the exception I mentionned.

I tried, just in case, to run "drupal self-update" outside of my Drupal site folder, and this only resulted to:

 DrupalConsole must be executed within a Drupal Site.

If I try to run in inside my Drupal site folder, the exception I mentionned in my previous command raise again.

**Comment by jmolivas** [comment]
@bpresles you installed using `composer global require`? how did you got the drupal outside of a `drupal` site if you do not used the Launcer aka the global installer?

**Comment by bpresles** [comment]
@jmolivas 
I installer using composer require (locally to my project, not globally), then I added the vendor/bin directory to my PATH environment variable, nothing more, just that.

**Comment by harold20** [comment]
This issue is no longer present in the current version 1.8.0
