### ISSUE TITLE
[contrib] Rename console-core namespace references on contrib modules.

### ISSUE THREAD

**Issue by jmolivas** [hechoendrupal/drupal-console#3049]
In preparation for the stable release. We required to change the project namespaces for the split repositories.

This is the latest API change that will break integrations and the main reasons we have not yet tagged an stable release.

### Drupal Console Core 
https://github.com/hechoendrupal/drupal-console-core/blob/master/composer.json#L63

### Drupal Console Launcher (this do not affect contributed modules)
https://github.com/hechoendrupal/drupal-console-launcher/blob/master/composer.json#L61

If you have a contributed module providing DrupalConsole integration ping us. Next release will break your code you can find instructions below. 

## Required code changes:
* CommandTrait
```
use Drupal\Console\Command\Shared\CommandTrait;
use Drupal\Console\Core\Command\Shared\CommandTrait;
```
* ContainerAwareCommandTrait
```
use Drupal\Console\Command\Shared\ContainerAwareCommandTrait;
use Drupal\Console\Core\Command\Shared\ContainerAwareCommandTrait;
```
* DrupalStyle
```
use Drupal\Console\Style\DrupalStyle;
use Drupal\Console\Core\Style\DrupalStyle;
```
* Generator
```
use Drupal\Console\Generator\Generator;
use Drupal\Console\Core\Generator\Generator;
```
* TwigRenderer
```
use Drupal\Console\Utils\TwigRenderer;
use Drupal\Console\Core\Utils\TwigRenderer;
```
* ChainQueue
```
use Drupal\Console\Utils\ChainQueue;
use Drupal\Console\Core\Utils\ChainQueue;
```
* ShellProcess
```
use Drupal\Console\Utils\ShellProcess;
use Drupal\Console\Core\Utils\ShellProcess;
```
* StringConverter
```
use Drupal\Console\Utils\StringConverter;
use Drupal\Console\Core\Utils\StringConverter;
```
* InputTrait
```
use Drupal\Console\Command\Shared\InputTrait;
use Drupal\Console\Core\Command\Shared\InputTrait;
```
* ConfigurationManager
```
use Drupal\Console\Utils\ConfigurationManager;
use Drupal\Console\Core\Utils\ConfigurationManager;
```
* TranslatorManager
```
use Drupal\Console\Utils\TranslatorManager;
use Drupal\Console\Utils\TranslatorManager;
```
* NestedArray
```
use Drupal\Console\Utils\NestedArray;
use Drupal\Console\Core\Utils\NestedArray;
```
*  ArgvInputReader
```
use Drupal\Console\Utils\ArgvInputReader;
use Drupal\Console\Core\Utils\ArgvInputReader;
```
* DrupalConsoleCore
```
use Drupal\Console\Bootstrap\DrupalConsoleCore;
use Drupal\Console\Core\Bootstrap\DrupalConsoleCore;
```

This is the list of the known contributed modules providing commands, we have identified and we are planning to help update and fix to be RC-13 compatible.

- [ ] Metatag @damienmckenna - [d.o. issue and patch](https://www.drupal.org/node/2840222)
- [ ] Webprofiler @lussoluca - [d.o. issue and patch](https://www.drupal.org/node/2840230)
- [ ] Drupal Commerce @bojanz -- [no commads found :(]
- [ ] Configuration Split - [d.o. issue and patch](https://www.drupal.org/node/2840233)
- [ ] Scheduled Updates @tedbow - [d.o. issue and patch](https://www.drupal.org/node/2840235) 
- [ ] Drupal Remote Dashboard @jurgenhaas - [d.o. issue and patch](https://www.drupal.org/node/2840224)

Our goal is to help fix those integrations once RC-13 is released on January 3, 2017.

> NOTE: If you know of another module(s) providing DrupalConsole integration please let us know by commenting on this issue.

**Comment by jurgenhaas** [comment]
[Drupal Remote Dashboard](https://www.drupal.org/project/drd) also provides quite a few commands and I'm planning a release candidate the next couple of days. I may hold off if I got a better understanding on you timeframe for your RC-13.

**Comment by jmolivas** [comment]
@jurgenhaas thanks for letting us now, we will update the issue.

Next release RC-13 is scheduled for Jan 3rd 2017.

**Comment by jmolivas** [comment]
I wrote an script to have this fixed, code is at this gist:
https://gist.github.com/jmolivas/96e842a7c598ee0df262ee3ac50fd9c9

Instructions to use:
```
# change to drupal site where module is installed to update and test
cd /path/to/drupal-site

# download file
curl https://gist.githubusercontent.com/jmolivas/96e842a7c598ee0df262ee3ac50fd9c9/raw/7e7e1aff75a283f5d8b5c0a8f205484f8a654d1e/fix-rc13.php > fix-rc13.php

# execute script
php fix-rc13.php

# confirm module is functional executing drupal console
drupal list 
#or
vendor/bin/drupal
```

NOTE: Enter path of module to process ex: `web/modules/contrib/metatag/`

<img width="910" alt="fix-rc13" src="https://cloud.githubusercontent.com/assets/366275/21578969/102ea99c-cf4b-11e6-8057-85dccd66f6b8.png">

**Comment by jmolivas** [comment]
The DrupalConsole RC-13 is out.
