### ISSUE TITLE
Does not work with Drupal Composer Project

### ISSUE THREAD

**Issue by ArtuGit** [hechoendrupal/drupal-console#3058]
I use 'drupal-composer/drupal-project'.

I perform 'drupal' inside a website folder and I have:

```
Recoverable fatal error: Argument 1 passed to Drupal\Console\Command\Site\DebugCommand::__construct() must be an instance of Drupal\Console\Utils\ConfigurationManager, instance of Drupal\Console\Utils\Site given in phar:///usr/local/bin/drupal/vendor/drupal/console-core/src/Command/Site/DebugCommand.php on line 39 #0 /var/www/drupalvm/mysite/web/core/includes/bootstrap.inc(548): _drupal_error_handler_real(4096, 'Argument 1 pass...', 'phar:///usr/loc...', 39, Array)
#1 phar:///usr/local/bin/drupal/vendor/drupal/console-core/src/Command/Site/DebugCommand.php(39): _drupal_error_handler(4096, 'Argument 1 pass...', 'phar:///usr/loc...', 39, Array)
#2 [internal function]: Drupal\Console\Command\Site\DebugCommand->__construct(Object(Drupal\Console\Utils\Site), Object(Drupal\Console\Utils\ConfigurationManager))
#3 phar:///usr/local/bin/drupal/vendor/symfony/dependency-injection/ContainerBuilder.php(928): ReflectionClass->newInstanceArgs(Array)
#4 phar:///usr/local/bin/drupal/vendor/symfony/dependency-injection/ContainerBuilder.php(468): Symfony\Component\DependencyInjection\ContainerBuilder->createService(Object(Symfony\Component\DependencyInjection\Definition), 'console.site_de...')
#5 /var/www/drupalvm/mysite/vendor/drupal/console/src/Application.php(143): Symfony\Component\DependencyInjection\ContainerBuilder->get('console.site_de...')
#6 /var/www/drupalvm/mysite/vendor/drupal/console/src/Application.php(38): Drupal\Console\Application->registerCommands()
#7 phar:///usr/local/bin/drupal/vendor/symfony/console/Application.php(124): Drupal\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /var/www/drupalvm/mysite/vendor/drupal/console/bin/drupal.php(70): Symfony\Component\Console\Application->run()
#9 phar:///usr/local/bin/drupal/src/Utils/Launcher.php(28): include_once('/var/www/drupal...')
#10 phar:///usr/local/bin/drupal/bin/drupal.php(87): Drupal\Console\Utils\Launcher->launch('/var/www/drupal...')
#11 phar:///usr/local/bin/drupal/bin/drupal(3): require('phar:///usr/loc...')
#12 /usr/local/bin/drupal(10): require('phar:///usr/loc...')
#13 {main}
Recoverable fatal error: Argument 1 passed to Drupal\Console\Command\Site\DebugCommand::__construct() must be an instance of Drupal\Console\Utils\ConfigurationManager, instance of Drupal\Console\Utils\Site given in Drupal\Console\Command\Site\DebugCommand->__construct() (line 39 of phar:///usr/local/bin/drupal/vendor/drupal/console-core/src/Command/Site/DebugCommand.php).

```

What is the problem?

**Comment by jmolivas** [comment]
@ArtuGit which version of the project do you have installed?

**Comment by jmolivas** [comment]
@ArtuGit can you confirm  you have RC12 on the site and the launcher?

**Comment by ArtuGit** [comment]
@jmolivas 
Yes, 
Drupal Console Launcher version 1.0.0-rc12

**Comment by ArtuGit** [comment]
And "drupal/console": "~1.0" in the composer.json (of the Drupal Composer Project)

**Comment by jmolivas** [comment]
try executing within your site then copy/paste results please
```
 composer show | grep drupal/console
```

**Comment by ArtuGit** [comment]
_drupal/console                        1.0.0-rc10      The Drupal CLI. A tool to generate b...
drupal/console-core                   1.0.0-rc10      Drupal Console Core
drupal/console-en                     1.0.0-rc9       Drupal Console English Language_

**Comment by jmolivas** [comment]
Try updating executing:
```
composer update drupal/console 
```

**Comment by ArtuGit** [comment]
Now I have _drupal/console 1.0.0-rc11_  and a message:

```
[Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException]  
You have requested a non-existent service "console.chain_discovery".        

```

**Comment by jmolivas** [comment]
@ArtuGit can you try updating to latest RC-13?

**Comment by ArtuGit** [comment]
How can I do it correctly (for the both)?

**Comment by jmolivas** [comment]
@ArtuGit https://gist.github.com/jmolivas/a0970e1ea252ecb852fe8c7182d85d3e

**Comment by ArtuGit** [comment]
@jmolivas, thanks.

After 'drupal self-update' I have:
_[OK] Updated from version "1.0.0-rc12" to version "1.0.0-rc13"_.

When I perform 'drupal' inside the website folder I have:
_PHP Fatal error:  Trait 'Drupal\Console\Command\Shared\InputTrait' not found in /var/www/drupalvm//vendor/drupal/console/src/Command/Generate/ControllerCommand.php on line 32
Fatal error: Trait 'Drupal\Console\Command\Shared\InputTrait' not found in /var/www/drupalvm/mysite/vendor/drupal/console/src/Command/Generate/ControllerCommand.php on line 32_
((

**Comment by jmolivas** [comment]
@ArtuGit did you updated DC within the site too? execute this form the site root
```
 composer show | grep drupal/console
```

**Comment by ArtuGit** [comment]
@jmolivas 
There was  'Nothing to install or update".
Currently, I still have:

_drupal/console                        1.0.0-rc11      The Drupal CLI. A tool to generate boilerplate code...
drupal/console-core                   1.0.0-rc10      Drupal Console Core
drupal/console-en                     1.0.0-rc9       Drupal Console English Language_

**Comment by jmolivas** [comment]
@ArtuGit Latest release is RC-13 not sure why executing form your site root `composer update drupal/console` or `composer update drupal/console --with-dependencies` does not update your site. Maybe you have a fixed version presented at your `composer.json` file

**Comment by ArtuGit** [comment]
`update drupal/console --with-dependencies` works and now `drupal` works too!
Thank you a lot. ))

**Comment by mmwebaze** [comment]
Hi,
I am getting this error

Fatal error: Cannot use Drupal\Console\Core\Bootstrap\DrupalConsoleCore as DrupalConsoleCore because the name is already in use

with 

drupal/console                        1.0.0-rc16
drupal/console-core                   1.0.0-rc16
drupal/console-en                     1.0.0-rc16

**Comment by jmolivas** [comment]
@mmwebaze what are your OS and PHP versions?

**Comment by jmolivas** [comment]
@mmwebaze do you mind to share how did you fix it?

**Comment by mmwebaze** [comment]
@jmolivas update drupal/console --with-dependencies worked for me.

**Comment by bonrita** [comment]
`PHP Fatal error:  Call to undefined function _drupal_error_handler_real() in /home/bona/php_projects/drupal8/core/includes/bootstrap.inc on line 542
PHP Stack trace:
PHP   1. {main}() /usr/local/bin/drupal:0
PHP   2. require() /usr/local/bin/drupal:10
PHP   3. require() phar:///usr/local/bin/drupal/bin/drupal:3
PHP   4. Drupal\Console\Launcher\Utils\Launcher->launch() phar:///usr/local/bin/drupal/bin/drupal.php:86
PHP   5. include_once() phar:///usr/local/bin/drupal/src/Utils/Launcher.php:30
PHP   6. Drupal\Console\Bootstrap\Drupal->boot() /home/bona/php_projects/drupal8/vendor/drupal/console/bin/drupal.php:51
PHP   7. Drupal\Console\Bootstrap\DrupalKernel::createFromRequest() /home/bona/php_projects/drupal8/vendor/drupal/console/src/Bootstrap/Drupal.php:91
PHP   8. Drupal\Core\DrupalKernel->handle() /home/bona/php_projects/drupal8/vendor/drupal/console/src/Bootstrap/DrupalKernel.php:29
PHP   9. Drupal\Core\DrupalKernel->boot() /home/bona/php_projects/drupal8/core/lib/Drupal/Core/DrupalKernel.php:636
PHP  10. Drupal\Core\DrupalKernel->initializeContainer() /home/bona/php_projects/drupal8/core/lib/Drupal/Core/DrupalKernel.php:441
PHP  11. Drupal\Core\DrupalKernel->compileContainer() /home/bona/php_projects/drupal8/core/lib/Drupal/Core/DrupalKernel.php:824
PHP  12. Drupal\Core\DependencyInjection\YamlFileLoader->load() /home/bona/php_projects/drupal8/core/lib/Drupal/Core/DrupalKernel.php:1169
PHP  13. Drupal\Core\DependencyInjection\YamlFileLoader->parseDefinitions() /home/bona/php_projects/drupal8/core/lib/Drupal/Core/DependencyInjection/YamlFileLoader.php:100
PHP  14. Drupal\Core\DependencyInjection\YamlFileLoader->parseDefinition() /home/bona/php_projects/drupal8/core/lib/Drupal/Core/DependencyInjection/YamlFileLoader.php:120
PHP  15. spl_autoload_call() /home/bona/php_projects/drupal8/core/lib/Drupal/Core/DependencyInjection/YamlFileLoader.php:153
PHP  16. Composer\Autoload\ClassLoader->loadClass() /home/bona/php_projects/drupal8/core/lib/Drupal/Core/DependencyInjection/YamlFileLoader.php:153
PHP  17. Composer\Autoload\includeFile() phar:///usr/local/bin/drupal/vendor/composer/ClassLoader.php:322
PHP  18. _drupal_error_handler() phar:///usr/local/bin/drupal/vendor/composer/ClassLoader.php:440
`

drupal/console                        1.0.0-rc16         The Drupal CLI. A tool to generate boilerplate code, interact with and debug Drupal.
drupal/console-core                   1.0.0-rc16         Drupal Console Core
drupal/console-en                     1.0.0-rc16         Drupal Console English Language
drupal/console-extend-plugin          0.4.0              Drupal Console Extend Plugin

I also tried "composer update drupal/console --with-dependencies¨ 

The console is not working for me I am wondering what l am missing. Could some one help, please.

**Comment by mmwebaze** [comment]
@bonrita this might be a path issue. Make sure you don't have multiple composer installations in your path. I had that as an issue and when I resolved that it worked.

**Comment by bonrita** [comment]
@mmwebaze Thanks for the reply. 
The problem is fixed when l upgrade from drupal 8.0 to 8.2.

**Comment by geolivero** [comment]
Fatal error: Call to undefined function Drupal\Console\Launcher\Utils\pcntl_exec() in phar:///usr/local/bin/drupal/src/Utils/Launcher.php on line 34

Found out today that the command "drupal" doesn't work anymore after Drupal upgrade 8.3.2.
Thank for all your help.

Don't know what else todo. I tried:
- composer update drupal/console --with-dependencies
- drupal self-update
- also tried dowloading drupal/console-launcher but with no success

Output of **composer show | grep drupal/console**
drupal/console                        1.0.0-rc19         The Drupal CLI. ...
drupal/console-core                   1.0.0-rc19         Drupal Console Core
drupal/console-en                     1.0.0-rc19         Drupal Console E...
drupal/console-extend-plugin          0.6.0              Drupal Console E...
drupal/console-launcher               1.0.0-rc19         Drupal Console l...

composer.json
{
    "name": "drupal/drupal",
    "description": "Drupal is an open source content management platform powering millions of websites and applications.",
    "type": "project",
    "license": "GPL-2.0+",
    "require": {
        "composer/installers": "^1.0.24",
        "wikimedia/composer-merge-plugin": "~1.3",
        "stecman/symfony-console-completion": "^0.7.0",
        "symfony/dom-crawler": "2.8.11",
        "drupal/core": "^8.3.2",
        "drush/drush": "~8.0",
        "webmozart/path-util": "^2.3",
        "drupal/console-launcher": "^1.0@RC",
        "drupal/console": "~1.0"
    },
    "replace": {
        "drupal/core": "~8.3"
    },
    "conflict": {
        "drupal/drupal": "*"
    },
    "minimum-stability": "dev",
    "prefer-stable": true,
    "config": {
        "preferred-install": "dist",
        "autoloader-suffix": "Drupal8"
    },
    "extra": {
        "_readme": [
            "By default Drupal loads the autoloader from ./vendor/autoload.php.",
            "To change the autoloader you can edit ./autoload.php.",
            "This file specifies the packages.drupal.org repository.",
            "You can read more about this composer repository at:",
            "https://www.drupal.org/node/2718229"
        ],
        "merge-plugin": {
            "include": [
                "core/composer.json"
            ],
            "recurse": false,
            "replace": false,
            "merge-extra": false
        },
        "installer-paths": {
            "core": ["type:drupal-core"],
            "modules/contrib/{$name}": ["type:drupal-module"],
            "profiles/contrib/{$name}": ["type:drupal-profile"],
            "themes/contrib/{$name}": ["type:drupal-theme"],
            "drush/contrib/{$name}": ["type:drupal-drush"],
            "modules/custom/{$name}": ["type:drupal-custom-module"],
            "themes/custom/{$name}": ["type:drupal-custom-theme"]
        }
    },
    "autoload": {
        "psr-4": {
            "Drupal\\Core\\Composer\\": "core/lib/Drupal/Core/Composer"
        }
    },
    "scripts": {
        "pre-autoload-dump": "Drupal\\Core\\Composer\\Composer::preAutoloadDump",
        "post-autoload-dump": [
          "Drupal\\Core\\Composer\\Composer::ensureHtaccess"
        ],
        "post-package-install": "Drupal\\Core\\Composer\\Composer::vendorTestCodeCleanup",
        "post-package-update": "Drupal\\Core\\Composer\\Composer::vendorTestCodeCleanup"
    },
    "repositories": [
        {
            "type": "composer",
            "url": "https://packages.drupal.org/8"
        }
    ]
}

**Comment by sakonn** [comment]
Hello guys, 
I have similar issue. I tried instructions above but nothing is working for me. 
When I run any drupal console command I get this:

`[23-May-2017 14:38:16 UTC] PHP Fatal error:  Uncaught Error: Call to undefined method Drupal\Console\Core\Utils\DrupalFinder::getVendorDir() in /var/www/html/docroot/vendor/drupal/console-core/src/Utils/DrupalFinder.php:24
Stack trace:
#0 /var/www/html/docroot/vendor/drupal/console/bin/drupal.php(37): Drupal\Console\Core\Utils\DrupalFinder->locateRoot('/var/www/html/d...')
#1 phar:///usr/local/bin/drupal/src/Utils/Launcher.php(28): include_once('/var/www/html/d...')
#2 phar:///usr/local/bin/drupal/bin/drupal.php(91): Drupal\Console\Utils\Launcher->launch('/var/www/html/d...')
#3 phar:///usr/local/bin/drupal/bin/drupal(3): require('phar:///usr/loc...')
#4 /usr/local/bin/drupal(10): require('phar:///usr/loc...')
#5 {main}
  thrown in /var/www/html/docroot/vendor/drupal/console-core/src/Utils/DrupalFinder.php on line 24

Fatal error: Uncaught Error: Call to undefined method Drupal\Console\Core\Utils\DrupalFinder::getVendorDir() in /var/www/html/docroot/vendor/drupal/console-core/src/Utils/DrupalFinder.php:24
Stack trace:
#0 /var/www/html/docroot/vendor/drupal/console/bin/drupal.php(37): Drupal\Console\Core\Utils\DrupalFinder->locateRoot('/var/www/html/d...')
#1 phar:///usr/local/bin/drupal/src/Utils/Launcher.php(28): include_once('/var/www/html/d...')
#2 phar:///usr/local/bin/drupal/bin/drupal.php(91): Drupal\Console\Utils\Launcher->launch('/var/www/html/d...')
#3 phar:///usr/local/bin/drupal/bin/drupal(3): require('phar:///usr/loc...')
#4 /usr/local/bin/drupal(10): require('phar:///usr/loc...')
#5 {main}
  thrown in /var/www/html/docroot/vendor/drupal/console-core/src/Utils/DrupalFinder.php on line 24`
 
The `composer show | grep drupal/console` return this:
`drupal/console                        1.0.0-rc19         The Drupal CLI. A tool to generate boilerplate code, interact with and debug Drupal.
drupal/console-core                   1.0.0-rc19         Drupal Console Core
drupal/console-en                     1.0.0-rc19         Drupal Console English Language
drupal/console-extend-plugin          0.6.0              Drupal Console Extend Plugin`
