### ISSUE TITLE
Invalid version string exception when installing with composer

### ISSUE THREAD

**Issue by arnoldbird** [hechoendrupal/drupal-console#3059]
When I run...
`composer require drupal/console:~1.0 --prefer-dist`

...I get...
```
...
sebastian/global-state suggests installing ext-uopz (*)
phpunit/php-code-coverage suggests installing ext-xdebug (>=2.2.1)
phpunit/phpunit suggests installing phpunit/php-invoker (~1.1)
Writing lock file
Generating autoload files
Script Drupal\Core\Composer\Composer::preAutoloadDump handling the pre-autoload-dump event terminated with an exception
  [UnexpectedValueException]  
  Invalid version string ">"  
```
I am able to use the drupal command in some parts of my file system, such as /root and /var, but not in /var/www

**Comment by jmolivas** [comment]
Is this related to https://github.com/hechoendrupal/drupal-console/issues/3060 ?

**Comment by jmolivas** [comment]
@arnoldbird  Is this related to https://github.com/hechoendrupal/drupal-console/issues/3060 ?

**Comment by arnoldbird** [comment]
Yes.  I will close it.
