### ISSUE TITLE
[generate:entity:content] generated code doesn't show fields for administrate

### ISSUE THREAD

**Issue by vacho** [hechoendrupal/drupal-console#3067]
### Problem/Motivation
Sometimes we need since drupal UI to administrate fields: edit, add, delete. 

### How to reproduce
Review that the fields generated like 'name' doesn't show at admin/structure/{entity_name}/settings path

### Solution
Review the code of node or others content entities at core, an contrast with console generated code.

**Comment by LOBsTerr** [comment]
Currently generate:entity:content generates content entity with support of the field 
For example if we generated an entity without bundles, like this
```
drupal generate:entity:content  --module="mg" --entity-class="MyEntity" --entity-name="my_entity" --base-path="/admin/structure" --label="My entity"
```
then we can new fields here admin/structure/my_entity/settings/fields

If we generated an entity with bundles, like this  
```
drupal generate:entity:content  --module="mg" --entity-class="YourEntity" --entity-name="your_entity" --base-path="/admin/structure" --label="Your entity" --has-bundles 
```

Then we can add new fields on the bundle here: admin/structure/your_entity_type
keep in mind you need to add a new bundle first.

I'm closing the issue, feel free to reopen.
