### ISSUE TITLE
[console] Packages "conflict with your requirements or minimum-stability"

### ISSUE THREAD

**Issue by arnoldbird** [hechoendrupal/drupal-console#3073]
### Problem/Motivation

I'm not able to install console in an existing project.

ryan@ryandw-desktop:/var/www/issues/public_html$ sudo /usr/local/bin/composer require drupal/console:~1.0 --prefer-dist --optimize-autoloader  
[sudo] password for ryan: 
Do not run Composer as root/super user! See https://getcomposer.org/root for details
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.
Problem 1
    - The requested package drupal/console ~1.0 is satisfiable by drupal/console[1.0.0-alpha1, 1.0.0-alpha2, 1.0.0-beta1, 1.0.0-beta2, 1.0.0-beta3, 1.0.0-beta4, 1.0.0-beta5, 1.0.0-rc1, 1.0.0-rc10, 1.0.0-rc11, 1.0.0-rc12, 1.0.0-rc13, 1.0.0-rc2, 1.0.0-rc3, 1.0.0-rc4, 1.0.0-rc5, 1.0.0-rc6, 1.0.0-rc7, 1.0.0-rc8, 1.0.0-rc9] but these conflict with your requirements or minimum-stability.
Installation failed, deleting ./composer.json.

**Comment by jmolivas** [comment]
@arnoldbird there is currently a site at `/var/www/issues/public_html` ?

**Comment by arnoldbird** [comment]
Yes.  The problem has been resolved.  I'm not quite sure how.

At one point I did this...
composer clearcache
composer global require drupal/console:@stable

And then some time later I did...
sudo composer require drupal/console:~1.0 --prefer-dist --optimize-autoloader --sort-packages

...and now it works.
