### ISSUE TITLE
[generate:content:entity] Make creating admin routes/forms optional

### ISSUE THREAD

**Issue by recidive** [hechoendrupal/drupal-console#3074]
Sometimes, specially when using Drupal as headless backend server, you don't need anything related to entity administration.

The routes for configuring entity fields, display settings, etc could be optional. This would help a lot when using Drupal entities only through services since you end up having to remove a lot of code that you are not going to need.

We could ask some questions like:

Do you want an administration interface for configuring fields and display settings for your entity?

Do you want an administration interface and forms for administrating instances for you entity type?

**Comment by jmolivas** [comment]
Like the idea. We just need to investigate which pieces we do not require to render.

**Comment by LOBsTerr** [comment]
@recidive I have tried to check this improvements. Are you expecting that user will not be able to add/edit/remove the entities through admin web interface.
