### ISSUE TITLE
site:mode doesn'e exists

### ISSUE THREAD

**Issue by adubovskoy** [hechoendrupal/drupal-console#3079]
### site:mode doesn'e exists

Two different environments - local docker (docker4drupal.org) and digital ocean centos. The same thing - after installing drupal console, everithing works fine but drupal site:mode doesn't exist.

~~~
[mipezzij@s1 public_html]$ drupal list | grep mode
      --no-debug         Switches off debug mode
  sma                               Switch site into maintenance mode
  site:maintenance                  Switch site into maintenance mode
[mipezzij@s1 public_html]$ 
~~~

~~~
[mipezzij@s1 public_html]$ drupal --version
Drupal Console version 1.0.0-rc14
~~~

**Comment by jmolivas** [comment]
@adubovskoy it was disabled because it had some bugs, will be back in 1 or 2 releases.

**Comment by adubovskoy** [comment]
tnx!

**Comment by frederickjh** [comment]
Is this in the RC-16 release? I ask since this was closed but no mention of a commit that fixed it.

**Comment by jmolivas** [comment]
This should not be closed

**Comment by nvaken** [comment]
Is there any workaround to still be able to set the site mode?

**Comment by frederickjh** [comment]
Maybe something like [this](https://github.com/AmazeeLabs/d8-starter-composer/blob/dev/web/sites/default/settings.php#L105-L109) in your **settings.php** to load the service file(s) you want for each environment.

**Comment by frederickjh** [comment]
@nvaken They are using an environmental variable in the example I pointed to to set the environment but you can also do this with a custom option in a Drush Site Alias file.

**Comment by landsman** [comment]
What is state of it?

**Comment by xaqrox** [comment]
Is there an issue somewhere with more information on whatever bugs caused this command to be removed?

**Comment by maznu** [comment]
> will be back in 1 or 2 releases

What help do you need to get site:mode working again?

**Comment by jmolivas** [comment]
Fixed command is back on the latest rc21 release.

**Comment by webjazznl** [comment]
I am using a local docker installation on Windows 10

vendor/bin/drupal --version
Drupal Console version 1.8.0

When I enter
vendor/bin/drupal site:mode dev

 [ERROR] Command "site:mode", is not a valid command name.

Your help is appreciated!

**Comment by jmolivas** [comment]
@webjazznl  When using containers you must execute DrupalConsole on the container. You can do this by creating a site alias => https://docs.drupalconsole.com/en/alias/using-site-alias.html
