### ISSUE TITLE
[config:import] set exit status on failure.

### ISSUE THREAD

**Issue by cburschka** [hechoendrupal/drupal-console#3083]
### Problem/Motivation

For non-interactive usage, it would be useful to allow scripts to react to the exit status of a drupal-console command.

For example if `drupal config:import` fails for any reason, the command will output an error message but otherwise give no indication to the caller that the import failed and (for example) a setup script should be aborted.

### Solution

This might be solved by defining a new exception type that is thrown by a failing command (after showing the appropriate UI errors), then catching this exception from the top-level `$application->run()` call and using `exit(1)` to set the exit status.

**Comment by cburschka** [comment]
Update: Actually, the Symfony console already has exit codes - it's the return value of any function overriding `Symfony\Component\Console\Command::execute()`. So the only fix needed would be to check that all core commands that have their own error handling return 1 if they fail.

Back to the config:import example, this is related to an apparent bug in which the line `$io->success($this->trans('commands.config.import.messages.imported'));` is never executed, because `configImport()` doesn't return anything (neither on success nor failure).

**Comment by cburschka** [comment]
(I see that the support for this was added very recently in #3078, which is great!)

**Comment by jmolivas** [comment]
Closing this one. Since PR #3078 merged.
