### ISSUE TITLE
Dependency problem with drupal 8.2.5

### ISSUE THREAD

**Issue by alvar0hurtad0** [hechoendrupal/drupal-console#3093]
### Problem/Motivation
Package symfony/dom-crawler is locked at v3.2.2 (http://cgit.drupalcode.org/drupal/tree/composer.lock#n4161) and dependency is   `"symfony/dom-crawler": ">=2.7 <3.2"`,

### How to reproduce
Install drupal 8.2.5

composer require --dev drupal/console:~1.0@rc 

### Solution
Change dependencies to:
"symfony/dom-crawler": ">=2.7 <3.3"

**Comment by jmolivas** [comment]
PR merged
