### ISSUE TITLE
[database:add] Unable to run install related commands without a database

### ISSUE THREAD

**Issue by rbayliss** [hechoendrupal/drupal-console#3097]
### Problem/Motivation
Attempting to run any of the database:* commands on a site that does not have a fully installed database (either no $databases entry in settings.php, or a $databases entry, but no tables) triggers a fatal error.  

### How to reproduce

1. Install a fresh Drupal site
2. Drop the database (drupal database:drop)
3. Try running database:add or database:restore

### Solution
I would expect to be able to run most of the database commands, regardless of whether the site is able to bootstrap.  

I'd say these are must-haves for day to day operation:

database:add (for configuring your new site's settings.php prior to an import)
database:connect (for connecting, to create the database for instance)
database:query (same as database:connect)
database:restore (for importing an SQL file into the db you've created)

I think in general though, I'd expect all of the low level database commands (everything except database:log:*) to work with or without a Drupal bootstrap.  I could see getting into a situation where the site doesn't bootstrap, but you still need to take a backup, for instance.

**Comment by marcelovani** [comment]
See if this helps https://github.com/hechoendrupal/drupal-console/pull/3856

**Comment by enzolutions** [comment]
Partially solved with https://github.com/hechoendrupal/drupal-console/pull/4037

We are working in exposing the command `database:add`, to fully solve this issue.

**Comment by marcelovani** [comment]
Maybe we could call it database:create
That would help got users familiar with drush
Or maybe create both

**Comment by enzolutions** [comment]
The remaining issues were solved on https://github.com/hechoendrupal/drupal-console/pull/4038

@marcelovani you mean `database:add` to `database:create`? we could include this change in `Drupal Console 2.0`

**Comment by marcelovani** [comment]
Maybe have both command names but they do the same thing. Then you don’t need to change the docs
