### ISSUE TITLE
[site:install] After the last version update error in escapeTrailingBackslash

### ISSUE THREAD

**Issue by FabricioBedoya** [hechoendrupal/drupal-console#3100]
### Issue title
Call to undefined method Symfony\Component\Console\Formatter\OutputFormatter::escapeTrailingBackslash()
The issue title should comply with the following structure:

[ *ISSUE-GROUP* ] Short description

The *ISSUE-GROUP* should be one of:

* `site:install`
* `generate:controller`

### Problem/Motivation
When I try to launch site:install command an error occur, for almost all commands

**Details to include:**
Error: Call to undefined method Symfony\Component\Console\Formatter\OutputFormatter::escapeTrailingBackslash() in /Users/fabriciobedoya/Documents/projects/drupal8_test/vendor/symfony/console/Helper/SymfonyQuestionHelper.php on line 57 #0 phar:///usr/local/bin/drupal/vendor/symfony/console/Helper/QuestionHelper.php(119): Symfony\Component\Console\Helper\SymfonyQuestionHelper->writePrompt(Object(Drupal\Console\Core\Style\DrupalStyle), Object(Symfony\Component\Console\Question\ChoiceQuestion))
#1 phar:///usr/local/bin/drupal/vendor/symfony/console/Helper/QuestionHelper.php(62): Symfony\Component\Console\Helper\QuestionHelper->doAsk(Object(Drupal\Console\Core\Style\DrupalStyle), Object(Symfony\Component\Console\Question\ChoiceQuestion))
#2 phar:///usr/local/bin/drupal/vendor/symfony/console/Helper/QuestionHelper.php(401): Symfony\Component\Console\Helper\QuestionHelper->Symfony\Component\Console\Helper\{closure}()
#3 phar:///usr/local/bin/drupal/vendor/symfony/console/Helper/QuestionHelper.php(65): Symfony\Component\Console\Helper\QuestionHelper->validateAttempts(Object(Closure), Object(Drupal\Console\Core\Style\DrupalStyle), Object(Symfony\Component\Console\Question\ChoiceQuestion))

### How to reproduce
Include steps related how to reproduce.

**Details to include:**
- Drupal version (8.2.5).
- Console version (1.0.0-rc14).
- Console Launcher version (1.0.0-rc14).

**Comment by jmolivas** [comment]
This PR https://github.com/hechoendrupal/drupal-console-launcher/pull/82 should fix this.

**Comment by PatrickBauer** [comment]
Is there a way to test this without waiting for another console-launcher release?

**Comment by jmolivas** [comment]
@PatrickBauer you can try by 
1) cloning the repo https://github.com/hechoendrupal/drupal-console-launcher 
2) using composer to install dependencies
3) building the phar using https://github.com/box-project/box2

**Comment by PatrickBauer** [comment]
Thank you. tried it and the PR fixes the problem 👍

**Comment by arnoldbird** [comment]
@FabricioBedoya 
Can you provide more detail on this:
"using composer to install dependencies"

I know it's documented elsewhere, but I'm not sure how to do it in a way that will pull the latest dev code.  I tried this in my composer.json require but it was rejected by composer:
` "drupal/console": "dev-master",`

**Comment by PatrickBauer** [comment]
@arnoldbird 

Follow these steps:
```
git clone git@github.com:hechoendrupal/drupal-console-launcher.git
cd drupal-console-launcher
composer install
composer global require kherge/box --prefer-source
box build
mv drupal.phar /usr/local/bin/drupal
```

For the last step you have should change the path to your current drupal console launcher.

**Comment by arnoldbird** [comment]
Thanks!

For the first step, I needed to do...
`git clone https://github.com/hechoendrupal/drupal-console-launcher.git`

When I ran 'box build', I got...
```[UnexpectedValueException]                                                   
  creating archive "/root/drupal-console-launcher/drupal.phar" disabled by th  
  e php.ini setting phar.readonly
```    

I resolved that by setting **phar.readonly = Off** in /etc/php5/apache2/php.ini
It seems that phar.readonly defaults to On.

Now I can install modules with console.

**Comment by daften** [comment]
I had problems with generate functions, the mentioned PR fixed that for me too.

**Comment by jmolivas** [comment]
Closing this one. Feel free to re-open if still happening after updating to the latest version.

**Comment by dstorozhuk** [comment]
It still doesn't work. I trien php 7.0, php 5.6.

**Comment by PatrickBauer** [comment]
@dstorozhuk There were two updates already in the meantime. Just use drupal self-update outside of a drupal project (e.g. your home folder) and it should work again.

**Comment by dstorozhuk** [comment]
Yes, looks like it works. 
I updated the global console to  from version 1.0.0-alpha2 to version 1.0.0-rc16.
However, I was nod able  to add it to the project with command:
```sh
# https://hechoendrupal.gitbooks.io/drupal-console/content/en/getting/installer.html
composer require drupal/console:~1.0 --prefer-dist --optimize-autoloader
```
Because of requirements problem.
```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - drupal/console 1.0.0-rc15 requires doctrine/collections 1.3.0 -> satisfiable by doctrine/collections[v1.3.0].
    - drupal/console 1.0.0-rc16 requires doctrine/collections 1.3.0 -> satisfiable by doctrine/collections[v1.3.0].
...
```
So I added the the line  `"drupal/console": "~1.0",` to my project composer.json.
And then run  `composer update`
Now it works.

**Comment by xpersonas** [comment]
I'm sort of in the same boat. I have **Drupal Console Launcher version 1.0.0-rc16**. I am getting the same error regarding doctrine/collections. But your solution is not working for me. 

  Problem 1
    - drupal/console 1.0.0-rc15 requires doctrine/collections 1.3.0 -> satisfiable by doctrine/collections[v1.3.0].
    - drupal/console 1.0.0-rc16 requires doctrine/collections 1.3.0 -> satisfiable by doctrine/collections[v1.3.0].
    - Conclusion: don't install doctrine/collections v1.3.0
    - Conclusion: don't install psy/psysh v0.8.0
....

I love Drupal Console, but not sure how to get it running again.
