### ISSUE TITLE
[console] Deleting sites/default/files/php directory is not always possible

### ISSUE THREAD

**Issue by vasi** [hechoendrupal/drupal-console#3102]
### Problem/Motivation

As of #3090 , we delete the entire PhpStorage directory (`sites/default/files/php`) on every run of Drupal console.  On some systems, permissions may prevent this, which causes Console to die.

This occurs in particular with Acquia Dev Desktop on Windows.

### How to reproduce

* Install Dev Desktop (I used the current version, 2016-09-06) on Windows 10
* Install a Drupal site (I used 8.2.5)
* Install Drupal Console, using composer
* Run `vendor\bin\drupal`. The first time, with nothing in the `php` directory, it may succeed.
* Run `vendor\bin\drupal` again. It will fail with a permission error similar to this:

```
 [ERROR] Failed to remove file
 "C:\Users\Dave\Sites\devdesktop\drupal-8.2.5/sites/default/files/php\twig\9a2bf118_toolbar.html.twig_72e85e9e07d545a96d
 b5b5f664df3aa1d23e29fe9555a3c1151af4ae185c1597\aa26448c2e7dd560e529c6d328a9f547b25d5a6c8b1d698e507abf16a1146981.php":
 unlink(C:\Users\Dave\Sites\devdesktop\drupal-8.2.5/sites/default/files/php\twig\9a2bf118_toolbar.html.twig_72e85e9e07d5
 45a96db5b5f664df3aa1d23e29fe9555a3c1151af4ae185c1597\aa26448c2e7dd560e529c6d328a9f547b25d5a6c8b1d698e507abf16a1146981.p
 hp): Permission denied.
```

### Solution

I'm not sure exactly what #3090 is trying to do, the description is quite vague.

* Why do we want #3090? Under what situation is PhpStorage requiring a cache:rebuild when we don't want one?
* Is removing this directory safe, when we don't yet know if `PublicStream::basePath()` is `sites/default/files` or something else?
* Do we really want to clear the entire Twig cache every time we run Drupal Console, even a simple command like `drupal list`?

Possible solutions include:

* Revert #3090 
* Figure out what #3090 is trying to achieve, and do it another way
* Gracefully handle being unable to remove files in PhpStorage, even though it risks breaking whatever #3090 is trying to do
* Modify Drupal to use different permissions on PhpStorage

**Comment by jmolivas** [comment]
@vasi Fixed with https://github.com/hechoendrupal/drupal-console/pull/3103 thanks for reporting.

**Comment by jmolivas** [comment]
Closing this one. Feel free to re-open if still happening after updating to the latest version.

**Comment by vasi** [comment]
Thanks!
