### ISSUE TITLE
[module:install] Call to undefined method Symfony\Component\Console\Formatter\OutputFormatter::escapeTrailingBackslash()

### ISSUE THREAD

**Issue by arnoldbird** [hechoendrupal/drupal-console#3107]
I was not able to install a module with console.  This is in a fresh install of Drupal 8.2.5.

root@ryandw-desktop:/var/www/issues/public_html# /usr/local/bin/drupal module:install devel
 One or more modules "devel" are not available, running download process to get those modules
 Getting releases for module "devel"

PHP Fatal error:  Call to undefined method Symfony\Component\Console\Formatter\OutputFormatter::escapeTrailingBackslash() in /var/www/issues/public_html/vendor/symfony/console/Helper/SymfonyQuestionHelper.php on line 57

**Comment by arnoldbird** [comment]
Actually this looks to be a duplicate of https://github.com/symfony/symfony/issues/21337
I'm reading that thread now.

**Comment by arnoldbird** [comment]
And this:  https://github.com/hechoendrupal/drupal-console/issues/3100

**Comment by arnoldbird** [comment]
I will close this because it's a duplicate : )

**Comment by ndf** [comment]
It helped me to not use the global executable, but run the version that is in your drupal installation.

`cd <your-drupal-path>`
`vendor/bin/drupal module:install devel`
