### ISSUE TITLE
[update:execute] ignores <module> argument

### ISSUE THREAD

**Issue by cburschka-pwc** [hechoendrupal/drupal-console#3108]
There's some broken logic in the Command\Update\ExecuteCommand - the module argument is required, but the command always prints the error that no updates exist for the given module, and then runs all updates for all modules anyway.

As the execute() function seems to show, there isn't actually any code that would filter the updates by module:

        $this->module = $input->getArgument('module');
        $updates = update_get_update_list();
        $this->checkUpdates($io);

And in checkUpdates we have...

    private function checkUpdates(DrupalStyle $io)
    {
        if ($this->module != 'all') {
            if (!isset($updates[$this->module])) {

Looks like an improper refactoring: The local $updates variable wasn't turned into an argument or property. Also, even though checkUpdates returns with an error, the main execute() function just continues. ;)

(There might be some more errors in this; might check later.)

**Comment by cburschka** [comment]
Bug's actually been in here since July - 036aa15ee376f4a45c2c17949f8f932eb35bc32e 

So I guess everyone is just using the `drupal update:execute all` syntax? ;)
