### ISSUE TITLE
[config:export:content:type] Title field label setting not exported

### ISSUE THREAD

**Issue by colans** [hechoendrupal/drupal-console#3109]
### Problem/Motivation
On running the `drupal config:export:content:type` command, deleting the content type, and then importing exported content type configuration, the title field label gets set to the default "Title" even though it was set to something else before export.

### How to reproduce
1. Create a content type from the Web UI.
1. On the Edit form, change the *Title field label* setting from *Title* to *Banana*.
1. Run `drupal config:export:content:type` to export it.
1. Include it in your module's config/install directory.
1. Delete the content type from the Web UI.
1. Uninstall your module.
1. Re-install it.
1. Edit the newly created content type.
1. Notice that the *Title field label* is set to *Title* instead of *Banana*.

### Version info
* Drupal version: 8.2.3
* Console version: 1.0.0-rc14
* Console Launcher version: 1.0.0-rc13

### Solution
Include the missing `core.base_field_override.node.CONTENT_TYPE.title.yml` in the export as it doesn't seem to be included.

### Workaround
Run `drush cex -y`, copy the file from there, and include it with your other YAML files for the content type.

**Comment by worthwhileindustries** [comment]
I can't even seem to get that far....? What am I doing wrong here. Why is it asking about a module??

```
root@e4411300c0fa:/var/www/html/web# ../vendor/bin/drupal config:export:content:type region
 Enter the module name [authorization]:
 > 
```

### Version info

Drupal version: 8.2.6
Console version: 1.0.0-rc16

**Comment by colans** [comment]
@worthwhileindustries : That's the module where you'd like the configuration housed.  So when you enable the module, this configuration gets imported.

**Comment by worthwhileindustries** [comment]
Thanks for clarifying that. I guess I can copy from a module. Not sure why there is no option to export to sync or other directory AFAIK. Your workaround seems to work.

**Comment by enzolutions** [comment]
Resolved with PR https://github.com/hechoendrupal/drupal-console/pull/4083
