### ISSUE TITLE
Use StorageInterface in config commands?

### ISSUE THREAD

**Issue by kmajzlik** [hechoendrupal/drupal-console#3111]
Use StorageInterface in config commands instead of FileStorage

### Problem/Motivation
config_split module do not work with Console

**Details to include:**
That module creates own implementation of that interface and we have TypeError

### How to reproduce
Current config_split + https://www.drupal.org/node/2830660

### Solution
vendor/drupal/console/src/Command/Config/DeleteCommand.php line 52
```
-         FileStorage $configStorageSync
+        StorageInterface $configStorageSync
```

There should be other changes in "use" etc. This one line only fixes basic "drupal about" command for me.

**Comment by jmolivas** [comment]
Fixed with PR https://github.com/hechoendrupal/drupal-console/pull/3118

**Comment by jmolivas** [comment]
Closing this one. Feel free to re-open if still happening after updating to the latest version.
