### ISSUE TITLE
[ generate:cache:context ] [Bug] Missing required dependecy/service

### ISSUE THREAD

**Issue by joshirohit100** [hechoendrupal/drupal-console#3113]
In this new command, Extension manager dependency/service was missing which is kind of required to execute/run the command.

**Comment by joshirohit100** [comment]
PR - https://github.com/hechoendrupal/drupal-console/pull/3114

**Comment by joshirohit100** [comment]
PR - https://github.com/hechoendrupal/drupal-console/pull/3114

**Comment by jmolivas** [comment]
PR merged
