### ISSUE TITLE
`console` Any drupal console commands for site in maintenance mode fails

### ISSUE THREAD

**Issue by daften** [hechoendrupal/drupal-console#3121]
### Problem/Motivation
When a site is in maintenance mode, I get this error message for every command, including site:status and site:maintenance off
```
Recoverable fatal error: Argument 2 passed to Drupal\Core\Controller\TitleResolver::getTitle() must be an instance of Symfony\Component\Routing\Route, null given, called in .../web/modules/contrib/token/token.tokens.inc on line 741 and defined in Drupal\Core\Controller\TitleResolver->getTitle() (line 39 of .../web/core/lib/Drupal/Core/Controller/TitleResolver.php).
```

**Details to include:**
- Drupal version: 8.2.5
- Console version: 1.0.0-rc14
- Console Launcher version: 1.0.0-rc14 (latest version manually installed)

### Solution
No clue to be honest.

**Comment by joshirohit100** [comment]
This looks like token module issue because no check is there if route object or not

`$route = $request->attributes->get(RouteObjectInterface::ROUTE_OBJECT);
 $title = \Drupal::service('title_resolver')->getTitle($request, $route);`

here looks like culprit

**Comment by yasenivanov** [comment]
I am receiving the same error when putting the site in maintenance mode and trying to access invalid page (404) as anonymous user.

**Comment by Geomage** [comment]
Same issue.

**Comment by LOBsTerr** [comment]
I have checked this issue using 1.6.1. It looks like it is not a case anymore. Can anybody reproduce it ?

**Comment by harold20** [comment]
I can't reproduce it using 1.8.0
