### ISSUE TITLE
cron:execute - why is the all key required?

### ISSUE THREAD

**Issue by twhiston** [hechoendrupal/drupal-console#3126]
Why is the all key required in the cron:execute command? It seems slightly strange to me that the default behavior (with no argument) is just to fail and not run all the cron, which to me would be the expected behavior (and analogous to hitting the run cron button in the interface)

### How to reproduce
run `drupal cron:execute` and it will fail saying no module was specified

### Solution
Its very easy to keep the existing behavior and make no argument trigger the 'all' function. See PR
https://github.com/hechoendrupal/drupal-console/pull/3127

**Comment by jmolivas** [comment]
@twhiston I tested the PR and it works as expected and agree about the analogous to hitting the run cron button in the interface.

**Comment by jmolivas** [comment]
Closing this one. Feel free to re-open if still happening after updating to the latest version.
