### ISSUE TITLE
'generate:module' Missing <?php tag in .module file some cases

### ISSUE THREAD

**Issue by lachezarvalchev** [hechoendrupal/drupal-console#3131]
### Problem/Motivation
When the .module file is generated because of the need to implement hooks it does not have <?php

### How to reproduce
I have used 'generate:module' command to generate my custom module.
On the question about do I want .module file I replied no.
However on the question do I want themable template I answered yes.
DrupalConsole automatically created .module file and added implementation of hook_theme() which is cool, but the .module file does not have <?php tag

**Details to include:**
- Drupal version 8.2.5
 - drupal/console 1.0.0-rc15
- drupal/console-core 1.0.0-rc15
- drupal/console-en 1.0.0-rc15
![screen shot 2017-01-25 at 17 52 06 2](https://cloud.githubusercontent.com/assets/2161802/22298501/62f39754-e329-11e6-8c4b-5f0642ec66dc.png)

**Comment by joshirohit100** [comment]
Here is PR - https://github.com/hechoendrupal/drupal-console/pull/3135
