### ISSUE TITLE
[console] console.create_terms - The "taxonomy_vocabulary" entity type does not exist.

### ISSUE THREAD

**Issue by derhasi** [hechoendrupal/drupal-console#3132]
### Problem/Motivation
When the `taxonomy` module is not installed, the following message appears at every console command run:
```
console.create_terms - The "taxonomy_vocabulary" entity type does not exist.
```
The message can confuse users and clutters up the logs. Therefore it should not be displayed when _taxonomy_ module is not enabled. 

### How to reproduce

* Drupal: 8.2.5
* Drupal Console: 1.0.0-rc15
* Local Drupal Console in `../vendor/bin/drupal` added via composer

* Run any `../vendor/bin/drupal` command from within the docroot of your drupal installation

### Solution

* No solution known yet
* Workaround: enable `taxonomy`

**Comment by joshirohit100** [comment]
Lets see if https://github.com/hechoendrupal/drupal-console/pull/3136 helps

**Comment by jorissteyn** [comment]
I believe the expected behaviour is that no error is shown to the user: if a site doesn't provide specific functionality, drupal console should simply not activate the corresponding commands. For example, if you don't have features installed, you won't get an error about features not being installed.

The same logic should apply to the node and taxonomy modules:

    console.create_nodes - The "node_type" entity type does not exist.
    console.create_terms - The "taxonomy_vocabulary" entity type does not exist.

**Comment by joshirohit100** [comment]
@jorissteyn what I feel is that showing no error/message is also not good UX. If no error/message is shown, user will be in impression that there is something wrong with the setup.

**Comment by jorissteyn** [comment]
I agree we should show an error if the user executes a command that needs the module enabled, like "create:nodes", but not at every invocation of the drupal console. Currently, even this produces the messages:

    $ vendor/bin/drupal --help

It is perfectly valid to have a site without taxonomy or even node enabled, so why bother the user with the messages while there is nothing wrong?

**Comment by derhasi** [comment]
I'd expect that those commands won't show up, if the dependencies are not installed. And therefore I would expect to not see any message related to those commands.

I do not know if there is any mechanism for defining dependencies for commands. If it does not exists, maybe that is something to add to the services definitions. That way `drupal list` could distinguish commands with and without sufficient dependencies and maybe only show all available ones, with something like `drupal list --all`. 

@jmolivas what do you think of this "problem"?

**Comment by jmolivas** [comment]
@derhasi  We can hide command from showing  as an example the features:* commands. This is accomplished by using annotations.

In this same features command example this looks somethinkg like this
```
/**
 * @DrupalCommand(
 *     extension = "features",
 *     extensionType = "module"
 * )
 */
```

https://github.com/hechoendrupal/drupal-console/blob/master/src/Command/Features/DebugCommand.php#L19-L24

**Comment by jmolivas** [comment]
This PR https://github.com/hechoendrupal/drupal-console/pull/3159 fix this issue
