### ISSUE TITLE
[queue:debug / queue:run] Fatal errors on queue commands

### ISSUE THREAD

**Issue by derhasi** [hechoendrupal/drupal-console#3133]
### Problem/Motivation
Both queue commands fail for me with a fatal error at the moment. I _drupal/console_ want to implement these commands those should be fixed or removed instead in favour of _drush/drush_.

### How to reproduce

* Drupal: 8.2.5
* Drupal Console: 1.0.0-rc15
* Local Drupal Console in ../vendor/bin/drupal added via composer

#### queue:debug

Run `../vendor/bin/drupal queue:debug` from docroot, then following output occurs:
```
Fatal error: Call to undefined method Drupal\Console\Command\Queue\DebugCommand::getDrupalService() in [..]/vendor/drupal/console/src/Command/Queue/DebugCommand.php on line 91
```

#### queue:run

Run `../vendor/bin/drupal queue:run toggl_time_entry_import` from docroot, then following output occurs:
```
Fatal error: Call to undefined method Drupal\Core\Queue\QueueFactory::numberOfItems() in [...]/vendor/drupal/console/src/Command/Queue/RunCommand.php on line 134
```

### Solution

* Proposed solution: fix implementation of used interfaces
* Workaround: use `drush queue-list` and `drush queue-run [...]`

**Comment by OnkelTem** [comment]
Confirm

**Comment by kabanon** [comment]
Same issue with

- Drupal Console version 1.0.0
- Drupal 8.4.4

**Comment by LOBsTerr** [comment]
@kabanon Drupal console's current version is 1.6.0. Can you try to update?

**Comment by kabanon** [comment]
Same error.
See [PR 3793](https://github.com/hechoendrupal/drupal-console/pull/3793) for proposed patch.
