### ISSUE TITLE
It's not working after composer update

### ISSUE THREAD

**Issue by boesbo** [hechoendrupal/drupal-console#3147]
It's not working after composer update, It happens for example after getting Done composer remove / supplier / pack

Never in console:
`project -> vendor/bin/drupal cache:rebuild all`
`project ->`

Drupal 8.2.5, Drupal Console RC15
Scaffolding with Drupal composer

**Comment by joshirohit100** [comment]
@boesbo - What you see when you run it ?

**Comment by boesbo** [comment]
➜  recensioni_tech vendor/bin/drupal cache:rebuild           
<div class="view view-frontpage view-id-frontpage view-display-id-page_1 js-view-dom-id-689690f006b2ce3dd8db81538157778ceae5d7f2a02d09aeb3a1d0c6de98e9ee">
  
    
      
      <div class="view-content">
          <div class="views-row">
    %

**Comment by jmolivas** [comment]
@boesbo  Closing this one. Since you mentioned is solved. Feel free to re-open if still happening
