### ISSUE TITLE
Error when trying to run Drupal Console in local site.

### ISSUE THREAD

**Issue by lukejoliat** [hechoendrupal/drupal-console#3148]
I get these errors when trying to run any Drupal Console command in the root folder of my local Drupal site: 

/usr/local/bin/drupal: line 1: syntax error near unexpected token `<'
/usr/local/bin/drupal: line 1: `The website encountered an unexpected error. Please try again later.</br></br><em class="placeholder">Github\Exception\RuntimeException</em>: You have reached GitHub hour limit! Actual limit is: 60 in <em class="placeholder">Github\HttpClient\HttpClient-&gt;request()</em> (line <em class="placeholder">145</em> of <em class="placeholder">vendor/knplabs/github-api/lib/Github/HttpClient/HttpClient.php</em>).'
mbp-ljoliat:java-app ljoliat$ 

Any ideas?

**Comment by jmolivas** [comment]
@lukejoliat try downloading again the Launcher aka global executable 
https://github.com/hechoendrupal/drupal-console#install-drupal-console-launcher

**Comment by jmolivas** [comment]
Closing this one. Feel free to re-open if still happening after updating to the latest version.

**Comment by xieyanxy9** [comment]
https://docs.drupalconsole.com/en/getting/launcher.html
**Install Drupal Console Launcher**
curl https://drupalconsole.com/installer -L -o drupal.phar
mv drupal.phar /usr/local/bin/drupal
chmod +x /usr/local/bin/drupal
**Update DrupalConsole Launcher**
drupal self-update

**Comment by jmolivas** [comment]
@xieyanxy9 not sure about what was your comment ?

**Comment by benedikt-d** [comment]
I'm having the same issue installing: https://drupalconsole.com/installer

**Comment by jmolivas** [comment]
@benedikt-d  I just tried and it works. I will send a fix to add a cache feature to avoid having issue with the github limit.
