### ISSUE TITLE
[generate:module] outputs bad .module file in some conditions

### ISSUE THREAD

**Issue by cburschka-pwc** [hechoendrupal/drupal-console#3150]
### How to reproduce

* Run `drupal generate:module`
* Deselect the .module file generation
* Enable the template generation later

A header-less .module file is created that *only* contains hook_theme() without a PHP tag or PHPdoc header.

Instead we could either error, printing no .module, or force the .module option back on.

**Comment by joshirohit100** [comment]
Fixed in https://github.com/hechoendrupal/drupal-console/issues/3131

**Comment by jmolivas** [comment]
Fixed and merged
