### ISSUE TITLE
[site:install] The ".../drivers/lib/Drupal/Driver/Database" directory does not exist.

### ISSUE THREAD

**Issue by jover** [hechoendrupal/drupal-console#3151]
### Problem/Motivation
Installing a Drupal 8 website using Drupal Console `site:install` throws the following error:
```
[InvalidArgumentException]
The "[APP_ROOT]/drivers/lib/Drupal/Driver/Database" directory does not exist.
```

### How to reproduce
- Drupal 8.2.6
- Console version: 1.0.0-rc15

### Solution
```
public function getDatabaseTypes()
    {
        $this->loadLegacyFile('/core/includes/install.inc');
        $this->setMinimalContainerPreKernel();

        $finder = new Finder();
        $finder->directories()
            ->in($this->appRoot . '/core/lib/Drupal/Core/Database/Driver')
            ->in($this->appRoot . '/drivers/lib/Drupal/Driver/Database')
            ->depth('== 0');
    
    ...

    }
```

Removing the line with `->in($this->appRoot . '/drivers/lib/Drupal/Driver/Database')` works for me.

**Comment by jmolivas** [comment]
Fixed with PR https://github.com/hechoendrupal/drupal-console/pull/3125

**Comment by jmolivas** [comment]
@jover Closing this one. Feel free to re-open if still happening after updating to the latest version.
