### ISSUE TITLE
[config:export:single] does not generate .yml file

### ISSUE THREAD

**Issue by carsonblack** [hechoendrupal/drupal-console#3152]
When I run the config:export:single command it will ask me questions for the following:
- config type
- name
- remove the uuid (I answer yes) 
- remove the site hash (I answer yes)

It then displays the message "Configuration(s) exported sucessfully" (side note: sucessfully is misspelled, should be successfully) and exists.

No config is generated anywhere. I also tried to add the --directory flag to get it to write the config to the install directory of a profile I am working on and it would write there either. 

- Drupal version: 8.2.6
- Console version: 1.0.0-rc15
- Console Launcher version: 1.0.0-rc15

**Comment by harold20** [comment]
This is not longer present in the version 1.9.0
