### ISSUE TITLE
Library project-wide custom commands

### ISSUE THREAD

**Issue by nvaken** [hechoendrupal/drupal-console#3154]
### Problem/Motivation
To package custom, project specific, commands into a project the only solution at this point is to create a Drupal module and enable it in Drupal itself to provide the commands. To create development workflow related commands, you will be forced to clutter your Drupal workspace and enable a module. This results in the following problems: 

- Deployment to non-dev environments will include dev tools, cluttering the codebase. Additionally, it introduces a new security vector, however unlikely.
- Unnecessary (small) performance impact on Drupal (dev environment) in favor of CLI commands. 
- Unnecessary differences between environments (if disabled correctly on production / acceptance / test environments), which could potentially make debugging harder. 

Although some of above motivations might be trivial, they are substantial. 

### Solution
As proposed by @jmolivas via Gitter: 

> The first thing I can think for doing sometthing like this is to:
> - Add the capability for php-libraries to provide commands and not only modules/.themes/profiles as now.
> - Add this library on the required-dev section of your composer file.
> - Deploy using composer install --no-dev and those commands will not be available at prod.

**Comment by jmolivas** [comment]
PR to load commands from libraries https://github.com/hechoendrupal/drupal-console/pull/3157

Project must be `drupal-console-library` example:
```
{
    "name": "",
    "description": "",
    "type": "drupal-console-library",
    "authors": [
        {
        }
    ],
    "require": {},
    "minimum-stability": "dev",
    "prefer-stable": true,
    "autoload": {
    },
    "require-dev": {
    }
}
```

Commands provided by the library must be registered as services on a file named `console.services.yml`

**Comment by jmolivas** [comment]
@nvaken PR to load commands from libraries https://github.com/hechoendrupal/drupal-console/pull/3157

Project must be `drupal-console-library` example:
```
{
    "name": "",
    "description": "",
    "type": "drupal-console-library",
    "authors": [
        {
        }
    ],
    "require": {},
    "minimum-stability": "dev",
    "prefer-stable": true,
    "autoload": {
    },
    "require-dev": {
    }
}
```

Commands provided by the library must be registered as services on a file named `console.services.yml`

**Comment by nvaken** [comment]
Works like a charm after following up instructions and analysing the following example project from @jmolivas. 

https://github.com/hechoendrupal/drupal-console-extend-example

**Comment by dillix** [comment]
When I try to update "Drupal Project" from 8.7.2 to latest version, I got:
```
- Installing vlucas/phpdotenv (v2.6.1): Loading from cache

                                                          
  [InvalidArgumentException]                              
  Package type "drupal-console-library" is not supported
```
