### ISSUE TITLE
[create:terms] startup warning without taxonomy installed

### ISSUE THREAD

**Issue by cburschka** [hechoendrupal/drupal-console#3158]
To reproduce: Install Drupal 8 with the minimal profile (which doesn't include taxonomy), then use any console command (tested with generate:module, site:status, server and cache:rebuild).

On startup, the following warning will appear:

    console.create_terms - The "taxonomy_vocabulary" entity type does not exist.

In a related issue, `drupal list` will still show the `create:vocabularies` command (but not `create:terms`, likely because of the above), but throw a PluginNotFoundException because of the same missing entity type.

Both of these commands should probably be silently unavailable if the taxonomy module and its entity types are not installed.

(This is a relatively minor problem.)

**Comment by jmolivas** [comment]
This PR https://github.com/hechoendrupal/drupal-console/pull/3159 fix this issue
