### ISSUE TITLE
[console config:import] Importing not working anymore after smtp module got removed

### ISSUE THREAD

**Issue by lblissett** [hechoendrupal/drupal-console#3163]
When i run `config:import` i get the following error:
```

 [ERROR] An error accurred while trying to write the config file: "The import failed due for the         
         following reasons:                                                                              
         Unable to install the <em class="placeholder">smtp</em> module since it does not exist."   
```
 
### Details:

I installed the drupal/smtp module via composer and enabled it with drush. After i messed a bit around with it, i decided not to use it anymore. So i removed the smtp module again via composer.

AFTER this i saved my site configuration with config:export.

But the config:import of this new generated settings always fail with the error message from above. So there is still something left from the smtp module but i don't know how to get rid of this.

Drupal Version: 8.2.6
Drupal Console (1.0.0-rc15)

**Comment by joshirohit100** [comment]
Check if core.extensions.yml contains smtp refernce

**Comment by lblissett** [comment]
Yes, there was one entry: `smtp: 0` in `core.extensions.yml` which i deleted .. and there was also a  `smtp.settings.yml` file which i deleted, too. 

Now, it is working again! Thanks a lot for your help.
