### ISSUE TITLE
site:mode not available

### ISSUE THREAD

**Issue by 999omben** [hechoendrupal/drupal-console#3166]
I have installed Drupal console with the [drupal-composer/drupal-project](https://github.com/drupal-composer/drupal-project) (1.0.0-rc15) and i don't have the **site:mode**. 
what im doing wrong?
![capture d ecran 2017-02-09 a 11 02 13](https://cloud.githubusercontent.com/assets/25667307/22791630/0e22c782-eeb8-11e6-85ab-0b9ded260a88.png)
`[ERROR] Command "site:mode", is not a valid command name.`

Thx you !

**Comment by jmolivas** [comment]
Duplicated issue https://github.com/hechoendrupal/drupal-console/issues/3079

**Comment by jmolivas** [comment]
@999omben Duplicated issue https://github.com/hechoendrupal/drupal-console/issues/3079

**Comment by 999omben** [comment]
Thx you !
