### ISSUE TITLE
[console] review the usage of Command::addOption()

### ISSUE THREAD

**Issue by ao2** [hechoendrupal/drupal-console#3174]
Hi,

when working on #3092 I noticed that in some cases `false` is passed as the second argument of `Command::addOption()`, and sometimes an empty string is passed.

This made me wonder that some reader might naively end up thinking that this second argument could be the default value of the option in case the option mode is `InputOption::VALUE_OPTIONAL` (for a moment I did), but that would be wrong.

The second argument is a shortcut name for the command, and the documentation says that it can be `null` if there is none:
http://api.symfony.com/3.1/Symfony/Component/Console/Command/Command.html#method_addOption
A possible default value goes in the fifth argument if needed.

So what about using `null` everywhere for the shortcut argument of `addOption()`?
Just an idea.

**Comment by jmolivas** [comment]
@ao2 Totally agree on the idea of standardize this argument, and using `null` sounds like a good option.

**Comment by ao2** [comment]
@jmolivas can you do it, or should I?

Thanks,
   Antonio

**Comment by jmolivas** [comment]
@ao2 Feel free to take this task.

**Comment by ao2** [comment]
OK, I'll look into it after #3173 gets processed, to minimize possible merge conflicts.

Thanks,
   Antonio
