### ISSUE TITLE
[generate:entity:content] buildRow function uses deprecated l() function

### ISSUE THREAD

**Issue by khgoldberg** [hechoendrupal/drupal-console#3176]
The `buildRow()` code that is generated from `generate:entity:content` uses the `l()` function which is deprecated (as I'm sure you know).

To replicate, I executed `generate:entity:content`, selected the custom module I'd created using `drupal generate:module --learning`.  Detailed execution is below.

Drupal version:  8.2.6
Console version: 1.0.0-rc16 Drupal Console English Language
drupal/console-extend-plugin          0.2.0      Drupal Console Extend Plugin
Console launcher: 1.0.0-rc16 

### Detailed Execution

Enter the module name [timetracking]:
 >

 Enter the class of your new content entity [DefaultEntity]:
 > Subcategory

 Enter the machine name of your new content entity [subcategory]:
 >

 Enter the label of your new content entity [Subcategory]:
 >

 Enter the base-path for the content entity routes [/admin/structure]:
 > /timetracking

 Do you want this (content) entity to have bundles (yes/no) [no]:
 >

 Is your entity translatable (yes/no) [yes]:
 > no

 Is your entity revisionable (yes/no) [yes]:
 > no

Generated or updated files

 1 - modules/custom/timetracking/timetracking.permissions.yml
 2 - modules/custom/timetracking/timetracking.links.menu.yml
 3 - modules/custom/timetracking/timetracking.links.task.yml
 4 - modules/custom/timetracking/timetracking.links.action.yml
 5 - modules/custom/timetracking/src/SubcategoryAccessControlHandler.php
 6 - modules/custom/timetracking/src/Entity/SubcategoryInterface.php
 7 - modules/custom/timetracking/src/Entity/Subcategory.php
 8 - modules/custom/timetracking/src/SubcategoryHtmlRouteProvider.php
 9 - modules/custom/timetracking/src/Entity/SubcategoryViewsData.php
 10 - modules/custom/timetracking/src/SubcategoryListBuilder.php
 11 - modules/custom/timetracking/src/Form/SubcategorySettingsForm.php
 12 - modules/custom/timetracking/src/Form/SubcategoryForm.php
 13 - modules/custom/timetracking/src/Form/SubcategoryDeleteForm.php
 14 - modules/custom/timetracking/subcategory.page.inc
 15 - modules/custom/timetracking/templates/subcategory.html.twig

**Comment by gnuget** [comment]
I just create a pull request with a fix. 

Thanks for report the problem.

- David.
