### ISSUE TITLE
Warning: Missing argument 1 for Drupal\Console\Bootstrap\Drupal::boot()

### ISSUE THREAD

**Issue by nvaken** [hechoendrupal/drupal-console#3179]
I'm seeing the following warnings in `database:log:debug` after a simple `site:install`. Also, tailing this warning are a few undefined variable notices for the `$debug` variable. 

```
Warning: Missing argument 1 for Drupal\Console\Bootstrap\Drupal::boot(), called in /Users/nvaken/Develop/playgrounds/d8_5/vendor/drupal/console/src/Command/Site/InstallCommand.php on line 446 and defined in Drupal\Console\Bootstrap\Drupal->boot() (regel 34 van /Users/nvaken/Develop/playgrounds/d8_5/vendor/drupal/console/src/Bootstrap/Drupal.php) #0 /Users/nvaken/Develop/playgrounds/d8_5/web/core/includes/bootstrap.inc(548): _drupal_error_handler_real(2, 'Missing argumen...', '/Users/nvaken/D…    (0)
```

I think this is a bug that has been introduced in the following commit: 9e6ba52b84d6b70bd6bebd1edefabf62418a82e1. Probably best to make the `$debug` parameter optional and `FALSE` by default in `Drupal->boot()`?

**Comment by nvaken** [comment]
Wrong paste on the title, sorry 'bout that.

**Comment by jmolivas** [comment]
@nvaken yes debug parameter must be set to false as default at the method

**Comment by nvaken** [comment]
@jmolivas See above PR.

**Comment by neclimdul** [comment]
Any chance of this fix getting fast tracked into a release? This isn't a warning in php 7.1 but actually a fatal error making those commands completely broken.

http://php.net/manual/en/migration71.incompatible.php

**Comment by jmolivas** [comment]
Closing this one. Feel free to comment if still happening after updating to the latest version.
