### ISSUE TITLE
Allow config_directories key to be used in config:export

### ISSUE THREAD

**Issue by nvaken** [hechoendrupal/drupal-console#3180]
Same functionality exists in Drush. When you have a `$config_directory['foo'] = 'bar/';` setup in your settings.php, it will allow to export to that specific bar directory by using:

```
drush config-export foo
```

In Drupal Console there could be a same approach:

```
drupal config:export foo
```

Edit: Might even be nice to make this interactive? Selecting the `$config_directories` interactively.

**Comment by enzolutions** [comment]
Resolved with https://github.com/hechoendrupal/drupal-console/pull/4097
