### ISSUE TITLE
PHP Fatal error:  Cannot use Drupal\Console\Core\Bootstrap\DrupalConsoleCore as DrupalConsoleCore because the name is already in use in /var/www/public_html/vendor/drupal/console/src/Bootstrap/Drupal.php on line 11

### ISSUE THREAD

**Issue by hatuhay** [hechoendrupal/drupal-console#3181]
I execute a `composer update`

After command completed, I run the `drupal` command and got following error:

`PHP Fatal error:  Cannot use Drupal\Console\Core\Bootstrap\DrupalConsoleCore as DrupalConsoleCore because the name is already in use in /var/www/public_html/vendor/drupal/console/src/Bootstrap/Drupal.php on line 11`

Tried running directly ` vendor/bin/drupal` and got this error:

`Uncaught PHP Exception Drupal\Component\Plugin\Exception\PluginNotFoundException: "The "team" entity type does not exist." at /var/www/public_html/core/lib/Drupal/Core/Entity/EntityTypeManager.php line 133`

**Comment by hatuhay** [comment]
Reinstalling the global executable https://github.com/hechoendrupal/drupal-console#install-drupal-console-launcher, solved the problem.

**Comment by aangelinsf** [comment]
Thanks you, just hit the same problem and your solution did the trick.

**Comment by artatum** [comment]
Same here, but for me this message is only happening on specific projects, cloned from a repo. (built somewhere else). In others projects, created on my local, console works.

**Comment by jmolivas** [comment]
Make sure you have the latest DrupalConsole and Launcher version.

Closing this one. Feel free to comment if still happening after updating to the latest version.
