### ISSUE TITLE
[config:export] misses the config translation entities

### ISSUE THREAD

**Issue by cburschka-pwc** [hechoendrupal/drupal-console#3182]
When exporting the configuration via the site, the translated objects and entities are exported as `language/XY/ID.yml` files.

drupal config:export must export these as well - if it doesn't, they will get lost on subsequent imports.

**Comment by cburschka-pwc** [comment]
Some investigation shows that the code I'm adding was actually in the class until removed by 186db04dc7b983b27ad0a4188564ec689a7a9b56 in November '15. The only indication I can find in the commit message is "removing unused code". Was that intentional?

The above change adds the collection export back, and it's definitely required for the config_translation strings to get properly exported.

(I haven't checked config:import yet, only the web import.)

**Comment by jmolivas** [comment]
@cburschka-pwc  PR https://github.com/hechoendrupal/drupal-console/pull/3482 merged. Can we consider this one fixed?

**Comment by enzolutions** [comment]
@cburschka-pwc Can we consider this one fixed?

**Comment by cburschka** [comment]
I think that's a safe assumption, based on the PR being merged, though it's been at least two years since I looked at this code. ;-)
