### ISSUE TITLE
drupal generate:plugin:views:field  overriding custom_modules.views.inc file every time I generate new field.

### ISSUE THREAD

**Issue by suresh-kumara-gist** [hechoendrupal/drupal-console#3183]
drupal generate:plugin:views:field  overriding custom_modules.views.inc file every time I generate new field. 
I have created 2 views custom field using drupal generate:plugin:views:field   2 times, both field classes are generated  src/Plugin/views/field/fieldclassName . But problem with custom_modules.views.inc file the second filed data is overriding first one. Instead both field information should present in hook_views_data(). 
But 2nd field is overriding first one.

**Comment by LOBsTerr** [comment]
PR - https://github.com/hechoendrupal/drupal-console/pull/3814
Translation PR - https://github.com/hechoendrupal/drupal-console-en/pull/188
