### ISSUE TITLE
Console: dangling symlinks in bin

### ISSUE THREAD

**Issue by twhiston** [hechoendrupal/drupal-console#3186]
### Issue 

Drupal console contains some dangling symlinks in the /bin folder 

During our build process we see the following errors because of these symlinks

```
chgrp: cannot dereference './src/app/vendor/drupal/console/bin/psysh': No such file or directory
chgrp: cannot dereference './src/app/vendor/drupal/console/bin/php-parse': No such file or directory
chmod: cannot operate on dangling symlink './src/app/vendor/drupal/console/bin/psysh'
chmod: cannot operate on dangling symlink './src/app/vendor/drupal/console/bin/php-parse'
```

and if you check the /bin folder you can see that this is true.

Are these symlinks in the project /bin actually needed as they are from third party libraries and a composer install of drupal console should actually link these into /vendor/bin and not /vendor/drupal/console/bin

### How to reproduce

Install drupal console via composer
check /vendor/drupal/console/bin and see dangling symlinks

### Solution
Remove symlinks from the project bin if possible

**Comment by lmakarov** [comment]
Fixing might be a better solution. These two symlinks point to wrong locations.
The actual binaries are three levels above instead of one (`../../../` instead of `../`).

```
drupal8/docroot/vendor/drupal/console/bin
$ ls -la
total 32
drwxr-xr-x   6 leonid  _lpoperator   204 Feb  9 10:54 .
drwxr-xr-x  25 leonid  _lpoperator   850 Mar  3 08:41 ..
-rwxr-xr-x   1 leonid  _lpoperator    48 Feb  9 10:54 drupal
-rw-r--r--   1 leonid  _lpoperator  1757 Feb  9 10:54 drupal.php
lrwxrwxrwx   1 leonid  _lpoperator    40 Mar  3 08:41 php-parse -> ../vendor/nikic/php-parser/bin/php-parse
lrwxrwxrwx   1 leonid  _lpoperator    29 Mar  3 08:41 psysh -> ../vendor/psy/psysh/bin/psysh
```

```
$ ls -la ../../../psy/psysh/bin/psysh
-rwxr-xr-x  1 leonid  _lpoperator  4158 Feb 28 16:13 ../../../psy/psysh/bin/psysh

$ ls -la ../../../nikic/php-parser/bin/php-parse
-rwxr-xr-x  1 leonid  _lpoperator  6098 Feb 10 12:20 ../../../nikic/php-parser/bin/php-parse
```

**Comment by back-2-95** [comment]
For me this prevents deployments where codebase is created and then artifact tar is created.
Tar will fail when it hits to these broken symlinks.

**Comment by tdm4** [comment]
We have this problem too. We're using Atlassian Bamboo so broken symlinks basically prevents an artifact from being created. It appears these symlinks exist in the git repo itself. If you git clone it and look in bin, the symlinks are there and also broken because they link to a ../vendor directory that does not exist. Best thing to do would be to remove the symlinks from the git repo.

**Comment by jmolivas** [comment]
@tdm4 exactly, we need to remove those symlinks and also add `bin/php-parse` and `bin/psysh` to the `.gitignore` file.

**Comment by jmolivas** [comment]
PR sent https://github.com/hechoendrupal/drupal-console/pull/3276

**Comment by jmolivas** [comment]
I removed the symlinks, these will be created by composer once composer require `drupal/console` is executed.
