### ISSUE TITLE
Allow database:add to be used even when Drupal is not installed

### ISSUE THREAD

**Issue by nvaken** [hechoendrupal/drupal-console#3187]
Currently you need Drupal to be installed to add database entries to settings.php. This makes it in most use-cases a bit useless; only in a multisite setup where you already have one database setup you're able to use this command for other databases.

It would be great to use this command when Drupal is not installed.

**Comment by harold20** [comment]
Duplicated https://github.com/hechoendrupal/drupal-console/issues/3097
