### ISSUE TITLE
config:export seems to ignore components (such as blocks) for uninstalled themes

### ISSUE THREAD

**Issue by clrockwell79** [hechoendrupal/drupal-console#3199]
### Problem/Motivation
I used `config:export` to export configuration after uninstalling Bartik.  When importing this configuration I received the error:

> The import failed due for the following reasons: [error]
> Configuration <em class="placeholder">block.block.bartik_account_menu</em> depends on the > <em class="placeholder">Bartik</em> theme
> that will not be installed after import.

After this, I exported the configuration using `drush config-export` and found that drush was deleting several bartik related configuration files while Drupal Console was not - console was only updating `core.extension.yml` to set `bartik: 0`.

### How to reproduce

1. Export configuration and import into another site
2. Uninstall a theme from /admin/appearance.  I have done this with Bartik and Stark
3. Export configuration again
4. Import configuration - this will produce the error.

I am attaching a screenshot that shows:
1. Export using drush, which is cancelled
2. Export using Console
3. View of the diff from the Console export

![image](https://cloud.githubusercontent.com/assets/1805757/23195734/2636a1a2-f883-11e6-920f-d3d821b3c894.png)

**Details to include:**
- Drupal 8.1.9
- Console version 1.0.0-rc16.
- Drupal Console Launcher version 1.0.0-rc16

**Comment by harold20** [comment]
This issue is no longer present in the current version 1.9.0
