### ISSUE TITLE
[*module:install*] wrong dependency reported when installing file_browser

### ISSUE THREAD

**Issue by GiorgosK** [hechoendrupal/drupal-console#3201]
tried to install file_browser with drupalconsole 1.0.0-rc16 (latest at this time)

>drupal module:install file_browser

and it reported the following dependencies

>Module 'file_browser' cannot be installed: Imagesloaded library missing |
Module 'file_browser' cannot be installed: Dropzone library missing |

which was incorrect as I realized when going to the project's main page it turns out `imagesloaded` and `masonry` libraries are required.  Finally succeeded installing from the drupal GUI.

support request was originally reported here https://www.drupal.org/node/2853764

**Comment by harold20** [comment]
This is no longer present using the version 1.9.0
