### ISSUE TITLE
Can't use custom Console Commands

### ISSUE THREAD

**Issue by geerlingguy** [hechoendrupal/drupal-console#3203]
### Can't use contrib module Console Commands

[ *console* ] After installing Entity Pilot Git, I can't use the commands it adds in.

### Problem/Motivation

When I install a contrib module that has extra Drupal Console commands, I can't find them in `drupal list`, and I can't run them with `drupal module:command`.

### How to reproduce

```
$ drupal --version
Drupal Console version 1.0.0-rc13
```

1. Install an instance of Drupal VM with `drupalconsole` in `installed_extras`
2. Log into the VM
3. `cd /var/www/drupalvm/drupal`
4. `composer require drupal/entity_pilot:1.x-dev` (dev required to install correctly)
5. `composer require drupal/entity_pilot_git:^1.0`
6. `drupal module:install entity_pilot_git`
7. `drupal list` <-- Doesn't show the `entity_pilot_git:import` or `entity_pilot_git:export` commands
8. Try to run the command directly:

```
$ drupal entity_pilot_git:import

                                                                                                                        
 [ERROR] Command "entity_pilot_git:import", is not a valid command name.
```

### Solution

Find a way to make it so I can have Drupal Console automatically pick up contributed module commands. Note that I also tried with `rc16` and was still unable to get this working...

Do I need to run some other additional command to get Drupal Console to find contrib module's commands? No matter what I do, I can only use the Drupal Console core commands :(

**Comment by jmolivas** [comment]
@geerlingguy I will take a look and ping you back

**Comment by geerlingguy** [comment]
Thanks! I should also be able to hop on Gitter later too.

**Comment by nvaken** [comment]
@geerlingguy Not that I know of a fix in any of the latest versions of DC, but did you try upgrading to the latest RC16?

**Comment by geerlingguy** [comment]
@nvaken I've tried both rc16 and rc13, no luck.

**Comment by geerlingguy** [comment]
I'm on rc16, and still having trouble. I just created one custom command then tried using it, and it's saying it's not available. Exact steps below:

  1. `./vendor/bin/drupal generate:command` (generate a new command called `mymodule:export`)
  2. `./vendor/bin/drupal list` (command is not in the list)
  3. `./vendor/bin/drupal mymodule:export` (returns below error)

```
$ ./vendor/bin/drupal mymodule:export

                                                                                                                        
 [ERROR] Command "mymodule:export", is not a valid command name.   
```

**Comment by geerlingguy** [comment]
Ah, so it looks like there are two parts missing: all older contrib projects using custom commands generated pre-rc16 need to have a `console.services.yml` file added:

```yaml
services:
  mymodule.mymodule_export:
    class: Drupal\mymodule\Command\ExportCommand
    arguments: []
    tags:
      - { name: drupal.command }

```

Then on top of that, one must run `drupal cr all` to flush the caches after said file is added, and then the command will be picked up.

I'm going to test with the `entity_pilot_git` module and will file an upstream patch if that's the case.

**Comment by geerlingguy** [comment]
See patch for the module in question here: https://www.drupal.org/node/2854972#comment-11964466

Thanks for the pointers, @jmolivas !

**Comment by acbramley** [comment]
https://hechoendrupal.gitbooks.io/drupal-console/content/en/extending/creating-custom-commands.html and https://hechoendrupal.gitbooks.io/drupal-console/content/en/extending/registering-commands-automatically.html need updating

**Comment by geerlingguy** [comment]
Maybe we reopen this ticket until the docs reflect the usage?

**Comment by acbramley** [comment]
@geerlingguy yeah, I'm trying your patch for entity_pilot_git and I still can't see the commands registered. I've even tried using the `drupal generate:command` and not even the generated command is showing up. Not sure what I'm missing here.

**Comment by acbramley** [comment]
Ahah! I was missing running `drupal init`

**Comment by geerlingguy** [comment]
Ha, that'll do it.

**Comment by PatrickBauer** [comment]
When did it change from MODULE_NAME.services.yml to console.services.yml?
I had to copy&paste the new entries in console.services.yml to my MODULE_NAME.services.yml to make the commands work again.

**Comment by jmolivas** [comment]
@PatrickBauer we changed because an issue with metatag. We did this to avoid Drupal trying to load DC services on sites where DrupalConsole is not installed.
