### ISSUE TITLE
generate:entity:content Removing the owner breaks entity type discovery

### ISSUE THREAD

**Issue by jchatard** [hechoendrupal/drupal-console#3205]
### Problem/Motivation

Removing owner from a `generate:entity:content` entity blocks the discovery of the entity type.

### How to reproduce

**Details to include:**
- Drupal version 8.2.6
- Console version 1.0.0-rc16
- Console Launcher version 1.0.0-rc16

Generate a content entity using `generate:entity:content`. No revision, not translatable, but I think it's not the point.

After code generation, I edited the files:

In `src/Entity/FooEntityInterface.php` removing:

* `use Drupal\user\EntityOwnerInterface;`
* `EntityOwnerInterface` from `extends...`

In `src/Entity/FooEntity.php` removing:

`use Drupal\user\UserInterface;`

```php
$values += array(
      'user_id' => \Drupal::currentUser()->id(),
);
```

Removing:

```php
/**
   * {@inheritdoc}
   */
  public function getOwner() {
    return $this->get('user_id')->entity;
  }

  /**
   * {@inheritdoc}
   */
  public function getOwnerId() {
    return $this->get('user_id')->target_id;
  }

  /**
   * {@inheritdoc}
   */
  public function setOwnerId($uid) {
    $this->set('user_id', $uid);
    return $this;
  }

  /**
   * {@inheritdoc}
   */
  public function setOwner(UserInterface $account) {
    $this->set('user_id', $account->id());
    return $this;
  }
```

```php
$fields['user_id'] = BaseFieldDefinition::create('entity_reference')....
// And following lines related to this property.
```

Then enable the module. The new entity type is not visible in the UI, no routes, no `config/structure` links either, etc. But the table is created in the database. When accessing a route which should have been defined, I get the following error:

```
PHP message: Uncaught PHP Exception Drupal\Component\Plugin\Exception\PluginNotFoundException: "The "foo" entity type does not exist." at /var/www/core/lib/Drupal/Core/Entity/EntityTypeManager.php line 133
```

As a consequence, my question is: Is it supported to remove the owner dependency from a custom entity type? Because I don't need this information for this content entity type.

Does drupal console allow to create such an entity? Or should I create it from scratch?

Thanks,
Jérémy

**Comment by jmolivas** [comment]
@jchatard We can probably add a question to ask if you want to generate the owner code section.

**Comment by jchatard** [comment]
@jmolivas this sounds reasonable.

Thanks.

**Comment by enzolutions** [comment]
Solved with PR https://github.com/hechoendrupal/drupal-console/pull/4098
