### ISSUE TITLE
Display error when broken composer.json has been found

### ISSUE THREAD

**Issue by nvaken** [hechoendrupal/drupal-console#3206]
Currently, when using launcher on a project with a broken `composer.json` file it will report that you have to execute drupal console in a Drupal root folder. It might be nice to include a small check, that when a composer.json file has been found, but cannot be read, it will trigger a other message, reporting that it cannot read the current composer.json file. 

Just a small sanity check for the developer.

**Comment by jmolivas** [comment]
@nvaken you can use `composer validate` to check your composer file.

I added a message when drupal is not loaded but a `composer.json` file is found
https://github.com/hechoendrupal/drupal-console-launcher/pull/90

<img width="715" alt="drupal-launcher-composer-validate" src="https://cloud.githubusercontent.com/assets/366275/24394229/03099972-1350-11e7-83b1-816e165d6d7d.png">

I will try to do the same for this project.

**Comment by nvaken** [comment]
That feedback seems a bit confusing, does it execute the validation? 

Line `Use composer to validate your composer.json file.` seems to suggest that you execute it yourself.
Line `Executing: composer validate` seems to suggest it is now being executed, in contrary with the first line. 

Sorry for nitpicking :)

**Comment by jmolivas** [comment]
Worry not what would be a better message ?

Instead of 
```
Executing: composer validate
```
Use something like:
```
Please execute: composer validate
```

**Comment by nvaken** [comment]
Sounds good to me! 👍

**Comment by jmolivas** [comment]
Fixed on RC17 current error message:

<img width="649" alt="drupal-list-broken-composer-1" src="https://cloud.githubusercontent.com/assets/366275/25567645/723612c8-2da7-11e7-8517-9a76b570923c.png">

I am planning to change the message on RC18 and will be like this:

<img width="781" alt="drupal-list-broken-composer-2" src="https://cloud.githubusercontent.com/assets/366275/25567728/22ca79f2-2da9-11e7-88c2-31c3c071a38f.png">

**Comment by jmolivas** [comment]
Fixed on RC17.
