### ISSUE TITLE
router:debug [argument] 

### ISSUE THREAD

**Issue by taeyoun** [hechoendrupal/drupal-console#3208]
### Issue title

The issue title should comply with the following structure:

[ *ROUTERP:DEBUG* ] Short description

The *ROUTER:DEBUG* should be one of:

* `router:debug [argument]`
* `console`

### Problem/Motivation
"drupal router:debug" works but it returns nothing for "drupal router:debug views_ui.form_handler_extra".

### How to reproduce
type "drupal router:debug views_ui.form_handler_extra" in CLI

**Details to include:**
- Drupal version (8.2.6).
- Console version (you can obtain this by running `composer show | grep drupal/console`).
- Console Launcher version (0.10.14).

**Comment by jmolivas** [comment]
@taeyoun your DC version is really old, you  should update it
https://github.com/hechoendrupal/drupal-console#update-drupalconsole-launcher

If that does not work try installing latest version
https://github.com/hechoendrupal/drupal-console#install-drupal-console-launcher 

Starting on RC releases DrupalConsole must be installer per site you can find instructions at
https://github.com/hechoendrupal/drupal-console#download-as-new-dependency

<img width="1401" alt="drupal-router-debug-views_ui form_handler_extra" src="https://cloud.githubusercontent.com/assets/366275/24393674/cd98218e-134d-11e7-8f4a-c0e191ddcc13.png">

**Comment by jmolivas** [comment]
Closing this one. Feel free to re-open if still happening after updating to the latest version.
