### ISSUE TITLE
[generate:command] ArgumentCountError: Too few arguments to function Manager::getList()

### ISSUE THREAD

**Issue by PatrickBauer** [hechoendrupal/drupal-console#3209]
The generate:command Command uses the ExtensionTrait  and this uses ExtensionManager::getList() but without any arguments, throwing an "ArgumentCountError: Too few arguments to function Manager::getList()"

The following pull request solves the issue by providing an argument to the function call.
https://github.com/hechoendrupal/drupal-console/pull/3207

**Comment by jmolivas** [comment]
Fixed with #3207
