### ISSUE TITLE
Windows 10 Git bash tar error

### ISSUE THREAD

**Issue by forethoughtde** [hechoendrupal/drupal-console#3211]
### Windows Git bash tar error 

The issue title should comply with the following structure:

Summary: Could not able to install Drupal 8 from Drupal Console in Windows 10 OS.  

Issue Area:
* drupal chain --file=.console/chain/quick-start.yml
* `console`

### How to reproduce
Install the Drupal console from composer by running the following command in Git bash in Windows 10
` composer global require drupal/console:1.0.*@dev`
Then run the following to copy the configuration files to home directory
`drupal init --override`
Then run the command to install the Drupal 8
`drupal chain --file=.console\chain/quick-start.yml` 
Observe the error message. 
```
 [ERROR] Unable to execute the following command "C:\Program Files\Git\usr\bin\tar.EXE" "--extract"
         "--file=C:\Users\KARTHI~1\AppData\Local\Temp/drupal.tar.gz" "--overwrite-dir" "--overwrite" "--gzip"
         "--directory" "C:\Users\karthikeyan/" {output: /usr/bin/tar: '--overwrite' cannot be used with
         '--overwrite-dir'
Try '/usr/bin/tar --help' or '/usr/bin/tar --usage' for more information.
}
 Drupal "8.2.6" was downloaded in directory "drupal-8.2.6"
 [ERROR] An error occurred while renaming directory as "drupal8.dev"

```

**Comment by parijke** [comment]
I have got the same...
Ubuntu 17.04
Drupal Console (0.11.2)

command:
```
drupal site:new d8.dev 8.3.2
```

```
 [ERROR] Unable to execute the following command '/bin/tar' '--extract'         
 '--file=/tmp/drupal.tar.gz' '--overwrite-dir' '--overwrite' '--gzip'           
 '--directory' '/home/paul/www/' {output: /bin/tar: optie '--overwrite' gaat    
 niet samen met '--overwrite-dir'                                               
 Typ '/bin/tar --help' of '/bin/tar --usage' voor meer informatie.              
 }                                                                                                                                                              
                                                                                
 Drupal 8.3.2 was downloaded in directory drupal-8.3.2                          
                                                                                                                                                                
 [ERROR] An error occurred while renaming directory as d8.dev  ```

**Comment by nequeteme** [comment]
I tested and it works, @forethoughtde could you please use Cmder https://cmder.net (Console emulator for Windows), it have the command tar 

- Windows 10 Home
- Cmder version 180626
- XAMPP Version 7.3.9 

![image](https://user-images.githubusercontent.com/250047/66011452-c8f9a580-e488-11e9-97f7-373151fcfb1b.png)
