### ISSUE TITLE
Call to undefined method Drupal\Console\Core\Utils\ConfigurationManager::loadExtendConfiguration()

### ISSUE THREAD

**Issue by yassintahtah** [hechoendrupal/drupal-console#3212]
My drupal console suddenly stopped working, not sure what's causing it. I've tried reinstalling everything but I still get the same error.

My version:

drupal/console                        1.0.0-rc16    The Drupal CLI. A tool to generate boilerplate code, interact with and debug Drupal.
drupal/console-core                   1.0.0-rc16    Drupal Console Core
drupal/console-en                     1.0.0-rc16    Drupal Console English Language
drupal/console-extend-plugin          0.4.0         Drupal Console Extend Plugin

`PHP Fatal error:  Call to undefined method Drupal\Console\Core\Utils\ConfigurationManager::loadExtendConfiguration() in /Users/yassin/Projects/legrand/vendor/drupal/console-core/src/Application.php on line 284`

**Comment by jmolivas** [comment]
@yassintahtah are you using the Launcher aka global executable `drupal`?

If yes try updating that by executing `drupal self-update`

**Comment by mikl** [comment]
I'm seeing the same problem here.

**Comment by mikl** [comment]
After downgrading to 1.0.0-rc14, I can now use Drupal Console again. (Using Drupal 8.2.6).

**Comment by petiar** [comment]
Same error here. With any command, including the self-update.

**Comment by jmolivas** [comment]
@mikl @petiar try that DrupalConsole on the site and the Launcher to share the same version.

**Comment by hussainweb** [comment]
Just a tip: Running `drupal self-update` in your Drupal installation directory or even in the directory with composer.json results in the error. Try running it from a completely unrelated location, like your home directory. I also had to use `sudo` so that it gets permission to overwrite it in the `bin` directory.

**Comment by FatherShawn** [comment]
I just hit this error with `vendor/bin/drupal` directly, not with the launcher on RC16

**Comment by spideep** [comment]
@hussainweb your answer worked in my case. Thanks

**Comment by khananayat** [comment]
PHP Fatal error:  Call to undefined method Drupal\Console\Core\Utils\ConfigurationManager::loadExtendConfiguration() in /var/www/drupal-8261/vendor/drupal/console-core/src/Application.php on line 284

**Comment by jmolivas** [comment]
@yassintahtah @khananayat https://github.com/hechoendrupal/drupal-console/issues/3212#issuecomment-285883126

**Comment by jmolivas** [comment]
This issue will go away once we release new version since Launcher will not include commands other than self-update and will not depend on `drupal/console-core`

**Comment by smith-stevan** [comment]
Just try to run `drupal-self-update` in non drupal directory, it works for me.

**Comment by jmolivas** [comment]
@smith-stevan did you installed globally using the `launcher` or `composer global require`

**Comment by smith-stevan** [comment]
@jmolivas `composer global require`

**Comment by jmolivas** [comment]
did you follow instructions at => https://docs.drupalconsole.com/en/getting/project.html

**Comment by jmolivas** [comment]
Closing this one. Feel free to re-open if still happening after updating to the latest version.
