### ISSUE TITLE
[update:execute] Missing required &$sandbox parameter

### ISSUE THREAD

**Issue by cburschka-pwc** [hechoendrupal/drupal-console#3213]
hook_update_N takes a referenced array as a parameter. Most functions don't use it at all, but hook_update_8400 does, and can't be run by drupal-console.

Instead of using `@module_handler::invoke($module, 'update_' . $n)` here, the code probably needs to include `update.inc` and call `update_do_one($module, $n, $dependencies)`.

**Comment by harold20** [comment]
@cburschka-pwc this command has been refactored in the latest version 1.9.0. and we no longer use `module_handler::invoke`

We will close this issue and feel free to reopen if you think that it need more work
