### ISSUE TITLE
[console] Class DrupalFinder\DrupalFinder not found

### ISSUE THREAD

**Issue by ohthehugemanatee** [hechoendrupal/drupal-console#3214]
### Problem/Motivation
Installed console normally with `composer require drupal/console:~1.0 --prefer-dist --optimize-autoloader --sort-packages`. Got console version 1.0.0-rc11. Running any command with the console gives a fatal error:

```
Fatal error: Uncaught Error: Class 'DrupalFinder\DrupalFinder' not found in /var/www/html/vendor/drupal/console/bin/drupal.php on line 35

Error: Class 'DrupalFinder\DrupalFinder' not found in /var/www/html/vendor/drupal/console/bin/drupal.php on line 35

Call Stack:
    0.0002     358008   1. {main}() /var/www/html/vendor/drupal/console/bin/drupal:0
    0.0004     358800   2. require('/var/www/html/vendor/drupal/console/bin/drupal.php') /var/www/html/vendor/drupal/console/bin/drupal:4
```
I have no trouble with other composer-installed CLI tools (ie drush-8.x-dev)

### How to reproduce
Run any console command with:
PHP 7 (tested with 7.0.13-0ubuntu0.16.04.1 and 7.1.1)
Drupal 8.2.3
drupal/console 1.0.0-rc11
drupal/console-core v1.0.0-rc8
drupal/console-en 1.0.0-rc16

**Comment by jmolivas** [comment]
@ohthehugemanatee can you try to update DrupalConsole using composer
```
composer update drupal/console --with-dependencies
```
Not sure why you have different version of the DR projects.

**Comment by jmolivas** [comment]
Closing this one. Feel free to re-open if still happening after updating to the latest version.
