### ISSUE TITLE
Ask if user want to create config file on generate:form

### ISSUE THREAD

**Issue by guiajlopes** [hechoendrupal/drupal-console#3217]
### Ask if user want to create config file on generate:form

[command:name] Short description
We should ask the user if they want to create a config file on generate:form command

### Problem/Motivation
Currently the generate:form just create the config file, sometimes we don't need it, so I think is a good idea ask the users if they want to create the file or not.

### Solution
Ask the user before create the config file.

**Comment by miguel303** [comment]
PR sent at https://github.com/hechoendrupal/drupal-console/pull/3218

**Comment by jmolivas** [comment]
@guiajlopes  PR merged thanks @miguel303
