### ISSUE TITLE
[console] There is no hostname available when running requests using drupal console 

### ISSUE THREAD

**Issue by mariano-dagostino** [hechoendrupal/drupal-console#3221]
### Problem/Motivation

I'm reviewing this patch: https://www.drupal.org/node/2755497 but I'm not really sure this is a drupal core issue or a console issue.

The relevant comment #12 says:

> FYI, when running requests using drush/drupal console there is no hostname available.

I tried with drush, and it uses 'default' as default hostname. Is drupal console using something similar?

**Comment by mariano-dagostino** [comment]
I did some research, and drush specficy this value in

```php
/**
 * Find the URI that has been selected by the cwd
 * if it was not previously set via the --uri / -l option
 */
function _drush_bootstrap_selected_uri() {
  $uri = drush_get_context('DRUSH_SELECTED_URI');
  if (empty($uri)) {
    $site_path = drush_site_path();
    $elements = explode('/', $site_path);
    $current = array_pop($elements);
    if (!$current) {
      $current = 'default';
    }
    $uri = 'http://'. $current;
    $uri = drush_set_context('DRUSH_SELECTED_URI', $uri);
    drush_sitealias_create_self_alias();
  }

  return $uri;
}
```

**Comment by harold20** [comment]
Hi @mariano-dagostino Sorry for the late response.

We set 'default' as default hostname, when the uri option is not passsed.
You can see the code here https://github.com/hechoendrupal/drupal-console-core/blob/master/src/Utils/ArgvInputReader.php#L155

**Comment by enzolutions** [comment]
@mariano-dagostino  I will close this issue, if you think there is still a problem, please let me know with extra information to re-open it.
