### ISSUE TITLE
(Unconfirmed critical) Base path messed up by Drupal console after cache rebuild

### ISSUE THREAD

**Issue by nvaken** [hechoendrupal/drupal-console#3222]
**Steps to reproduce.** 
_Note that database:dump is probably easily replaced by any other command, just as long as Drupal Console gets run right after the caches have been emptied._ 

1. `drupal cr all`
2. `drupal database:dump --file=test.sql`

Now check your Drupal install, most notably assets that are being loaded (images, CSS, JS, etc..). Probably all or just some assets will have your Drupal Console binary root path as base_path. In Drupal Console Launcher, on Mac, this might potentially result in a path like: 

http://localhost/PATH/TO/DRUPAL/WEB/http:/:/usr/local/bin/sites/default/files/styles/visual/public/2017-03/visual.jpg?itok=_nxSlCtU

This essentially breaks the entire Drupal installation, only after clearing caches again and making sure the next interaction with Drupal is through HTTP, you'll get the correct base path again. 

**Critical**
I think this is a highly critical issue and should be solved as quickly as possible, due to:

1. The procedure isn't that uncommon (clearing caches and immediately running another DC command)
2. Will wreck the site untill a next cache rebuild (our login form was even to badly damaged to login anymore through HTTP)
3. Exposes potentially sensitive server-side information (path to DC binary)

CC: @jmolivas

**Comment by ruloweb** [comment]
I was trying to reproduce the issue, and noticed that it only appends for anonymous users. To keep in mind.

**Comment by nvaken** [comment]
Probably because most caching functions are (by default) only available for anonymous users. Still, since most setups will have way more anonymous users then authenticated, this remains critical I think.

**Comment by jmolivas** [comment]
Fixed with https://github.com/hechoendrupal/drupal-console/pull/3248
