### ISSUE TITLE
[generate:module] use dashes not underscores in TWIG template name

### ISSUE THREAD

**Issue by mvc1095** [hechoendrupal/drupal-console#3227]
### Problem/Motivation

Throughout Drupal the standard is to use dashes twig template filenames, but generate:module creates a twig file with underscores and so it has to create a hook_theme() function which includes the optional `template` parameter:

```
  function my_module_theme() {
    return [
      'my_module' => [
        'template' => 'my_module',
        'render element' => 'children',
      ],
    ];
  }
```

This will load the file `templates/my_module.html.twig`. However, Drupal core currently contains 472 .html.twig files, and not counting unit tests of the template and theme system automated tests only one contains underscores in the filename (config_translation_manage_form_element.html.twig).

### How to reproduce

Produced using console 1.0.0-rc16

### Solution

If this function was written like this it would load the file `templates/my-module.html.twig`, which would be more standard.

```
  function my_module_theme() {
    return [
      'my_module' => [
        'render element' => 'children',
      ],
    ];
  }
```

**Comment by jmolivas** [comment]
Fixed with PR https://github.com/hechoendrupal/drupal-console/pull/3241

**Comment by jmolivas** [comment]
@mvc1095 Closing this one. Feel free to re-open if still happening after updating to the latest version.

**Comment by jmolivas** [comment]
PR to make sure generated twig file uses `-` instead of `_` https://github.com/hechoendrupal/drupal-console/pull/3242
