### ISSUE TITLE
Regenerate cached services files

### ISSUE THREAD

**Issue by nvaken** [hechoendrupal/drupal-console#3234]
When introducing new changes to your package `console.services.yml` file, you'll need to make sure the `extend.console.services.yml` is updated as well. As far as I know, composer install or composer update will regenerate. But, in favor of easy development of your package, it would be nice to regenerate the file on-the-fly.

**Comment by jmolivas** [comment]
@nvaken The files can be re-generated by executing `drupal cr all` command.

**Comment by cburschka-pwc** [comment]
Note that an outdated service cache will block the bootstrap (and thus cr
all) in many cases. I'm not sure if there's any way to solve that within
DC, though.

**Comment by jmolivas** [comment]
I added some logic to read if command is `cr` `cache:rebuild`
https://github.com/hechoendrupal/drupal-console/blob/master/src/Bootstrap/Drupal.php#L63 and rebuild re-generate the file.

**Comment by jmolivas** [comment]
This PR addresses this issue https://github.com/hechoendrupal/drupal-console/pull/3263

**Comment by jmolivas** [comment]
Closing this one. Feel free to re-open if still happening after updating to the latest version.

**Comment by nvaken** [comment]
Just downloaded the latest `master` but seems impossible for me to make sure `extend.console.*.services.yml` files are being regenerated.

**Comment by jmolivas** [comment]
We have some PRs on the composer plugin I will be reviewing and merging before DrupalCon.

**Comment by jmolivas** [comment]
@nvaken this is the repo where all this is happening => https://github.com/hechoendrupal/drupal-console-extend-plugin
