### ISSUE TITLE
DrupalConsole rc16 doesn't work

### ISSUE THREAD

**Issue by csandanov** [hechoendrupal/drupal-console#3250]
When I  execute `drupal` command in the drupal 8 root directory (installed via composer template) I get:
```
[ERROR] Class Drupal\Core\DrupalKernel do not exists.

  [Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException]
  You have requested a non-existent service "class_loader".
```

When I try the same with drupal downloaded via drush:
```
 [ERROR] Class Drupal\Core\DrupalKernel do not exists.


PHP Fatal error:  Uncaught InvalidArgumentException: The file "/var/www/html/drupal-8.2.7/vendor/drupal/console-core//services.yml" does not exist. in /home/www-data/.composer/vendor/symfony/config/FileLocator.php:44
Stack trace:
#0 /home/www-data/.composer/vendor/symfony/dependency-injection/Loader/YamlFileLoader.php(42): Symfony\Component\Config\FileLocator->locate('/var/www/html/d...')
#1 /home/www-data/.composer/vendor/drupal/console-core/src/Bootstrap/DrupalConsoleCore.php(48): Symfony\Component\DependencyInjection\Loader\YamlFileLoader->load('/var/www/html/d...')
#2 /home/www-data/.composer/vendor/drupal/console/src/Bootstrap/Drupal.php(44): Drupal\Console\Core\Bootstrap\DrupalConsoleCore->boot()
#3 /home/www-data/.composer/vendor/drupal/console/bin/drupal.php(51): Drupal\Console\Bootstrap\Drupal->boot(false)
#4 /home/www-data/.composer/vendor/drupal/console/bin/drupal(4): require('/home/www-data/...')
#5 {main}
  thrown in /home/www-data/.composer/vendor/symfony/config/FileLocator.php on line 44
```

Any suggestions?

**Comment by jmolivas** [comment]
@csandanov  Is the DrupalConsole Launcher `drupal` same version as DrupalConsole on the site?

**Comment by csandanov** [comment]
How can I check it? I just installed drupal console via composer:

```bash
$ composer global config minimum-stability rc
$ composer global require drupal/console:~1.0 drush/drush
```

You can reproduce it as:
```bash
$ docker run --rm -ti wodby/drupal-php:7.1 sh
$ drush dl drupal
$ drupal
```

**Comment by jmolivas** [comment]
DrupalConsole must be installer per-site (composer global require is not allowed)
https://docs.drupalconsole.com/en/getting/composer.html

We still provide a global executable aka Launcher
https://docs.drupalconsole.com/en/getting/launcher.html

**Comment by csandanov** [comment]
Ok, thanks for the clarification. I installed the Launcher as described in the documentation but when I go to drupal root (downloaded via drush) and run `drupal` it gives me:

```
 [ERROR] Drupal Console is not installed at:

 You must execute the following composer commands:

 composer require drupal/console:~1.0 --prefer-dist --optimize-autoloader
 composer update drupal/console --with-dependencies
```

What am I doing wrong?

**Comment by jmolivas** [comment]
@csandanov This is ok please read previous comment https://github.com/hechoendrupal/drupal-console/issues/3250#issuecomment-291912031

**Comment by jmolivas** [comment]
The launcher does not provide commands (still have some but those will go away on the next release) only `self-update` will be kept.

And DrupalConsole must be installer per site this is why you are getting this message:
```
 [ERROR] Drupal Console is not installed at:

 You must execute the following composer commands:

 composer require drupal/console:~1.0 --prefer-dist --optimize-autoloader
 composer update drupal/console --with-dependencies
```

We can probably improve the message to  something like:
```
 [ERROR] Drupal Console is not installed on this current site at:
 /path/to/drupal.dev

 You must execute the following composer commands:

 composer require drupal/console:~1.0 --prefer-dist --optimize-autoloader
 composer update drupal/console --with-dependencies
```

**Comment by csandanov** [comment]
@jmolivas so what's the point of this launcher? just to show a message that drupal console must be installed per each site?

**Comment by csandanov** [comment]
Ok, I think I got it – launcher helps to execute `drupal` without specifying the full path to the per project's console. Thanks for your help, Jesus.

**Comment by jmolivas** [comment]
Exactly @csandanov the idea of the launcher is to saving you time to figure out where are you located within the project and where is the `vendor/bin/drupal` binary and just type `drupal`.

**Comment by adriadrop** [comment]
I am wondering why this architectural change has happened, what were constrains that made globally available drupal console a problem?

**Comment by csandanov** [comment]
@adriadrop I think the main pro of this decision is that you can manage version of console per project which sometimes can be crucial due to constant changes/improvements and stability issues

**Comment by adriadrop** [comment]
You could do that before, it wasn't a must to put console in global.

**Comment by csandanov** [comment]
@adriadrop not sure I understand your question. You have drupal console per project installed via composer and you have console launcher aka `drupal` in CLI so you won't have to use the full path to the binary or even think where is it located.

**Comment by jmolivas** [comment]
@adriadrop  As mentioned on the docs Starting on RC releases DrupalConsole must be installed per site. Install Drupal Console using `composer global require` is no longer supported.
https://docs.drupalconsole.com/en/getting/project.html  

Instructions to install DrupalConsole per project
https://docs.drupalconsole.com/en/getting/composer.html

We still provide a global executable the aka as Launcher.
https://docs.drupalconsole.com/en/getting/launcher.html

The reason to manage DrupalConsole per site is that because you should Explicitly declare and isolate Application dependencies using a manifest file in this case `composer.json` to avoid conflict between dependencies of different projects installed globally.

@csandanov Explained properly we still provide a global executable aka Launcher.
