### ISSUE TITLE
Drupal console not working when composer file is in docroot

### ISSUE THREAD

**Issue by kgaut** [hechoendrupal/drupal-console#3253]
I've kind of the same issue that #3250 but with a specific setup.

I've drupal laucher installer globally : 

```
 drupal --verson
Drupal Console Launcher (1.0.0-rc16)
```

With many of my drupal website, console is working fine. But for a specific project, the composer.json file is in drupal docroot (not my choice). 
```
vendor/
   ....
web/
   core/
   modules/
   ....
   composer.json
   composer.lock
```

Sample of my composer.json file : 

```
    "require": {
        "composer/installers": "^1.2",
        "drupal-composer/drupal-scaffold": "^2.2",
        "cweagans/composer-patches": "~1.0",
        "drupal/core": "~8.0",
        "drush/drush": "~8.0",
        "drupal/console": "~1.0",
    ...
    },
    "extra": {
        "installer-paths": {
            "core": ["type:drupal-core"],
            "libraries/{$name}": ["type:drupal-library"],
            "modules/contrib/{$name}": ["type:drupal-module"],
            "profiles/contrib/{$name}": ["type:drupal-profile"],
            "themes/contrib/{$name}": ["type:drupal-theme"],
            "../drush/contrib/{$name}": ["type:drupal-drush"]
        },
    },
    "config": {
        "vendor-dir": "../vendor"
    }
```

when I cd in web directory and I try to use any console command here's the output : 

```
drupal
                                                                                                                        
 [ERROR] Drupal Console is not installed at:                   
 You must execute the following composer commands:                      
 composer require drupal/console:~1.0 --prefer-dist --optimize-autoloader                                               
 composer update drupal/console --with-dependencies               
```
Obvously I tried several times the above commands without any change.

I know my setup is not perfect, I'd rather prefer to have the composer files outside the docroot, but, as I said, it's not my choice.

Do you know how can I get drupal console to work ?

Thanks in advance.

**Comment by kgaut** [comment]
I've been digging a bit.

it seems that `Drupal\Console\Core\Bootstrap\DrupalConsoleCore::root` is returning the wrong path (it contains `web`)

And in `Drupal\Console\Bootstrap::__contruct` both `$this->root` and `$this->appRoot` cointain 'web' too.

**Comment by jmolivas** [comment]
@kgaut we are using the https://github.com/webflo/drupal-finder project to detect the drupal site.

**Comment by webflo** [comment]
@kgaut Can you open an issues in https://github.com/webflo/drupal-finder? Do you have another composer.json file above the web folder?

**Comment by webflo** [comment]
I looked at the issue, and there is nothing wrong in Drupal Finder. Drupal Finder has drupalRoot (location of DRUPAL_ROOT) and composerRoot (the location of composer.json). Its both ``/private/tmp/drupal-project/web/`` in my test. This is correct. Drupal Console assumes that composerRoot + '/vendor' is the location of the vendor folder. But the location is configurable in composer.

**Comment by webflo** [comment]
https://github.com/webflo/drupal-finder/pull/16 will help to resolve this issue, but some refactoring in drupal console is required to make it work.

**Comment by kgaut** [comment]
Thanks for your input !

> This is correct. Drupal Console assumes that composerRoot + '/vendor' is the location of the vendor folder. But the location is configurable in composer.

I'll try your PR on the website and try to refactor Console.

**Comment by webflo** [comment]
@jmolivas I found https://github.com/mindplay-dk/composer-locator a few minutes ago. Maybe it helps with refactoring.

**Comment by webflo** [comment]
But maybe its overhead, because its relatively easy with the vendor path.

**Comment by jmolivas** [comment]
@kgaut is this still happening using the latest DrupalConsole version?

**Comment by kgaut** [comment]
Hi,

Yep fantastic, it works fine now with 1.0.0-rc21 ! 

Thanks !

**Comment by begrafx** [comment]
I'm encountering the same issue. I'm using Drupal Console version 1.8.0, I have it installed globally. If I call it from almost anywhere, it'll work fine. However, if I call it from a directory that has a COMPOSER.JSON file in it I get the same error that @kgaut mentioned. I am using MAMP, and I have my various projects in separate folders within the HTDOCS folder. If I am in the HTDOCS folder:

<code>Brians-MacBook-Pro:htdocs brianeller$ drupal --version
Drupal Console Launcher 1.8.0</code>

all is good. Likewise, if I enter a folder that does not have a COMPOSER.JSON file. However, any folder that has a COMPOSER.JSON file in it:

<code>Brians-MacBook-Pro:sandbox brianeller$ drupal --version

                                                                                
 [ERROR] Drupal Console is not installed at: "                                  
         /Applications/MAMP/htdocs/sandbox"                                     
                                                                                

 You must execute the following composer commands:

                                                                                
 composer require drupal/console:~1.0 --prefer-dist --optimize-autoloader       
                                                                                

</code>

As you can see from the first example, I am running the most recent version of DrupalConsole.

**Comment by jmolivas** [comment]
How do you installed it?
>  I have it installed globally.

**Comment by begrafx** [comment]
I have Drupal Console installed Globally, and I have MAMP installed, 
with all of my sites in separate folders in the HTDOCS folder. As I say, 
I can call it from even the htdocs folder, within Terminal, and it'll 
work. I can go into a site folder that I haven't set up with GIT or any 
of that, so it doesn't have a COMPOSER.JSON file, and it'll work fine, 
but if I go into a folder that I've set up with GIT/Composer/etc., no go.

**Comment by jmolivas** [comment]
@begrafx  Starting on RC releases DrupalConsole must be installed per site. Install Drupal Console using `composer global require` is no longer supported. 

You can get more information at the docs https://docs.drupalconsole.com/en/index.html

**Comment by begrafx** [comment]
So I need to uninstall/delete the Global installation, and then add 
DrupalConsole to each COMPOSER.JSON, so it'll install for each site? Am 
I understanding you correctly?

**Comment by jmolivas** [comment]
Exactly you need to install per site.

The Launcher is the only one that is installed globally

**Comment by begrafx** [comment]
OK, so I need to delete the DRUPAL (Drupal Console) file from my 
/usr/local/bin folder, and then run

<code>composer require drupal/console:~1.0 --prefer-dist 
--optimize-autoloader </code>

in each site folder?
