### ISSUE TITLE
[module:install] does not check version dependencies

### ISSUE THREAD

**Issue by cburschka-pwc** [hechoendrupal/drupal-console#3254]
To reproduce:

- create a module with this dependency: `- drupal:system (>=8.3.0)`
- install a Drupal 8.2.7 site.
- visit /admin/modules to verify that the module is not installable: `Requires: System (>=8.3.0) (incompatible with version 8.2.7)`
- run `drupal module:install` in the console

Expected:

- The module fails to install due to broken requirements.

Actual:

- The module is installed successfully.

**Comment by harold20** [comment]
Thanks @cburschka-pwc It will be included in the next version 1.9.1
