### ISSUE TITLE
[config:export] doesn't seem to be removing configurations when a content type is removed

### ISSUE THREAD

**Issue by hanoii** [hechoendrupal/drupal-console#3256]
I removed the default Article content type and Tags vocabulary out of a normal install and drupal a `drupal ce` was not removing the config files. I was able to work around this by cleaning the sync dir first and then doing ci.

However, `drush cex` does remove them, which is odd, I thought the export was something out of drupal and the consoles were leveraging that, so that's why I think it could be a bug in console?

**Details to include:**
- Drupal version: 8.3.0
- Console version: 1.0.0-rc16
- Console Launcher version: 1.0.0-rc16

**Comment by jmolivas** [comment]
Thanks for reporting looking at this issue.

**Comment by jmolivas** [comment]
Fixed with https://github.com/hechoendrupal/drupal-console/pull/3288

Closing this one. Feel free to re-open if still happening after updating to the latest version.
