### ISSUE TITLE
Drupal\Console\Bootstrap\Drupal::boot method causes 404 errors

### ISSUE THREAD

**Issue by AlexKomm** [hechoendrupal/drupal-console#3264]
### [console] Drupal\Console\Bootstrap\Drupal::boot method causes 404 errors

Every console command causes 404 errors being logged in watchdog

In Drupal class there is a boot method where Request object is created
($request = Request::create($uri, 'GET', [], [], [], ['SCRIPT_NAME' => '/index.php']);).

Passing index.php as part of the uri string causes ResourceNotFoundException to be thrown in RouterListener service with message No route found for GET /index.php"

How can i solve this issue?

- Drupal version: 8.2.
- Console version: 1.0.0 rc-16

**Comment by jmolivas** [comment]
Closing this one. Feel free to re-open if still happening after updating to the latest version.
