### ISSUE TITLE
[generate:entity:content] creates translation elements when no translation chosen

### ISSUE THREAD

**Issue by Alluuu** [hechoendrupal/drupal-console#3275]
I am not yet extremely familiar with how entities are supposed to work, but for my content entity I chose it to be non translatable, yes revisionable and have no bundles.

However the created files have some translations related content: 
In CustomEntity.php preSave() function there's translations related code, and the Entity has langcode field.
It has created CustomEntityRevisionTranslationForm.php
CustomEntityStorage.php file has 2 language funcitons

Also even though I created the Entity without bundles it has field_ui_base_route = custom_entity.settings which I had to remove for everything to work, and as far as I can tell it's used for entities with bundles.

**Comment by paulmartin84** [comment]
Thanks, @Alluuu I ran into this issue as well, it also kills config translation when an incorrect  field_ui_base_route is set like that.

**Comment by LOBsTerr** [comment]
PR https://github.com/hechoendrupal/drupal-console/pull/3822

**Comment by LOBsTerr** [comment]
It was merged
