### ISSUE TITLE
[command:init] Current release is broken following install instructions

### ISSUE THREAD

**Issue by oxyc** [hechoendrupal/drupal-console#3279]
### Problem/Motivation

Since a few hours ago [Drupal VM travis](https://travis-ci.org/geerlingguy/drupal-vm/builds/225003977) started failing with _Could not find Drupal in the current path._ on the following command

```sh
php /usr/local/bin/drupal init
```

### How to reproduce

Follow the _Install Drupal Console Launcher_ steps.

```
$ curl https://drupalconsole.com/installer -L -o drupal.phar
$ chmod +x drupal.phar
$ php drupal.phar init
Could not find Drupal in the current path.
```

**Comment by jmolivas** [comment]
@oxyc `init` command is no longer valid.

**Comment by oxyc** [comment]
Thanks for the clarification!
