### ISSUE TITLE
Error upon running Drupal Console after Drupal was updated.

### ISSUE THREAD

**Issue by roman-yakimkin** [hechoendrupal/drupal-console#3282]
Hello.
Sorry for troubling but I had to open this issue.
The reason of it in an error displaying when I'm trying to run the console.

`
TypeError: Argument 2 passed to Drupal\Console\Command\Config\ExportCommand::__construct() must implement interface Drupal\Core\Config\StorageInterface, none given in Drupal\Console\Command\Config\ExportCommand->__construct() (line 43 of D:\OpenServer\domains\mysite.local\vendor\drupal\console\src\Command\Config\ExportCommand.php).
`
It happened after I had updated Drupal from 8.3.0 to 8.3.1. Before it I deleted the vendor folder from the site and after it I reinstalled locally and updated the Drupal Console.
Could you clarify me, what did I do wrong and how to repair it ?

**Comment by AndyD328** [comment]
Having the exact same error here. 

I tried removing vendor and re-installing everything as well as doing a self-update but it made no difference. 
Rolling back to rc16 has worked as a temporary fix with d 8.3.1

`TypeError: Argument 2 passed to Drupal\Console\Command\Config\ExportCommand::__construct() must implement interface Drupal\Core\Config\StorageInterface, none given in /var/www/sites/d8/thestyx.org.nz/drupal/vendor/drupal/console/src/Command/Config/ExportCommand.php on line 43 #0 [internal function]: Drupal\Console\Command\Config\ExportCommand->__construct(Object(Drupal\Core\Config\ConfigManager))

#1 /var/www/sites/d8/thestyx.org.nz/drupal/vendor/symfony/dependency-injection/ContainerBuilder.php(936): ReflectionClass->newInstanceArgs(Array)

#2 /var/www/sites/d8/thestyx.org.nz/drupal/vendor/symfony/dependency-injection/ContainerBuilder.php(476): Symfony\Component\DependencyInjection\ContainerBuilder->createService(Object(Symfony\Component\DependencyInjection\Definition), 'console.config_...')

#3 /var/www/sites/d8/thestyx.org.nz/drupal/vendor/drupal/console/src/Application.php(170): Symfony\Component\DependencyInjection\ContainerBuilder->get('console.config_...')

#4 /var/www/sites/d8/thestyx.org.nz/drupal/vendor/drupal/console/src/Application.php(41): Drupal\Console\Application->registerCommands()

#5 /var/www/sites/d8/thestyx.org.nz/drupal/vendor/symfony/console/Application.php(123): Drupal\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))

#6 /var/www/sites/d8/thestyx.org.nz/drupal/vendor/drupal/console/bin/drupal.php(68): Symfony\Component\Console\Application->run()

#7 phar:///usr/local/bin/drupal/src/Utils/Launcher.php(30): include_once('/var/www/sites/...')

#8 phar:///usr/local/bin/drupal/bin/drupal.php(52): Drupal\Console\Launcher\Utils\Launcher->launch('/var/www/sites/...')

#9 phar:///usr/local/bin/drupal/bin/drupal(3): require('phar:///usr/loc...')

#10 /usr/local/bin/drupal(10): require('phar:///usr/loc...')

#11 {main}
TypeError: Argument 2 passed to Drupal\Console\Command\Config\ExportCommand::__construct() must implement interface Drupal\Core\Config\StorageInterface, none given in Drupal\Console\Command\Config\ExportCommand->__construct() (line 43 of /var/www/sites/d8/thestyx.org.nz/drupal/vendor/drupal/console/src/Command/Config/ExportCommand.php).`

**Comment by mattwebdev** [comment]
im having this issue as well, im on a per-site installation of drupal console. running self-update returns "command not found" - Drupal Console (1.0.0-rc17)

**Comment by jmolivas** [comment]
@mattwebdev `drupal self-updare` must be run outside of the drupal root.

**Comment by j3ll3nl** [comment]
When i run self-update outside of the drupal root at the "Whereis drupal" location is says:
Checking for updates from version: "1.0.0-rc16-2-g56546c5"
Updated from version "1.0.0-rc16-2-g56546c5" to version "1.0.0-rc17".

But then it stays at the same version.

**Comment by dgpalmer** [comment]
I am getting the same thing @j3ll3nl

**Comment by jmolivas** [comment]
Try updating to latest DrupalConsole, executing from the site root directory
```
composer update drupal/console --with-dependencies
```

Also try updating Launcher,  executing from the outside of site root directory:
```
drupal self-update
```

And finally rebuild cache executing from your drupal site:
```
drupal cr all
```

**Comment by jmolivas** [comment]
@j3ll3nl and @dgpalmer hash was removed and will be fixed on next release RC18.

<img width="772" alt="drupal-self-update" src="https://cloud.githubusercontent.com/assets/366275/25567507/121b7890-2da4-11e7-9619-74f0efbc87da.png">

Also on RC18 you will be able to execute self-update from the site, it means no need to move outside of drupal root directory to execute the `self-update` command.

<img width="925" alt="drupal-self-update-2" src="https://cloud.githubusercontent.com/assets/366275/25567514/23a97620-2da4-11e7-8af5-2031768ea9cc.png">

**Comment by wizonesolutions** [comment]
@jmolivas Did all this, but the launcher won't stay updated (ran from outside of the site root), and it still fails to run in the Drupal directory.

**Comment by wizonesolutions** [comment]
Actually — cache clear did work.

**Comment by jgunawan** [comment]
Do the: drupal cr all

**Comment by jmolivas** [comment]
Closing this one. Feel free to comment if still happening after updating to the latest version.

**Comment by GhostInTheMachines** [comment]
Tried these directions from above:
Try updating to latest DrupalConsole, executing from the site root directory

composer update drupal/console --with-dependencies
If using the Launcher, try updating it by executing from outside of site root directory:

drupal self-update
And finally rebuild cache executing from your drupal site:

drupal cr all

My result was that I ran out of memory but when I go to the line of code that the error suggests I do not see a variable that I can increment.
Error thrown after running drupal cr all was:
Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 88 bytes) in /Users/kimbled/Sites/devdesktop/tsbvi-dev/docroot/vendor/symfony/dependency-injection/ParameterBag/ParameterBag.php on line 267

**Comment by GhostInTheMachines** [comment]
drupal list also throws the error:
Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 64 bytes) in /Users/kimbled/Sites/devdesktop/tsbvi-dev/docroot/vendor/symfony/dependency-injection/ParameterBag/ParameterBag.php on line 267

**Comment by jmolivas** [comment]
@GhostInTheMachines you need to increase that value on your `php.ini` file.

You can find which `php.ini` file is loaded via the CLI by executing `php --ini`

**Comment by GhostInTheMachines** [comment]
Does drupalconsole use the apache default on a Mac running Sierra or the one that Dev Desktop is using when I am in that docroot?

I ran the php --ini command and it reported the file to be in /etc but I only find example.php.ini when I look in this directory.

**Comment by GhostInTheMachines** [comment]
sorry that was php.ini.default .  I will try to increase the memory by a Meg in this file and see if it makes a difference.

**Comment by GhostInTheMachines** [comment]
changed the memory_limit to 256M from 128 and now it reports that it tried to allocate 32 bytes instead of 64.  Numbers don't seem accurate but it sounds like I am on the right track with the correct file being php.ini.default.
I'll just up it to 512M and see if that gets it.

**Comment by jmolivas** [comment]
can you try this ` php -i | grep memory_limit` and check the new value is applying ?

**Comment by GhostInTheMachines** [comment]
Weird, now the error states that it tried to allocate 75 bytes.  Looks like it is random


Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 32 bytes) in /Users/kimbled/Sites/devdesktop/tsbvi-dev/docroot/vendor/symfony/dependency-injection/ParameterBag/ParameterBag.php on line 261
kilroy:docroot kimbled$ drupal list

Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 75 bytes) in /Users/kimbled/Sites/devdesktop/tsbvi-dev/docroot/vendor/symfony/dependency-injection/ParameterBag/ParameterBag.php on line 267

**Comment by GhostInTheMachines** [comment]
Sure thing: looks like I am in the wrong file

kilroy:docroot kimbled$ php -i | grep memory_limit
memory_limit => 128M => 128M

**Comment by jmolivas** [comment]
Try renaming `php.ini.default` as `php.ini`.

**Comment by GhostInTheMachines** [comment]
BINGO!  It worked.

Thank you
