### ISSUE TITLE
Sudden error: Call to member function

### ISSUE THREAD

**Issue by Christofferberg** [hechoendrupal/drupal-console#3284]
I suddenly can't use any drupal console commands, and I don't understand what the issue is.
Work's perfectly on my other installations.  

I'm on a Docksal Mac environment. 

Error: Call to a member function getId() on null in
/var/www/docroot/core/lib/Drupal/Core/Cache/Context/SessionCacheContext.php on line 25 #0 /var/www/docroot/core/lib/Drupal/Core/Cache/Context/CacheContextsManager.php(118): Drupal\Core\Cache\Context\SessionCacheContext->getContext(NULL)

Drupal core 8.3.1
Drupal Console version 1.0.0-rc16

Any ideas? :)

* edit

I found that the issue happened after I added a webform to my frontpage via a paragraph type. But why?

**Comment by jmolivas** [comment]
@Christofferberg can you try update to latest RC-17 and after that execute `drupal cr` command to clear DrupalConsole cache.

**Comment by jmolivas** [comment]
@Christofferberg Do you have any special configuration for the modules?

**Comment by Christofferberg** [comment]
@jmolivas I have no special configuration for any modules. It is more or less a clean install. 

I've created a paragraph type, with a webform field. I've then created a content type, with a paragraph field that references that paragraph type. As soon as I add that paragraph, with the webform to my page, I can't use any drupal-console commands. 

![screen shot 2017-05-01 at 10 20 01](https://cloud.githubusercontent.com/assets/10507071/25575439/c3ba97c6-2e57-11e7-99c5-03a6da307f65.png)

![screen shot 2017-05-01 at 10 26 02](https://cloud.githubusercontent.com/assets/10507071/25575557/cf25a79e-2e58-11e7-88eb-231fc2f5d57c.png)

"fd" is an alias for "fin drupal" used to run drupal-console commands through docksal. 

![screen shot 2017-05-01 at 10 27 05](https://cloud.githubusercontent.com/assets/10507071/25575563/e49c4c7c-2e58-11e7-938c-860183c1453c.png)

SessionsCacheContext.php, which it seems to be complaining about.

**Comment by LOBsTerr** [comment]
@Christofferberg do you still experience the issue?

**Comment by Christofferberg** [comment]
It was resolved, if I remember correctly. 

I believe I ran updates on my whole Docksal environment, updated images, updated drupal console in the CLI image and such.

**Comment by jmolivas** [comment]
Closing this one. Feel free to re-open if still happening after updating to the latest version.
