### ISSUE TITLE
generate:entity:content - PHP Fatal error

### ISSUE THREAD

**Issue by extravio** [hechoendrupal/drupal-console#3294]
The drupal generate:entity:content command throws the following error

PHP Fatal error:  Call to a member function getPath() on null in [...]/vendor/drupal/console/src/Generator/EntityContentGenerator.php on line 84

Drupal 8.3.1 
Drupal Console version 1.0.0-rc18

**Comment by jmolivas** [comment]
@extravio I just ran it and it works:

![drupal-generate-entity-content](https://cloud.githubusercontent.com/assets/366275/25648181/0bf42ab2-2f7e-11e7-8ded-729ec6fd615c.png)

Are you passing arguments/parameters when executing the command?

**Comment by extravio** [comment]
That's another issue: I have to specify --module, otherwise I get an error 
[ERROR] Value "example" is invalid
![dc_error1](https://cloud.githubusercontent.com/assets/1171158/25648306/98908592-301e-11e7-84c0-b392c09bdeba.png)
here's the screenshot of the error
![dc_error2](https://cloud.githubusercontent.com/assets/1171158/25648316/ac029e76-301e-11e7-8448-20b1a269444e.png)
I tried on both an existing project and a fresh install

**Comment by jmolivas** [comment]
Module should be generated before using it.

That is why `baba` is not valid.

When passing `--module example` is this `example` module a valid module?

We need to validate if the passed module is not valid and trigger an exception instead of continue execution and ask more questions.

**Comment by extravio** [comment]
Thanks! I thought the module would be created automatically as part of the entity generation.
All working now.

**Comment by rpsu** [comment]
Would it be easy to alter the message (sent with the exception) to be more helpful in terms of understainding why "Value 'xxx' is invalid"?

**Comment by LOBsTerr** [comment]
@rpsu we have already improved it some versions ago.
