### ISSUE TITLE
[event:debug] Display event subscriber priority in output of event:debug

### ISSUE THREAD

**Issue by jasonawant** [hechoendrupal/drupal-console#3297]
### Problem/Motivation
It would be helpful to see the priority of all registered event subscribers when adding your own custom subscriber and setting its priority.

### Solution
TBD

**Comment by jmolivas** [comment]
PR #3298 add this feature. This is the output

<img width="1414" alt="drupal-event-debug-1" src="https://cloud.githubusercontent.com/assets/366275/25777558/8d81a4c8-3295-11e7-9d9b-35d9890d19c8.png">

<img width="1414" alt="drupal-event-debug-2" src="https://cloud.githubusercontent.com/assets/366275/25777559/8d86b454-3295-11e7-9127-8b56c5e21e13.png">

**Comment by jmolivas** [comment]
@jasonawant PR #3298 add this feature. This is the output

<img width="1414" alt="drupal-event-debug-1" src="https://cloud.githubusercontent.com/assets/366275/25777558/8d81a4c8-3295-11e7-9d9b-35d9890d19c8.png">

<img width="1414" alt="drupal-event-debug-2" src="https://cloud.githubusercontent.com/assets/366275/25777559/8d86b454-3295-11e7-9127-8b56c5e21e13.png">

**Comment by jasonawant** [comment]
Nice, thanks!
