### ISSUE TITLE
Composer install failed

### ISSUE THREAD

**Issue by thom8** [hechoendrupal/drupal-console#3303]
```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package drupal/console ~1.0 is satisfiable by drupal/console[1.0.0-alpha1, 1.0.0-alpha2, 1.0.0-beta1, 1.0.0-beta2, 1.0.0-beta3, 1.0.0-beta4, 1.0.0-beta5, 1.0.0-rc1, 1.0.0-rc10, 1.0.0-rc11, 1.0.0-rc12, 1.0.0-rc13, 1.0.0-rc14, 1.0.0-rc15, 1.0.0-rc16, 1.0.0-rc17, 1.0.0-rc18, 1.0.0-rc19, 1.0.0-rc2, 1.0.0-rc3, 1.0.0-rc4, 1.0.0-rc5, 1.0.0-rc6, 1.0.0-rc7, 1.0.0-rc8, 1.0.0-rc9] but these conflict with your requirements or minimum-stability.

```

This has come up a lot recently as there is no stable release and the [installation instructions](https://docs.drupalconsole.com/en/getting/composer.html) advise using --

```
composer require drupal/console:~1.0 \
--prefer-dist \
--optimize-autoloader
```

Can I suggest either making a note about setting the `minimum-stability` otherwise use

```
composer require drupal/console:~1.0@dev \
--prefer-dist \
--optimize-autoloader
```

However, this currently resolves the latest version as `1.0.0.0-beta5` as it seems that composer `RC` tags are case sensitive -- https://getcomposer.org/doc/04-schema.md#version

If you use `RC` on the next release you could then use `composer require drupal/console:~1.0@RC`

**Comment by hejiann** [comment]
Same issue here

**Comment by harold20** [comment]
This issue is no longer present using the version 1.9.0
