### ISSUE TITLE
drupal create:nodes [arguments] [options] throws a fatal error while attempting to create nodes

### ISSUE THREAD

**Issue by sangeethg** [hechoendrupal/drupal-console#3307]
drupal create:nodes throws a fatal error.

drupal create:nodes [arguments] [options] throws a fatal error while attempting to create nodes
drupal create:nodes

Trying to create a new node using drupal console and it throws an error.
Recoverable fatal error: Argument 2 passed to Drupal\Console\Core\Style\DrupalStyle::table() must be of the type array, null given, called in /var/www/html/drupal_eight/vendor/drupal/console/src/Command/Create/NodesCommand.php on line 224 and defined in Drupal\Console\Core\Style\DrupalStyle->table() (line 175 of /var/www/html/drupal_eight/vendor/drupal/console-core/src/Style/DrupalStyle.php)

Go to drupal installation folder.
Use drupal create:nodes and provide necessary information as you are requested.

Drupal Console Launcher version 1.0.0-rc19
Drupal Console version 1.0.0-rc19

### Solution
Variable type casting

**Comment by sangeethg** [comment]
I tried this solution and its working for me fine...

$nodes = $this->createNodeData->create(
$contentTypes,
$limit,
$titleWords,
$timeRange,
$language
);
$nodes = (array) $nodes;

**Comment by jmolivas** [comment]
Fixed with #3310
