### ISSUE TITLE
 Call to undefined function Drupal console in phar:///usr/local/bin/drupal/src/Utils/Launcher.php

### ISSUE THREAD

**Issue by geolivero** [hechoendrupal/drupal-console#3312]
Fatal error: Call to undefined function Drupal\Console\Launcher\Utils\pcntl_exec() in phar:///usr/local/bin/drupal/src/Utils/Launcher.php on line 34

Found out today that the command "drupal" doesn't work anymore after Drupal upgrade 8.3.2.
Thank for all your help.

Don't know what else todo. I tried:
- composer update drupal/console --with-dependencies
- drupal self-update
- also tried dowloading drupal/console-launcher but with no success

Output of **composer show | grep drupal/console**
drupal/console                        1.0.0-rc19         The Drupal CLI. ...
drupal/console-core                   1.0.0-rc19         Drupal Console Core
drupal/console-en                     1.0.0-rc19         Drupal Console E...
drupal/console-extend-plugin          0.6.0              Drupal Console E...
drupal/console-launcher               1.0.0-rc19         Drupal Console l...

composer.json
{
    "name": "drupal/drupal",
    "description": "Drupal is an open source content management platform powering millions of websites and applications.",
    "type": "project",
    "license": "GPL-2.0+",
    "require": {
        "composer/installers": "^1.0.24",
        "wikimedia/composer-merge-plugin": "~1.3",
        "stecman/symfony-console-completion": "^0.7.0",
        "symfony/dom-crawler": "2.8.11",
        "drupal/core": "^8.3.2",
        "drush/drush": "~8.0",
        "webmozart/path-util": "^2.3",
        "drupal/console-launcher": "^1.0@RC",
        "drupal/console": "~1.0"
    },
    "replace": {
        "drupal/core": "~8.3"
    },
    "conflict": {
        "drupal/drupal": "*"
    },
    "minimum-stability": "dev",
    "prefer-stable": true,
    "config": {
        "preferred-install": "dist",
        "autoloader-suffix": "Drupal8"
    },
    "extra": {
        "_readme": [
            "By default Drupal loads the autoloader from ./vendor/autoload.php.",
            "To change the autoloader you can edit ./autoload.php.",
            "This file specifies the packages.drupal.org repository.",
            "You can read more about this composer repository at:",
            "https://www.drupal.org/node/2718229"
        ],
        "merge-plugin": {
            "include": [
                "core/composer.json"
            ],
            "recurse": false,
            "replace": false,
            "merge-extra": false
        },
        "installer-paths": {
            "core": ["type:drupal-core"],
            "modules/contrib/{$name}": ["type:drupal-module"],
            "profiles/contrib/{$name}": ["type:drupal-profile"],
            "themes/contrib/{$name}": ["type:drupal-theme"],
            "drush/contrib/{$name}": ["type:drupal-drush"],
            "modules/custom/{$name}": ["type:drupal-custom-module"],
            "themes/custom/{$name}": ["type:drupal-custom-theme"]
        }
    },
    "autoload": {
        "psr-4": {
            "Drupal\\Core\\Composer\\": "core/lib/Drupal/Core/Composer"
        }
    },
    "scripts": {
        "pre-autoload-dump": "Drupal\\Core\\Composer\\Composer::preAutoloadDump",
        "post-autoload-dump": [
          "Drupal\\Core\\Composer\\Composer::ensureHtaccess"
        ],
        "post-package-install": "Drupal\\Core\\Composer\\Composer::vendorTestCodeCleanup",
        "post-package-update": "Drupal\\Core\\Composer\\Composer::vendorTestCodeCleanup"
    },
    "repositories": [
        {
            "type": "composer",
            "url": "https://packages.drupal.org/8"
        }
    ]
}

**Comment by nvaken** [comment]
Hi @geolivero, did you check out the following issue? Probably the same issue.

https://github.com/hechoendrupal/drupal-console/issues/3308

**Comment by geolivero** [comment]
Thanks I will try it later

**Comment by nvaken** [comment]
Seems like this one should be closed now. This has been continued in above stated issue.

**Comment by jmolivas** [comment]
@geolivero Can you try updating to latest RC20 and validate is this still happening.

Make sure you update Launcher and Site installation.

**Comment by jmolivas** [comment]
Closing this one. Feel free to re-open if still happening after updating to the latest version.
