### ISSUE TITLE
[console] launcher says 'Could not find DrupalConsole in the current site'

### ISSUE THREAD

**Issue by joachim-n** [hechoendrupal/drupal-console#3314]
I have just downloaded Drupal Console Launcher version 1.0.0-rc19. 

When I run it in my drupal site root, it says:

`
Could not find DrupalConsole in the current site (/Users/joachim/Sites/8-drupal).
Please execute: composer require drupal/console:~1.0
`

**Comment by nvaken** [comment]
Only installing the launcher is not enough, the launcher's functionality is only to make sure you can execute Drupal Console globally through a simple command. Please make sure you have executed the `composer require drupal/console:~1.0` as noted in the error.

**Comment by joachim-n** [comment]
The instructions here don't mention any of that: https://docs.drupalconsole.com/en/getting/launcher.html

Or at least, they don't explain what the launcher actually *is*. There's no mention that it's not the whole of Drupal Console.

**Comment by carsonblack** [comment]
I have created a new issue in the drupal-console-book repo to fix the wording of the launcher page to be more explanatory: https://github.com/hechoendrupal/drupal-console-book/issues/263

**Comment by nvaken** [comment]
Hi @joachim-n, you're right, that specific page does not really explain anything. That's something we'll have to tackle in the issue @carsonblack created above. 

For the time being, you might want to check out the main [chapter page](https://docs.drupalconsole.com/en/getting/project.html) of the launcher page, it explains why you'd need the launcher.

**Comment by joachim-n** [comment]
Thanks! :)
