### ISSUE TITLE
Error Command line to generate module

### ISSUE THREAD

**Issue by kamalkech** [hechoendrupal/drupal-console#3315]
### Version Drupal console
Drupal Console version 0.11.3

### Version Drupal
Drupal 8

### Version
drupal generate:module

### Error message 
  [Symfony\Component\Console\Exception\CommandNotFoundException]
  There are no commands defined in the "generate" namespace.

Any Idea ??

**Comment by jmolivas** [comment]
@kamalkech 
- Are you executing from a Drupal site directory?
- Is Drupal installed ? 
- Could you see the `generate:module` command when listing commands using `drupal list`?

**Comment by clucas1976** [comment]
I cannot see the generate:module commands when I do drupal list it is short menu and says for full menu install drupal. I have drupal installed and am running everything in the site route, using mamp for a local host installation. I have never used drupal before and want to build a custom multi page form

**Comment by jmolivas** [comment]
@kamalkech you should update DrupalConsole you ins taller version is really outdated.

**Comment by jmolivas** [comment]
@clucas1976 which version of DrupalConsole do you have installed?

**Comment by clucas1976** [comment]
I downloaded it from the link in the documentation I will check when I get
home thank you for the fast response 😊

**Comment by clucas1976** [comment]
Composer version 1.4.2

Drupal Console (1.0.0-rc20)

**Comment by clucas1976** [comment]
I followed the following steps

  1. create folder for new site

  2. Install Drupal in this folder

  3. navigate to site folder in terminal window

   1. Run $ curl https://drupalconsole.com/installer -L -o drupal.phar
   2. Run $ sudo mv drupal.phar /usr/local/bin/drupal
   3. Run $ chmod +x /usr/local/bin/drupal
   4. Run $ sudo chown -R $USER $HOME/.composer
   5. Run $ composer require drupal/console:~1.0
   6. Run $ drupal init --override

**Comment by clucas1976** [comment]
using macOS Sierra v 10.12.5

**Comment by jmolivas** [comment]
@clucas1976 can you follow the updated  instructions https://docs.drupalconsole.com/en/getting/project.html

**Comment by clucas1976** [comment]
I really cannot follow the guide as nothing works and i end up in a mess
with the same issues, is there an idiots guide??

**Comment by jmolivas** [comment]
@clucas1976 this is the installation instruction https://docs.drupalconsole.com/en/getting/composer.html

Existing proyect
```
cd /path/to/drupal8.dev

composer require drupal/console:~1.0 \
--prefer-dist \
--optimize-autoloader
```

Starting a new project
```
composer create-project \
drupal-composer/drupal-project:8.x-dev \
drupal8.dev \
--prefer-dist \
--no-progress \
--no-interaction
```

**Comment by jmolivas** [comment]
@clucas1976 is this issue still happening?

**Comment by clucas1976** [comment]
Yes unfortunately, I followed your instructions but cannot get it to work
at all, very frustrating.

**Comment by jmolivas** [comment]
@clucas1976 not sure why is not working for you, did you see my comment https://github.com/hechoendrupal/drupal-console/issues/3315#issuecomment-304686657

**Comment by LOBsTerr** [comment]
@clucas1976 can you check this issue with the latest version? It is still the case for you?

**Comment by jmolivas** [comment]
This is a really old issue since no reply back. I will have it closed.

Closing this one. Feel free to re-open if still happening after updating to the latest version.
