### ISSUE TITLE
update:execute - Be more verbose

### ISSUE THREAD

**Issue by nvaken** [hechoendrupal/drupal-console#3316]
Currently, `update:execute` does not show any information about the updates being run but their update number and module name. Even in there is a `drupal_set_message()` in the update hook, it will not display the message.

I think `update:execute` should show:
* Comments above function name
* Feedback from the update (drupal_set_message())

**Comment by jmolivas** [comment]
Fixed with https://github.com/hechoendrupal/drupal-console/pull/3335
