### ISSUE TITLE
[ console ] Cannot run any Console command after update to 1.0.0-rc20

### ISSUE THREAD

**Issue by ergonlogic** [hechoendrupal/drupal-console#3326]
### Problem/Motivation
After upgrading to the latest release of Console, I can no longer run _any_ Console commands.

### How to reproduce

**Details:**
- Drupal version: 8.3.1
- Console version: 1.0.0-rc20
- Console Launcher version: 1.0.0-rc20
- Steps to reproduce:

Just try to run any Console command, whether in a site directory, or not:

```
$ vendor/bin/drupal -V

  [Symfony\Component\Debug\Exception\FatalThrowableError]
  Type error: Argument 3 passed to Drupal\Console\Command\Config\ExportSingleCommand::__construct() must be an instance of Drupal\Console\Extension\Manager  
  , none given
```

### Solution

As far as I can tell, this is related to #3306. Reverting the associated commit allows Console to run again. Obviously that code was introduced to resolve an issue (#3305), but perhaps there's some other component/code that also needs to be updated to make this work?

As an aside, I haven't dug into Console's bootstrapping code, but it seems odd that such an error in one command would break the entirety of Drupal Console. While throwing a fatal error is appropriate when failing to instantiate a specific command class, perhaps there's a more graceful way to handle such isolated issues. That is, it seems unnecessary to instantiate objects for every _other_ command when running any given command. That said, it looks like that may be an issue with the Symfony Console component, rather than Drupal Console.

**Comment by psnc** [comment]
The same probleme
Drupal version: 8.3.2
Console version: 1.0.0-rc20
Console Launcher version: 1.0.0-rc20

**Comment by psnc** [comment]
Here it work

` Mon 29 Mai - 19:18  /var/www/html/local/demo/drupal/drupal-8/drupal/test/module/drupalsite 
 @patrick  sudo  composer update
[sudo] password for patrick: 
Do not run Composer as root/super user! See https://getcomposer.org/root for details
> DrupalProject\composer\ScriptHandler::checkComposerVersion
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 0 installs, 6 updates, 0 removals
  - Updating drupal/console-en (1.0.0-rc19 => 1.0.0-rc20) Downloading: 100%         
  - Updating drupal/console-core (1.0.0-rc19 => 1.0.0-rc20) Downloading: 100%         
  - Updating drupal/console (1.0.0-rc19 => 1.0.0-rc20) Downloading: 100%         
  - Updating phpdocumentor/reflection-docblock (2.0.4 => 2.0.5) Downloading: 100%         
  - Updating drupal/entity_reference_revisions (1.2.0 => 1.3.0) Downloading: 100%         
  - Updating sebastian/diff (1.4.2 => 1.4.3) Downloading: 100%         
Writing lock file
Generating autoload files
> DrupalProject\composer\ScriptHandler::createRequiredFiles

 Mon 29 Mai - 19:21  /var/www/html/local/demo/drupal/drupal-8/drupal/test/module/drupalsite 
 @patrick  l
insgesamt 316K
drwxr-xr-x  6 www-data www-data 4,0K Apr  6 15:04 .
drwxr-xr-x  3 www-data www-data 4,0K Dez 10 20:56 ..
-rw-r--r--  1 www-data www-data 2,5K Apr  6 15:04 composer.json
-rw-r--r--  1 www-data www-data 247K Mai 29 19:21 composer.lock
drwxr-xr-x  2 www-data www-data 4,0K Dez 10 20:55 drush
-rw-r--r--  1 www-data www-data  295 Dez 10 20:55 .gitignore
-rw-r--r--  1 www-data www-data  18K Dez 10 20:55 LICENSE
-rw-r--r--  1 www-data www-data  481 Dez 10 20:55 phpunit.xml.dist
-rw-r--r--  1 www-data www-data 5,6K Dez 10 20:55 README.md
drwxr-xr-x  3 www-data www-data 4,0K Dez 10 20:55 scripts
-rw-r--r--  1 www-data www-data 1,3K Dez 10 20:55 .travis.yml
drwxr-xr-x 43 www-data www-data 4,0K Mai 29 19:21 vendor
drwxr-xr-x  7 www-data www-data 4,0K Mai  4 21:57 web
                                                                                                                                                                                                                                                                                               
 ✘  Mon 29 Mai - 19:22  /var/www/html/local/demo/drupal/drupal-8/drupal/test/module/drupalsite 
 @patrick  ll
insgesamt 300K
-rw-r--r--  1 www-data www-data 2,5K Apr  6 15:04 composer.json
-rw-r--r--  1 www-data www-data 247K Mai 29 19:21 composer.lock
drwxr-xr-x  2 www-data www-data 4,0K Dez 10 20:55 drush
-rw-r--r--  1 www-data www-data  18K Dez 10 20:55 LICENSE
-rw-r--r--  1 www-data www-data  481 Dez 10 20:55 phpunit.xml.dist
-rw-r--r--  1 www-data www-data 5,6K Dez 10 20:55 README.md
drwxr-xr-x  3 www-data www-data 4,0K Dez 10 20:55 scripts
drwxr-xr-x 43 www-data www-data 4,0K Mai 29 19:21 vendor
drwxr-xr-x  7 www-data www-data 4,0K Mai  4 21:57 web
                                                                                                                                                                   
 Mon 29 Mai - 19:22  /var/www/html/local/demo/drupal/drupal-8/drupal/test/module/drupalsite 
 @patrick  sudo drupal _cr_
 Select cache. [all]:
 > all
__
 Rebuilding cache(s), wait a moment please.

                                                                                                                        
 [OK] Done clearing cache(s).                                                                                           
                                                                                                 __                       

`

**Comment by jmolivas** [comment]
@ergonlogic 

Exactly this is how he symfony/console component works

> That is, it seems unnecessary to instantiate objects for every other command when running any given command. That said, it looks like that may be an issue with the Symfony Console component, rather than Drupal Console.

**Comment by jmolivas** [comment]
@ergonlogic also make sure you execute `drupal cr all` after any update

**Comment by ergonlogic** [comment]
Aha! The Cache rebuild appears to have worked.

**Comment by ergonlogic** [comment]
A couple closing notes:

1. It might be worthwhile to document this in either or both of the install/update docs, or the FAQ/troubleshooting sections.
2. Composer supports a `post-update-cmd` hook that could run the cache-rebuild automaticlly whenever Drupal Console is updated. AFAICT, it'd have to be added manually to the top-level project `composer.json`, but this too could be added to https://docs.drupalconsole.com/en/getting/composer.html

**Comment by jmolivas** [comment]
@ergonlogic That update to the docs could be done at this repo https://github.com/hechoendrupal/drupal-console-book

**Comment by xmacinfo** [comment]
PHP Fatal error:  Call to undefined method Drupal\Console\Core\Utils\DrupalFinder::getVendorDir() in /site/vendor/drupal/console-core/src/Utils/DrupalFinder.php on line 24

Composer installs :  
  - Updating drupal/console-en (1.0.0-rc16 => 1.0.0-rc20): Downloading (100%)    
  - Updating drupal/console-core (1.0.0-rc16 => 1.0.0-rc20): Downloading (100%)   
  - Updating drupal/console (1.0.0-rc16 => 1.0.0-rc20): Downloading (100%)

But it will never run.

Deleting the cache does not help on my install.

**Comment by jmolivas** [comment]
@xmacinfo which command are you executing? if using the launcher make sure you update it as well executing `drupal self-update`
