### ISSUE TITLE
Display messages during update execute

### ISSUE THREAD

**Issue by albertski** [hechoendrupal/drupal-console#3327]
### Display messages during update execute

The issue title should comply with the following structure:

[ *update:execute* ] Add ability to display messages during update

### Problem/Motivation
Some modules return messages in hook_update_N. For example:

```
/**
 * Adds new functionality to custom field.
 */
function mymodule_update_8003() {
  .....
  .....
  // Performs custom operation.
  .....
  .....

  return t('Important message to display to user.');
}
```

If you run updates via update.php, these messages get displayed. If you run via Drupal Console, these messages don't get displayed.  It would be nice to add this functionality.

**Comment by jmolivas** [comment]
Fixed with https://github.com/hechoendrupal/drupal-console/pull/3335
