### ISSUE TITLE
[console] General TypeErrors when running drupal console

### ISSUE THREAD

**Issue by TiMESPLiNTER** [hechoendrupal/drupal-console#3330]
### Problem/Motivation
The problem is that I get generel TypeErrors once I try to execute the drupal console.

### How to reproduce
1. Run `composer require drupal/console ~1.0` in drupal project root
2. Run `vendor/bin/drupal help`

You get an error:

```
TypeError: Argument 3 passed to Drupal\Console\Command\Module\InstallDependencyCommand::__construct() must be an instance of Drupal\Core\ProxyClass\Extension\ModuleInstaller, instance of Drupal\disable_modules\ProxyClass\Extension\ModuleInstallerDisableModules given in /.../vendor/drupal/console/src/Command/Module/InstallDependencyCommand.php on line 62 #0 [internal function]: Drupal\Console\Command\Module\InstallDependencyCommand->__construct(Object(Drupal\Console\Utils\Site), Object(Drupal\Console\Utils\Validator), Object(Drupal\disable_modules\ProxyClass\Extension\ModuleInstallerDisableModules), Object(Drupal\Console\Core\Utils\ChainQueue))
```

**Details to include:**
- Drupal version: 8.3.x
- Console version: 1.0.0-rc20
- Console Launcher version: 1.0.0-rc20
- PHP version: 7.1.0

### Solution
No solution yet.

**Comment by jmolivas** [comment]
@TiMESPLiNTER try rebuilding caches executing `drupal cr all`

**Comment by jmolivas** [comment]
@TiMESPLiNTER Closing this one. Feel free to comment if still happening after trying the suggested solution?
