### ISSUE TITLE
[DOCS] Make the contributing workflow part of the docs.

### ISSUE THREAD

**Issue by clemens-tolboom** [hechoendrupal/drupal-console#3331]
### Problem/Motivation

I cannot make Drupal console run. I want to use the none existing stand alone __git clone__ variant.

**Details to include:**

I want to be able to contribute / debug the console so need it's code. I don't want the phar install and neither the https://docs.drupalconsole.com/en/getting/composer.html as that would mean I have to change every Drupal 8 project

I ran into #3283 which cannot find the Drupal autoload.php file obviously.

https://github.com/hechoendrupal/drupal-console/blob/master/README.md#getting-the-project-to-contribute links to an __old gist__ https://gist.github.com/jmolivas/97bbd07f328217be3564a434c5bd2618

### How to reproduce

- `git clone` the repo in ie ~/lib and add a symlink into ~/bin to the drupal script.
- cd into drupal root
- run `drupal`

### Solution

I expected the documentation to contain a section here https://docs.drupalconsole.com/en/getting/project.html explaining how to __globally install__ the __git clone__ so my Drupal 8 installs kept clean.

**Comment by jmolivas** [comment]
@clemens-tolboom There is no global install for DrupalConsole you must install it per site.

**Comment by jmolivas** [comment]
And yes I do agree the docs need to reflect the contributing instructions.

**Comment by clemens-tolboom** [comment]
From https://github.com/hechoendrupal/drupal-console/blob/master/README.md

> We highly recommend you to install the global executable, but if is not installed

I'll retry :)

**Comment by jmolivas** [comment]
The global executable is only a Launcher
https://docs.drupalconsole.com/en/getting/launcher.html

More info about the Launcher and per-site installation
https://docs.drupalconsole.com/en/getting/project.html

**Comment by jmolivas** [comment]
@clemens-tolboom  Contribute instructions added to the docs https://docs.drupalconsole.com/en/contributing/running-the-project.html and readme updated https://github.com/hechoendrupal/drupal-console#contribute-to-drupal-console

**Comment by jmolivas** [comment]
Closing this one. Feel free to re-open if still need some clarification.
