### ISSUE TITLE
Error after update to rc20 from rc19

### ISSUE THREAD

**Issue by rodrigoaguilera** [hechoendrupal/drupal-console#3332]
[ console ] Short description

### Problem/Motivation
I can't run drupal console after upgrading to rc20

**Details to include:**
I get the following error no matter what command or just "drupal"
```
ArgumentCountError: Too few arguments to function Drupal\Console\Command\Config\ExportSingleCommand::__construct(), 2 passed and exactly 3 expected in /var/www/html/vendor/drupal/console/src/Command/Config/ExportSingleCommand.php on line 52 #0 [internal function]: Drupal\Console\Command\Config\ExportSingleCommand->__construct(Object(Drupal\Core\Entity\EntityTypeManager), Object(Drupal\Core\Config\CachedStorage))
#1 /var/www/html/vendor/symfony/dependency-injection/ContainerBuilder.php(936): ReflectionClass->newInstanceArgs(Array)
#2 /var/www/html/vendor/symfony/dependency-injection/ContainerBuilder.php(476): Symfony\Component\DependencyInjection\ContainerBuilder->createService(Object(Symfony\Component\DependencyInjection\Definition), 'console.config_...')
#3 /var/www/html/vendor/drupal/console/src/Application.php(192): Symfony\Component\DependencyInjection\ContainerBuilder->get('console.config_...')
#4 /var/www/html/vendor/drupal/console/src/Application.php(63): Drupal\Console\Application->registerCommands()
#5 /var/www/html/vendor/symfony/console/Application.php(127): Drupal\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /var/www/html/vendor/drupal/console/bin/drupal.php(71): Symfony\Component\Console\Application->run()
#7 /var/www/html/vendor/drupal/console/bin/drupal(4): require('/var/www/html/v...')
#8 {main}
```

I am using the drupal-project structure
https://github.com/drupal-composer/drupal-project

**Details to include:**
- Drupal version: 8.3.2
- PHP 7.1.4

### Solution
No idea

**Comment by jmolivas** [comment]
@rodrigoaguilera try rebuilding caches `drupal cr all`

**Comment by rodrigoaguilera** [comment]
@jmolivas That fixed the issue but I really don't this to happen to other people. 
Can the cache be invalidated by drupal console version?

**Comment by jmolivas** [comment]
@rodrigoaguilera We can try to enable/disable cache generation via the `console/config.yml` file and make cache generation as command. This command could be included as part of your build process before deploying site.

**Comment by rodrigoaguilera** [comment]
Muy case is different. After running componer udpdate drupal console stopped working without a many clues. I wonder if the cache can be tagged/namespaced depending on the version so in this example a cache generated by rc19 will never be used by rc20 and drupal cr all will also delete caches from old versions. I think this can save a lot of headaches.

**Comment by jmolivas** [comment]
Make sense either tagging ver version or just regenerated once DC is updated.

**Comment by jmolivas** [comment]
Latest changes to the composer plugin removes the cache https://github.com/hechoendrupal/drupal-console-extend-plugin/blob/master/src/Extender.php#L131
