### ISSUE TITLE
PHP Error : DrupalFinder::getVendorDir() -

### ISSUE THREAD

**Issue by justinlevi** [hechoendrupal/drupal-console#3333]
### Issue title

PHP Fatal error:  Uncaught Error: Call to undefined method Drupal\Console\Core\Utils\DrupalFinder::getVendorDir() in /var/www/docroot/vendor/drupal/console-core/src/Utils/DrupalFinder.php:24

[ *ISSUE-GROUP* ] Short description : Same issue as here: https://github.com/hechoendrupal/drupal-console/issues/3302#issuecomment-306553159

Reopening

The *ISSUE-GROUP* should be one of:

* `command:name` - all commands
* `console`

### Problem/Motivation
Can't get console to run properly with rc20

### How to reproduce
Stock drupal install using latest version of Dock sail

**Comment by jmolivas** [comment]
@justinlevi Closing this one based on you comment at https://github.com/hechoendrupal/drupal-console/issues/3302#issuecomment-306592578
