### ISSUE TITLE
TypeError: Argument 2 passed to Drupal\Console\Bootstrap\Drupal::__construct() must be an instance of Drupal\Console\Core\Utils\DrupalFinder, string given

### ISSUE THREAD

**Issue by nvaken** [hechoendrupal/drupal-console#3340]
A colleague receives this error after a `site:install`. Using RC21 for both launcher as well as the core.

`TypeError: Argument 2 passed to Drupal\Console\Bootstrap\Drupal::__construct() must be an instance of Drupal\Console\Core\Utils\DrupalFinder, string given, called .../vendor/drupal/console/src/Command/Site/InstallCommand.php on line 445 in .../vendor/drupal/console/src/Bootstrap/Drupal.php on line 30 #0 .../vendor/drupal/console/src/Command/Site/InstallCommand.php(445): Drupal\Console\Bootstrap\Drupal->__construct(Object(Composer\Autoload\ClassLoader), '.../', '.../')`

**Comment by flatline-studios** [comment]
Please try from your drupal root directory:

`composer require webflo/drupal-finder:^0.3.0`

And then:

`drupal cr all`

**Comment by jmolivas** [comment]
@nvaken wich version of `webflo/drupal-finder` is installed on then site?

You can check by executing `composer show webflo/drupal-finder`

You can check who is requiring the package `webflo/drupal-finder` by executing `composer why webflo/drupal-finder`

Since the pakage `webflo/drupal-finder` is not required directly you can update it by executing `composer update drupal/console --with-dependencies`

**Comment by jkuma** [comment]
@jmolivas I'm facing the same issue here. The version 0.3.0 of `webflo/drupal-finder` is shipped with RC21 of `drupal/console`.

Output of `composer show webflo/drupal-finder` is : 
```
name     : webflo/drupal-finder
descrip. : Helper class to locate a Drupal installation from a given path.
keywords : 
versions : * 0.3.0
type     : library
license  : GPL-2.0+
source   : [git] https://github.com/webflo/drupal-finder.git 6ef150707aad1755d91f9b0d2108bcc16661e76b
dist     : [zip] https://api.github.com/repos/webflo/drupal-finder/zipball/6ef150707aad1755d91f9b0d2108bcc16661e76b 6ef150707aad1755d91f9b0d2108bcc16661e76b
names    : webflo/drupal-finder
```

**Comment by jmolivas** [comment]
This is fixed with https://github.com/hechoendrupal/drupal-console/pull/3345

**Comment by jmolivas** [comment]
PR #3345 merged
