### ISSUE TITLE
[ console ] Silent failure when running any command within web root

### ISSUE THREAD

**Issue by tanc** [hechoendrupal/drupal-console#3346]
### Problem/Motivation
When trying to run drupal console, using the drupal helper or directly running the command in venders/bin, the command silently fails, even when using the `--debug` or `--vvv` switches.

Ideally some form of output should help the developer understand why the command is failing.

### How to reproduce

- Drupal version: 8.3.2
- Console version: 1.0.0-rc21 or 1.x-dev
- Console Launcher: 1.0.0-rc21
- Steps to reproduce: `drupal` or `drupal generate:module` or any other command silently fails.

![silent-fail](https://user-images.githubusercontent.com/76320/27074428-633fa638-5027-11e7-9f79-1c28dc84ad32.jpg)

In the screenshot above you can see that `drush sql` works so the settings for the database are being picked up and are correct. Then running `drupal` silently fails.

### Solution
No solution proposed

**Comment by tanc** [comment]
Output of `drupal generate:module --debug` while in a drupal web root:

```
Drupal Console Launcher version 1.0.0-rc21
Launcher path: /usr/local/bin/drupal
```

But no other output or indication of failure reason

**Comment by jmolivas** [comment]
@tanc  can you try rebuilding cache using `drupal cr all`

**Comment by tanc** [comment]
Hmm... the drupal console is currently working. I'll keep my eye on it and if it this happens again I'll report back (after rebuilding caches). If its all fine I'll close this issue in a few days

**Comment by jeanfredrik** [comment]
@jmolivas I have the same problem; silent failure since rc19. I solved it by explicitly requiring 1.0.0-rc18 and removing `.console` in my home dir. Rc18 works great now, but I can’t update beyond that.

```
rm -rf ~/.console
composer require drupal/console:1.0.0-rc18
```

**Comment by geroldkl** [comment]
I am encountering the same issue. Using `drupal about --debug` I get:

`Drupal Console Launcher version 1.0.1
Launcher path: /usr/local/bin/drupal
Drupal Console version 1.0.0`

**Comment by jmolivas** [comment]
This error can be fixed by removing the `.console` directory. We deactivated drupal console cache for now and will re-introduce a new cache strategy in a future release.

**Comment by jmolivas** [comment]
Closing this one. Feel free to re-open if still happening after updating to the latest version.
