### ISSUE TITLE
[site:install] Don't write database config to settings.php on reinstall

### ISSUE THREAD

**Issue by bradjones1** [hechoendrupal/drupal-console#3347]
https://github.com/hechoendrupal/drupal-console/issues/2269 allowed re-install/re-use of database credentials for site installation, however when re-installing, Console writes what is essentially an unnecessary database config to `settings.php`. Removing this duplicate db config is required to restore function of Drupal post-install.

### How to reproduce
Install Drupal with `site:install`, having db credentials already present in `settings.php` sufficient for the installer to connect and do its thing.

After install, a [duplicate] db config is appended to `settings.php`.

**Comment by bradjones1** [comment]
I should also note that in the meantime, if settings.php isn't writeable, the add db connection code just exits without an error, so this is one way to get around this for the time being.

**Comment by jmolivas** [comment]
@bradjones1 updating the settings file is a feature from Drupal not DrupalConsole, do you have the `hash_salt` value added to your settings file?

**Comment by bradjones1** [comment]
@jmolivas Thank you... yes it was the missing `hash_salt` config.
