### ISSUE TITLE
PHP Fatal error:  Class 'Novia713\Maginot\Maginot' not found in /vendor/drupal/console/src/Command/Site/ModeCommand.php on line 85

### ISSUE THREAD

**Issue by nvaken** [hechoendrupal/drupal-console#3348]
Not entirely sure when this is triggered, I'm suspecting this is happening in non-launcher version. (using `vendor/bin/drupal`).

```
PHP Fatal error:  Class 'Novia713\Maginot\Maginot' not found in /vendor/drupal/console/src/Command/Site/ModeCommand.php on line 85
```

**Comment by jmolivas** [comment]
@nvaken Which version of DrupalConsole is showing this error?

**Comment by nvaken** [comment]
I would think rc20, not entirely sure though. I'd have to check. I'll try looping back to this this week.

**Comment by JoeKersey** [comment]
Upgrading to rc23 fixed this for me, now I have a different issue..

**Comment by Narretz** [comment]
I also had this in rc.17 with this cmd: `vendor/drupal/console/bin/drupal config:export --directory=config-backup`

updating to rc.23 works

**Comment by jmolivas** [comment]
Closing this one. Feel free to re-open if still happening after updating to the latest version.
