### ISSUE TITLE
[generate:entity:content] Generate entity with Uppercase generate form id with uppercase

### ISSUE THREAD

**Issue by GoZOo** [hechoendrupal/drupal-console#3364]
### Problem/Motivation
When generating a new entity with an uppercase, form id does not convert uppercase to lowercase which is not ok with coding standards.
Ex: Contact entity =>
```class ContactSettingsForm extends FormBase {
  /**
   * Returns a unique string identifying the form.
   *
   * @return string
   *   The unique string identifying the form.
   */
  public function getFormId() {
    return 'Contact_settings';
  }

  /**
   * Defines the settings form for Contact entities.
   *
   * @param array $form
   *   An associative array containing the structure of the form.
   * @param \Drupal\Core\Form\FormStateInterface $form_state
   *   The current state of the form.
   *
   * @return array
   *   Form definition array.
   */
  public function buildForm(array $form, FormStateInterface $form_state) {
    $form['Contact_settings']['#markup'] = 'Settings form for Contact entities. Manage field settings here.';
    return $form;
  }
```

### How to reproduce

**Details to include:**
- Drupal version 8.3.4.
- Drupal Console version 1.0.0-rc20.
- Steps to reproduce:
  - Generate custom entity `drupal generate:entity:content`
  - Set `Contact` as entity name.
  - Settings form will take a form_id with uppercase.

### Solution
Convert to lowercase form ids during generation.

**Comment by jmolivas** [comment]
Fixed with https://github.com/hechoendrupal/drupal-console/pull/3370

**Comment by LOBsTerr** [comment]
@jmolivas  I think it can be closed

**Comment by jmolivas** [comment]
Closing this one. Feel free to re-open if still happening after updating to the latest version.
