### ISSUE TITLE
Feature Request - Add entity validation 

### ISSUE THREAD

**Issue by tmli3b3rm4n** [hechoendrupal/drupal-console#3366]
### Add entity validation 
Add options to the `generate:entity:config` and `generate:entity:config` or create a `generate:entity:validation`

### Problem/Motivation
I'm having to validate entities and I feel this could be done better via script or far enough ahead that tightening the rest of it up would be quick.   

### Solution
I'm working on this parallel to a module refactor command.  ETA two weeks.  If it's works as visioned I'll make PR.

**Comment by LOBsTerr** [comment]
@tmli3b3rm4n did you come up with some solution? Or can you provide an example on drupal.org?

**Comment by LOBsTerr** [comment]
I'm closing, due to no reply from the author. I think it can be solve by creating custom validation constraints. Feel free to reopen
