### ISSUE TITLE
[views:debug] Fatal error: Call to undefined method getViewDisplayManager()

### ISSUE THREAD

**Issue by mauhg** [hechoendrupal/drupal-console#3392]
### Problem/Motivation
When running `drupal views:debug archive` or with any other `view-id` the console throws the following error:
`PHP Fatal error:  Call to undefined method Drupal\Console\Command\Debug\ViewsCommand::getViewDisplayManager() in /Users/mauhg/anexus/DrupalConsole/src/Command/Debug/ViewsCommand.php on line 221`

- Drupal version 8.3.4
- Console version 1.0.0-rc23
- Console Launcher version 1.0.0-rc23

**Comment by LOBsTerr** [comment]
I have created PR https://github.com/hechoendrupal/drupal-console/pull/3646, which solves the issue

**Comment by jmolivas** [comment]
@mauhg @LOBsTerr PR #3646 merged
