### ISSUE TITLE
Error: Call to a member function id() on null Taxonomy/DeleteTermCommand.php on line 94

### ISSUE THREAD

**Issue by blasvicco** [hechoendrupal/drupal-console#3419]
### Error: Call to a member function id() on null Taxonomy/DeleteTermCommand.php on line 94

[ command:taxonomy:term:delete ] If the vid is not valid then we get the error

### Problem/Motivation
We should handle the exception.

**Details to include:**
- If the vid is not valid we are calling $io->error("Invalid vid: {$item}."); but then we continue with $vocabulary = $vocabularies[$item]; and because $item is not a valid index then
$vocabulary is null and the call $vocabulary->id() throw the exception.

### How to reproduce
Executing the console command:
drupal taxonomy:term:delete ANotValidVid

**Details to include:**
- Drupal version 8.3.5.
- Console version 1.0.0-rc23.
- Console Launcher version 1.0.0-rc21.

### Solution
After the line $io->error("Invalid vid: {$item}."); add continue; to force next item in the for avoiding the wrong call to $vocabulary->id()

**Comment by jmolivas** [comment]
Fixed with https://github.com/hechoendrupal/drupal-console/pull/3426
