### ISSUE TITLE
Error: Call to a member function getPath() on null Theme/PathCommand.php on line 70

### ISSUE THREAD

**Issue by blasvicco** [hechoendrupal/drupal-console#3420]
### Error: Call to a member function getPath() on null Theme/PathCommand.php on line 70

[ command:theme:path ] If $this->extensionManager->getTheme($theme); return null then we get the error

### Problem/Motivation
We should handle the exception.

**Details to include:**
- We are doing $theme = $this->extensionManager->getTheme($theme); but if $theme is null then we get an exception because we are calling to $theme->getPath($fullPath) without check $theme value

### How to reproduce
Executing the console command:
drupal theme:path ModuleNAme

**Details to include:**
- Drupal version 8.3.5.
- Console version 1.0.0-rc23.
- Console Launcher version 1.0.0-rc21.

### Solution
we can check if the $theme var is null before call to $io->info($theme->getPath($fullPath));

**Comment by jmolivas** [comment]
Fixed with https://github.com/hechoendrupal/drupal-console/pull/3425
