### ISSUE TITLE
drupal quick:start + drupal site:new not available

### ISSUE THREAD

**Issue by jepster** [hechoendrupal/drupal-console#3421]
### Problem/Motivation
I have installed Drupal Console via the instruction at https://drupalconsole.com/articles/how-to-install-drupal-console on Linux Mint 18.1 (based on Ubuntu 16.04 Linux). Afterwards I was able to start Drupal Console via the "drupal" command and use the "drupal list" command to see the possible command. But I was not able to use drupal quick:start + drupal site:new. I got the following errors:

> jepster@computer ~/PhpstormProjects/d8-playground $ drupal quick:start
> 
>                                                                                 
>  [ERROR] Command "quick:start", is not a valid command name.                    
>                                                                                 
> 
> jepster@computer ~/PhpstormProjects/d8-playground $ drupal site:new
> 
>                                                                                 
>  [ERROR] Command "site:new", is not a valid command name.    

My Drupal Console version:

> jepster@computer ~/PhpstormProjects/d8-playground $ drupal --version
> Drupal Console Launcher version 1.0.0-rc23

I suppose that I do not need to download Drupal 8 by my own in any directory. The quick:start and site:new commands will do that for me. I am using PHP 7.1.

**Comment by jmolivas** [comment]
@jepster we need to update the docs. In order to have those commands available you need to execute `drupal init` command first.

**Comment by jepster** [comment]
@jmolivas I have been executing `drupal init`.

> jepster@computer ~/PhpstormProjects/d8-playground $ drupal init
> 
>  Select destination to copy configuration:
>   [0] /etc/console/
>   [1] /home/jepster/.console/
>  > 1

But this didn't help.

**Comment by jmolivas** [comment]
@jepster which Launcher version you installed?

**Comment by jepster** [comment]
My Drupal Console version:

> jepster@computer ~/PhpstormProjects/d8-playground $ drupal --version
> Drupal Console Launcher version 1.0.0-rc23

**Comment by jmolivas** [comment]
My bad try `drupal init` again and make sure you answer yes on `Copy chain files examples`

**Comment by jepster** [comment]
If I answer yes on `Copy chain files examples`, I am able to execute other commands. But this isn't intuitive. It should not be necessary to copy any examples, to be able to execute the commands. I consider this a bug.

**Comment by jepster** [comment]
Even with the `Copy chain files examples` option, the command seems not to work entirely properly. After I have executed `drupal quick:start` there come errors:
                                                        
```
 [ERROR] Unable to find the binary drupal to execute.                           
                                                                                

 // exec


                                                                                
 [ERROR] Unable to find the binary drupal to execute.                           
                                                                                

> jepster@computer ~/PhpstormProjects/d8-playground $ ls
> playground
> jepster@computer ~/PhpstormProjects/d8-playground $ cd playground/
> jepster@computer ~/PhpstormProjects/d8-playground/playground $ ls
> composer.json  drush	phpunit.xml.dist  scripts  web
> composer.lock  LICENSE	README.md	  vendor
```
I also cannot generate an entity:

> jepster@computer ~/PhpstormProjects/d8-playground/playground $ drupal generate:entity:bundle
> 
>  // Welcome to the Drupal Content Type generator
>  Enter the module name [minimal]:
>  > playground
> 
>                                                                                 
>  [ERROR] Value "playground" is invalid                                          
>                                                                                 
> 
>  Enter the module name [minimal]:
>  > 
> jepster@computer ~/PhpstormProjects/d8-playground/playground $ ls
> composer.json  config	drush	 phpunit.xml.dist  scripts  web
> composer.lock  console	LICENSE  README.md	   vendor
> jepster@computer ~/PhpstormProjects/d8-playground/playground $ cd web
> jepster@computer ~/PhpstormProjects/d8-playground/playground/web $ drupal geb
> 
>  // Welcome to the Drupal Content Type generator
>  Enter the module name [minimal]:
>  > playground
> 
>                                                                                 
>  [ERROR] Value "playground" is invalid                                          
>                                                                                 
> 
>  Enter the module name [minimal]:
>  > 
> 
>

**Comment by jmolivas** [comment]
Does the `playground` exists?

**Comment by jepster** [comment]
Aha, I need to generate a module first. After I have a module with the name `playground`, it works.

**Comment by jmolivas** [comment]
I think message should mention that instead of just fail with a random error message.

**Comment by jepster** [comment]
Yep, that would help.

**Comment by jmolivas** [comment]
I will check `quick:start` for now you can try `site:new` to download drupal and execute `drupal site:install` within the site directory.

**Comment by jepster** [comment]
Great, Drupal Console is doing a good job! :)

**Comment by jmolivas** [comment]
@jepster I tried `quick:start` on latest release and it works fine, make sure you execute `drupal init --override` to copy new files to your local.

**Comment by jmolivas** [comment]
Based on your recommendation 'site:new' and `quick:start` commands are copied automatically  when `init` is executed. The rest of the chain files are optional and copied if yes is entered when `Copy chain files examples` is asked.

**Comment by jmolivas** [comment]
@jepster Closing this one. Feel free to re-open if happens again
