### ISSUE TITLE
[generate:plugin:field] Missing my_module.schema.yml and missing module annotation

### ISSUE THREAD

**Issue by pslcbs** [hechoendrupal/drupal-console#3432]
- Drupal console 1.0.0-rc23
- Drupal 8.3.4 - English (default) and Spanish
- Command: generate:plugin:field

### Motivation

1. Generates all files but not /my_module/config/schema/my_module.schema.yml

2. Missing annotation  * module = "myModule" in field type class

Is there a reason to that?

### How to reproduce

Use command as normal

**Comment by Greg-Boggs** [comment]
Sounds like the generation for this just needs to be programmed.
