### ISSUE TITLE
Space in `__con struct` in skeleton.php.twig

### ISSUE THREAD

**Issue by clrockwell79** [hechoendrupal/drupal-console#3438]
There is a typo - an extra space - in the template within skeleton.php.twig

`template` 

### Problem/Motivation
Using `drupal generate:plugin:skeleton` results in an extra space in the plugin's `__construct` method, which results in an error.

### How to reproduce
Use `drupal generate:plugin:skeleton`, e.g. `drupal generate:plugin:skeleton --module="commerce_form_customizations" --plugin-id="commerce_checkout_pane" --class="CustomLoginRegisterPane"`

**Details to include:**
- Drupal version 8.3.2
- Console version I'm using 1.0.0-rc19 but it's also in master and 1.0.0-rc24.
- Console Launcher version 1.0.0-rc23.

### Solution
Submitting a pull request

**Comment by jmolivas** [comment]
Fixed with https://github.com/hechoendrupal/drupal-console/pull/3439
