### ISSUE TITLE
I can't run commands on RC24

### ISSUE THREAD

**Issue by betoquiroga** [hechoendrupal/drupal-console#3440]
### Problem
With the last release (RC24) all commands return this error:

[Symfony\Component\Console\Exception\InvalidArgumentException]
  Command name "" is invalid.

In others projects with RC23 all is working 

### How to reproduce
1.-  Execute
composer create-project drupal-composer/drupal-project:8.x-dev project.dev --prefer-dist --no-progress --no-interaction

2. Try any command 

**Details to include:**
- Drupal versión: 8.3.5
- Console version: 1.0.0-rc24
- Console Launcher version: 1.0.0-rc24

**Comment by jmolivas** [comment]
@betoquiroga which OS and PHP version are you using?

**Comment by betoquiroga** [comment]
MacOS Sierra 10.12   & PHP 5.6.30

**Comment by jmolivas** [comment]
@betoquiroga  I tested rc24 on my local and it works fine

![Alt text](https://monosnap.com/file/JMh7XqSdj1uoXw437SqBdZaa9Xyri5.png)

**Comment by jmolivas** [comment]
I updated my OSX to `10.12.5`and rc24 works as expected
![Alt text](https://monosnap.com/file/Gck2jsvWdFocgNrgGqDbYTaMVH2doz.png)

**Comment by jmolivas** [comment]
I also tested on a new DrupalVM and test rc24 and it works fine  
![Alt text](https://monosnap.com/file/u1s1Yy0JSfP5k2c8yY3jNJq52PqB40.png)

**Comment by Narretz** [comment]
Same here for me. I'm on Windows 10 with php 5.6.23 and I'm accessing drupal like this: `vendor/drupal/console/bin/drupal` Always gives me 
```
  [Symfony\Component\Console\Exception\InvalidArgumentException]
  Command name "" is invalid.
```

Started with rc.24. .rc25 is broken, too. rc.23 works

**Comment by jmolivas** [comment]
@Narretz I was testing this with @betoquiroga and we found the fix try this:

```
drupal init --override
```
To test change directory to your site and `drupal list`

If that does not work then try removing the global console directory (backup if you make changes to any of those files)
```
rm -rf `~/.console`
```
To test change directory to your site and `drupal list`

**Comment by cjwills** [comment]
Blowing away ~/.console fixed it for me (rc25, linux, php 7.0)

**Comment by Narretz** [comment]
@jmolivas Thanks, I emptied .console in my user folder (on Windows) and now it works. I can't use `drupal` directly in my project folder, though (always have to use `vendor/drupal/console/bin/drupal` but I assume that's a different issue.

**Comment by jmolivas** [comment]
@Narretz Did you installed the Launcher?
https://docs.drupalconsole.com/en/getting/launcher.html

**Comment by bigsony** [comment]
It works for me after removing the global console directory. Thanks (rc25, PHP 7.0.15-0 ubuntu0.16.04.4 )

**Comment by jmolivas** [comment]
Closing this one. Feel free to re-open if still happening after applying the fix.

**Comment by nilanjanray** [comment]
OK, This is fixed by removing the ~/.console seems that earlier versions initialization was still exists and unable to continue current one

**Comment by MPParsley** [comment]
Removing ~/.console fixed it.
