### ISSUE TITLE
drush php is broken

### ISSUE THREAD

**Issue by chx** [hechoendrupal/drupal-console#3448]
I am working on a project that has `"drupal/console": "~1.0"`, in the  requirements of its composer.json. According to composer.lock, this in turn requires `"psy/psysh": "0.6.* || ~0.8"` and has been satisfied with `"version": "v0.8.9"`.

After installing `drush.phar` from `http://files.drush.org/drush.phar` as `/usr/local/bin/drush` , `drush php` breaks with a crazy error message: 

    "Error: Cannot instantiate interface Psy\VersionUpdater\Checker in Psy\info() (line 56 of phar:///usr/local/bin/drush/vendor/psy/psysh/src/Psy/functions.php) 
    #0 /path/to/vendor/psy/psysh/src/Psy/Shell.php(89): Psy\info(Object(Psy\Configuration))
    #1 phar:///usr/local/bin/drush/commands/core/cli.drush.inc(44): Psy\Shell->__construct(Object(Psy\Configuration))

I have n idea why it breaks out of the phar to the local copy but renaming `vendor/psy` to `vendor/_psy` unbreaks drush php. Drush reports Psy Shell v0.8.0.

My PHP is 7.1.3.

**Comment by bobthecow** [comment]
This is more of an issue with drush than drupal console, so the issue should probably be raised there. If you're just interested in a quick fix for the issue, add an explicit dependency on `"psy/psysh": "~0.6"` to your project's `composer.json`.

**Comment by chx** [comment]
`"psy/psysh": "0.8.0"` solved this. The root cause of course is https://www.drupal.org/node/2391219 but no one listened to me then so I guess one can't expect sanity now either.

**Comment by greg-1-anderson** [comment]
chx's problem was caused by using a global Drush install; see https://github.com/drush-ops/drush/pull/2853#issuecomment-317595718.

The broader problem of dependency mismatches is more of a Composer issue than anything that can be attributed to one dependency over another.
