### ISSUE TITLE
[generate:command] extension instead of module

### ISSUE THREAD

**Issue by lalop** [hechoendrupal/drupal-console#3463]
### Problem/Motivation

While generating some classes for my module I was disapointed by the wording, the commands ask for a module for controller's generation and for an extension for command's generation
Is there a reason why the wording is different ?

**Details to include:**
- Drupal version 8.3.5
- Console version  1.0.0-rc25

### Solution
Change the wording in the command's generation command.
I wanted to make a pr for that but I'm not sure of what is the extension's type.

**Comment by harold20** [comment]
Hi @lalop The command generate:command can be generate on modules, themes or profiles, so you need to provide the extension's name in interactive mode and the console will add the extension type, but if you pass the values, you need to specify if the extension's name is a module, theme or profiles on extension-type field.

I will change the translation
