### ISSUE TITLE
Can't make Drupal Console work

### ISSUE THREAD

**Issue by fede-green** [hechoendrupal/drupal-console#3464]
Hello, 

i run the latest Ubuntu and am trying to get Drupal Console to work. Installed it with 
`composer require drupal/console:~1.0 \
--prefer-dist \
--optimize-autoloader`

and added ~/.composer/vendot/bin to my $PATH. When i run `drupal` in a random dir i get the error "DrupalConsole must be executed within a Drupal Site". So i move into a dir where Drupal files are present and there i get the error ` [ERROR] Class Drupal\Core\DrupalKernel does not exist.` . What am i missing?

thanks

**Comment by jmolivas** [comment]
@fede-green DrupalConsole must be installed per-site not globally. You can find more info at the docs
https://docs.drupalconsole.com/en/getting/composer.html

You can still have a global executable we called launcher docs at 
https://docs.drupalconsole.com/en/getting/launcher.html
