### ISSUE TITLE
Translations of Drupal Console on localize.drupal.org

### ISSUE THREAD

**Issue by horvan** [hechoendrupal/drupal-console#3466]
### Drupal Console on localize.drupal.org

[ *TRANSLATION* ] Make Drupal Consoole available on localize.drupal.org

### Problem/Motivation
Today I have seen That Drush is available for translation on loclaize.drupal.org. The Command Line Tool just has about 800 Strings to translate including all versions. Drupal console isn't translatable in that way yet. Among others I like to have the ability to do so.

**Details to include:**

Almost every Drupal related module could be translated in to over 100 Languages thees days. Drush has translation support, too. If it is possible Drupal console should be made available for translation too as soon as possible.

### How to reproduce
There is nothing to reproduce this is just a suggestion to consider.

### Solution
-   Check the code of Drupal Console to make sure every string is translatable and exportable in a .po-file 
    that fits drupals standards. 
-  release Drupal Console on drupal.org
**Details to include:**
I am not  a developer of this great tool. Perhaps you guys have some great ideas how to achieve this.

**Comment by jmolivas** [comment]
@horvan DrupalConsole is translatable but we use the [symfony/translation](http://symfony.com/doc/current/translation.html)

You can find the repos at github => https://github.com/hechoendrupal/drupal-console-[LANGUAGE_CODE]

Examples:
https://github.com/hechoendrupal/drupal-console-en
https://github.com/hechoendrupal/drupal-console-es
https://github.com/hechoendrupal/drupal-console-zh-hans

**Comment by LOBsTerr** [comment]
I am closing the issue. Feel free to reopen it if you have further questions
