### ISSUE TITLE
[ generate:plugin ] Provide option to create twig template

### ISSUE THREAD

**Issue by andileco** [hechoendrupal/drupal-console#3467]
### Problem/Motivation
Frequently plugins such as blocks or views require a twig template, but it can be a little difficult to know where to put the template file and what to name it. When generating a module, Drupal Console asks about a twig template; why not also make this available when generating a plugin?

### Solution
I would think this could be done the way it is for generating a module template (where the user is asked during the generate:plugin command). However, I could alternatively see a separate command like generate:plugin:template or generate:plugin:twig being useful if adding a question during generate:plugin is too burdensome.

**Comment by lfjimenez** [comment]
@andileco do you have an update about this subject ?

**Comment by andileco** [comment]
No, I haven't heard any update. But still think it could be useful.
