### ISSUE TITLE
[ test ] Generate tests for existing modules

### ISSUE THREAD

**Issue by andileco** [hechoendrupal/drupal-console#3468]
### Problem/Motivation
For modules that were created/ported without Drupal Console and that do not currently have testing scaffolding, it would be nice if Drupal Console could generate their test scaffolding. This could go a long way in improving existing Drupal 8 modules.

**Comment by LOBsTerr** [comment]
@jmolivas it is a duplication. Please close it. Let's continue to work on it in this ticket https://github.com/hechoendrupal/drupal-console/issues/902

**Comment by jmolivas** [comment]
Duplicated
