### ISSUE TITLE
Drupal Console not working with site paths that contain spaces

### ISSUE THREAD

**Issue by martinduvergey** [hechoendrupal/drupal-console#3469]
### Drupal Console not working with site paths that contain spaces

[ *console* ] Drupal Console not working with site paths that contain spaces

### Problem/Motivation
Drupal Console does not work with site paths that contain spaces (e.g. `/Users/martin/web projects/my-site`).
When running the `drupal` command in the aforementioned folder, the following error message is shown:
> sh: /Users/martin/web: No such file or directory

### How to reproduce
Create a new Drupal project in a directory whose path contains one or more spaces.
Run the `drupal` command in that directory.

Version info:
- Drupal version: 8.3.5
- Console version: 1.0.0-rc26
- Console Launcher version: 1.0.0-rc26

### Solution
Support site paths that contain spaces.

Known workaround: move the project to a path that contains no space.

**Comment by mark-schaal** [comment]
I recently ran into this as well. Drupal Console is living inside of the project directory and is accessible with a direct call to `vendor/bin/drupal`, but using the launcher from `/usr/local/bin/drupal` breaks due to the directory path containing spaces.

```
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.12.5
BuildVersion:	16F73

$ php -v
PHP 5.6.16 (cli) (built: Nov 27 2015 10:28:34) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2015, by Zend Technologies
```

**Comment by AaronMcHale** [comment]
Same issue

**Comment by harold20** [comment]
Hi @martinduvergey, @mark-schaal, @AaronMcHale 
I couldn't reproduce this issue using the new release (1.9.0) 

Could any of you check it again?

**Comment by AaronMcHale** [comment]
With version 1.9.1 I get
sh: 1: /PATH: Permission denied

**Comment by enzolutions** [comment]
@AaronMcHale could you give us a screenshot of your execution error? Thanks in advance
