### ISSUE TITLE
[ quick:start ] 1.0.0 drupal quick:start results in `Cannot declare class Drupal\Console\Composer\Plugin\ExtenderManager`

### ISSUE THREAD

**Issue by illepic** [hechoendrupal/drupal-console#3475]
On drupal console 1.0.0, running a simple `drupal quick:start` results in the following output:

```
...
  - Installing symfony/yaml (v2.8.26): Loading from cache
  - Installing drupal/console-extend-plugin (0.9.2): Loading from cache
PHP Fatal error:  Cannot declare class Drupal\Console\Composer\Plugin\ExtenderManager, because the name is already in use in /Users/illepic/dev/p2/drupal8.dev/web/vendor/drupal/console-extend-plugin/src/ExtenderManager.php on line 8

Fatal error: Cannot declare class Drupal\Console\Composer\Plugin\ExtenderManager, because the name is already in use in /Users/illepic/dev/p2/drupal8.dev/web/vendor/drupal/console-extend-plugin/src/ExtenderManager.php on line 8
```

![2017-08-05 at 22 35](https://user-images.githubusercontent.com/295127/29000637-6e6b6070-7a2e-11e7-84e8-1e51a5048948.png)
![2017-08-05 at 22 35](https://user-images.githubusercontent.com/295127/29000640-80d927c4-7a2e-11e7-9eb9-536dbc0809de.png)

For "repository placeholder" I chose:

    [0] drupal-composer/drupal-project:8.x-dev

For "directory placeholder" I chose `web`. For "profile placeholder" I chose `profile`.

**Comment by jmolivas** [comment]
@illepic try updating DrupalConsole Lancher de outside for any drupal site and then execute 
```
drupal init --override --no-interaction
```

**Comment by illepic** [comment]
Getting farther along here!

````
// exec

 Executing command: drupal site:install profile --root=web --db-type="sqlite" --no-interaction

 [ERROR] Drupal Console is not installed at: web

 You must execute the following composer commands:
````

![2017-08-07 at 05 28](https://user-images.githubusercontent.com/295127/29025456-0786e17a-7b34-11e7-920f-826717b1376a.png)

I'll keep poking it.

**Comment by jmolivas** [comment]
@illepic which values are you passing or setting on the interactive mode?. Try using a full path when asked for the directory 

You can use the interactive mode or pass options ie:
```
drupal quick:start --directory="/path/to/drupal-project/" --profile="standard"

drupal  quick:start \
--repository="acquia/lightning-project:^8.1" \
--directory="/path/to/drupal-project/" --profile="lightning" \
```

**Comment by illepic** [comment]
That was exactly what I needed: an absolute path for `--directory`. Thanks @jmolivas!

**Comment by phannphong** [comment]
@jmolivas thanks. 

> drupal quick:start --directory="/path/to/drupal-project/" --profile="standard"
can run normally without error.
