### ISSUE TITLE
[generate:command] Command "example:dosomething", is not a valid command name.

### ISSUE THREAD

**Issue by hitfactory** [hechoendrupal/drupal-console#3476]
I successfully created and executed a custom command for an existing module/extension.

However, after generating a second custom command using generate:command for the same module/extension, I am unable to execute the newly-created command.

Drupal 8.3.5
Drupal Console version 1.0.0
Drupal Console Launcher 1.0.0

```
$ vendor/drupal/console/bin/drupal generate:command

... (deleted for brevity)

Generated or updated files

 1 - modules/custom/example/src/Command/DoSomethingCommand.php
 2 - modules/custom/example/console.services.yml
 3 - modules/custom/example/console/translations/en/example.dosomething.yml

$ vendor/drupal/console/bin/drupal cr all
$ vendor/drupal/console/bin/drupal example:dosomething

 [ERROR] Command "example:dosomething", is not a valid command name.
```

**Comment by jmolivas** [comment]
@hitfactory Did you installed the `example` module?

**Comment by hitfactory** [comment]
Thanks for quick follow up.

No, I am not using example module. I used 'example' as a placeholder for the actual name of my module which is the name of my client.

**Comment by jmolivas** [comment]
Is the actual command installed?

**Comment by hitfactory** [comment]
The module is enabled, the command is listed in console.services.yml and the command class file has been correctly created, but even after clearing cache the command is not discoverable. I also tried removing the changed/new command files and regenerating the command, but still no luck.

As mentioned above, however, the first command I generated for the same module does work. 

```
$ vendor/drupal/console/bin/drupal example:fixbodysummary

 [ERROR] Command "example:fixbodysummary", is not a valid command name.

$ vendor/drupal/console/bin/drupal example:fixmetatagdescription
 Set metatag description to [node:summary] on 0 nodes.
 Finished setting metatag description to [node:summary].

$ vendor/drupal/console/bin/drupal example:fixbodysummary

 [ERROR] Command "example:fixbodysummary", is not a valid command name.
```

It is just the second command (example:fixbodysummary)which, for some reason, is not being picked up.

Aside from a cache rebuild, is there anything else I should do to "install" the command?

**Comment by hitfactory** [comment]
So I deleted the command class again, deleted lines from console.services.yml, the yml translation files etc, re-ran generate:command to recreate example:fixbodysummary command...and now it works. No idea why.

One thing I didn't notice before is that there is a  vendor/drupal/console/<hash>-console.services.yml with both of my custom commands appended to it.  If that is some kind of cache of commands, perhaps previously it wasn't being updated with the new command?

I will file another issue if this happens again, so feel free to close this issue.

**Comment by jmolivas** [comment]
Maybe a cache issue lets keep an eye on it.

**Comment by acha5066** [comment]
I had the same issue because I'm on Acquia cloud and commited the vendor file (like they recommend). There is a .gitignore in drupal console's directory that ignores *-console.services.yml so when you try and run your command on the server it won't work as that file never gets commited to Acquia cloud.

**Comment by dodozhang21** [comment]
We are having the same issue.

**Comment by harold20** [comment]
I couldn't reproduce it using DC 1.9.0
