### ISSUE TITLE
Interactive way to add site config

### ISSUE THREAD

**Issue by nvaken** [hechoendrupal/drupal-console#3477]
Feature request. It would be nice to be able to add site config interactively. For our use-case the most valuable way would be project specific. For example in the following location:

`/path/to/drupal/composer/project/console/sites/[sitename].yml`

In time I might add my own contribution on this but not in the near future.

**Comment by jmolivas** [comment]
Sounds like a good idea @nvaken

**Comment by harold20** [comment]
It's already implemented.
