### ISSUE TITLE
-l short option doesn't work

### ISSUE THREAD

**Issue by neclimdul** [hechoendrupal/drupal-console#3478]
I couldn't figure out what the template was asking me to do so... here's a summary of the problem.

From the help text:
```
-l, --uri=URI          URI of the Drupal site to use (for multi-site environments or when running on an alternate port)
```

Using it in a command.
```
./vendor/bin/drupal -l https://drupal.example.com cron:execute
 [ERROR] Command "https://drupal.example.org", is not a valid command name.            
```

Obviously this should have executed the cron but instead it tries to parse the URL as the command.

**Comment by scubafly** [comment]
I had the same issue.
`drupal -l=sitename.dev` does not work ( gives the error message `[ERROR]`)
`drupal --uri=sitename.dev` does work

**Comment by harold20** [comment]
It's working as expected.

To use the short option, you must give a space, example:
```
drupal -l  sitename.dev
```

**Comment by neclimdul** [comment]
I don't know, still broken for me. Guess I need to open a new issue though?

```                                                                 
bash-4.4$ ./vendor/bin/drupal --version
Drupal Console version 1.9.3
bash-4.4$ ./vendor/bin/drupal -l drupal.example.com cron:execute
                                                                                                                        
 [ERROR] Command "drupal.example.com", is not a valid command name.                                                                                                                                                                         

bash-4.4$ ./vendor/bin/drupal --uri=drupal.example.com cron:execute
 Executing cron function of module "comment"
 Executing cron function of module "dblog"
 Executing cron function of module "field"
 Executing cron function of module "file"
 Executing cron function of module "node"
 Executing cron function of module "system"
 Executing cron function of module "update"
                                                                                                                        
 [OK] All cron implementations requested were executed successfully                                                     
                                                                                                                        
```

**Comment by harold20** [comment]
Hi @neclimdul, see my output. Could you try to execute the commands like the image?
```
➜  drupal --version
Drupal Console version 1.9.3

➜ drupal debug:multisite
 Sites are written using the format: <port>.<domain>.<path>
 -------------------- --------------------------------------------------------
  Site                                Directory
 -------------------- --------------------------------------------------------
  drupal.example.com   /path-to-drupal/web/sites/drupalExample.com
 -------------------- --------------------------------------------------------
```
![image](https://user-images.githubusercontent.com/8105777/67418221-9e7ea200-f587-11e9-9b08-209498dff524.png)

**Comment by neclimdul** [comment]
sorry for the late comment, don't see github comments that often and been pretty busy. So, yeah your test works but I don't know that this is fixed. `-ldrupal.example.com cron:execute` works but `-l drupal.example.com cron:execute` which is what I would have expected does not.

**Comment by neclimdul** [comment]
I should probably be clear on why I would expect that. The convention in cli applications is that `-ldrupal.example.com` would be equivalent to `-l -d -u -p -a -l -. -e -x -a -m -p -l -e -. -c -o -m` since single dash short options can be grouped like `-qvn`. so you would always write `-l` with a space after it to make sure it wasn't parsed as such and may applications would give errors like "Unknown option -p" or what ever failed if you did this.
