### ISSUE TITLE
[ERROR] Command "quick:start", is not a valid command name.                                                            

### ISSUE THREAD

**Issue by fusionx1** [hechoendrupal/drupal-console#3484]
### Issue title

[ERROR] Command "quick:start", is not a valid command name.                                                            

### Problem/Motivation
This could be a core issue where one of the major commands is not being recognized and Im using the latest version

**Details to include:**
Tried multiple time to run the quick start command but it Im getting an error, that says that its an invalid command.

### How to reproduce
Include steps related how to reproduce.

**Details to include:**
$ composer --version
Composer version 1.2.1 2016-09-12 11:27:19

$ drupal --version
Drupal Console Launcher 1.0.0

Im using macOS Sierra 10.12.4

Steps taken:
$> drupal init
$> drupal quick:start --directory=mydir

<img width="859" alt="screen shot 2017-08-13 at 6 16 04 am" src="https://user-images.githubusercontent.com/642874/29244668-5ec2f468-7ff0-11e7-80a7-630fefd58d7b.png">

**Comment by jmolivas** [comment]
@fusionx1  can you try `drupal init --override`

**Comment by LOBsTerr** [comment]
I am closing it, because there is no response. Feel free to reopen it
