### ISSUE TITLE
Call to undefined method QueueFactory::numberOfItems() in Queue/RunCommand.php

### ISSUE THREAD

**Issue by kylethebaker** [hechoendrupal/drupal-console#3486]
### numberOfItems() being called on QueueFactory instance rather than QueueInterface

[ *queue:run* ] The injected QueueFactory instance is being used directly as if it were a QueueInterface in  `runQueue()`. 

### Problem/Motivation
This causes the command to fail, triggering an `Call to undefined method QueueFactory::numberOfItems() in Queue/RunCommand.php`. 

### How to reproduce
Drupal 8.3.5
Console 1.0.0-rc25

Try to run a queue import.

#### Can see here:

 - [QueueFactory Injected and set to `$this->queue`](https://github.com/hechoendrupal/drupal-console/blob/master/src/Command/Queue/RunCommand.php#L42)
 - [QueueFactory::numberOfItems() erroneously called via `$this->queue->numberOfItems()`](https://github.com/hechoendrupal/drupal-console/blob/master/src/Command/Queue/RunCommand.php#L132)
- [QueueInterface contract showing that numberOfItems() is a method of QueueInterface rather than QueueFactory](https://github.com/drupal/drupal/blob/8.4.x/core/lib/Drupal/Core/Queue/QueueInterface.php#L43)

### Solution
The factory needs to be used to fetch the actual QueueInterface implementation. I have a fix that renames the QueueFactory instance var from `$this->queue` to `$this->queueFactory`, and then inside the try block that creates the worker instance I instantiate `$this->queue` to the actual QueueInterface using the queue $name.

An alternative fix with less LOC changes (though it's not much either way) is to pass the queue $name directly to `runQueue` and pulling the queue out of the factory there.

I have tested this fix and its working, I just need to put a pull request together.

**Comment by kylethebaker** [comment]
This is also referenced #3133, I have a fix incoming for this specific issue though.

**Comment by kylethebaker** [comment]
I decided to go with the slightly simpler fix here, which is renaming `$this->query` to `$this->queryFactory` (just for clarity), then retrieving the `QueryInstance` from the factory alongside the worker factory inside the try block (since it involves catches errors related the the queue name, which both factories share), and then finally just passing an instantiated queue object directly into `runQueue`.

This successfully fixed the issue for me.

**Comment by jmolivas** [comment]
PR  https://github.com/hechoendrupal/drupal-console/pull/3487 merged
