### ISSUE TITLE
[config:import] Symfony\Component\Console\Exception\RuntimeException The "--y" option does not exist.

### ISSUE THREAD

**Issue by allgood2386** [hechoendrupal/drupal-console#3489]
When using certain commands, possibly all of them (will have to test more) and using the -y flag, it resutls in an error saying --y isn't a flag.

I'm guessing the intended use is for the -y flag to work and not be interpreted with --

### How to reproduce
Run the config import command with the -y flag.

Drupal 8.4.0-alpha1
Drupal 8.3.x
Console 1.0.0
Launcher 1.0.0

### Solution
I don't know of the solution yet, I'll need to put in more time to figure out what is going on.

**Comment by allgood2386** [comment]
yes, thinking it's a global issue:

```drupal dbd -y


  [Symfony\Component\Console\Exception\RuntimeException]
  The "--y" option does not exist.```

**Comment by harold20** [comment]
Hi @allgood2386, the option `-y` is working on the DC 1.9.0
