### ISSUE TITLE
remove the command alias "dbc" from "database:log:clear"

### ISSUE THREAD

**Issue by terryzwt** [hechoendrupal/drupal-console#3491]
### Issue title
remove the command alias "dbc" from "database:log:clear"

As "database:log:clear" and "database:client" use the same alias "dbc". 

If I execute "drupal dbc", it only show me "[OK] Clear of events was successfully"

**Comment by kylethebaker** [comment]
This has been fixed in newer versions: `database:log:clear` is now aliased to `dblc`. 

It was fixed [in this commit](https://github.com/hechoendrupal/drupal-console/commit/e07a79ec27cf3f71970c223fd4ce06adad7bfc7b#diff-4d8d936fcb6fae430aa268322acb319fl).

**Comment by jmolivas** [comment]
Duplicated removed with PR on `drupal/console-core` https://github.com/hechoendrupal/drupal-console-core/pull/224
