### ISSUE TITLE
[generate:theme] Call to undefined method when using --machine-name option

### ISSUE THREAD

**Issue by flynnt** [hechoendrupal/drupal-console#3495]
### Problem/Motivation
Theme generation errors out when trying to manually set the theme machine name when scaffolding a theme.

**Details to include:**
- Correcting this would allow for the theme generation functionality to work as described in the documentation.

### How to reproduce
From within an active Drupal site:
`drupal generate:theme --theme="Foo"  --machine-name="foo_bar"` results in:
"Error: Call to undefined method Drupal\Console\Utils\Validator::validateModule() in /var/www/drupalvm/drupal/vendor/drupal/console/src/Command/Generate/ThemeCommand.php on line 246"

**Details to include:**
- Drupal version: 8.3.7
- Console version: 1.0.0
- Console Launcher version: 1.0.0

### Solution
Update [line 246 of ThemeCommand.php](https://github.com/hechoendrupal/drupal-console/blob/master/src/Command/Generate/ThemeCommand.php#L246) to reference the correct validator method: `$this->validator->validateModuleName`.

**Comment by jmolivas** [comment]
PR https://github.com/hechoendrupal/drupal-console/pull/3496 merged
