### ISSUE TITLE
Limited permissions for custom content entities, no bundle perms

### ISSUE THREAD

**Issue by betz** [hechoendrupal/drupal-console#3498]
### Issue title
[standard] Limited permissions for custom content entities

### Problem/Motivation
When creating a custom content entity, the permission are limited to the whole entity.
It would be nice if we could have a permission that limits on bundle.
Like 'Create new bundlexyz entity'

**Comment by jmolivas** [comment]
@betz  Any link to the docs or a code snippet we can use to implement

**Comment by betz** [comment]
well, i just created a custom content entity called 'Booking' console.
on the permissions page i find:
- Create new Booking entities
- Delete Booking entities
- Delete all revisions
- Edit Booking entities
- Revert all Booking revisions
- View all Booking revisions
- View published Booking entities
- View unpublished Booking entities

Nothing about a bundle, like node has.
- Article: Create new content
- Article: Delete any content
- ...

**Comment by LOBsTerr** [comment]
As far as I see node module provides this functionality -  to have specific permissions per content type. Node module also handles it a custom way. I'm not sure we want to have such complex case in the content entity generation command

**Comment by enzolutions** [comment]
I agree with @LOBsTerr  closing this issue. feel free to request to reopen if you have a strong use case.

**Comment by clemens-tolboom** [comment]
I'm trying to get `permission_granularity = "bundle"` for my custom entity. AFAIK there is no documentation on what is needed. 

### Core bundle permissions

modules/taxonomy/src/Entity/Term.php
68: *   permission_granularity = "bundle",

modules/node/src/Entity/Node.php
72: *   permission_granularity = "bundle",

modules/media/src/Entity/Media.php
71: *   permission_granularity = "bundle",

### Contrib bundle permissions

Not sure how to find those apart from google which did not help.

Unfortunately https://www.drupal.org/project/examples has `entity_type`.

So please reopen :-)

**Comment by clemens-tolboom** [comment]
We need to copy ie core/modules/media/src/MediaAccessControlHandler.php

- Add switch `--permission_granularity [bundle|entity_type]` to  command chain for EntityContentGenerator
- Adjust templates/module/src/accesscontrolhandler-entity-content.php.twig to generate fine grained pemissions
- Add permission_granularity to templates/module/src/Entity/entity-content.php.twig

Guess I missed some steps

**Comment by jmolivas** [comment]
@enzolutions ^^

**Comment by clemens-tolboom** [comment]
- vendor/drupal/console/templates/module/src/Controller/entity-controller.php.twig has permissions too

**Comment by clemens-tolboom** [comment]
- Something similar to \Drupal\node\NodePermissions for when creating a new entityType it's permissions are made available too.
- this is called from core/modules/node/node.permissions.yml:27 permission_callbacks

Quite some work :-p

**Comment by clemens-tolboom** [comment]
I have now a WIP PR #4138 to indicate I'm working on it and get test results (if any).

**Comment by clemens-tolboom** [comment]
Hmmm ... not sure why my second commit is not added to the PR. Anyone?

**Comment by enzolutions** [comment]
Let us know when is ready to test, we would like to include in Sep release 1.9.3

**Comment by clemens-tolboom** [comment]
I'll do my best. 3 tasks to check in #4138 :-)

**Comment by clemens-tolboom** [comment]
I remove WIP from  #4138 as it looks OK to me. It does contain PR #4139

**Comment by clemens-tolboom** [comment]
@enzolutions please review my PR #4138 :)

**Comment by enzolutions** [comment]
Thanks, @clemens-tolboom  we will check in a week-ish
