### ISSUE TITLE
Topics to blog about and update or add to the documentation

### ISSUE THREAD

**Issue by jmolivas** [hechoendrupal/drupal-console#3499]
### I am planning to write a weekly/bi-weekly blog and update the DrupalConsole documentation which topics will you be interested to learn about it?

- [ ] How to execute DrupalConsole commands on remote sites.
- [ ] How to execute DrupalConsole commands on a site using Docker.
- [ ] How to execute DrupalConsole commands on a site using DrupalVM.
- [ ] How to execute DrupalConsole commands on Acquia and Pantheon.
- [ ] How to create custom DrupalConsole commands.
- [ ] Creating custom Chain commands.
- [ ] Setup DrupalConsole on Windows.
- [ ] Setup local environment to contribute new features to DrupalConsole.
- [ ] Build an artifact and Deploy your Drupal 8 site using DrupalConsole.
- [ ] How to resolve dependency issues with Composer.

> NOTE: Feel free to suggest a topic.

**Comment by Oquile** [comment]
Creating custom DrupalConsole commands & creating custom Chain commands would be good. 

If you like live examples: The Liberty theme needs it's custom commands updated to use a console.services.yml.

I have also been wondering if it is possible to run node.js commands such as npm install or npm start as part of a console command.

**Comment by arturolinares** [comment]
How to handle site ids and config hashes in the app life-cycle:

From Dev to Stage/Prod:
- Export configs and add them to a VCS
- Deployment: import configs and how to handle uuids and config hashes
- How to handle dev modules/configs in prod (for example, disable devel in prod, change site email, etc).

From Stage/Prod to Dev:
- If there are some settings allowed to be edited in the live site, how to import them in a dev environment.

Finally, how to quickly load a new dev environment.

**Comment by gaelg** [comment]
How to execute DrupalConsole commands on a site using Docker.

**Comment by jmolivas** [comment]
@gaelg we update the docs about executing DrupalConsole commands on a site using Docker. https://docs.drupalconsole.com/en/alias/connecting-to-a-virtual-environment.html a blog post will be published after DrupalCon Vienna.
