### ISSUE TITLE
[generate:theme]: not working with regions parameter

### ISSUE THREAD

**Issue by stefan-korn** [hechoendrupal/drupal-console#3501]
### Problem
the generate:theme command is not working as expected when using the regions parameter on the command line. See second example on this page: https://docs.drupalconsole.com/en/commands/generate-theme.html

If you execute the command like given in the example, the regions are not correctly written to theme.info.yml file. Only the regions key is written but not the regions themself.

If you add the regions on the other hand not via command line but within the questioning process of generate:theme it is working as expected

Version of Drupal Console: 1.0.1

Reason is that the questioning process creates an array for the region input given, while the region parameter on the command line does not create such an array.

### Solution
I would propose to change the handling of the parameter input to make this work.
It would also be necessary to give all regions in one regions parameters on the command line, because otherwise only the latest parameter will be caught.

**Comment by stefan-korn** [comment]
The second example from here (https://docs.drupalconsole.com/en/commands/generate-theme.html) should then be noted like this:

```
drupal generate:theme  \
--theme="MyTheme"  \
--machine-name="mytheme"  \
--theme-path="/themes/custom"  \
--description="My Awesome theme"  \
--core="8.x"  \
--package="MyThemePackage"  \
--global-library="global-styling"  \
--base-theme="stable"  \
--regions='{"region_name":"Content", "region_machine_name":"content"},{"region_name":"Panel", "region_machine_name":"panel"}'  \
--breakpoints='"breakpoint_name":"narrow", "breakpoint_label":"narrow", "breakpoint_media_query":"all and (min-width: 560px) and (max-width: 850px)", "breakpoint_weight":"1", "breakpoint_multipliers":"1x"'
```

**Comment by jmolivas** [comment]
@stefan-korn Thanks for the PR we will review and add comments.

**Comment by LOBsTerr** [comment]
After some investigation of this issue, I have found the next:
1) Many commands (which ask for multiple items input) have similar issue;
2) This command generate code properly, if we use interactive mode only. In other case we receive just string (like this '"region_name":"Content", "region_machine_name":"content"'), which must be parsed separately
3) I like the idea to use json format for such cases
4) but I still believe we should use symfony approach to get array options:
`
...   
--regions='{"region_name":"Content", "region_machine_name":"content"}' \   
--regions='{"region_name":"Panel", "region_machine_name":"panel"}'  \   
--regions='{"region_name":"Sidebar", "region_machine_name":"sidebar"}'  \   
...   
`
5) Also we need to switch all this options from InputOption::VALUE_OPTIONAL to InputOption::VALUE_OPTIONAL | InputOption::VALUE_IS_ARRAY

@jmolivas  What do you think about this, if we will use the json for the complex structures ?

**Comment by LOBsTerr** [comment]
It is a first version, in future we should move the parsing to Trait or Parent class.

Drupal Console PR - https://github.com/hechoendrupal/drupal-console/pull/3711
Drupal Console Core PR - https://github.com/hechoendrupal/drupal-console-core/pull/289

**Comment by LOBsTerr** [comment]
If this solution will be accepted, I will do the changes for other commands

**Comment by jmolivas** [comment]
@LOBsTerr  Not a big fan of using JSON format to pass input options. 

What we did for `generate:form:config` instead was

Use the symfony standard way of reading arrays passing multiple (as you mentioned no 4)
```
--option_name=VALUE-1
--option_name=VALUE-2
--option_name=VALUE-3
```
And using the following format 
```
  --inputs='"name":"inputname", "type":"text_format", "label":"InputName", "options":"", "description":"Just a text input", "maxlength":"", "size":"", "default_value":"", "weight":"0", "fieldset":""'  \
  --inputs='"name":"email", "type":"email", "label":"Email", "options":"", "description":"Just an email input", "maxlength":"", "size":"", "default_value":"", "weight":"0", "fieldset":""'  \
```

To see a full example you can execute `drupal generate:form:config --help`
```
  drupal generate:form:config  \
  --module="modulename"  \
  --class="DefaultForm"  \
  --form-id="default_form"  \
  --config-file  \
  --inputs='"name":"inputname", "type":"text_format", "label":"InputName", "options":"", "description":"Just a text input", "maxlength":"", "size":"", "default_value":"", "weight":"0", "fieldset":""'  \
  --inputs='"name":"email", "type":"email", "label":"Email", "options":"", "description":"Just an email input", "maxlength":"", "size":"", "default_value":"", "weight":"0", "fieldset":""'  \
  --path="/modulename/form/default"
```

**Comment by LOBsTerr** [comment]
I found something similar in [generate:form:alter], but it also doesn't work there as it should be. I will fix it soon

**Comment by LOBsTerr** [comment]
@jmolivas PR https://github.com/hechoendrupal/drupal-console/pull/3712
Basically, I have moved the parser (it is based on this method https://github.com/drupalprojects/console/blob/c3a8b53c960354b4bf53ab2130c5f9d06de4e58e/src/Command/Generate/FormAlterCommand.php#L271) to the separate Trait for now. Also, I have fixed it. I didn't parse the string key:value properly.
Then I updated the logic and switched modes for multi value options to InputOption::VALUE_OPTIONAL | InputOption::VALUE_IS_ARRAY. So, we can handle it proper way.
So, for now ThemeCommand generates properly regions, libraries and breakpoints, when we pass them using inline options.

I will continue fix other commands, when you check this PR.

**Comment by jmolivas** [comment]
Done @LOBsTerr PR merged feel free to make the other changes.

**Comment by LOBsTerr** [comment]
PR - https://github.com/hechoendrupal/drupal-console/pull/3713

**Comment by LOBsTerr** [comment]
@jmolivas I think we can close this. 

The only thing left the update of docs examples. I have created a PR https://github.com/hechoendrupal/drupal-console-en/pull/157
