### ISSUE TITLE
[update:entities] Error message not printed correctly

### ISSUE THREAD

**Issue by kylethebaker** [hechoendrupal/drupal-console#3503]
### Error message not printed correctly in update:entities command

[update:entities]

The `$variables` array from `Error::decodeException` is being passed directly to `$io->info()` without being destructured  or turned into a message. This results in `Array` being printed in place of the error message leaving no indication of what the error actually was.

[Error::decodeException return type](https://github.com/drupal/drupal/blob/8.4.x/core/lib/Drupal/Core/Utility/Error.php#L34)

[Call inside of command](https://github.com/hechoendrupal/drupal-console/blob/master/src/Command/Update/EntitiesCommand.php#L89)

### How to reproduce
You can confirm this by adding a line `throw new EntityExceptionStorage("test")` inside of the `try` block.

- Drupal version (8.3.7)
- Console version (confirmed on 1.0.0-rc25 and current master).

### Solution
The pieces of the `$variables` array need to be put into a string message.

**Comment by jmolivas** [comment]
PR https://github.com/hechoendrupal/drupal-console/pull/3504 merged
