### ISSUE TITLE
[console] Drupal console dies without notice.

### ISSUE THREAD

**Issue by lslinnet** [hechoendrupal/drupal-console#3506]
### Problem/Motivation
Sometimes the php twig cache will cause an fatal error when loaded in initialization of the Drupal kernel and silently kill Drupal console execution.

An example of the cli command and execution output with debug:
```
➜  d8_demo drupal help
➜  d8_demo drupal
➜  d8_demo which drupal
/usr/local/bin/drupal
➜  d8_demo drupal --debug
Drupal Console Launcher version 1.0.1
Launcher path: /usr/local/bin/drupal
Drupal Console version 1.0.0
Per-Site path: /Users/lslinnet/Sites/d8_demo/vendor/drupal/console/bin/drupal

✔ Creating request
➤ Creating Drupal kernel
➜  d8_demo
```
This is very hard to track down why it is happening and there might be multiple causes of this, I have not figured out how to reproduce this and in my rush to fix it I forgot to make a backup of the corrupted php twig cache.

I suspect this might be caused when updating modules or perhaps Drupal core or something similar, a cache clear from within Drupal did not solve it neither is it possible to execute  ```drupal cr all``` as Drupal kernel crashes before it gets to the cache rebuilding part.

Quote from Slack:
> all drupal commands was broken, died in the kernel initialisation step, basically got to the rendering in the kernel boot and fatal errored out and but was not being caught due to a @ in front of the include call.

### How to reproduce
I am not certain what steps can be taken to reproduce this, and as mentioned didn't safe the state of the cached files when it happened – if it happens again or if someone else experience this please share those cached files.
A possible step to reproduce was mentioned by [geroldk](https://drupal.slack.com/archives/C20LD4Z8S/p1504071358000146) on Slack
>Yes, I deleted the twig php cache then Console worked … for a while … stopped again after I used it to enable a module. Had to delete the twig php cache again. Works since. Let’s see for how long.

[@geroldk](https://drupal.slack.com/archives/C20LD4Z8S/p1504165878000275?thread_ts=1504076977.000158&cid=C20LD4Z8S) wrote on slack how he could reproduce this issue, haven't verified it.

> What I did this time to get the failure was to install the Google Adsense module (randomly picked). 
> 1. `composer require drupal/adsense`
> 2. `drupal module:install adsense`
> 3. `drupal` to test. Still worked!
> 4. visited my site in the browser
> 5. `drupal` to test again. Failure, no output.
> 6. Zipped the `twig` folder in `sites/files/default/php`

**Drupal site:status**
```
➜  d84_demo drupal site:status

 System Info
 Drupal                                    8.3.6
 Access to update.php                      Protected
 always_populate_raw_post_data PHP setting Not set to -1.
 Configuration files                       Not protected
 Cron maintenance tasks                    Last run 2 days 22 hours ago
 Database system                           MySQL, MariaDB, Percona Server, or equivalent
 Database system version                   5.5.5-10.1.22-MariaDB
 Database updates                          Up to date
 Devel module enabled
 Entity/field definitions                  Up to date
 Experimental modules enabled              Experimental modules found: Content Moderation, Inline Form Errors, Migrate, Workflows. Experimental modules are provided for testing purposes only. Use at your own risk.
 File system                               Writable (public download method)
 GD library                                bundled (2.1.0 compatible)
 GD library PNG support                    bundled (2.1.0 compatible)
 Image toolkit                             gd
 Node Access Permissions                   Disabled
 PHP                                       5.6.31 (more information)
 PHP extensions                            Enabled
 PHP memory limit                          256M
 PHP OPcode caching                        Not enabled
 Random number generation                  Successful
 Rebuild access                            Enabled
 Search index progress                     98% (1 remaining)
 Serialized data types                     Not enabled
 Translation update status                 Up to date
 Trusted Host Settings                     Not enabled
 Unicode library                           PHP Mbstring Extension
 Update notifications                      Not enabled
 Upload progress                           Not enabled
 Web server
 Hash salt                                 XYn9bJpLGBLE0uGd24X7s1Mumw-C_HmNa0hruMGdS0MQxcnX_Ob5lssglwO7tly8lUFnQzGYGQ
 Drupal Console                            1.0.0
```

**Drupal console version**
```
drupal/console                        1.0.0           The Drupal CLI. A tool to generate boilerplate code, interact...
drupal/console-core                   1.0.0           Drupal Console Core
drupal/console-dotenv                 0.3.0           Drupal Console Dotenv
drupal/console-en                     1.0.0           Drupal Console English Language
drupal/console-extend-plugin          0.9.2           Drupal Console Extend Plugin
```
**Drupal console launcher version**
```
➜  ~ drupal --version
Drupal Console Launcher 1.0.1
```

### Solution
I suggest that a command gets build into Drupal console which can clear file caches without the need to bootstrap the Drupal kernel, as this seems to be the cause of this issue.

It might be prudent to add some catch all statement around the entire launcher execution and output helping text in case this happens.

**Workaround**
Find your PHP Twig cache and delete it, I solved it by deleting ```sites/default/files/php/twig```

**Comment by geroldkl** [comment]
Compressed archive of the twig cache as mentioned in step 6 under **How To Reproduce** the failure.

[twig cache corrupted.zip](https://github.com/hechoendrupal/drupal-console/files/1266277/twig.cache.corrupted.zip)

**Comment by harold20** [comment]
I couldn't reproduce it using DC 1.9.0
