### ISSUE TITLE
PHP Fatal error:  Cannot redeclare class Drupal\Console\Composer\Plugin\ExtenderManager

### ISSUE THREAD

**Issue by webfaqtory** [hechoendrupal/drupal-console#3513]
On step 2 of installation "Download using DrupalComposer project template" issuing the command:
`composer create-project \
drupal-composer/drupal-project:8.x-dev \
drupal8.dev \
--prefer-dist \
--no-progress \
--no-interaction`

I get:
`PHP Fatal error:  Cannot redeclare class Drupal\Console\Composer\Plugin\ExtenderManager in /var/www/drupal8/drupal8.dev/vendor/drupal/console-extend-plugin/src/ExtenderManager.php on line 9
`
Tried installing as well on a clean Drupal 8.3 install and had the same results.

![drupal](https://user-images.githubusercontent.com/2583085/30064902-11fa1266-924b-11e7-9ce6-f98a651fcd9c.png)

**Comment by weitzman** [comment]
I am seeing this as well.

**Comment by jmolivas** [comment]
@weitzman which OS and DrupalConsole version are you using?

**Comment by webfaqtory** [comment]
Ubuntu 14.04 and the latest download of DrupalConsole

**Comment by weitzman** [comment]
I'm on OSX. Just did  a vanilla `composer create-project drupal-composer/drupal-project`

**Comment by jmolivas** [comment]
@weitzman how about the Launcher?

**Comment by jmolivas** [comment]
The error is just by executing `composer create-project drupal-composer/drupal-project`

**Comment by clausbruun** [comment]
I get this too

**Comment by jmolivas** [comment]
@clausbruun which PHP version do you have?

**Comment by clausbruun** [comment]
@jmolivas PHP 7.1.7

**Comment by christophe-natale** [comment]
same problem on php 7.1

**Comment by jmolivas** [comment]
I was not been able to replicate this. Did any of you would like to share your `php.ini`?

**Comment by christophe-natale** [comment]
I launched the console from the root of drupal, but it works when I launch the console outside (level -1)...

**Comment by Adwitiya012** [comment]
I have faced the same issue in Windows (PHP 5.6). This is because of another vendor which was created by first Command "composer require drupal/console:~1.0". 
I have fixed the issue in two ways-
1. Change directory to drupal installation folder
2. Run "composer update" command again.

**Comment by kporras07** [comment]
Hi there,
I'm getting the same issue. Linux Mint, php 7.1
If I run `composer install` and the vendor folder doesn't exist, I get the error. If I run the same command again it works as expected.

Any ideas?

**Comment by harold20** [comment]
I couldn't reproduce using DC v1.9.1 and php v7.1.23.
