### ISSUE TITLE
[console] Some commands like CacheRebuild should run without doing a full drupal boostrap

### ISSUE THREAD

**Issue by jackbravo** [hechoendrupal/drupal-console#3514]
### Problem/Motivation

Some commands like CacheRebuild, DatabaseRestore, DatabaseClient, DatabaseDump should run without doing a full drupal bootstrap. Sometimes the code or the database change and can have an inconsistent state that makes bootsraping impossible without rebuilding the cache or modifying the database.

### How to reproduce

For example, if you modify the constructor parameters of a service class in a service.yml file you will get an error when bootstraping drupal, clearing the cache solves this issue, but right now drupal console cannot clear the cache without bootstraping drupal.

**Comment by harold20** [comment]
Hi @jackbravo We already allowed to execute `database:client` and `database:restore` commands without drupal boostrap. The others commands still can't executed , but we will change the structure to allow it.
