### ISSUE TITLE
GitHub Rate Limit showing in manifest.json

### ISSUE THREAD

**Issue by RiaanBurger** [hechoendrupal/drupal-console#3519]
### [docs] GitHub Rate Limit showing in http://drupalconsole.com/manifest.json

Docs was the best issue-group I could guess for this one.

### Problem/Motivation

The current contents of http://drupalconsole.com/manifest.json is:

> The website encountered an unexpected error. Please try again later.
> 
> Github\Exception\RuntimeException: You have reached GitHub hour limit! Actual limit is: 60 in Github\HttpClient\HttpClient->request() (line 145 of vendor/knplabs/github-api/lib/Github/HttpClient/HttpClient.php).

**Comment by RiaanBurger** [comment]
Returned to normal now.

**Comment by blainelang** [comment]
What was the fix as I'm getting this error today while trying to install or update as well.

Thanks!

**Comment by RiaanBurger** [comment]
I'd love to know more too. I just reported the error and then later that it came right ;-)
