### ISSUE TITLE
Creating Content Entity Breaks site due to missing route

### ISSUE THREAD

**Issue by kcannick** [hechoendrupal/drupal-console#3520]
I've just installed the latest version of Drupal console and have created my first module. After creating  a entity using generate:entity:content command the site breaks once module is activated.  I receive the following error:

The website encountered an unexpected error. Please try again later.

Symfony\Component\Routing\Exception\RouteNotFoundException: Route "entity.organization_type.collection" does not exist. in Drupal\Core\Routing\RouteProvider->getRouteByName() (line 190 of core/lib/Drupal/Core/Routing/RouteProvider.php).

**Comment by LOBsTerr** [comment]
@kcannick Do you still experience this issue?

**Comment by lonalore** [comment]
Same issue here. Drupal 8.5.3. Drupal Console 1.8.0.

**Comment by LOBsTerr** [comment]
I am closing the issue. Feel free to reopen it
