### ISSUE TITLE
Drupal gets messed up after running DC on a cold cache

### ISSUE THREAD

**Issue by nvaken** [hechoendrupal/drupal-console#3526]
This might be related to https://github.com/hechoendrupal/drupal-console/issues/3222 or even a dupe. 

When running `drupal cr all` and *directly* after that `drupal ci` my Drupal install shows a blank page. I cannot find any error logs, not on Drupal-level nor Apache-level. Also the page source shows up empty and the server returns a 200 response code. 

When running `drupal cr all`, then first open up a browser to warm up the cache, then run `drupal ci` there are no problems. 

So this seems to be the problem that Drupal's cache is cold and is being warmed up from CLI in DC. 

Using: Drupal Console version 1.0.2

**Comment by nvaken** [comment]
I've been trying to debug this by ripping open Drupal and to check where it fails. I've come thus far that I noticed that `core/lib/Drupal/Core/Render/Renderer.php` `doRender` always returns empty. Which would explain the WSOD without errors, though I still do not know why rendering would be entirely empty.

**Comment by jmolivas** [comment]
@nvaken I tried this and it works:

```
drupal site:new
drupal site:install
drupal ce
drupal cr all
drupal ci
drupal server
```

Then point the browser to the link shown at the server command output and the site works fine.

**Comment by nvaken** [comment]
Hey @jmolivas, strange! When using the built-in webserver like you mentioned above I'm not able to reproduce the problem. Though, I am able to reproduce it on both a LAMP (Digital Ocean Droplet) and AMPPS (Local Mac setup). Any idea what might cause this difference in results?

**Comment by LOBsTerr** [comment]
@nvaken do you still have this issue? I tried to reproduce it, but without success

**Comment by nvaken** [comment]
I'm not really sure at this point @LOBsTerr, we currently use `drush cr all` to rebuild caches to circumvent this issue in our deployment process. I'll try to reproduce one of these days.

**Comment by harold20** [comment]
I couldn't reproduce it using v1.9.1
