### ISSUE TITLE
[update:execute] returns exit code 1 when no updates available

### ISSUE THREAD

**Issue by nvaken** [hechoendrupal/drupal-console#3527]
I think `update:execute` should not return the same exit code as a failed update. I think this has been recently implemented since recently our deployment process crashes since `update:execute` now returns a non-0 exit code if there are no updates. 

Arguably, it should return a dedicated exit code (eg. `2`) so you can differentiate between failed or no updates. If a dedicated exit code is not possible, it should return `0` in my opinion; not updating Drupal does not mean it failed. Let us discuss.

**Edit**: Also, I'd suggest that "error" message is reduced to a "warning". My colleagues are startled by the big red error message while deploying new versions of projects. `update:execute` is part of our deployment process, regardless if there are new updates, in that case it feels wrong to show errors; nothing's gone wrong.

**Comment by jmolivas** [comment]
Fixed with this PR https://github.com/hechoendrupal/drupal-console/pull/3518 you can apply this patch https://patch-diff.githubusercontent.com/raw/hechoendrupal/drupal-console/pull/3518.patch new release 1.1.0 will be tag next week during DrupalCon.

**Comment by nvaken** [comment]
Awesome, looks like a good patch on first sight, I'll be using that.
