### ISSUE TITLE
[console] Change warning message background color output.

### ISSUE THREAD

**Issue by jmolivas** [hechoendrupal/drupal-console#3529]
### Change warning message background color output.

Warning messages use a red background color which could be a little confusing sometimes. 

The issue with red is people associates the color with error messages.

This is happening because DrupalStyle extends SymfonyStyle but is easy to change by adding a warning method at DrupalStyle class.

I am attaching an image how this looks by changing the background color from red to yellow.

<img width="842" alt="drupal-warning-color-change" src="https://user-images.githubusercontent.com/366275/30731489-86185bfe-9f65-11e7-8a46-d1341c62bbe5.png">

PR to `drupal/console-core` project => https://github.com/hechoendrupal/drupal-console-core/pull/238

**Comment by javiereguiluz** [comment]
Back in the day, when we created the SymfonyStyle, we initially used a yellow background for the warning messages. However, we ultimately change it for two reasons:

1) If you use a yellow background and don't change the text color, there are a lot of console combinations where the text is not readable. Some users reported this. In your screenshot there's no problem, but developers love to change the color of their consoles.
2) If you use a yellow background and change the text to black, the previous readability issue is fixed ... but another issue may happen: Windows users reported that black on yellow wasn't displayed on the console.

Maybe all these issues are gone now, but back in the day they were a problem for us, so I just wanted to warn you. Cheers!

**Comment by jmolivas** [comment]
Thanks for your comment @javiereguiluz we will do some test on windows and changing colors on the terminal to double check your comments.

**Comment by danielrose28** [comment]
Dang. Just noticed that you created a PR already @jmolivas. :)   I was just working on this. Was going to see if I could figure it out. I found it, but if you already made a PR I'll find something else to work on. :)

**Comment by LOBsTerr** [comment]
@jmolivas it was implemented. It can be closed

**Comment by jmolivas** [comment]
We need to test how this looks and decide if PR hechoendrupal/drupal-console-core#238 will be merged

**Comment by jmolivas** [comment]
I tested the different style colors available on the console component. This is how the messages look like:

- black
- red
- green
- yellow
- blue
- magenta
- cyan
- white
- default

<img src="https://monosnap.com/file/FKqcFA97pMXe1rCt0BDN8wikhozSjO.png">

**Comment by danielrose28** [comment]
For warnings I'm in favor of the yellow. That's just my opinion though. Thanks for the comparisons @jmolivas. 👍

**Comment by jmolivas** [comment]
Same for me yellow for warning messages.

**Comment by LOBsTerr** [comment]
Also for yellow. It looks natural

**Comment by jmolivas** [comment]
PR merged. Let's keep an eye on this just to see if any report of what Javier commented is reported.
