### ISSUE TITLE
Possible clash with config_filter

### ISSUE THREAD

**Issue by tanc** [hechoendrupal/drupal-console#3539]
### Problem/Motivation
When running any drupal console command, including just `drupal` I'm seeing the following error thrown:

`Recoverable fatal error: Argument 3 passed to Drupal\Console\Command\Config\DeleteCommand::__construct() must be an instance of Drupal\Core\Config\FileStorage, instance of Drupal\config_filter\Config\FilteredStorage given in /var/www/stage.ippf.org/gitroot/vendor/drupal/console/src/Command/Config/DeleteCommand.php on line 51`

### How to reproduce

- Drupal version: 8.3.7
- Console version: 1.0.2
- Console Launcher version: 1.0.1
- Steps to reproduce:
I haven't tried this but I think it will probably be sufficient to install Drupal core with config_filter module and then try and run a Drupal Console command.

### Solution
I don't have a solution but I think that config_filter provides its own config storage interface and class which seems to be causing this issue.

**Comment by tanc** [comment]
I just tried this on a site with Console version 1.0.0 and config_filter installed and the problem didn't occur. I then reverted the problem site to console 1.0.0 and it became useable again.

**Comment by jmolivas** [comment]
@tanc maybe was a cache issue. :
* How did you download `config_filter` via `composer` of `GUI`
* How did you install `config_filter` via `drupalconsole`, `drush` or GUI?

**Comment by tanc** [comment]
hi @jmolivas, I downloaded `config_filter` via `composer`

I installed `config_filter` with `drush en` on local. Then committed the config, pushed to staging and then production and imported with `drush cim`.

**Comment by jmolivas** [comment]
I will replicate following the steps to and ping you back with my results.

**Comment by webjazznl** [comment]
I got the same error when trying to execute any drupal console command in a multisite environment. I disabled config_filter module but no joy...
Cheers Henk

**Comment by jmolivas** [comment]
@webjazznl which command did you execute?

**Comment by cburschka-pwc** [comment]
I'm confused by this error happening on 1.0.2:

```Argument 3 passed to Drupal\Console\Command\Config\DeleteCommand::__construct() must be an instance of Drupal\Core\Config\FileStorage```

DeleteCommand::__construct actually takes a StorageInterface (not a FileStorage) as its 3rd argument, and has done so since January (1.0.0-rc15): https://github.com/hechoendrupal/drupal-console/commit/5431707e9c0e0cd08cb128b1e9706fd81b261d6b#diff-ae1c0fc415981511f0548957c9840978R51

config_filter's FilteredStorage implements FilteredStorageInterface, which extends the core StorageInterface and should therefore be accepted.

Is it possible there's an old version of Drupal Console (1.0.0-rc14 or earlier) in the environment that is somehow interfering?

**Comment by webjazznl** [comment]
@jmolivas I tried a couple but generate:plugin:block i am very sure off. Tried some more on my multisite project. Uninstalling config_filter allows me to continue the generate block wizard.  Enabling config_filter produces the errror @tanc gets. 

I have a single site project too that has config_filter installed. Will investigate if that one has any issues with drupalconsole.

**Comment by harold20** [comment]
I couldn't reproduce it using v1.9.1
