### ISSUE TITLE
..

### ISSUE THREAD

**Issue by dennisworks** [hechoendrupal/drupal-console#3542]
### Issue title

The issue title should comply with the following structure:

[ *ISSUE-GROUP* ] Short description

The *ISSUE-GROUP* should be one of:

* `command:name`
* `console`
* `helper`
* `standard`
* `template`
* `translation`
* `test`
* `docs`

### Problem/Motivation
A brief statement describing why the issue was filed.

**Details to include:**
- Why are we doing this? Above all, a summary should explain why a change is needed, in a few short sentences.

### How to reproduce
Include steps related how to reproduce.

**Details to include:**
- Drupal version (you can obtain this by running `drupal site:status`).
- Console version (you can obtain this by running `composer show | grep drupal/console`).
- Console Launcher version (you can obtain this by running outside of a drupal site `drupal --version`).
- Steps to reproduce
- Include screen-shot or video whenever necessary.

### Solution
A brief description of the proposed fix.

**Details to include:**
- A short summary of the approach proposed or used in the PR.
- Approaches that have been tried and ruled out.
- Links to relevant API documentation or other resources.
- Known workarounds.

**Comment by jmolivas** [comment]
Not a real issue
