### ISSUE TITLE
[module:download] --composer option fails because packagist.drupal-composer.org died

### ISSUE THREAD

**Issue by novia713** [hechoendrupal/drupal-console#3550]
### Problem/Motivation
`packagist.drupal-composer.org` is no longer available

### Solution
a) use `https://packages.drupal.org/8` :+1: 
b) remove definitively `--composer` option :-1: 

@jmolivas what do you think?

**Comment by novia713** [comment]
just in case were of convenience updating the composer repo, i attach the following PR:
https://github.com/hechoendrupal/drupal-console/pull/3551

still remains an obscure point in this issue:
the file `DrupalApi.php` has the following method
```
    public function getPackagistModuleReleases($module, $limit = 10, $unstable = true)
    {
        if (!trim($module)) {
            return [];
        }

        return $this->getComposerReleases(
            sprintf(
                'http://packagist.drupal-composer.org/packages/drupal/%s.json',
                trim($module)
            ),
            $limit,
            $unstable
        );
    }
```

i can not change the URL because i can not figure out which is the correspondent in drupal composer repo :-(

**Comment by webflo** [comment]
You could retrieve the package information with composer, but you have to add ``composer/composer`` as dependency first.

```
$io = new \Composer\IO\NullIO();
$composer = Composer\Factory::create($io, [
    'repositories' => [
        'drupal' => [
            'type' => 'composer',
            'url' => 'https://packages.drupal.org/8'
        ],
        'packagist' => false
    ]
]);
$packages = $composer->getRepositoryManager()->findPackages('drupal/token', new \Composer\Semver\Constraint\EmptyConstraint());
```

**Comment by novia713** [comment]
what do you think, @jmolivas ?
would be a problemm to add `composer/composer` as dependency?

**Comment by cburschka-pwc** [comment]
I suspect adding a `composer/composer` dependency risks version problems if the globally installed composer is a different version than the project one, *and* it adds stuff you don't necessarily want in the production environment at all, but only the build environment.

As I understand, DrupalConsole is already looking to deprecate/remove these commands in favor of using composer directly (#2465). In that context, wouldn't it be better to look for a workaround that doesn't add new dependencies?

**Comment by novia713** [comment]
@cburschka i would like to add to the conversation the following:

firstly, the decision of deprecating this feature is already not taken

secondly, i would consider having drupal console as a `dev` requirement in my drupal project. considering this, any further DrupalConsole requirement would be in `dev` also: so no superficial additions in `prod` are added

thirdly, here goes a question to @webflo 
why is it mandatory `composer` as dependency? is it not implicitly already installed in the system?
i can't figure these days someone using DrupalConsole without `composer` ...
having globally installed `composer` i can't do `new \Composer\IO\NullIO();` in DrupalConsole code?

lastly, my option would be requiring `composer` (just in case it would be really necessary) as `dev` requirement

**Comment by harold20** [comment]
I created this PR https://github.com/hechoendrupal/drupal-console/pull/4124 to remove the composer option from the command

**Comment by jmolivas** [comment]
No need to keep supporting this, let's suggest instead to people to use composer.

This is a bc break should we hold this on until 2.0?

**Comment by enzolutions** [comment]
I merged because is not functional and to avoid people to continue complaining about this for the other 9 months.
