### ISSUE TITLE
PHP Fatal error ContextException: Required contexts without a value: commerce_product

### ISSUE THREAD

**Issue by citlacom** [hechoendrupal/drupal-console#3553]
### Fatal ContextException error when executing any Drupal Console command using version 1.0.2 and Drupal 8.3.7 due DrupalKernel console class calls $kernel->handle($request) at createFromRequest() method when not all contexts are initialized yet. Any global block which depend on 

[ *console* ] Fatal PHP ContextException error on globally displayed blocks due missing contexts at the execution point where request handle is processed.

### Problem/Motivation
There are many projects which uses globally display blocks which will be handled at any Drupal Console execution because handle request is processed but at the moment of the execution dependend contexts are not available yet. 

I'm not an expert on the Drupal 8 Kernel but it seems that as the request handle() is executed before:

```php
            $drupalKernel->invalidateContainer();
            $drupalKernel->rebuildContainer();
            $drupalKernel->boot();
```

The contexts are no yet prepared to be passed to the blocks plugins, here is the error with the backtrace to follow the order of execution:

Drupal\Component\Plugin\Exception\ContextException: Required contexts without a value: commerce_product. in /Users/pablocc/Sites/bluesparklabs/SO/web/core/lib/Drupal/Core/Plugin/Context/ContextHandler.php on line 112

- 0  Drupal\block\BlockAccessControlHandler->checkAccess() called at [/Users/pablocc/Sites/bluesparklabs/SO/web/core/lib/Drupal/Core/Entity/EntityAccessControlHandler.php:105]
- 1  Drupal\Core\Entity\EntityAccessControlHandler->access() called at [/Users/pablocc/Sites/bluesparklabs/SO/web/core/lib/Drupal/Core/Entity/Entity.php:340]
- 2  Drupal\Core\Entity\Entity->access() called at [/Users/pablocc/Sites/bluesparklabs/SO/web/core/modules/block/src/BlockRepository.php:57]
- 3  Drupal\block\BlockRepository->getVisibleBlocksPerRegion() called at [/Users/pablocc/Sites/bluesparklabs/SO/web/core/modules/block/src/Plugin/DisplayVariant/BlockPageVariant.php:137]
- 4  Drupal\block\Plugin\DisplayVariant\BlockPageVariant->build() called at [/Users/pablocc/Sites/bluesparklabs/SO/web/core/lib/Drupal/Core/Render/MainContent/HtmlRenderer.php:259]
- 5  Drupal\Core\Render\MainContent\HtmlRenderer->prepare() called at [/Users/pablocc/Sites/bluesparklabs/SO/web/core/lib/Drupal/Core/Render/MainContent/HtmlRenderer.php:117]
- 6  Drupal\Core\Render\MainContent\HtmlRenderer->renderResponse() called at [/Users/pablocc/Sites/bluesparklabs/SO/web/core/lib/Drupal/Core/EventSubscriber/MainContentViewSubscriber.php:90]
- 7  Drupal\Core\EventSubscriber\MainContentViewSubscriber->onViewRenderArray() called at [/Users/pablocc/Sites/bluesparklabs/SO/web/core/lib/Drupal/Component/EventDispatcher/ContainerAwareEventDispatcher.php:111]
- 8  Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher->dispatch() called at [/Users/pablocc/Sites/bluesparklabs/SO/vendor/symfony/http-kernel/HttpKernel.php:149]
- 9  Symfony\Component\HttpKernel\HttpKernel->handleRaw() called at [/Users/pablocc/Sites/bluesparklabs/SO/vendor/symfony/http-kernel/HttpKernel.php:64]
- 10 Symfony\Component\HttpKernel\HttpKernel->handle() called at [/Users/pablocc/Sites/bluesparklabs/SO/web/core/lib/Drupal/Core/StackMiddleware/Session.php:57]
- 11 Drupal\Core\StackMiddleware\Session->handle() called at [/Users/pablocc/Sites/bluesparklabs/SO/web/core/lib/Drupal/Core/StackMiddleware/KernelPreHandle.php:47]
- 12 Drupal\Core\StackMiddleware\KernelPreHandle->handle() called at [/Users/pablocc/Sites/bluesparklabs/SO/web/core/modules/page_cache/src/StackMiddleware/PageCache.php:99]
- 13 Drupal\page_cache\StackMiddleware\PageCache->pass() called at [/Users/pablocc/Sites/bluesparklabs/SO/web/core/modules/page_cache/src/StackMiddleware/PageCache.php:78]
- 14 Drupal\page_cache\StackMiddleware\PageCache->handle() called at [/Users/pablocc/Sites/bluesparklabs/SO/web/core/lib/Drupal/Core/StackMiddleware/ReverseProxyMiddleware.php:47]
- 15 Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle() called at [/Users/pablocc/Sites/bluesparklabs/SO/web/core/lib/Drupal/Core/StackMiddleware/NegotiationMiddleware.php:50]
- 16 Drupal\Core\StackMiddleware\NegotiationMiddleware->handle() called at [/Users/pablocc/Sites/bluesparklabs/SO/vendor/stack/builder/src/Stack/StackedHttpKernel.php:23]
- 17 Stack\StackedHttpKernel->handle() called at [/Users/pablocc/Sites/bluesparklabs/SO/web/core/lib/Drupal/Core/DrupalKernel.php:656]
- 18 Drupal\Core\DrupalKernel->handle() called at [/Users/pablocc/Sites/bluesparklabs/SO/vendor/drupal/console/src/Bootstrap/DrupalKernel.php:29]
- 19 Drupal\Console\Bootstrap\DrupalKernel::createFromRequest() called at [/Users/pablocc/Sites/bluesparklabs/SO/vendor/drupal/console/src/Bootstrap/Drupal.php:115]
- 20 Drupal\Console\Bootstrap\Drupal->boot() called at [/Users/pablocc/Sites/bluesparklabs/SO/vendor/drupal/console/bin/drupal.php:78]
- 21 require(/Users/pablocc/Sites/bluesparklabs/SO/vendor/drupal/console/bin/drupal.php) called at [/Users/pablocc/Sites/bluesparklabs/SO/vendor/drupal/console/bin/drupal:4]

### How to reproduce
With Drupal core 8.3.7 and Drupal Console 1.0.2 you need to have a block that has a visibility condition (for example bundle condition) that depends on commerce_product context. Then run any Drupal Console command like: ../bin/vendor/drupal list

### Solution
I have been experimenting to change the order of execution of the request handle() call but cannot really find a solution so no idea or suggestion on how to solve.

**Comment by citlacom** [comment]
A fix for this issue was sent on PR https://github.com/hechoendrupal/drupal-console/pull/3558

For any developer experimenting similar issues I have documented on https://github.com/hechoendrupal/drupal-console/issues/3091#issuecomment-339727657 how to test the fix on your projects until is reviewed and the maintainers do a new release.

**Comment by jmolivas** [comment]
PR merged ;) thanks @citlacom
