### ISSUE TITLE
[generate:profile] add an option to specify the destination directory

### ISSUE THREAD

**Issue by ao2** [hechoendrupal/drupal-console#3557]
Hi,

in [drupal-init-tools](https://ao2.it/en/blog/2017/08/02/drupal-init-tools-quick-and-easy-drupal-8-setup) I am doing a little dance before calling the `generate:profile` command: I remove the current profile and then copy the generated profile from `$appRoot/profiles` to the current working directory, see https://git.ao2.it/drupal-init-tools.git/blob/HEAD:/libexec/create-profile.sh#l88

This is to allow recreating a profile with the same machine name of the installed one.

However this `rm` hack does not seem to work anymore with recent drupal versions: `system_rebuild_module_data()` gives errors if it can't find the profile dir, which definitely makes sense.

So, it would be great if I could pass a `--directory` option to the `generate:profile` command just like I do for the `config:export` command. This way I wouldn't have to care about possible naming conflicts between the generated profile and the current installation profile.

If the feature makes sense to you I can send a PR for it.

Thanks,
   Antonio

**Comment by jmolivas** [comment]
@ao2 Is this similar to what this PR is trying to add https://github.com/hechoendrupal/drupal-console/pull/3524

**Comment by ao2** [comment]
@jmolivas `--base-path` assumes that the generated profile should be under the app root, while a `--directory` option sounds more generic to me, it would follow what the `config:export` command does, and should still cover @harold20 use case.

TBH, for my specific use case, I could use `--base-path="/.."` even if it looks a little weird and hackish.

Last thing, I noticed that the `/profiles` default value does not get set when using `--no-interaction` and NOT passing `--base-path`, is this expected? Should I always pass **ALL** options when using `--no-interaction`?

Anyways if @harold20 wants to test the `--directory` approach, here is a preview:  https://github.com/ao2/drupal-console/commit/fc30fd8fc12eaac4d59b4ac29130ea170000be33

Ciao,
   Antonio

**Comment by ao2** [comment]
@harold20 ping, also about the fact that https://github.com/hechoendrupal/drupal-console/pull/3524 breaks any scripts using `--no-interaction` because the new `--base-path` option does not fallback to the default `profiles/` dir in these cases.

To be more precise: in case a script was using `--no-interaction`, before `--base-path` was implemented it would expect to find the generated profile under `profile/` while now the profile gets generated in `/`.

Of course passing `--base-path` fixes the issue. I can send a patch to fix this if the `--directory` idea gets discarded.

Ciao,
   Antonio

**Comment by harold20** [comment]
Hi @ao2. I saw the error when I used the command with ```--no-interaction```, so I created this PR #3596, This contains the solution and also I added validation in the execute when a path doesn't come in the command.

**Comment by jmolivas** [comment]
@harold20 do you PR allow full paths or is still relative to the site?

**Comment by harold20** [comment]
Both @jmolivas! Allow absolute and relative paths, If you type ```/``` when starting the route, that is an absolute and will be generated off-site, but if you don't type ```/``` then it will be generate within the site.

**Comment by jmolivas** [comment]
Awesome @harold20 this should cover @ao2 needs

**Comment by ao2** [comment]
I tested the changes in https://github.com/hechoendrupal/drupal-console/pull/3596 and they work for me. Thanks.

Just a question: is the practice of considering relative paths as relative to the **app root** a standard behavior of drupal-console? I noticed that the `--directory` option of `config:export` seems to behave the same way even if the implementation is different, it's using the `Filesystem` component from Symfony instead of `Webmozart\PathUtil\Path`.

Ciao,
   Antonio

**Comment by ao2** [comment]
We should also double check the case when the destination profile-path **already exists** but the user cannot write to it, maybe this is a general drupal-console overlook and not strictly related to these recent changes.

A quick test can be performed by running `--profile-path="/"` as a normal user. I would expect an error but the command fails **silently**.

Thanks,
   Antonio

**Comment by harold20** [comment]
You right @ao2 ! We don't catch the error, but now we do it! If you want test this, you will need this repository to test [PR '#252' drupal-core](https://github.com/hechoendrupal/drupal-console-core/pull/252)

**Comment by ao2** [comment]
@harold20 I like that.

And for a little more robustness maybe an `is_writable()` check can also be added to `Validator::validateModulePath()`, what do you think?

I think this would be good because there the mkdir is executed only if the dir does not exist already, so the code doesn't cover the case of an existing but non-writable dir.

**Comment by ao2** [comment]
OK, since https://github.com/hechoendrupal/drupal-console/pull/3596 and https://github.com/hechoendrupal/drupal-console-core/pull/252 have been merged I can close this issue.

I'll file another one if I think that an `is_writable()` check for the module path is still needed in `Validator::validateModulePath()`.

Thanks everyone.

Ciao,
   Antonio
