### ISSUE TITLE
[generate:event:subscriber] lists only a few event names in the autocomplete and gives an error if I enter an event name manually

### ISSUE THREAD

**Issue by marcusx** [hechoendrupal/drupal-console#3567]
### Problem/Motivation
If I try to create an event subscriber with ```drupal ges``` it fails on the question about the event name. If I use up/down arrows for going through the available names I have only a very short list. (Where does this list come from? What will I have to do to make my own event show up here? I was under the expectation that it is built from the @Event annotation in an Events class.)

But even if I enter an event name I am sure it must exist. I get an error, e.g.:
```
 Enter event name [ ]:
 > address.address_format


 [ERROR] Value "address.address_format" is invalid
```

- Drupal version 8.3.7
- Console version  1.0.2.

**Comment by jmolivas** [comment]
@marcusx Is `address.address_format` a valid Drupal event?

How do I get `address.address_format` loaded in my local to test this?

**Comment by webexpert5** [comment]
I am facing the same issue.
The autocomplete does not list all events. And does not accept event names.
I was trying with the events provided by jwt module.

**Comment by esolitos** [comment]
Same issue here, but with a different event.
I'm trying to generate a subscriber for `profile.label`, which comes from [the `profile` module](http://cgit.drupalcode.org/profile/tree/src/Event/ProfileEvents.php#n17).

**Comment by LOBsTerr** [comment]
I have investigate this issue. The problem here unfortunately, there is no way to get all events of the system, of specific dynamic nature of the Symfony. Currently, we return only the list of the dispatched events, which were registered in the system. I hope it will be improved in the future versions of Symfony . All events will inherit specific class and the name will be take from this class. Now it is not a case.
I believe, we should remove validation and allow users to set any events they want.

**Comment by esolitos** [comment]
Seems sad and reasonable at the same time, if we can't have a proper validation, a broken one is just in the way for a proper usage.
I think the autocomplete/suggestion could still be there, but allow any value in the end.

**Comment by LOBsTerr** [comment]
@esolitos I will present this fix soon

**Comment by LOBsTerr** [comment]
I have checked it. Currently we skip the validation for events. So, it is possible to enter any value for event.

https://github.com/hechoendrupal/drupal-console/blob/2e7e1b351e5b219182f9228db0037cee43a79075/src/Command/Shared/EventsTrait.php#L32

I'm closing the issue. Reopen the issue if it is still the case
