### ISSUE TITLE
[site:install] fails when the settings file is populated

### ISSUE THREAD

**Issue by cburschka-pwc** [hechoendrupal/drupal-console#3572]
To reproduce this:

1. Install Drupal
2. Drop all tables
3. Use `drupal site:install` again.

The wizard continues until the installation starts, and then fails with the error `Drupal is already installed`. (This seems like a valid use case, especially in local environments where the database is frequently torn down and reinstalled. Also, note that Drupal's web installer seemingly has no problem with an existing settings.php, as long as the DB isn't installed yet.)

Investigation shows that this is actually caused by the bootstrap adding some tables automatically, and adding a single config object (which then makes the configuration fail the "non-empty" check).

```
collection	name    	data
	        system.file	a:1:{s:4:"path";a:1:{s:9:"temporary";s:4:"/tmp";}}
```

A workaround is to run `drupal site:install`, then (once it has bootstrapped and reached the first prompt), manually truncate the config table, and then let the installer continue. Maybe we can somehow prevent this config object from being inserted during bootstrap, or remove it before the installation begins?

**Comment by jmolivas** [comment]
@cburschka-pwc You can use the `--force` option/flag to force the installation even if database exists. Using `--force` will drop the site database.

```
drupal site:install --force
```

**Comment by cburschka-pwc** [comment]
Unfortunately, in 1.1.0 this problem has been exacerbated, and `--force` no longer works.

Running `site:install` with an empty database now crashes with the following error (after first auto-creating the cache_bootstrap and cache_config tables):

```
  [Drupal\Core\Database\DatabaseExceptionWrapper]                                                                          
  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'database.key_value' doesn't exist: SELECT 1 AS expression  
  FROM                                                                                                                     
  {key_value} key_value                                                                                                    
  WHERE (name = :db_condition_placeholder_0) AND (collection = :db_condition_placeholder_1); Array                         
  (                                                                                                                        
      [:db_condition_placeholder_0] => system.module.files                                                                 
      [:db_condition_placeholder_1] => state                                                                               
  )                                                                                                                        
                                                                                                   
  [PDOException]                                                                                   
  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'database.key_value' doesn't exist  
```

In particular, this happens with *all* commands, including `list`, and probably others that should be available without a full site. 

In 1.0.2, `dr list` with a settings.php file and no database shows the missing table warning, but then lists the available commands, and `dr si --force` installs the database with the given settings.

In 1.1.* and 1.2, both crash with the above error.

**Comment by jmolivas** [comment]
@cburschka-pwc I will check this and add some comments on this issue.
