### ISSUE TITLE
Generate form command description should be more informative

### ISSUE THREAD

**Issue by cjgratacos** [hechoendrupal/drupal-console#3573]
### Generate Form Command description fix

* `generate:form`

### Problem/Motivation
The Generate Form Command description should be fixed. Currently it says:
`Generate a new "%s" ` when it should be more informative, example: `Generate a new Form`

**Details to include:**
The following is a picture of the current issue
![Generate Form Command Description](https://user-images.githubusercontent.com/5974887/32512261-7464fae2-c3c4-11e7-846a-49e0a487a587.png)

### How to reproduce
run `drupal | grep generate:form`

**Details to include:**
- Drupal version: 8.4.0
- Console version: 1.0.2
- Console Launcher version: 1.0.2

**Comment by LOBsTerr** [comment]
After some investigation, I found that method "configure" of FormCommand is executed, when a Translator is not set for the Command class. As, a result $this->trans('commands.generate.form.description') returns 'commands.generate.form.description' and later when we call getDescription it returns translated string as it is without replacement.

Conclusion, it is impossible to use translation strings for description with placeholders or we need to update the logic of getDescription method in CommandTrait class.
The similar issue with the help text - "commands.generate.form.help", I reported about it recently (https://github.com/hechoendrupal/drupal-console-core/issues/261).
The easiest way just create a separate translation strings (description and help) for 'FormBase' and 'ConfigFormBase'.

@jmolivas Any thoughts?

**Comment by LOBsTerr** [comment]
Another idea to set translator in the constructor of  Command class (drupal-console-core) and the run parent constructor, but not sure that it is a correct way to do it.

**Comment by LOBsTerr** [comment]
@jmolivas Can you check it? 
I have checked different ways how to make the translator available in Command class and the best way is with current code structure is just to pass it through DI into form generator commands

PR https://github.com/hechoendrupal/drupal-console/pull/3763
