### ISSUE TITLE
[console]: Container service-yaml files overwritten 

### ISSUE THREAD

**Issue by julian-** [hechoendrupal/drupal-console#3591]
### Problem/Motivation
After upgrading *drupal/console* to "~1.1" via composer, a hidden error was thrown, "The service "my_service" has a dependency on a non-existent parameter "my_parameter".

After further digging I've found the issue:
During the build process of the Kernel, rather of the service container. The *Drupal\Console\Bootstrap\DrupalKernelTrait* overwrites the site service files with an empty array.

Line 87:  `$this->addServiceFiles($servicesFiles);`

Unfortunately the `addServiceFiles` does not *add*, it *sets* the array and overwrites existing files which where set by the original drupal kernel by calling method `::discoverServiceProviders()`

```php
// Modified
$existingSiteServices = empty($this->serviceYamls['site']) ? [] : $this->serviceYamls['site'];
// Add DrupalConsole module(s) services
$this->addDrupalConsoleModuleServices($drupalFinder->getDrupalRoot(), $existingSiteServices);
```

### How to reproduce
Add following to your *setting.php*
`$settings['container_yamls'][] = DRUPAL_ROOT . '/sites/parameters.local.yml';`
Create the file and define a parameter in there, and try to reuse it in some of your service, run drupal console.

### Solution
I am just using this section to point exactly where to look at, whether the solution is acceptable or not, it's up to you.

Merge existing service files:

- add parameter `$mergeFiles = []`
- pass parameter from method `DrupalKernelTrait::discoverServiceProviders()`

My quickfix looks like:

```php
// Drupal\Console\Bootstrap\DrupalKernelTrait
protected function addDrupalConsoleModuleServices($root, $mergeFiles = [])
{
    $servicesFiles  = [];
    $moduleFileNames = $this->getModuleFileNames();
    foreach ($moduleFileNames as $module => $filename) {
        $servicesFile = $root . '/' .
            dirname($filename) .
            "/console.services.yml";
        if (file_exists($servicesFile)) {
            $servicesFiles[] = $servicesFile;
        }
    }

    // $this->addServiceFiles($servicesFiles);
    $this->addServiceFiles(array_unique(array_merge($servicesFiles, $mergeFiles)));
}
```

### Info

**Details to include:**
- Drupal version:  *8.4.2*
- Console version *1.1.1*

**Comment by jmolivas** [comment]
@julian- Very nice catch Iasst night I sent a ~~hack~~ PR https://github.com/hechoendrupal/drupal-console/pull/3590 to have this fixed temporarly.

How about doing this instead of passing the `$mergeFiles` array of file to the `addDrupalConsoleModuleServices` method 

```
  protected function addDrupalConsoleModuleServices($root, $mergeFiles = [])
```
And do the merge :
```

  $this->addServiceFiles(array_unique(array_merge($servicesFiles, $mergeFiles)));
```
Justs acces and update the `$this->serviceYamls['site']` like this:
```
  $this->serviceYamls['site'] = array_merge(
      $this->serviceYamls['site'],
      $servicesFiles
  );
```

**Comment by jmolivas** [comment]
PR including fix => https://github.com/hechoendrupal/drupal-console/pull/3592

**Comment by jmolivas** [comment]
Closing this one since new release tagged https://github.com/hechoendrupal/drupal-console/releases/tag/1.2.0

Feel free to re-open if still happening after updating to the latest version.

**Comment by julian-** [comment]
Of course :) It's simplified and makes much more sense, maybe i lost myself during debugging :)

Thank you very much 👍
