### ISSUE TITLE
[generate:entity:config] deletion form should match core EntityDeleteForm more closely

### ISSUE THREAD

**Issue by cburschka-pwc** [hechoendrupal/drupal-console#3595]
The template for the entity deletion form currently extends EntityConfirmFormBase. This duplicates a lot of code that is provided by EntityDeleteForm and EntityDeleteFormTrait. Also, the duplication is incomplete; for example the deleted dependencies are not listed.

Suggestion: Update the template to make the form class extend EntityDeleteForm.

**Comment by Chi-teck** [comment]
_EntityDeleteForm_ class has been marked as internal in Drupal 8.5.x
https://www.drupal.org/node/2873696

**Comment by cburschka-pwc** [comment]
Ah, that is indeed a pity; it looks like very useful functionality that should have been part of the API.

I guess it can still be used by modules that closely track core and have frequent releases, but the generated code should keep using ECFB as recommended.

**Comment by cburschka-pwc** [comment]
Actually, reopening for some alternative ideas:

- `EntityDeleteFormTrait` is *not* marked `@internal`; maybe we can use that even if we don't extend EntityDeleteForm itself?
- The rest of EntityDeleteForm consists mostly of glue code; in particular there's a call to `$this->addDependencyListsToForm($form, $entity->getConfigDependencyKey(), $this->getConfigNamesToDelete($entity), $this->getConfigManager(), $this->entityManager);` in the ::buildForm() function.

Maybe the DrupalConsole template could simply duplicate the core EntityDeleteForm class with some adjustments?

**Comment by cburschka-pwc** [comment]
I haven't worked extensively with the DrupalConsole code-generation templates, but this does seem to generate the right code. As a result, newly created forms will automatically show deleted dependencies, and the `getCancelUrl()` etc methods are no longer needed as the trait provides them.

**Comment by LOBsTerr** [comment]
@cburschka-pwc it can be closed?
