### ISSUE TITLE
Fatal error: Call to a member function inspect() on null in /vendor/drupal/console/src/Command/Debug/DatabaseTableCommand.php on line 92

### ISSUE THREAD

**Issue by developperKesako** [hechoendrupal/drupal-console#3600]
### Fatal error: Call to a member function inspect() on null in /vendor/drupal/console/src/Command/Debug/DatabaseTableCommand.php on line 92

* `drupal debug:database:table users`

## How to reproduce

- PostgreSQL 9.4.13
- Drupal 8.4.2 
- version console : Drupal Console version 1.2.0
- PHP 5.6.30-0+deb8u1 (cli)
- Debian GNU/Linux 8 (jessie). 
I have this problem when I execute this command in shell . 
I don't have problems when I do `drupal debug:database:table` - Only executing `drupal debug:database:table users`

### Solution
I don't have solution

**Comment by LOBsTerr** [comment]
Additional information how to reproduce, we add information to settings.php, about the db which doesn't exist and then try to call 
`
drupal debug:database:table  users --database="my"

`
Basically, it can't connect to db and we try to use this connection.

**Comment by LOBsTerr** [comment]
PR https://github.com/hechoendrupal/drupal-console/pull/3680

**Comment by LOBsTerr** [comment]
@jmolivas can be closed

**Comment by jmolivas** [comment]
Closing this one. Feel free to re-open if still happening after updating to the latest version.
