### ISSUE TITLE
config:export:content:type command fails, Call to a member function getConfigOptionalDirectory() on null

### ISSUE THREAD

**Issue by djmaschinen** [hechoendrupal/drupal-console#3609]
config:export:content:type command fails with error "Call to a member function getConfigOptionalDirectory() on null"

Drupal ver:  8.1.13
Console/launcher ver: 1.2.0

Executed command with verbose output as follows: 
----
$ drupal config:export:content:type profile --module=profileconfig -v

 Export content type in module as an optional configuration (yes/no) [yes]:
 > yes

 Exporting content type

  [Symfony\Component\Debug\Exception\FatalThrowableError]
  Call to a member function getConfigOptionalDirectory() on null

Exception trace:
 () at C:\xampp\htdocs\pantheon\ccad\vendor\drupal\console\src\Command\Shared\ExportTrait.php:88
 Drupal\Console\Command\Config\ExportContentTypeCommand->exportConfigToModule() at C:\xampp\htdocs\pantheon\ccad\vendor\drupal\console\src\Command\Config\ExportContentTypeCommand.php:151
 Drupal\Console\Command\Config\ExportContentTypeCommand->execute() at C:\xampp\htdocs\pantheon\ccad\vendor\symfony\console\Command\Command.php:264
 Symfony\Component\Console\Command\Command->run() at C:\xampp\htdocs\pantheon\ccad\vendor\symfony\console\Application.php:853
 Symfony\Component\Console\Application->doRunCommand() at C:\xampp\htdocs\pantheon\ccad\vendor\symfony\console\Application.php:200
 Symfony\Component\Console\Application->doRun() at C:\xampp\htdocs\pantheon\ccad\vendor\drupal\console-core\src\Application.php:191
 Drupal\Console\Core\Application->doRun() at C:\xampp\htdocs\pantheon\ccad\vendor\drupal\console\src\Application.php:64
 Drupal\Console\Application->doRun() at C:\xampp\htdocs\pantheon\ccad\vendor\symfony\console\Application.php:124
 Symfony\Component\Console\Application->run() at C:\xampp\htdocs\pantheon\ccad\vendor\drupal\console\bin\drupal.php:88

config:export:content:type [--module MODULE] [--optional-config [OPTIONAL-CONFIG]] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env [ENV]] [--root [ROOT]] [--debug] [--learning] [-c|--generate-chain] [-i|--generate-inline] [-d|--generate-doc] [-t|--target [TARGET]] [-l|--uri URI] [-y|--yes] [--] <command> <content-type>

**Comment by malcomio** [comment]
does the module you're trying to write to already exist?

**Comment by malcomio** [comment]
see #3625
