### ISSUE TITLE
[site:install] No error code returned when installation encounters an error

### ISSUE THREAD

**Issue by misterkay** [hechoendrupal/drupal-console#3611]
### Problem/Motivation
If an error is encountered while installing, the command returns an exit code of 0. This is problematic if this is a step within a shell script.
In my case I was getting and SQLSTATE error due to a misconfigured config file.

Perhaps detecting errors is documented somewhere, but I couldn't locate it in documentation.

### How to reproduce
Attempt to install a profile containing a core.extensions.yml file. Checking the status code of the previous command results in an exit value of 0.

- Drupal version (8.4.0).
- Console version (1.0.2/1.2.0).
- Console Launcher version (1.0.2/1.2.0).

### Solution
Return a non-zero error code when encountering an error during a command, or more prominent documentation for detecting errors when running commands.

**Comment by LOBsTerr** [comment]
It was fixed here https://github.com/hechoendrupal/drupal-console/issues/3758

Closing this one
