### ISSUE TITLE
config:export:single doesn't treat _core the same as core config export

### ISSUE THREAD

**Issue by andrewbelcher** [hechoendrupal/drupal-console#3621]
### Problem/Motivation
`drupal config:export:single` is really handy for exporting install config for modules. For this, you need to remove the site hash, which you can do with `--remove-config-hash`. However, this only removes `_core:default_config_hash`, producing different results to the core's pattern for committed config, which completely removes the `_core` key.

### How to reproduce
- Export a config entity using `drupal config:export:single --remove-config-hash`, it will have:
```yml
_core: { }
```

### Solution
Make the export match core's commit pattern by removing `_core` entirely, or at least removing an empty `_core`.

**Comment by harold20** [comment]
This issue is already fixed
