### ISSUE TITLE
the install website is down

### ISSUE THREAD

**Issue by tmli3b3rm4n** [hechoendrupal/drupal-console#3630]
## https://docs.drupalconsole.com/en/getting/composer.html
 Tried accessing it to install drupal because for some reason (most likely intrusive, analytical and/or mine with my browser) the instructions aren't in the Readme.

**Comment by jmolivas** [comment]
The docs are down Thanks for reporting

**Comment by jmolivas** [comment]
@tmli3b3rm4n  Fixed it was a DNS issue.
