### ISSUE TITLE
Fatal error on generate:config:entity when module is not generated.

### ISSUE THREAD

**Issue by Greg-Boggs** [hechoendrupal/drupal-console#3635]
### Fatal error on generate:config:entity when module is not generated.

[generate:config:entity] Short description

Error: Call to a member function getPath() on null in Drupal\Console\Generator\EntityContentGenerator->generate() (line 84 of EntityContentGenerator.php).

### Problem/Motivation

When you generate an entity without first generating a module, you get an unfriendly error.

### Solution

We should catch this exception and display a user friendly error message like:

    "Please generate a module before generating an entity with drupal generate:module"

**Comment by LOBsTerr** [comment]
@jmolivas I think it could be closed, this issue was fixed in https://github.com/hechoendrupal/drupal-console/issues/2178

**Comment by jmolivas** [comment]
@LOBsTerr  Exactly fixed on 1.4.0 @Greg-Boggs
