### ISSUE TITLE
[template] Replace deprecated assertResponse()

### ISSUE THREAD

**Issue by jcandan** [hechoendrupal/drupal-console#3639]
### Problem/Motivation
Two templates are using a deprecated call to `$this->assertResponse()` marked for removal in Drupal 9.0.0.

```
drupal-console/templates/module/src/Tests/js-test.php.twig
drupal-console/templates/module/src/Tests/load-test.php.twig
```

**Details to include:**
The deprecation documentation can be seen in `core/tests/Drupal/FunctionalTests/AssertLegacyTrait.php`.

### Solution
Simply change the method call to the replacement method, namely `$this->assertSession()->statusCodeEquals($code);`, in each of the twig files listed above.

**Comment by jcandan** [comment]
This is a very simple fix, and I would recommend labeling `novice` and/or `Hacktoberfest`.

**Comment by LOBsTerr** [comment]
PR: https://github.com/hechoendrupal/drupal-console/pull/3654

**Comment by jmolivas** [comment]
PR: #3654 merged
