### ISSUE TITLE
 [ERROR] Command "site:new", is not a valid command name.

### ISSUE THREAD

**Issue by hanmant-sapkal** [hechoendrupal/drupal-console#3641]
### Problem
Trying to install drupal project using drupal-console command "site-new"

### Details
- Console Launcher version: `1.3.1`
- ***Environment*** : (Windows Subsystem for Linux) Ubuntu 16.04.3 LTS

![image](https://user-images.githubusercontent.com/8626816/34436294-744df6f2-ecba-11e7-8d84-eb480677a340.png)

**Comment by LOBsTerr** [comment]
@hanmant-sapkal Did you run **drupal init** to create configuration and chain files ?

**Comment by jmolivas** [comment]
@LOBsTerr Thanks for commenting.

@hanmant-sapkal To avoid confusion about this, starting in 1.4.0 (released today a few minutes ago) execute `init`is no longer required. DrupalConsole will read the `chain` within the project files.

More information about the latest 1.4.0 release https://drupalconsole.com/articles/drupal-console-1-4-0

**Comment by hanmant-sapkal** [comment]
Thanks.

Regards,
Hanmant Ananda Sapkal
