### ISSUE TITLE
field plugin validator

### ISSUE THREAD

**Issue by chocho11** [hechoendrupal/drupal-console#3647]
Hi,

is it possible to generate validation/constraint  plugin for my field type plugin ?
(
use Symfony\Component\Validator\Constraint;
use Symfony\Component\Validator\ConstraintValidator;
)
Regards

**Comment by LOBsTerr** [comment]
PR: https://github.com/hechoendrupal/drupal-console/pull/3768
Translations PR: https://github.com/hechoendrupal/drupal-console-en/pull/172

**Comment by LOBsTerr** [comment]
it was merged
