### ISSUE TITLE
Add support of --yes param to all generation command

### ISSUE THREAD

**Issue by LOBsTerr** [hechoendrupal/drupal-console#3655]
### Problem/Motivation
Make it more convenient the use of commands, which generate the code and files.

### How to reproduce
`
generate:service --yes
`

The yes param is not applied

### Solution
Override confirmGeneration method in ConfirmationTrait and it's call in other classes .

**Comment by LOBsTerr** [comment]
The solution was implemented in PR: https://github.com/hechoendrupal/drupal-console/pull/3656

**Comment by jmolivas** [comment]
PR #3656 merged
