### ISSUE TITLE
Refactoring : Improve codebase of RebuildCommand

### ISSUE THREAD

**Issue by LOBsTerr** [hechoendrupal/drupal-console#3662]
### Problem/Motivation
I propose step by step do the small refactoring of all commands' classes, which have some coding issues (missing comments, wrong structure, double empty strings and etc.)
It will help us to keep the code clean and make it more easier to support.

**Comment by LOBsTerr** [comment]
PR - https://github.com/hechoendrupal/drupal-console/pull/3663

If you like such kind of small improvements. I will continue to commit these improvements each time I face a similar issue.

**Comment by jmolivas** [comment]
Sure we like this PRs
