### ISSUE TITLE
Unused / undefined variables in BreakPointCommand

### ISSUE THREAD

**Issue by LOBsTerr** [hechoendrupal/drupal-console#3664]
### Remove unused variables in BreakPointCommand

- $drupal_root
- $drupalRoot = $this->appRoot;
The path of the theme received based on the name of the theme and it includes already the root directory.

### Problem/Motivation
Improve the code of BreakPointCommand

**Comment by LOBsTerr** [comment]
PR https://github.com/hechoendrupal/drupal-console/pull/3665

**Comment by jmolivas** [comment]
Nice catch.
