### ISSUE TITLE
[generate:*] Some values must be quoted in YAML

### ISSUE THREAD

**Issue by cburschka** [hechoendrupal/drupal-console#3672]
Encountered while entering "[]" into the name field in `generate:module` - the file `*.info.yml` contains the name as an unquoted expression, but square brackets in string expressions must be quoted.

To avoid this problem, the value could either always be quoted, or DC could use a YAML exporter instead of a twig template.

(Haven't tested, but the same problem may exist for several other values and YAML files created by `generate:` commands.)

**Comment by LOBsTerr** [comment]
PR https://github.com/hechoendrupal/drupal-console/pull/3679

I have checked all yml templates and I have found some other similar issues.

**Comment by LOBsTerr** [comment]
@jmolivas The issue can be closed

**Comment by jmolivas** [comment]
Fixed with PR #3679

Closing this one. Feel free to re-open if still happening after updating to the latest version.
