### ISSUE TITLE
generate:form:config reuses gf alias

### ISSUE THREAD

**Issue by cburschka** [hechoendrupal/drupal-console#3673]
In `ConfigFormBaseCommand::configure()`, the alias `gfc` is set before calling `parent::configure()`, but `parent::configure()` resets the alias to `gf`.

This results in the alias `gf` being used twice (with the `generate:form:config` command winning the conflict), and the `generate:form` command only being available in long form.

**Comment by LOBsTerr** [comment]
PR https://github.com/hechoendrupal/drupal-console/pull/3678

**Comment by LOBsTerr** [comment]
@jmolivas The issue can be closed

**Comment by jmolivas** [comment]
Fixed with PR #3678

Closing this one. Feel free to re-open if still happening after updating to the latest version.
