### ISSUE TITLE
Dflydev\DotAccessConfiguration\YamlFileConfigurationBuilder::__construct() must be of the type array error

### ISSUE THREAD

**Issue by itsmeguru786** [hechoendrupal/drupal-console#3674]
### Dflydev\DotAccessConfiguration\YamlFileConfigurationBuilder::__construct() must be of the type array

[ *console* ] Freshly installed drupal console on Mac as per below commands. All went fine without error.

Command Sequence
1. Change directory to Drupal site:
2. composer require drupal/console:~1.0 \
--prefer-dist \
--optimize-autoloader

All look fine in terms of command execution but at site level console it appeared not proper. 
Then attempted with :  
*    curl https://drupalconsole.com/installer -L -o drupal.phar
*    mv drupal.phar /usr/local/bin/drupal
*   chmod +x /usr/local/bin/drupal

### Problem/Motivation
Running `drupal` or `drupal site:status` command gives following error:
Last login: Wed Jan 10 22:02:20 on ttys000
Sowmyas-MacBook-Pro:~ sowmyaharish$ drupal

Warning: dirname() expects exactly 1 parameter, 2 given in phar:///usr/local/bin/drupal/vendor/drupal/console-core/src/Utils/ConfigurationManager.php on line 214

Notice: Undefined index: config in phar:///usr/local/bin/drupal/vendor/drupal/console-core/src/Utils/ConfigurationManager.php on line 67

Catchable fatal error: Argument 1 passed to Dflydev\DotAccessConfiguration\YamlFileConfigurationBuilder::__construct() must be of the type array, null given, called in phar:///usr/local/bin/drupal/vendor/drupal/console-core/src/Utils/ConfigurationManager.php on line 68 and defined in phar:///usr/local/bin/drupal/vendor/dflydev/dot-access-configuration/src/Dflydev/DotAccessConfiguration/YamlFileConfigurationBuilder.php on line 31

**OtherDetails :**
Drupal Version : 8.4
Console Version:
Sowmyas-MacBook-Pro:drupaltheming sowmyaharish$ composer.phar show | grep drupal/console
drupal/console                        1.4.0              The Drupal CLI. ...
drupal/console-core                   1.4.0              Drupal Console Core
drupal/console-dotenv                 0.3.0              Drupal Console D...
drupal/console-en                     1.4.0              Drupal Console E...
drupal/console-extend-plugin          0.9.2              Drupal Console E...
Sowmyas-MacBook-Pro:drupaltheming sowmyaharish$

**Comment by jmolivas** [comment]
@itsmeguru786 1.4.0 introduced a few changes and may require some manual work.

Some copied files via `init` command to home and/or project directory are no longer required. Files to remove:

#### From path(s) `~/.console/` and/or `path/to/site/console`
- aliases.yml
- phpcheck.yml
- router.php
- site.mode.yml

#### From path(s) `~/.console/chain` and/or `path/to/site/console/chain`

- develop-contribute.yml
- quick-start.yml
- site-new.yml

If the issue still persists and you do not have any custom files at `~/.console/chain` and/or `path/to/site/console/chain` you can safely remove those directories:

* `~/.console/`
* `path/to/site/console/`


You can read more about the 1.4.0 changes 
https://drupalconsole.com/articles/drupal-console-1-4-0

**Comment by hejiann** [comment]
Got the same issue:

Step 20/46 : RUN composer require drupal/console
 ---> Running in cdac044c720e
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Using version ^1.4 for drupal/console
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 20 installs, 0 updates, 0 removals
  - Installing drupal/console-extend-plugin (0.9.2): Downloading (100%)         
> Drupal\Core\Composer\Composer::vendorTestCodeCleanup
  - Installing psr/simple-cache (1.0.0): Downloading (100%)         
> Drupal\Core\Composer\Composer::vendorTestCodeCleanup
  - Installing psr/cache (1.0.1): Downloading (100%)         
> Drupal\Core\Composer\Composer::vendorTestCodeCleanup
  - Installing symfony/polyfill-apcu (v1.6.0): Downloading (100%)         
> Drupal\Core\Composer\Composer::vendorTestCodeCleanup
  - Installing symfony/cache (v3.4.3): Downloading (100%)         
> Drupal\Core\Composer\Composer::vendorTestCodeCleanup
  - Installing symfony/expression-language (v3.4.3): Downloading (100%)         
> Drupal\Core\Composer\Composer::vendorTestCodeCleanup
  - Installing gabordemooij/redbean (v4.3.4): Downloading (100%)         
> Drupal\Core\Composer\Composer::vendorTestCodeCleanup
  - Installing vlucas/phpdotenv (v2.4.0): Downloading (100%)         
> Drupal\Core\Composer\Composer::vendorTestCodeCleanup
  - Installing drupal/console-dotenv (0.3.0): Downloading (100%)         
> Drupal\Core\Composer\Composer::vendorTestCodeCleanup
  - Installing webflo/drupal-finder (1.1.0): Downloading (100%)         
> Drupal\Core\Composer\Composer::vendorTestCodeCleanup
  - Installing symfony/filesystem (v3.4.3): Downloading (100%)         
> Drupal\Core\Composer\Composer::vendorTestCodeCleanup
  - Installing symfony/config (v3.2.14): Downloading (100%)         
> Drupal\Core\Composer\Composer::vendorTestCodeCleanup
  - Installing stecman/symfony-console-completion (0.7.0): Downloading (100%)   > Drupal\Core\Composer\Composer::vendorTestCodeCleanup
  - Installing drupal/console-en (1.4.0): Downloading (100%)         
> Drupal\Core\Composer\Composer::vendorTestCodeCleanup
  - Installing dflydev/placeholder-resolver (v1.0.2): Downloading (100%)        > Drupal\Core\Composer\Composer::vendorTestCodeCleanup
  - Installing dflydev/dot-access-data (v1.1.0): Downloading (100%)         
> Drupal\Core\Composer\Composer::vendorTestCodeCleanup
  - Installing dflydev/dot-access-configuration (v1.0.2): Downloading (100%)    > Drupal\Core\Composer\Composer::vendorTestCodeCleanup
  - Installing drupal/console-core (1.4.0): Downloading (100%)         
> Drupal\Core\Composer\Composer::vendorTestCodeCleanup
  - Installing alchemy/zippy (0.4.3): Downloading (100%)         
> Drupal\Core\Composer\Composer::vendorTestCodeCleanup
  - Installing drupal/console (1.4.0): Downloading (100%)         
> Drupal\Core\Composer\Composer::vendorTestCodeCleanup
alchemy/zippy suggests installing guzzle/guzzle (To use the GuzzleTeleporter with Guzzle 3)
Writing lock file
Generating autoload files
> Drupal\Core\Composer\Composer::preAutoloadDump
> Drupal\Core\Composer\Composer::ensureHtaccess
Creating packages services cache file:
/var/www/html/vendor/drupal/console/extend.console.uninstall.services.yml
 ---> 948f1c1524c8
Removing intermediate container cdac044c720e
Step 21/46 : RUN /etc/init.d/mysql start &&   vendor/bin/drupal site:mode prod
 ---> Running in 424af371d452
Starting MySQL database server: mysqld ..
Checking for tables which need an upgrade, are corrupt or were
not closed cleanly..

Warning: dirname() expects exactly 1 parameter, 2 given in /var/www/html/vendor/drupal/console-core/src/Utils/ConfigurationManager.php on line 214
PHP Warning:  dirname() expects exactly 1 parameter, 2 given in /var/www/html/vendor/drupal/console-core/src/Utils/ConfigurationManager.php on line 214

Notice: Undefined index: config in /var/www/html/vendor/drupal/console-core/src/Utils/ConfigurationManager.php on line 67

Catchable fatal error: Argument 1 passed to Dflydev\DotAccessConfiguration\YamlFileConfigurationBuilder::__construct() must be of the type array, null given, called in /var/www/html/vendor/drupal/console-core/src/Utils/ConfigurationManager.php on line 68 and defined in /var/www/html/vendor/dflydev/dot-access-configuration/src/Dflydev/DotAccessConfiguration/YamlFileConfigurationBuilder.php on line 31
PHP Notice:  Undefined index: config in /var/www/html/vendor/drupal/console-core/src/Utils/ConfigurationManager.php on line 67
PHP Catchable fatal error:  Argument 1 passed to Dflydev\DotAccessConfiguration\YamlFileConfigurationBuilder::__construct() must be of the type array, null given, called in /var/www/html/vendor/drupal/console-core/src/Utils/ConfigurationManager.php on line 68 and defined in /var/www/html/vendor/dflydev/dot-access-configuration/src/Dflydev/DotAccessConfiguration/YamlFileConfigurationBuilder.php on line 31
The command '/bin/sh -c /etc/init.d/mysql start &&   vendor/bin/drupal site:mode prod' returned a non-zero code: 255

**Comment by hejiann** [comment]
It seems drupal-console not compatible with the most recent drupal 8.5.x code.

**Comment by jmolivas** [comment]
Testing with 8.5 and sending the fix in a few.

**Comment by jmolivas** [comment]
Fix https://github.com/hechoendrupal/drupal-console-core/pull/277

**Comment by jmolivas** [comment]
@itsmeguru786 @hejiann  This should be fixed on 1.5.0 could you update to latest version and confirm.

**Comment by itsmeguru786** [comment]
@jmolivas Thanks a ton for the fix suggestion. Able to find the beauty in action. 

Following the Fix suggestion above, was able to resolve the warning thrown and raising the PHPVersion to 7.0 helped with Fatal Error resolution. 

*Console OutPut*

`Last login: Fri Jan 12 06:03:03 on ttys000
Sowmyas-MacBook-Pro:~ sowmyaharish$ **export PHP_ID=php7_0;** export PATH="/Applications/DevDesktop/$PHP_ID/bin:/Applications/DevDesktop/mysql/bin:/Applications/DevDesktop/tools:$PATH" && cd "/Users/sowmyaharish/Sites/devdesktop/drupaltheming"
Sowmyas-MacBook-Pro:drupaltheming sowmyaharish$ 
Sowmyas-MacBook-Pro:drupaltheming sowmyaharish$ drupal
Drupal Console version 1.4.0

Usage:
  command [options] [arguments]

Options:
  -h, --help             Display this help message
  -q, --quiet            Do not output any message
  -V, --version          Display this application version
      --ansi             Force ANSI output
      --no-ansi          Disable ANSI output
`
