### ISSUE TITLE
Running Drupal console on Platform.sh

### ISSUE THREAD

**Issue by jepster** [hechoendrupal/drupal-console#3699]
I want to run Drupal console in the Platform.sh hosting environment. However I am getting the following errors, when I am running the 

> drupal cr

command.

> PHP Warning:  mkdir(): Read-only file system in /app/.global/vendor/drupal/console-core/src/Utils/ConfigurationManager.php on line 249
> 
> Warning: mkdir(): Read-only file system in /app/.global/vendor/drupal/console-core/src/Utils/ConfigurationManager.php on line 249
> PHP Warning:  mkdir(): Read-only file system in /app/.global/vendor/drupal/console-core/src/Utils/ConfigurationManager.php on line 249
> 
> Warning: mkdir(): Read-only file system in /app/.global/vendor/drupal/console-core/src/Utils/ConfigurationManager.php on line 249
> 
>                                                                                                                         
>  [ERROR] Class Drupal\Core\DrupalKernel does not exist.                                                                 
>                                                                                                                         
> 
> PHP Warning:  mkdir(): Read-only file system in /app/.global/vendor/drupal/console-core/src/Utils/ConfigurationManager.php on line 249
> 
> Warning: mkdir(): Read-only file system in /app/.global/vendor/drupal/console-core/src/Utils/ConfigurationManager.php on line 249
> PHP Warning:  mkdir(): Read-only file system in /app/.global/vendor/drupal/console-core/src/Utils/ConfigurationManager.php on line 249
> 
> Warning: mkdir(): Read-only file system in /app/.global/vendor/drupal/console-core/src/Utils/ConfigurationManager.php on line 249
> PHP Warning:  mkdir(): Read-only file system in /app/.global/vendor/drupal/console-core/src/Utils/ConfigurationManager.php on line 249
> 
> Warning: mkdir(): Read-only file system in /app/.global/vendor/drupal/console-core/src/Utils/ConfigurationManager.php on line 249
> PHP Warning:  mkdir(): Read-only file system in /app/.global/vendor/drupal/console-core/src/Utils/ConfigurationManager.php on line 249
> 
> Warning: mkdir(): Read-only file system in /app/.global/vendor/drupal/console-core/src/Utils/ConfigurationManager.php on line 249
> 
>                                                                                                                         
>  [ERROR] Command "cr", is not a valid command name.         

I have been adding the "/app/.global" folder to the mounts config from my hosting, to have a persistent filesystem mount for this folder. However, I have still the same errors. The "files" and "tmp" folders are already mounted and configured properly.

Do you know how I can solve this issue?

**Comment by jmolivas** [comment]
@jepster which DC version are you using?

**Comment by jepster** [comment]
It was a Platform.sh config related issue. Thanks for your reply! This issue can be closed.
