### ISSUE TITLE
Feature request: command to generate custom block type (bundle)

### ISSUE THREAD

**Issue by andileco** [hechoendrupal/drupal-console#3700]
Drupal Console is great for generating a block plugin. However, users may also want to use it to generate a block type with a set of fields, just as one would want to create a content type with a custom set of fields. I image the code for this would be similar to what is required for a content bundle, so hopefully it would not be a heavy lift.

**Comment by gilbertomangones** [comment]
Hi, is added a new command inner to generate a block content type and block type as well.
 ```drupal generate:block:type```

https://github.com/hechoendrupal/drupal-console/pull/4160
https://github.com/hechoendrupal/drupal-console-en/pull/254

**Using**
Drupal Console        : 1.9.3
Drupal Console-en  : 1.9.3
Drupal core              : 8.7.7

**Images**
Block Content Type
![blocktype](https://user-images.githubusercontent.com/6983125/65737711-0636ef80-e0a5-11e9-9caa-87b212de8d22.png)
Block Custom Type
![blockcustom](https://user-images.githubusercontent.com/6983125/65737695-f61f1000-e0a4-11e9-8b06-dba7b34d5ae4.png)

Video test: https://youtu.be/xbx-dM1fT6I
