### ISSUE TITLE
generate:module command is adding an extra single quote

### ISSUE THREAD

**Issue by bailey86** [hechoendrupal/drupal-console#3707]
### Issue title

The issue title should comply with the following structure:

[ *ISSUE-GROUP* ] Short description

The *ISSUE-GROUP* should be one of:

* `command:name`
* `console`
* `helper`
* `standard`
* `template`
* `translation`
* `test`
* `docs`

### Problem/Motivation
After using generate:module I get this error:

The website encountered an unexpected error. Please try again later.</br></br><em class="placeholder">Drupal\Core\Extension\InfoParserException</em>: Unable to parse modules/custom/qf_plugins/qf_plugins.info.yml Malformed inline YAML string: &#039;QF plugins&#039;&#039; at line 1 (near &quot;name: &#039;QF plugins&#039;&#039;&quot;). in <em class="placeholder">Drupal\Core\Extension\InfoParserDynamic-&gt;parse()</em> (line <em class="placeholder">25</em> of <em class="placeholder">core/lib/Drupal/Core/Extension/InfoParserDynamic.php</em>).
![image](https://user-images.githubusercontent.com/1262839/35149065-a9904862-fd0c-11e7-9cc9-70f8c4c5969a.png)

In the qf_plugins.info.yml file extra single quotes have been added to two lines:

name: 'QQ Plugins''
type: module
description: 'Form element plugins and submission handler plugins for XYZ project''
core: 8.x
package: 'XYZ'

I can confirm that removing the extra quotes resolves the problem.

### How to reproduce
Brand new Drupal site built using Composer from 
$ composer create-project drupal-composer/drupal-project:8.x-dev
Installed webforms module - not sure if this is relevant but it is all I have done apart from creating one really basic webform.
Then ran drupal generate:module.  I did this twice to confirm the same error occured.

**Details to include:**
- Drupal version (you can obtain this by running `drupal site:status`).
 Drupal                         8.4.4

- Console version (you can obtain this by running `composer show | grep drupal/console`).

$ composer show | grep drupal/console
drupal/console                        1.5.0     The Drupal CLI. A tool to generate boilerplate code, interact with and debug Drupal.
drupal/console-core                   1.5.0     Drupal Console Core
drupal/console-dotenv                 0.3.0     Drupal Console Dotenv
drupal/console-en                     1.5.0     Drupal Console English Language
drupal/console-extend-plugin          0.9.2     Drupal Console Extend Plugin

- Console Launcher version (you can obtain this by running outside of a drupal site `drupal --version`).

- Steps to reproduce
See above.

- Include screen-shot or video whenever necessary.

### Solution
Don't output extra single quotes.

**Comment by LOBsTerr** [comment]
@bailey86  Thank you for your report. I have already fixed the issue in this PR  - https://github.com/hechoendrupal/drupal-console/pull/3691

in this commit - https://github.com/hechoendrupal/drupal-console/pull/3691/commits/508919ba1abe68b5b3ab3cdde9b6d91dfbeb6987

Try to use the latest dev version to avoid the issue, before the 1.5.1 has been released

**Comment by LOBsTerr** [comment]
@jmolivas we can close it, check my previous commet

**Comment by jmolivas** [comment]
Yes, let close since fixed already.
