### ISSUE TITLE
Get rid off the fake services

### ISSUE THREAD

**Issue by LOBsTerr** [hechoendrupal/drupal-console#3710]
### Issue title
Get rid off fake services like console.invalid_commands and etc.

### Problem/Motivation
We expect that all services are classes, but in this case we must handle service a special way.
### Solution
Create a service class which will handle fake services.
An example: https://github.com/hechoendrupal/drupal-console-core/blob/master/src/Utils/MessageManager.php

**Comment by jmolivas** [comment]
Another change we can do here is: 
- Use a container params instead of a service.
- Add a key-value service to get/set objects/arrays related to DC.

**Comment by LOBsTerr** [comment]
@jmolivas 

PR DC: https://github.com/hechoendrupal/drupal-console/pull/3759
PR Core: https://github.com/hechoendrupal/drupal-console-core/pull/304

Unfortunately, we can't use container params in that stage of the application, because the container is compiled already and parameterBag is set to frozen and it can't be changed. Plus it is not recommended to store such kind of information there.
I have created a new class ConsoleContainer, which similar to parameterBag. It will contain necessary application configuration. Currently I have replace invalid_commands service with a new implementation. If it is ok I will continue to replace the next services like:

- app.root
- site.path
- update.root
- console.root
- console.cache_key

and may be some others. I need to check the code.

**Comment by jmolivas** [comment]
@LOBsTerr Looks great to me.

The only thing that I am not sure is if the class name `ConsoleContainer` is descriptive enough.

How about using something like `KeyValue` or `KeyValueStorage`.

**Comment by LOBsTerr** [comment]
@jmolivas Honestly, I don't like KeyValue name, but I can't find the better name. Words like dictionary, bag, container probably are more confusing. So, let's  KeyValueStorage. I will update it

**Comment by jmolivas** [comment]
What I find confusing on `ConsoleContainer` is we already have a Drupal container object.

**Comment by LOBsTerr** [comment]
@jmolivas I have updated the PRs.

I think it is much evident what class does :) Please check PR and I will continue update fake services one by one, because some of them require a lot of changes.

**Comment by jmolivas** [comment]
@LOBsTerr  Looks great to me.

**Comment by LOBsTerr** [comment]
@jmolivas 
So, Actually I was confused a little bit. It is a normal way to use SplString as services.
For example:
- site.path
- update.root
- app.root

They are defined in Drupal.
In our case we use only console.cache_key as string, but there were no definition of this service. I have added it to the services.yml. 
So, we will use KeyValueStorage class only for invalid commands. I checked other console services. No other changes are required.

**Comment by jmolivas** [comment]
@LOBsTerr  Yes is a common practice to use `SplString`.

But I like the idea of the `KeyValueStorage` seems like easier to manage scale adding more values in the future, without the need of creating a new `SplString` service each time.

Can you think how this chage from `SplString` as services to `KeyValueStorage` can affect us?

**Comment by LOBsTerr** [comment]
@jmolivas I prefer to keep things as native as possible. In this case we introduce additional complexity, which I don't like. Let's keep it like this for now. I will try to check one more time our infrastructure. Maybe I will find other cases.
