### ISSUE TITLE
[generate:command] during the process of adding new services, impossible to exit using Enter.

### ISSUE THREAD

**Issue by LOBsTerr** [hechoendrupal/drupal-console#3714]
### Issue title

Adding new services causing infinite loop, until the moment we add all available services.
Other command, which are using ServicesTrait, EventsTrait and other can be also affected

### Problem/Motivation
Impossible to add some options using interaction

### How to reproduce
We add the first service, then we push "Enter" button ... and again and again.

**Details to include:**
- Console version 1.5.0

### Solution
The problem is when we push  "Enter" button on the first question we receive as result 0 and we exit the while loop, but if we enter the name of the first service and we push  "Enter" button we receive 1.
Because of that we can't exit the loop.
1) We can avoid default value for autocomplete value passing empty string
2) Figure out, why on the second question enter return 1

**Comment by jmolivas** [comment]
Fixed with PR at console-core hechoendrupal/drupal-console-core#292

**Comment by LOBsTerr** [comment]
@jmolivas The problem still exists

I have just merged the upstreams for core and DC. As you see I enter the first service and then can't exit using "Enter". I can't reopen the ticket, feel free to do it.

`Type the service name or use keyup or keydown.
This is optional, press enter to continue

 Enter your service [class_loader]:
 > class_loader
 Enter your service [kernel]:
 > 
 Enter your service [kernel]:
 > 
`

**Comment by jmolivas** [comment]
@LOBsTerr Did you sync and symlink `dupal-console` and `drupal-console-core` repos?

**Comment by LOBsTerr** [comment]
@jmolivas I have updated the code from references again. Still the same.

Yes, of course I have everything symlinked.
Check the screenshot. I insert the first command and the just press enter.
Also, there is output on symlinked directories.

![screenshot from 2018-01-22 20-39-29](https://user-images.githubusercontent.com/537500/35240685-86d88154-ffb4-11e7-8f1f-8065ee0c2e49.png)

**Comment by jmolivas** [comment]
My bad. I was hitting enter without adding the first one and I was able to exit the loop.

Got it fixed now. Sending a PR in a few minutes.

![](https://monosnap.com/file/EKiFroh1gj5dLQgQrB7SgB9BJQHuwn.png)

**Comment by LOBsTerr** [comment]
@jmolivas Super! Thanks. I tried to explain this, but probably used the wrong words. The next time I will add a screenshot directly!

**Comment by jmolivas** [comment]
@LOBsTerr  PR => https://github.com/hechoendrupal/drupal-console/pull/3728

**Comment by LOBsTerr** [comment]
@jmolivas I have checked. It works. Thanks

If you want I can handle in other places

**Comment by jmolivas** [comment]
@LOBsTerr that will be great. We only need to fix when this combination happens
```
$VAR_NAME = $this->getIo()->choiceNoList(
  $this->trans('...'),
  ARRAY_OPTIONS,
  null,
  true
);
```

When `null` is 3rd parameter and `true` is 4th 

We need to replace `null` as empty string `''`

**Comment by jmolivas** [comment]
@LOBsTerr  I found it at the folloging classes:
* src/Command/Role/DeleteCommand.php
* src/Command/Shared/FormTrait.php (twice)
* src/Command/Shared/ProjectDownloadTrait.php (twice)
* src/Command/Theme/UninstallCommand.php
* src/Command/Theme/InstallCommand.php
* src/Command/Generate/PluginBlockCommand.php

**Comment by LOBsTerr** [comment]
@jmolivas Thanks for information, I will fix it

**Comment by LOBsTerr** [comment]
@jmolivas  PR https://github.com/hechoendrupal/drupal-console/pull/3730
I have found another case:
src/Command/Migrate/ExecuteCommand.php

**Comment by koalacoder** [comment]
Hi there, I've the same problem on module install (drupal moi) and module download (drupa mod)
I can't exit the loop.

![screen shot 2018-04-03 at 11 36 03](https://user-images.githubusercontent.com/12950112/38241723-3ee63dc6-3733-11e8-8751-207d6c2302f6.png)

Many thanks for your work! This console is awesome.

**Comment by LOBsTerr** [comment]
@koalacoder I will take a look

**Comment by LOBsTerr** [comment]
@jmolivas Can you review this small PR https://github.com/hechoendrupal/drupal-console/pull/3855
