### ISSUE TITLE
[generate:controller] throws Exception after settings up controller class

### ISSUE THREAD

**Issue by LOBsTerr** [hechoendrupal/drupal-console#3719]
### Issue title
An exception happens when we run drupal gcon command

`
Recoverable fatal error: Object of class Closure could not be converted to string in /home/nikolay/www/drupal_console_site/vendor/symfony/console/Formatter/OutputFormatter.php on line 36 #0 /home/nikolay/www/drupal_console_site/web/core/includes/bootstrap.inc(566): _drupal_error_handler_real(4096, 'Object of class...', '/home/nikolay/w...', 36, Array)
#1 [internal function]: _drupal_error_handler(4096, 'Object of class...', '/home/nikolay/w...', 36, Array)
#2 /home/nikolay/www/drupal_console_site/vendor/symfony/console/Formatter/OutputFormatter.php(36): preg_replace('/([^\\\\]?)</', '$1\\<', Object(Closure))
#3 /home/nikolay/www/drupal_console_site/vendor/symfony/console/Helper/SymfonyQuestionHelper.php(90): Symfony\Component\Console\Formatter\OutputFormatter::escape(Object(Closure))
#4 /home/nikolay/www/drupal_console_site/vendor/symfony/console/Helper/QuestionHelper.php(131): Symfony\Component\Console\Helper\SymfonyQuestionHelper->writePrompt(Object(Drupal\Console\Core\Style\DrupalStyle), Object(Symfony\Component\Console\Question\Question))
#5 /home/nikolay/www/drupal_console_site/vendor/symfony/console/Helper/QuestionHelper.php(65): Symfony\Component\Console\Helper\QuestionHelper->doAsk(Object(Drupal\Console\Core\Style\DrupalStyle), Object(Symfony\Component\Console\Question\Question))
#6 /home/nikolay/www/drupal_console_site/vendor/symfony/console/Helper/QuestionHelper.php(413): Symfony\Component\Console\Helper\QuestionHelper->Symfony\Component\Console\Helper\{closure}()
#7 /home/nikolay/www/drupal_console_site/vendor/symfony/console/Helper/QuestionHelper.php(68): Symfony\Component\Console\Helper\QuestionHelper->validateAttempts(Object(Closure), Object(Drupal\Console\Core\Style\DrupalStyle), Object(Symfony\Component\Console\Question\Question))
#8 /home/nikolay/www/drupal_console_site/vendor/symfony/console/Helper/SymfonyQuestionHelper.php(49): Symfony\Component\Console\Helper\QuestionHelper->ask(Object(Symfony\Component\Console\Input\ArgvInput), Object(Drupal\Console\Core\Style\DrupalStyle), Object(Symfony\Component\Console\Question\Question))
#9 /home/nikolay/www/drupal_console_site/vendor/symfony/console/Style/SymfonyStyle.php(303): Symfony\Component\Console\Helper\SymfonyQuestionHelper->ask(Object(Symfony\Component\Console\Input\ArgvInput), Object(Drupal\Console\Core\Style\DrupalStyle), Object(Symfony\Component\Console\Question\Question))
#10 /home/nikolay/www/drupal-console-repositories/drupal-console-core/src/Style/DrupalStyle.php(144): Symfony\Component\Console\Style\SymfonyStyle->askQuestion(Object(Symfony\Component\Console\Question\Question))
#11 /home/nikolay/www/drupal-console-repositories/drupal-console/src/Command/Generate/ControllerCommand.php(218): Drupal\Console\Core\Style\DrupalStyle->askEmpty(Object(Symfony\Component\Console\Question\Question), Object(Closure))
#12 /home/nikolay/www/drupal_console_site/vendor/symfony/console/Command/Command.php(249): Drupal\Console\Command\Generate\ControllerCommand->interact(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /home/nikolay/www/drupal_console_site/vendor/symfony/console/Application.php(859): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 /home/nikolay/www/drupal_console_site/vendor/symfony/console/Application.php(206): Symfony\Component\Console\Application->doRunCommand(Object(Drupal\Console\Command\Generate\ControllerCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 /home/nikolay/www/drupal-console-repositories/drupal-console-core/src/Application.php(200): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 /home/nikolay/www/drupal-console-repositories/drupal-console/src/Application.php(64): Drupal\Console\Core\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 /home/nikolay/www/drupal_console_site/vendor/symfony/console/Application.php(125): Drupal\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 /home/nikolay/www/drupal-console-repositories/drupal-console/bin/drupal.php(89): Symfony\Component\Console\Application->run()
#19 /home/nikolay/www/drupal-console-repositories/drupal-console/bin/drupal(4): require('/home/nikolay/w...')
#20 {main}
Recoverable fatal error: Object of class Closure could not be converted to string in Symfony\Component\Console\Formatter\OutputFormatter::escape() (line 36 of /home/nikolay/www/drupal_console_site/vendor/symfony/console/Formatter/OutputFormatter.php).
`

### Problem/Motivation
Impossible to generate Controller

### How to reproduce
1) run drupal gcon
2) enter module 
3) Enter Controller class name

You will see the exception 

It happens, that we pass a validator function to askEmpty, which doesn't have this parameter

### Solution
No solutions for the moment, I need sometime to understand the logic of adding title. If someone can help or direct, it would be great.
From the first glance, it looks like we just need to remove validation function or use ask instead of askEmpty.

### Version

Drupal Console 1.5.0

**Comment by jmolivas** [comment]
@LOBsTerr I will take care of this one thanks for reporting it.

**Comment by jmolivas** [comment]
Fixed with PR https://github.com/hechoendrupal/drupal-console/pull/3722

Related PR at `console-core` https://github.com/hechoendrupal/drupal-console-core/pull/292
