### ISSUE TITLE
[locale:language:add] Enhancement

### ISSUE THREAD

**Issue by djenniex-bene** [hechoendrupal/drupal-console#3736]
### Issue title

`locale:language:add` command only allows one language as an argument.

### Problem/Motivation

Having to run a seperate command for each language can become cumbersome and repetitive if there is a large number of languages to install. Other commands, such as `module:install` allow multiple modules separated by spaces to be installed at the same time. There should be some consistency between modules and how they install multiple things.

### Solution

Change the LanguageAddCommand.php -> language argument to accept an `InputArgument::Array`. Then loop through the arguments and install each language.

**Comment by LOBsTerr** [comment]
PR https://github.com/hechoendrupal/drupal-console/pull/3738
Now we can pass multiple arguments as a codes and as names.
I also have add the check for the case when the language already exists.

Further improvements

1.  Show a proper message / warning, when we add/miss one or multiple languages
2. Show a warning that some languages have been already installed
3. Update the documentation / translation files accordingly

**Comment by LOBsTerr** [comment]
1) Update the messages - #3738
2) Update translations https://github.com/hechoendrupal/drupal-console-en/pull/158

**Comment by LOBsTerr** [comment]
Closing the issue. Feel free to reopen if you have new proposals
