### ISSUE TITLE
Console alias duplicate

### ISSUE THREAD

**Issue by ludohartzema** [hechoendrupal/drupal-console#3746]
### Console alias duplicate

On my local environments I get aliases for `create:roles (crr)` & `cron:release (cror,crr)`.
Both suggest `crr` as alias, but `create:roles` seems to be the default action for this duplicate alias.

**Comment by jmolivas** [comment]
Nice catch and thanks for reporting it. I can confirm this is a bug:
```
drupal | grep crr
  create:roles (crr)                      Create dummy roles for your Drupal 8 application.
  cron:release (cror,crr)                 Release cron system lock to run cron again
```

I found the alias definition at this file on the `console-core` repository:
https://github.com/hechoendrupal/drupal-console-core/blob/master/config/aliases.yml#L8-L9

**Comment by jmolivas** [comment]
@LOBsTerr issue at console-core repository:
https://github.com/hechoendrupal/drupal-console-core/blob/master/config/aliases.yml#L16-L17

**Comment by jmolivas** [comment]
@LOBsTerr we need to remove the aliases mentioned definitions on this console-core file https://github.com/hechoendrupal/drupal-console-core/blob/master/config/aliases.yml to have both fixed.

**Comment by LOBsTerr** [comment]
@jmolivas PR https://github.com/hechoendrupal/drupal-console-core/pull/295

**Comment by LOBsTerr** [comment]
Closing this one. Feel free to re-open if still happening after updating to the latest version.
