### ISSUE TITLE
ConfigurationManager->readTarget() should use getSites()

### ISSUE THREAD

**Issue by nvaken** [hechoendrupal/drupal-console#3761]
`ConfigurationManager->readTarget()` tries to access it's `$sites` property directly. It should use `getSites()` because this method checks if `$this->sites` has been instantiated and if not it will instantiate the property.

**Comment by LOBsTerr** [comment]
PR https://github.com/hechoendrupal/drupal-console-core/pull/305

**Comment by nvaken** [comment]
Looking good! Thanks

**Comment by nvaken** [comment]
Oh, sorry, might need to keep this open, since the PR is not yet merged.
