### ISSUE TITLE
Generating a content entity creates a (entity).page.inc file which triggers errors after a cache clear

### ISSUE THREAD

**Issue by kevinquillen** [hechoendrupal/drupal-console#3762]
Drupal console version: 1.5.0
Command: `generate:entity:content`

Generating an entity creates an `entity.page.inc` file which is referenced by a hook_theme autogenerated by the command, which creates an error after cache clear like this:

`"Drupal\Core\Render\Markup":1:{s:9:"*string";s:162:"include_once(): Failed opening '/var/www/mysite/docroot/modules/custom/mymodule/room_entity.page.inc' for inclusion`

The file exists, as I just ran the generate command. I don't need it for my case and just removed the hook_theme hook and file. My data will be provided by REST endpoint only.

**Comment by LOBsTerr** [comment]
@kevinquillen
I'm trying to reproduce the issue, but with any success.
Can you provide additional information about the steps?
Can you attach the code of /var/www/mysite/docroot/modules/custom/mymodule/room_entity.page.inc ? 
Can you show me inline presentation of your command?
For this you need to update config file for DC  (console/config.yml)  and set generate-inline: true

**Comment by LOBsTerr** [comment]
Closing the issue for now, feel free to reopen it.
