### ISSUE TITLE
[generate:entity:content] Issues with fields on a generated content entity

### ISSUE THREAD

**Issue by kevinquillen** [hechoendrupal/drupal-console#3764]
I've generated a content entity (no revisionable) and noticed a few things.

One, the name field that is generated by console is not required in the form. I had to edit my entity definition and on the name field, add:

`->setRequired(TRUE)`

I feel like at a baseline it should be treated like the node title is, required. A thing needs a name.

I see extra fields too that don't appear on the generated form:

```
    $fields['status'] = BaseFieldDefinition::create('boolean')
      ->setLabel(t('Published'))
      ->setDescription(t('A room that is published will appear in Spacefinder.'))
      ->setDefaultValue(TRUE);

    $fields['created'] = BaseFieldDefinition::create('created')
      ->setLabel(t('Created'))
      ->setDescription(t('The time that the entity was created.'));

    $fields['changed'] = BaseFieldDefinition::create('changed')
      ->setLabel(t('Changed'))
      ->setDescription(t('The time that the entity was last edited.'));
```

However, for status, lets say, I had to make this edit:

```
    $fields['status'] = BaseFieldDefinition::create('boolean')
      ->setLabel(t('Published'))
      ->setDescription(t('A room that is published will appear in Spacefinder.'))
      ->setDefaultValue(TRUE)
      ->setDisplayOptions('form', [
        'type' => 'checkbox',
        'weight' => -3,
      ])
      ->setDisplayConfigurable('form', TRUE);
```

Otherwise I would have no way to toggle published or unpublished on the form. 

Shouldn't both name and status come out of the box like that? I think it can be confusing otherwise.

**Comment by LOBsTerr** [comment]
@kevinquillen I have added the proposed changes. I agree with you users must have it by default

PR https://github.com/hechoendrupal/drupal-console/pull/3775

**Comment by LOBsTerr** [comment]
Closing the issue. Feel free to reopen it if you have any new ideas

**Comment by crickford** [comment]
I'm getting errors on the form display page for generated content entities after this update - looks like
`'type' => 'checkbox'` is not a valid field widget type, should be changed to `'type' => 'boolean_checkbox'`

**Comment by LOBsTerr** [comment]
PR https://github.com/hechoendrupal/drupal-console/pull/3795
