### ISSUE TITLE
generate:module generates invalid *.info.yml files

### ISSUE THREAD

**Issue by nvaken** [hechoendrupal/drupal-console#3765]
Note the suffixing `'` on the multi-word strings (name and description):  

```
name: 'My Module''
type: module
description: 'My Module description'' 
core: 8.x
package: 'mypackage'
dependencies:
  - my_other_module
```

**Comment by LOBsTerr** [comment]
@nvaken
This issue was reported already here: https://github.com/hechoendrupal/drupal-console/issues/3707

I have fixed it here https://github.com/hechoendrupal/drupal-console/commit/508919ba1abe68b5b3ab3cdde9b6d91dfbeb6987

In this PR https://github.com/hechoendrupal/drupal-console/pull/3691

**Comment by nvaken** [comment]
Whoops, sorry @LOBsTerr, I'm usually a bit better in finding existing issues. :-)
