### ISSUE TITLE
Missing commands on installation

### ISSUE THREAD

**Issue by martincanon** [hechoendrupal/drupal-console#3767]
#Problem/Motivation
I'm migrating a Drupal 6 to Drupal 8 site and need Drupal Console to do it.

How to reproduce
- Drupal version 8.4.4
- Console version 1.5.0 
- Console Launcher version 1.5.0

I installed DC with composer, as instructed in DC documentation.

When updating with composer I get:

Dependency "composer/installers" is also a root requirement, but is not explicitly whitelisted. Ignoring.
Dependency "webflo/drupal-finder" is also a root requirement, but is not explicitly whitelisted. Ignoring.
Dependency "webmozart/path-util" is also a root requirement, but is not explicitly whitelisted. Ignoring.

Then, I got the plugin.manager.display.views error and fixed it with https://github.com/hechoendrupal/drupal-console/pull/3688 patch.

Now I get this when I execute the drupal console from within the drupal site:
[ERROR] SQLSTATE[HY000] [2002] No such file or directory

I changed the settings.php file host to 127.0.0.1
The error doesn't go away. Also, several commands are missing.

<img width="821" alt="screen shot 2018-02-07 at 11 28 05" src="https://user-images.githubusercontent.com/8813631/35928007-15520d82-0bfa-11e8-8980-36e896e77e92.png">

Thanks for your help.

FOUND THE ANSWER HERE: https://drupal.stackexchange.com/questions/99446/ive-got-pdoexception-sqlstatehy000-2002-no-such-file-or-directory-when-u/180924

**Comment by jmolivas** [comment]
@martincanon thanks for reporting and updating it with the solution.

I added the issue and fix to the [FAQ of the docs](https://docs.drupalconsole.com/en/drupal_console_faq/installation-problems.html )
