### ISSUE TITLE
[generate:plugin:migrate:data_parser] [New Command] Command to create data parser plugin for migration.

### ISSUE THREAD

**Issue by joshirohit100** [hechoendrupal/drupal-console#3773]
Command to create the data parser plugin for the migration.

**Comment by joshirohit100** [comment]
Initially i though for this to be part of migrate_plus module but then I checked the module and as there was no console command in the module so I created it here. Also as migrate_plus module is kind of a must rquirement for migration, I think this is right place to add this command.

**Comment by jmolivas** [comment]
PR https://github.com/hechoendrupal/drupal-console/pull/3774 merged
