### ISSUE TITLE
[cache:rebuild all] produces errors "array_key_exists() expects parameter 2 to be array, null given"

### ISSUE THREAD

**Issue by littlethoughts** [hechoendrupal/drupal-console#3786]
### Problem/Motivation
When running drupal cr all, the following error message appears multiple times:

`Warning: array_key_exists() expects parameter 2 to be array, null given in Drupal\Console\Core\Utils\ChainDiscovery-&gt;getChainCommands() (line 191 of /root/vendor/drupal/console-core/src/Utils/ChainDiscovery.php).     
                           Drupal\Console\Core\Utils\ChainDiscovery-&gt;getChainCommands() (Line: 632)             
                           Drupal\Console\Core\Application-&gt;registerChainCommands() (Line: 230)                                        
                           Drupal\Console\Core\Application-&gt;loadCommands() (Line: 116)                                                 
                           Drupal\Console\Core\Application-&gt;doRun(Object, Object) (Line: 64)                                           
                           Drupal\Console\Application-&gt;doRun(Object, Object) (Line: 117)                                               
                           Symfony\Component\Console\Application-&gt;run() (Line: 89)                                                     
                           require(&#039;/root/vendor/drupal/console/bin/drupal.php&#039;) (Line: 4)`

### How to reproduce

**Versions:**
- Drupal version 8.3.7.
- Console version 1.6.0.
- Console Launcher version 1.6.0.
- Steps to reproduce: Run command `drupal cr all`

**Comment by jmolivas** [comment]
@littlethoughts  I was not able to replicate on my local using `8.4.3` will check with `8.3.7` and add a new comment.

![](https://monosnap.com/file/mP0tBvvVoskp0R9KYcBXyKgEI7hMWb.png)

**Comment by littlethoughts** [comment]
Thanks for checking, I noticed the problems are some chain command files. I think they were added to the project with an older version of the drupal console, before it was added in vendor directory by composer. So it was still picking up files from the root `console/chain/` directory.
After removing these files the problem is solved:
all in `console/chain/`
`update-command-data.yml`
`form-sample.yml`
`quick-start-db.yml`
`create-data.yml`
`quick-start.yml`
`sample.yml`
`quick-start-db-env.yml`
`site-update.yml`
`update-gitbook.yml`

**Comment by littlethoughts** [comment]
You can also fix it by running `drupal init`.

I have one question regarding this, which was not clear from [the docs](https://hechoendrupal.gitbooks.io/drupal-console/content/en/using/how-to-copy-configuration-files.html): What exactly do I need the configuration files for? What can be configured? Is it required or just if you want to use certain features?
It also says to copy configuration files to your local computer. But then the command suggests to install it in your project root as well. I don't exactly see the point of copying config to my local computer as it is out of version control then.
Sorry for the many questions, should this rather be a feature request to update the docs?

**Comment by novia713** [comment]
i also experienciencing this issue also, 
not found yet how to solve it
![captura de pantalla 2018-03-02 a las 10 10 40](https://user-images.githubusercontent.com/423279/36891473-11066402-1e02-11e8-81b4-1c153d6b35f7.png)
