### ISSUE TITLE
[console] Malformed inline YAML string

### ISSUE THREAD

**Issue by Erikdekamps** [hechoendrupal/drupal-console#3791]
### Malformed inline YAML string

> [Fri Feb 16 09:08:11.811611 2018] [:error] [pid 17830] [client ::1:53545] Uncaught PHP Exception Drupal\\Core\\Extension\\InfoParserException: "Unable to parse modules/custom/paragraphs_columns/modules/paragraphs_columns_images/paragraphs_columns_images.info.yml Malformed inline YAML string: 'Paragraphs Columns Images'' at line 1 (near "name: 'Paragraphs Columns Images''")." at /Applications/AMPPS/www/home/drupal/d8/nested-paragraphs/web/core/lib/Drupal/Core/Extension/InfoParserDynamic.php line 25

### Problem/Motivation
When generating a module (as feature) it seems that the *.info.yml file get's filled with the following:

`name: 'Paragraphs Columns Images''
type: module
description: 'Paragraphs Columns Images''
core: 8.x
package: 'Paragraphs'`

**Details to include:**
- PHP 7.0.6 (cli)

### How to reproduce
- Generate a new feature.
- Check the module info yml file.

**Details to include:**
- Drupal version: 8.4.4
- Console version: 1.5.0 
- Console Launcher version: 1.5.0

**Comment by LOBsTerr** [comment]
@Erikdekamps It was fixed already. Please, update the module to the 1.6.0. Closing this issue

This issue was reported already here: https://github.com/hechoendrupal/drupal-console/issues/3707
In this PR https://github.com/hechoendrupal/drupal-console/pull/3691
