### ISSUE TITLE
Config Export Command on Entities

### ISSUE THREAD

**Issue by albertski** [hechoendrupal/drupal-console#3794]
It would be nice to be able to perform a `config:export:taxonomy:type [term name]` or  `config:export:paragraph:type [paragraph name]`.

Currently, it seems like we can only do nodes types with `config:export:content:type`.

**Comment by LOBsTerr** [comment]
PR https://github.com/hechoendrupal/drupal-console/pull/3875
PR for the translation - https://github.com/hechoendrupal/drupal-console-en/pull/205

@jmolivas I recommend mark command config:export:content:type as deprecated and remove it in the future. So, we will support only generic command.

**Comment by LOBsTerr** [comment]
It has been merged, I close it
