### ISSUE TITLE
Error when run "drupal help COMMAND"

### ISSUE THREAD

**Issue by drugan** [hechoendrupal/drupal-console#3808]
**UPDATE:** The error is disappered after installing the `sqlite`. if you have the same error please check whether the `sqlite` driver is installed for your PHP version:

 `php -i | grep sqlite`

if not, run this:

`sudo apt-get install php7.0-sqlite3`

So, the only question is left why the `drupal help COMMAND` requires `sqlite` to be installed. Then the issue could be closed, I "think". Sorry for disturbing all of you.
_______________________________________________________________________________

Hi, I am on Ubuntu 16.04 LTS and use this version of the Drupal Console:
```
Drupal Console Launcher version 1.6.1
Drupal Console version 1.6.1
```
`php -v`

```
PHP 7.0.25-0ubuntu0.16.04.1 (cli) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.25-0ubuntu0.16.04.1, Copyright (c) 1999-2017, by Zend Technologies
    with Xdebug v2.6.0, Copyright (c) 2002-2018, by Derick Rethans

```

I have the issue every time when I run `drupal help COMMAND` I get this:

![drupal-help-error](https://user-images.githubusercontent.com/3609840/36664547-b5be6e30-1aed-11e8-8565-ae7705ae2966.png)

**Comment by jmolivas** [comment]
Closing this one. Feel free to re-open if still happening after updating to the latest version.

**Comment by jmolivas** [comment]
@drugan Thanks for updating the issue
