### ISSUE TITLE
PostgreSQL Restore command malformed

### ISSUE THREAD

**Issue by dleras** [hechoendrupal/drupal-console#3816]
### Problem/Motivation

The restore command with postgres seems to not be well formatted. In the file vendor/drupal/console/src/Command/Database/RestoreCommand.php the command to restore a backup databse is :

'PGPASSWORD="%s" ' . $catCommand . 'psql -w -U %s -h %s -p %s -d %s' (catcommand also contains a token %s)

with the following parameters :
$file,
$databaseConnection['password'],
$databaseConnection['username'],
$databaseConnection['host'],
$databaseConnection['port'],
$databaseConnection['database']

The password is injected in the catcommand token and not in the PGPASSWORD token.

### Solution

The command should be the following  : 
$catCommand . 'PGPASSWORD="%s" psql -w -U %s -h %s -p %s -d %s'

**Comment by LOBsTerr** [comment]
@dleras Thank you for the proposed solution.
I have create PR https://github.com/hechoendrupal/drupal-console/pull/3849

**Comment by LOBsTerr** [comment]
It was merged
