### ISSUE TITLE
[Console] You have requested a non-existent service "system.config_subscriber"

### ISSUE THREAD

**Issue by robertbenparkinson** [hechoendrupal/drupal-console#3823]
# [Console] You have requested a non-existent service "system.config_subscriber"

## Console Issue Group##

Yesterday I tried setting up Drupal Console on my laptop for the first time. I used the Windows Installer for the Global portion and Composer to install the local site files. Every time I type 'Drupal' in bash it partially loads and at the bottom I get a the "You have requested a non-existent service "system.config_subscriber"" warning. 

Also most of the commands, like generate:module, are missing.  I hope the two problems are related.

Any help would be appreciated. 

Here is my set up:

Drupal 8.5
drupal/console                                   1.7.0              
drupal/console-core                          1.7.0             
drupal/console-en                             1.7.0              
drupal/console-extend-plugin          0.9.2              
Windows 10 
Ubuntu 16.04.3

![error](https://user-images.githubusercontent.com/5824662/37354417-8229ac68-26d9-11e8-84c3-70fb455c3f94.png)

**Comment by jmolivas** [comment]
@robertbenparkinson Fixed with this PR https://github.com/hechoendrupal/drupal-console/pull/3820

This fix will be included in the next release.

**Comment by robertbenparkinson** [comment]
Cool. That worked. Thanks!
