### ISSUE TITLE
Error: Call to undefined method Drupal\Console\Command\Debug\ThemeKeysCommand::getIo()

### ISSUE THREAD

**Issue by kabanon** [hechoendrupal/drupal-console#3831]
### Error: Call to undefined method Drupal\Console\Command\Debug\ThemeKeysCommand::getIo()

[ debug:theme:keys ] raise a php error 
`Call to undefined method Drupal\Console\Command\Debug\ThemeKeysCommand::getIo()`

### Problem/Motivation
Error occurs with drupal console 1.7.0
`php vendor/bin/drupal -V
Drupal Console version 1.7.0`

### How to reproduce
`php vendor/bin/drupal dtk
Error: Call to undefined method Drupal\Console\Command\Debug\ThemeKeysCommand::getIo() in .../vendor/drupal/console/src/Command/Debug/ThemeKeysCommand.php on line 83 #0 .../vendor/drupal/console/src/Command/Debug/ThemeKeysCommand.php(58): Drupal\Console\Command\Debug\ThemeKeysCommand->themeKeysList()
#1 .../vendor/symfony/console/Command/Command.php(252): Drupal\Console\Command\Debug\ThemeKeysCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 .../vendor/symfony/console/Application.php(964): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 .../vendor/symfony/console/Application.php(248): Symfony\Component\Console\Application->doRunCommand(Object(Drupal\Console\Command\Debug\ThemeKeysCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 .../vendor/drupal/console-core/src/Application.php(185): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 .../vendor/drupal/console/src/Application.php(64): Drupal\Console\Core\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 .../vendor/symfony/console/Application.php(148): Drupal\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 .../vendor/drupal/console/bin/drupal.php(89): Symfony\Component\Console\Application->run()
#8 .../vendor/drupal/console/bin/drupal(4): require('/var/www/vhosts...')
#9 {main}
Error: Call to undefined method Drupal\Console\Command\Debug\ThemeKeysCommand::getIo() in Drupal\Console\Command\Debug\ThemeKeysCommand->themeKeysList() (line 83 of .../vendor/drupal/console/src/Command/Debug/ThemeKeysCommand.php).
`

### Solution
Pull request in progress

**Comment by kabanon** [comment]
See PR [3832](https://github.com/hechoendrupal/drupal-console/pull/3832)

**Comment by LOBsTerr** [comment]
@kabanon Thank you for your contribution!
