### ISSUE TITLE
drupal site:mode dev doesn't switch off twig cache

### ISSUE THREAD

**Issue by LOBsTerr** [hechoendrupal/drupal-console#3854]
### Problem/Motivation
Disable the twig cache, because we don't need in the development environment

### How to reproduce
`drupal site:mode dev`

```
parameters:
    twig.config: { debug: true, auto_reload: true, cache: true }
```
should be
```
parameters:
    twig.config: { debug: true, auto_reload: true, cache: false }
```

### Solution
Set twig cache to false

**Comment by LOBsTerr** [comment]
@jmolivas PR https://github.com/hechoendrupal/drupal-console-core/pull/339

**Comment by ademarco** [comment]
:+1: this would be very useful indeed!

**Comment by LOBsTerr** [comment]
It was merged
