### ISSUE TITLE
drupal generate:plugin:migrate:source should include "source_module" definition

### ISSUE THREAD

**Issue by kalevitan** [hechoendrupal/drupal-console#3857]
### Problem/Motivation
Migrate API requires all source plugins have a "source_module" defined in the annotation.

**Details to include:**
-  Since it's a requirement, and Drupal throws an error if not present, I suggest that a prompt be added to include a source module when generating a migrate source plugin.

**Details to include:**
- Drupal version 8.5.1
- Console version 1.80

### Example Output Result
```
/**
 * field_collection_item source.
 *
 * @MigrateSource(
 *   id = "field_collection_item",
 *   source_module = "field_collection"
 * )
 */
```

**Comment by LOBsTerr** [comment]
@jmolivas PR https://github.com/hechoendrupal/drupal-console/pull/3858

I have fixed this issue + improved and fixed the code a little bit

**Comment by LOBsTerr** [comment]
Merged
