### ISSUE TITLE
Command module:install does not execute the install after adding modules to array

### ISSUE THREAD

**Issue by andrade1379** [hechoendrupal/drupal-console#3861]
### Command module:install does not execute the install after adding modules

Hey guys, just did a fresh install of Drupal 8 and I’m trying to install my new modules using command `drupal moi` I get the usual option to select the modules that I want to install but when I hit `<return>` It just keeps trying to add more modules.

My set up:
```
"drupal/console": "^1.0.2”,
 "drupal/core": "~8.5.1",
``

**Comment by LOBsTerr** [comment]
It has been fixed in this pr https://github.com/hechoendrupal/drupal-console/pull/3855/files

In this issue https://github.com/hechoendrupal/drupal-console/issues/3714
