### ISSUE TITLE
[config:export] Warnings on language/XX directories

### ISSUE THREAD

**Issue by Omegadela** [hechoendrupal/drupal-console#3862]
### Problem/Motivation
When using Drupal Console to export configuration made in development environments there should be no unnecessary warnings.  

### How to reproduce
- Drupal version : 8.5.1  
- Console version : 1.8.0  
- Run `drupal config:export` command on a site with multiple languages and a configuration already exported with the same command.  
PS: using [Lando](https://github.com/lando/lando) here, but not relevant for the issue.  

![image](https://user-images.githubusercontent.com/6665478/38623833-eef22850-3da6-11e8-888b-f012ef8b3bba.png)

- Known workarounds : manually delete `sync` folder before the command.

### Solution
Use Symfony's FileSystem component for `unlink` and `mkdir`

**Comment by Omegadela** [comment]
PR #3863

**Comment by LOBsTerr** [comment]
@Omegadela Thanks, it was merged
