### ISSUE TITLE
[generate:plugin:views:field] overwrites <module-name>.views.inc

### ISSUE THREAD

**Issue by com2** [hechoendrupal/drupal-console#3882]
### Problem/Motivation
After using generate:plugin:views:field to generate the first, I wanted also to add a second field. Apparently this is not supported because I saw in modules/custom/my_module/my_module.views.inc only the last field defined. As Drupal 8 beginner I am not sure if I am right, but I think it should append a second field in stead of overwriting the previous. Or at least it could politely give a warning that a second field is not supported. 

### How to reproduce
Generate a module and then two views field plugins:

> drupal generate:module --module="My Module" --machine-name=my_module --module-path=modules/custom --description="My Module description" --core=8.x --package=Other
> drupal generate:plugin:views:field --module=my_module --class=my_first_field_class --title="My first field title" --description="My first field description"
> drupal generate:plugin:views:field --module=my_module --class=my_second_field_class --title="My second field title" --description="My second field description"

**Details:**
- Drupal 8.5.3
- Console 1.8.0

**Comment by LOBsTerr** [comment]
@com2 I have checked the version 1.8.0 (the latest one). We append code to [module].view.inc file the code each time the command [generate:plugin:views:field] is executed.
```
$this->renderFile(
            'module/module.views.inc.twig',
            $this->extensionManager->getModule($module)->getPath() . '/' . $module . '.views.inc',
            $parameters,
            FILE_APPEND
        );
```
and normally then you need to merge it manually.

Anyway, I think it would be nice to have opportunity to add multiple fields

**Comment by LOBsTerr** [comment]
@com2 I didn't mention that if you have already views data hook implemented, we have a check and it will show the warning 
```
[WARNING] The hook views data was already implemented in module "sdsd". Please, merge the code manually
```

**Comment by LOBsTerr** [comment]
pr - https://github.com/hechoendrupal/drupal-console/pull/3883
translations pr - https://github.com/hechoendrupal/drupal-console-en/pull/208

**Comment by enzolutions** [comment]
Thanks @LOBsTerr
