### ISSUE TITLE
[database:dump] does not escape dollar sign

### ISSUE THREAD

**Issue by Zeviore** [hechoendrupal/drupal-console#3888]
### Problem/Motivation
The mysqldump command generated fails when the password contains a dollar sign. If i alter the command manually and escape the dollar sign with a backslash the mysqldump command works as expected.

### How to reproduce
- Drupal version: 8.5.3
- Console version: 1.8.0
- Steps to reproduce:
Install a drupal site and configure the database with a username and password with a dollar sign
Run database:dump

### Solution
escapeshellcmd (http://php.net/manual/en/function.escapeshellcmd.php) could be used

**Comment by LOBsTerr** [comment]
PR - https://github.com/hechoendrupal/drupal-console/pull/3906
PR for translations - https://github.com/hechoendrupal/drupal-console-en/pull/209

The code still requires some improvements. It can be done in separate tickets.
For example
1) We sometimes use ShellProcess class, sometime ProcessBuilder.
2) We need to split logic to separate classes for mysql and pgsql classes.
3) Move the logic to separate services, our commands contain to much logic

**Comment by LOBsTerr** [comment]
It has been merged
