### ISSUE TITLE
Drupal console crash on import with skip-uuid

### ISSUE THREAD

**Issue by julfabre** [hechoendrupal/drupal-console#3893]
### Drupal console crash on import with skip-uuid

* `./vendor/bin/drupal config:import --directory="./sync" --skip-uuid --uri=dev`
when you use drupal console to import configuration it's crash if you use --skip-uuid.
Because of the class " \Drupal\Console\Override\StorageComparer " that does'nt exist in recent builds.

up to  1.6.0 you use this class " \Drupal\Console\Override\StorageComparer " 
from 1.7.0 it's another system.

**Details to include:**
- Drupal version  8.5.3
- Console version 1.8

### Solution
I think it's just an update on this file src\Command\Config\ImportCommand.php L100 to 102
Or it's can be  adding getSubscribedEvents on src\Override\ConfigSubscriber.php
I'm not really sure. I've don't test one or another solution.

**Comment by arturolinares** [comment]
`--skip-uuid` should not be used any more. Instead you can configure it in your `console/config.yml`:
```
application:
...
  overrides:
    config:
      skip-validate-site-uuid: true
```

See https://weknowinc.com/blog/how-install-drupal-8-existing-configuration

**Comment by marcelovani** [comment]
If you prefer to run a command to set this config rather than editing the file use
`drupal settings:set overrides.config.skip-validate-site-uuid true`

**Comment by matias-miranda** [comment]
I tried configuring `console/config.yml` and also tried `drupal settings:set ...` without success:

```
Error: Class &#039;\Drupal\Console\Override\StorageComparer&#039; not found in Drupal\Console\Command\Config\ImportCommand->execute() (line 105 of [...]/vendor/drupal/console/src/Command/Config/ImportCommand.php).
```

**Comment by ericmorand** [comment]
And what about updating the docs?

**Comment by marcelovani** [comment]
https://github.com/hechoendrupal/drupal-console-book/pull/399/files

**Comment by enzolutions** [comment]
Thanks @marcelovani for updating the documentation

**Comment by stephang** [comment]
> --skip-uuid should not be used any more. Instead you can configure it in your console/config.yml:

I am not sure if this really fixes the issue. If `--skip-uuid` should not be used anymore, in my understanding it should be removed or somehow be deprecated.

> ... use `drupal settings:set overrides.config.skip-validate-site-uuid true`

Thanks for updating the docs, very nice. However, using this feature is tricky, because there's almost no documentation on how Console is generally configured. Please point out if I am missing some chapter in the [Console Book](https://github.com/hechoendrupal/drupal-console-book/).
