### ISSUE TITLE
drupalconsole installation for Drupal 8.5+ fails citing symfony conflicts in composer.lock

### ISSUE THREAD

**Issue by itsmeguru786** [hechoendrupal/drupal-console#3895]
### drupalconsole installation do not succeed with Drupal 8.5.3+

The issue title should comply with the following structure:

[ *console* ] 

### Problem/Motivation

Composer based installation attempt fails for Drupal 8.5.3 though same approach for Drupal 8.3.7 succeeds and drupalconsole commands executable.

**Details to include:**
- Problem with 8.5.3 versions but older versions Drupal 8.3.7+ versions same installation approach works with no conflicts.

### How to reproduce
Attempt to run the composer installation command:

Sowmyas-MacBook-Pro:drupal-8.5.3 sowmyaharish$> composer require drupal/console:~1.0 --prefer-dist --optimize-autoloader

**Details to include:**
    _For Drupal 8.3.7_
     - Sowmyas-MacBook-Pro:drupal-8.3.7 sowmyaharish$ drupal list
     - Drupal Console Launcher version 1.8.0
     - Drupal Console version 1.8.0

   _For Drupal 8.5.3_
      - Installation request for drupal/console ~1.0 -> satisfiable by drupal/console[1.0.0, 1.0.0-alpha1, 1.0.0-alpha2, 1.0.0-beta1, 1.0.0-beta2, 1.0.0-beta3, 1.0.0-beta4, 1.0.0-beta5, 1.0.0-rc1, 1.0.0-rc10, 1.0.0-rc11, 1.0.0-rc12, 1.0.0-rc13, 1.0.0-rc14, 1.0.0-rc15, 1.0.0-rc16, 1.0.0-rc17, 1.0.0-rc18, 1.0.0-rc19, 1.0.0-rc2, 1.0.0-rc20, 1.0.0-rc21, 1.0.0-rc22, 1.0.0-rc23, 1.0.0-rc24, 1.0.0-rc25, 1.0.0-rc26, 1.0.0-rc3, 1.0.0-rc4, 1.0.0-rc5, 1.0.0-rc6, 1.0.0-rc7, 1.0.0-rc8, 1.0.0-rc9, 1.0.1, 1.0.2, 1.1.0, 1.1.1, 1.2.0, 1.3.0, 1.3.1, 1.3.2, 1.4.0, 1.5.0, 1.6.0, 1.6.1, 1.7.0, 1.8.0].
    - **Conclusion: don't install symfony/console v3.4.4**
   - drupal/console-core v1.0.0-rc8 requires symfony/process ~2.8 -> satisfiable by symfony/process[2.8.x-dev].
    - symfony/process 2.7.x-dev conflicts with symfony/console[v3.4.4].
    - symfony/process 2.8.x-dev conflicts with symfony/console[v3.4.4].
    - symfony/process 3.0.x-dev conflicts with symfony/console[v3.4.4].
    - symfony/process 3.1.x-dev conflicts with symfony/console[v3.4.4].
    - Installation request for symfony/console (locked at v3.4.4, required as ~3.4.0) -> satisfiable by symfony/console[v3.4.4].

Installation failed, reverting ./composer.json to its original content.

Note: Would there be a workaround to get this working with 8.5.3 to setup drupalconsole for a existing project using Drupal version 8.5.3. Please advice.

**Comment by shelane** [comment]
Similar issue:
https://github.com/hechoendrupal/drupal-console/issues/3885

**Comment by itsmeguru786** [comment]
Thanks @shelane . For some reason, my search for issue for workaround didnt found mentioned #3885. I will close this issue and follow mentioned thread for any suggestion.

**Comment by bigsony** [comment]
I get this same thing when I try to install drupalconsole.
