### ISSUE TITLE
any generated custom command is not found

### ISSUE THREAD

**Issue by yakoub** [hechoendrupal/drupal-console#3904]
### Issue title  
[generate:command] generated is not found  

### Problem/Motivation  
any generated custom command is not found  

### How to reproduce  
- clone drupal 8.5.4 
- run composer install  
- install the website  
- run composer require drupal/console  
- run vendor/bin/drupal gm --module="mod1"  
- run vendor/bin/drupal generate:command --extension="mod1" ... --name="c1"  
- run vendor/bin/drupal module:install mod1
- run vendor/bin/drupla mod1:c1

produced error :  [ERROR] Command "mod1:c1", is not a valid command name.

**Comment by yakoub** [comment]
notes :  
- i install the website using web install.php and not console command
- i use multisite method by creating : sites/sites.php 
for example :  
`<?php
$sites = array(
  'web1.fedora.lan' => 'web1',
);
`
and create directory sites/web1

i really don't think this is the problem

**Comment by jmolivas** [comment]
@yakoub is your site installed?

**Comment by yakoub** [comment]
@jmolivas  site definitely installed .

**Comment by yakoub** [comment]
can someone please confirm whether the bug happens at their environment or not ?

**Comment by jmolivas** [comment]
@yakoub can you try 
```
drupal list
```
and also
```
drupal generate
```
and paste output or share ans screenshot

**Comment by jmolivas** [comment]
@yakoub is this  multisite installation? could you try 
```
drupal debug:site
```
also to interact with a multisite installation identified as `web1.fedora.lan` use the `uri` option
```
drupal --uri=web1.fedora.lan
```

**Comment by yakoub** [comment]
for command debug:site i get :  [WARNING] No sites defined.  

adding --uri doesn't change outcome .  

contents of my sites.php :  
<?php
$sites = array(
  'web1.fedora.lan' => 'default',
  'portal.fedora.lan' => 'portal',
  'portal2.fedora.lan' => 'portal2',
);
?>

**Comment by yakoub** [comment]
attached output of ` vendor/bin/drupal --uri="web1.fedora.lan" list `
[out.txt](https://github.com/hechoendrupal/drupal-console/files/2176697/out.txt)

**Comment by yakoub** [comment]
attached output of `vendor/bin/drupal --uri="web1.fedora.lan" generate`  
[out.txt](https://github.com/hechoendrupal/drupal-console/files/2176703/out.txt)

**Comment by yakoub** [comment]
how can i debug this issue myself ?

**Comment by yakoub** [comment]
it has been 7 days .

**Comment by yakoub** [comment]
solution :  
instead of `vendor/bin/drupal mod1:c1`  
run `vendor/bin/drupal c1`
without the module namepsace prefix
