### ISSUE TITLE
[site:install] Add a --db-url option

### ISSUE THREAD

**Issue by mondrake** [hechoendrupal/drupal-console#3907]
### Problem/Motivation
With [Testing framework does not work with contributed database drivers](https://www.drupal.org/project/drupal/issues/2605284), in Drupal 8.6.x a new set of methods has been introduced to convert DB URLs back and forth to database connection arrays.

While that's meant for testing, it would be great to enable a --db-url option for site install - the value passed in can be split by Drupal core in the relevant components without needing to pass all the separate --db-user, --db-pass etc. options.

The good thing is that it will be the same URL used to specify the value of the SIMPLETEST_DB variable in testing, so CI tools could unify on a single variable to specify installation and testing.

Example:
```
drupal site:install  standard  \
--langcode="en"  \
--db-url="mysql://u53rn4m3:dbp455@127.0.0.1:3306/drupal8"  \
--site-name="Drupal 8"  \
--site-mail="admin@example.com"  \
--account-name="admin"  \
--account-mail="admin@example.com"  \
--account-pass="p455w0rd"
```

**Comment by harold20** [comment]
Hi @mondrake, We already implement db-url as argument in drupal-console/pull/3917 and https://github.com/hechoendrupal/drupal-console/pull/4051. 

This will be available to the next release.

**Comment by mondrake** [comment]
Great! I was watching that :)

Please see #4048 for an issue, and #4049 for a suggested improvement.

**Comment by mondrake** [comment]
This can be closed now, I guess.
