### ISSUE TITLE
[module:uninstall]  Deprecated each() function 

### ISSUE THREAD

**Issue by jungleran** [hechoendrupal/drupal-console#3908]
### Problem/Motivation

Deprecated function: The each() function is deprecated. This message will be suppressed on further calls in Drupal\Console\Command\Module\UninstallCommand->execute() (line 182 of /var/www/html/vendor/drupal/console/src/Command/Module/UninstallCommand.php)

Releted Drupal core issue: [PHP 7.2] each() function is deprecated, https://www.drupal.org/project/drupal/issues/2885309

### How to reproduce

run `drupal mou MODULE_NAME`

**Details to include:**

- Console version

1.8.0

### Solution

User `foreach`

**Comment by LOBsTerr** [comment]
@jungleran Thank you for your contribution. I have merged your code
