### ISSUE TITLE
[create:nodes] For default Drupal installation created article will have "und" language code

### ISSUE THREAD

**Issue by mtodor** [hechoendrupal/drupal-console#3914]
### Problem/Motivation
When using `create:nodes` command for default Drupal installation to create articles, all created articles have "und" language code. But if article is created over UI it will have "en" language code.

So there is inconsistency there.

### Solution
Instead of using `LanguageInterface::LANGCODE_NOT_SPECIFIED` as fallback, we could use Drupal service and get default language code.

**Comment by LOBsTerr** [comment]
@mtodor I have merged your code
