### ISSUE TITLE
config:import:single - Issue with Config Split

### ISSUE THREAD

**Issue by kenorb** [hechoendrupal/drupal-console#3916]
### An error occurred while trying to write the config file

> [ERROR] An error occurred while trying to write the config file: "commands.config.import.messages.import-fail

### Problem/Motivation

Can't import `core.extension.yml` due to error as described.

I think the lay with [Config Split](https://www.drupal.org/project/config_split). The missing configuration is in `config/environments/development/` (such as `devel.settings.yml`), but not in `config/sync`.

**Details to include:**

```
web# drupal config:import:single --file=$PWD/../config/sync/core.extension.yml
// OR:
web# drupal config:import:single --directory=$PWD/../config/sync --file=core.extension.yml

                                                                                                                        
 [ERROR] An error occurred while trying to write the config file: "commands.config.import.messages.import-fail          
         Configuration <em class="placeholder">devel.settings</em> depends on the <em class="placeholder">Devel</em>    
         module that will not be installed after import.                                                                
         Configuration <em class="placeholder">rg</em> depends on the <em                           
         class="placeholder">Devel</em> module that will not be installed after import.                                 
         Configuration <em class="placeholder">webprofiler.config</em> depends on the <em class="placeholder">Web       
         Profiler</em> module that will not be installed after import."                                                 
                                                                                                                        
```

### How to reproduce

- Drupal version: 8.5.5
- Console version: 1.8.0
- Console Launcher version: 1.8.0
- Steps to reproduce: as above.

### Solution

Drupal Console only allows one path/folder to specify. So I'm not sure how it should support _Config Split_ when part of the configuration can be outside of `config/sync` dir.

**Details to include:**
- No `devel.settings`, `devel.toolbar.settings` or `webprofiler.config` files present in `config/sync` dir, however `devel.settings.yml` and `devel.toolbar.settings` appear in `config/environments/development`.
- Related bug: https://www.drupal.org/project/config_split/issues/2986601

**Comment by gilbertomangones** [comment]
Hi, I tried to reproduce the same error applying the next commands and Config Split module installed:
```drupal config:import:single --file=$PWD/config/sync/core.extension.yml```
and 
```drupal config:import:single --directory=$PWD/config/sync --file=core.extension.yml```
Display
[OK] La configuración "core.extension" ha sido importada con éxito.

Using
Drupal Console version 1.9.3
Drupal version   : 8.7.7

Images
![2019-09-25_1333](https://user-images.githubusercontent.com/6983125/65629518-1bbef300-df99-11e9-9b2f-b3c628ad2811.png)
![2019-09-25_1334](https://user-images.githubusercontent.com/6983125/65629519-1bbef300-df99-11e9-9af7-990cfa38be1d.png)

**Comment by enzolutions** [comment]
Thanks @gilbertomangones for the test
