### ISSUE TITLE
[ `console` ] Replace usages of `EntityTypeRepository` with `EntityTypeRepositoryInterface`

### ISSUE THREAD

**Issue by aronbeal** [hechoendrupal/drupal-console#3919]
### Problem/Motivation
A few classes rely on the injection of an `EntityTypeRepository` class, rather than `EntityTypeRepositoryInterface`, which precludes the replacement of these classes with 
Symfony decoration.

**Details to include:**
Need to generalize the passed objects to be interfaces rather than base class 
instances for the following classes:

- `\Drupal\Console\Command\Generate\PluginConditionCommand::__construct()`
- `\Drupal\Console\Command\Entity\DeleteCommand::__construct()`
- `\Drupal\Console\Command\Debug\EntityCommand::__construct()`

### How to reproduce
N/A

**Details to include:**
- Drupal version: 8.5.5
- Console version: 1.8.0 
- Drupal Console Launcher 1.8.0

### Solution

[drupal-console-constructor-fix.patch.txt](https://github.com/hechoendrupal/drupal-console/files/2229056/drupal-console-constructor-fix.patch.txt)

See attached patchfile:

- Replaces relevant usages with interface equivalents.

**Comment by aronbeal** [comment]
Note: we are specifically running into this issue because we are doing something similar to what is being done in https://www.drupal.org/project/entity_type_class.  It is the [Symfony Decorator Pattern](https://symfony.com/doc/current/service_container/service_decoration.html) being applied to `\Drupal\Core\Entity\EntityTypeRepository`, and because we are providing our subclasses rather than the original class, all these drupal console methods that expect the actual named class are breaking.

**Comment by aronbeal** [comment]
PR Introduced: https://github.com/hechoendrupal/drupal-console/pull/3934

**Comment by LOBsTerr** [comment]
@aronbeal I have merged it. Thanks for contribution
