### ISSUE TITLE
[config:export:single] UUID not removed from dependencies with --include-dependencies

### ISSUE THREAD

**Issue by TechN8** [hechoendrupal/drupal-console#3922]
### Problem/Motivation
When using the --include-dependencies and --remove-uuid or --remove-config-hash, the uuids and hashes are not removed from the exported dependencies.

**Details to include:**
- Should remove uuid / config hash from all generated YML files.

### How to reproduce
drupal config:export:single --include-dependencies --remove-uuid --remove-config-hash --name=core.entity_view_display.block_content.basic.default --optional

**Details to include:**
- Drupal version 8.5.6
- Console version 1.8.0
- Console Launcher version 1.8.0

### Solution
Pass options to remove uuid and config hash to ExportTrait::resolveDependencies  from ExportSingleCommand.php:288.

**Comment by LOBsTerr** [comment]
It has been solved already here https://github.com/hechoendrupal/drupal-console/issues/3965
Feel free to reopen it, if you find another cases
