### ISSUE TITLE
[Error] Command "generate:module" is not a valid command name

### ISSUE THREAD

**Issue by userraj** [hechoendrupal/drupal-console#3925]
### Problem/Motivation
When I run `drupal generate:module` or `drupal gm`, I am getting the following error message. I have installed using [Drupal Console using Composer](https://docs.drupalconsole.com/en/getting/composer.html) and found that even after following the steps to reproduce, when I run `drupal list`, I am not seeing all the commands. 

### Error message
> [Error] Command "generate:module" is not a valid command name

### How to reproduce

1. Open the local directory (`path/to/drupal-site`) where Drupal is already installed.
2. Run `composer require drupal/console:~1.0 --prefer-dist --optimize-autoloader`
3. Run `composer update drupal/console --with-dependencies`
4. Change to `drupal-site/vendor/bin/` directory or `drupal-site/vendor/drupal/console/bin`
5. Run `drupal generate:module`
6. Observe the error message that command is not a valid command name. 

**Details to include:**
- Drupal version `8.5.5`.
- Console version `1.8.0`.
- Windows `10`
- Composer version `1.6.3`

**composer show|grep drupal/console output**

```
$ composer show|grep drupal/console
drupal/console                        1.8.0              The Drupal CLI. A tool to generate boilerplate code, inte...
drupal/console-core                   1.8.0              Drupal Console Core
drupal/console-en                     1.8.0              Drupal Console English Language
drupal/console-extend-plugin          0.9.2              Drupal Console Extend Plugin
```

### drupal list output
```
Available commands:
  about                          Displays basic information about Drupal Console project
  chain                          Chain command execution
  check                          System requirement checker
  exec                           Execute an external command.
  help                           Displays help for a command
  init                           Copy configuration files.
  list                           Lists all available commands
  server (serve,rs)              Runs PHP built-in web server
 build
  build:install                  Build site by installing and importing configuration
 create
  create:data                    Create dummy data
 debug
  debug:chain (dch)              List available chain files.
  debug:dotenv                   Debug Dotenv debug values.
  debug:settings (dse)           List user Drupal Console settings.
  debug:site (dsi)               List all known local and remote sites.
 develop
  develop:contribute             Download Drupal + Drupal Console to contribute.
 docker
  docker:init                    Create a docker-compose.yml file
 dotenv
  dotenv:init                    Add support and required config to work with an .env file
 generate
  generate:example:form          Generate form example
  generate:example:module        Generate example module
  generate:site:alias (gsa)      Generates a site alias.
 multisite
  multisite:new (mun,sn)         Sets up the files for a new multisite install.
  multisite:update (muu)         Update the files for a multisite installed.
 quick
  quick:start                    Download, install and serve a new Drupal project
 settings
  settings:set                   Change a specific setting value in DrupalConsole config file
 site
  site:install (si)              Install a Drupal project
  site:install:env               Install site using environment placeholders
  site:install:inline            Install site using inline placeholders
  site:install:sqlite            Install site using sqlite
  site:new                       Download a new Drupal project
  site:update                    Execute update commands
 update
  update:command:data            Update gitbook
  update:gitbook                 Update gitbook
```

**Comment by yaazkal** [comment]
@userraj are you using Acquia Dev Desktop? Because in my case it seems that the issue is that despite the `databases[]` array si defined in a special file from DevDesktop, for some reason (maybe permissions) is not taked into account, so simply copy/pasting the array configuration into your settings.php file will do the trick.

Hope it helps.

**Comment by userraj** [comment]
@yaazkal Yes we are using `Acquia Dev Desktop`. In regards to the `settings.php` file, we are using a `settings.local.php` file which has the changes you mentioned. However, we ended up finding out the core issue with our situation. 

We had the following folder structure and found the issue to be a duplicate `composer.json` and `composer.lock` files. See below for recommended fix. 

### Current issue
/path/to/site/dev
- config/
- docroot/
- vendor/
- composer.json
- composer.lock
- docroot/composer.json
- docroot/composer.lock

### Proposed fix (after deleting docroot/composer.json and docroot/composer.lock)
/path/to/site/dev
- config/
- docroot/
- vendor/
- composer.json
- composer.lock
