### ISSUE TITLE
[ERROR] array_flip() error messages

### ISSUE THREAD

**Issue by sgortaisNC** [hechoendrupal/drupal-console#3927]
### [ERROR] array_flip() error messages

[ERROR] <em class="placeholder">Warning</em>: array_flip(): Can only flip STRING and INTEGER values! in <em
         class="placeholder">Drupal\Console\Core\Style\DrupalStyle-&gt;choiceNoList()</em> (line <em
         class="placeholder">62</em>

### How to reproduce
- Drupal 8.5.6
- Console 1.8.0
- PHP 7.0

**And then :**
drupal gpb

**Comment by novia713** [comment]
duped or, at least, related https://github.com/hechoendrupal/drupal-console/issues/3860

**Comment by LOBsTerr** [comment]
I'm closing this one as a duplication
