### ISSUE TITLE
user:create Can't skip user role, forced to choose administrator

### ISSUE THREAD

**Issue by wturrell** [hechoendrupal/drupal-console#3928]
### Problem/Motivation
When running user:create to add an account, you can, conveniently, leave lots of fields empty, but skipping "User roles"  apparently doesn't work - a blank answer "is invalid" and you're forced to choose 0 (administrator) before continuing (and, as you'd expect, the account you create ends up as an administrator when you didn't wish it to be).

### How to reproduce

```
wt@wt-macmini ~/Sites/devdesktop/drupalcore86 (8.6.x) $ drupal user:create

 // Welcome to the Drupal user create

 User name to be created:
 > alice

 User password (empty to auto-generate) []:
 >

 User roles (empty to skip):
  [0] Administrator
 >


 [ERROR] Value "" is invalid


 User roles (empty to skip):
  [0] Administrator
 >


 [ERROR] Value "" is invalid


 User roles (empty to skip):
  [0] Administrator
 >


 [ERROR] Value "" is invalid


 User roles (empty to skip):
  [0] Administrator
 > 0

 User e-mail (empty to skip) []:
 >

 User status (empty to skip) [1]:
  [0] 0
  [1] 1
 >
```

- Drupal version 8.6.x dev branch, commit 12737b3ce92c64c665d373b44d6a316d933f3f46
- Console version 1.8.0
- Console Launcher version 1.8.0.
- PHP: tested with both 7.1.12 and 7.1.21

**Comment by LOBsTerr** [comment]
Thank you for reporting the issue.
PR - https://github.com/hechoendrupal/drupal-console/pull/3946

Changed this for users generation command and also for user creation command

**Comment by LOBsTerr** [comment]
Merged
