### ISSUE TITLE
[site:install] Distinguish between an empty db prefix and no db prefix

### ISSUE THREAD

**Issue by jensschulze** [hechoendrupal/drupal-console#3930]
### Distinguish between an empty db prefix and no db prefix

[site:install] Atm you have to use `--no-interaction` if you want to pass an empty db prefix. If you type `--db-prefix=""` the result is the same as if you had just simply omitted this option.

### Problem/Motivation
If the value of an option is explicitly set it should not be asked for later. You can suppress this inconsistent behaviour with `--no-interaction` but one should not need 
I am running into this issue whenever I'm trying to set up a "throw away" installation.

### How to reproduce
Last checked on Drupal 8.6.1 with drupal/console 1.8.0

```bash
composer create-project drupal-composer/drupal-project:8.x-dev somedirectory --stability dev --no-interaction

cd somedirectory

vendor/bin/drupal si standard \
    --langcode="en" \
    --db-type="sqlite" \
    --db-file="sites/default/files/drupaldb.sqlite " \
    --db-prefix="" \
    --account-name=admin \
    --account-pass=admin \
    --account-mail=admin@example.com \
    --site-name="This is just a test" \
    --site-mail="admin@example.com"
```

Even though the `--db-prefix` is set, the command will ask for the prefix (the default value is an empty string).

### Solution
If no `--db-prefix` is given, the option's default value is _null_. So in Site\InstallCommand::interact() we can easily distinguish between "no `--db-prefix` given" (ask) and "empty `--db-prefix` given" (no action).

**Comment by LOBsTerr** [comment]
@jensschulze Thanks I have merged it
