### ISSUE TITLE
[database:restore] Command fails if database password contains special characters

### ISSUE THREAD

**Issue by guedressel** [hechoendrupal/drupal-console#3937]
To restore a database dump the original database clients are used in a sub-command: Either `mysql` or `psql` gets executed via `ProcessBuilder::run`:
https://github.com/hechoendrupal/drupal-console/blob/master/src/Command/Database/RestoreCommand.php#L85-L104

But the arguments for the commands are not quoted! Therefore the interpretation of the arguments is left solely for the sub-command environment (which might often be `bash`). This results in failures if special characters are used which influence the environment (in our case it's a `&` symbol in the password).

**Comment by guedressel** [comment]
`database:dump` actually does use quotes:
https://github.com/hechoendrupal/drupal-console/blob/master/src/Command/Database/DumpCommand.php#L98-L118

Proposed solution: copy the database command part from DumpCommand.

**Comment by LOBsTerr** [comment]
I have fixed it already in this task. Can you please verify it? Let me know if you find some other case
https://github.com/hechoendrupal/drupal-console/issues/3888

I'm closing this task
