### ISSUE TITLE
[update:entities] does not respect current state of maintenance mode

### ISSUE THREAD

**Issue by mdlutz24** [hechoendrupal/drupal-console#3943]
### Problem/Motivation
The update:entities command is part of a number of commands used as part of a normal production deployment process. Often it is desirable to place the site into maintenance mode prior to executing this chain of commands and leave it there until the chain is complete and the site integrity is verified. The update:entities command takes the site out of maintenance mode after it completes running regardless of whether the site was in maintenance mode when it was executed.

### How to reproduce
Place a site into maintenance mode, and execute "update:entities". Verify that the site is no longer in maintenance mode.

### Solution
The update:execute command saves the maintenance mode state prior to executing and restores it after.  It is desirable for the update:entities command to replicate this behavior.

**Comment by GuidoRobertone** [comment]
Nice one! I added a PR to resolve this [PR-3947](https://github.com/hechoendrupal/drupal-console/pull/3947/commits/711c6b977ceede3cc73ff7a786cf1a87d2a68b3b)

**Comment by LOBsTerr** [comment]
PR - https://github.com/hechoendrupal/drupal-console/pull/3963
This is a correct way to enable maintenance mode during the command execution

**Comment by GuidoRobertone** [comment]
> PR - #3963
> This is a correct way to enable maintenance mode during the command execution

Nice one! Sorry I didn't have time to send an update.

**Comment by LOBsTerr** [comment]
Merged
