### ISSUE TITLE
[database:restore] Sucess with no such file or directory detected.

### ISSUE THREAD

**Issue by GuidoRobertone** [hechoendrupal/drupal-console#3948]
### Problem/Motivation
When you are passing a path with an incorrect file or directory the output command show you successfully message.

### How to reproduce
`drupal database:restore --file=database.sql`
Where database.sql doesn't exist. 
A warning message appear: `cat: database.sql: No such file or directory`
but with a succesfully message:  `[OK] Database imported from: database.sql`                                                                              

**Details to include:**
- Drupal version : 8.5.6
- Console version : 1.8.0
- Console Launcher version : 1.8.0
![screenshot_2018-10-12_00-18-08](https://user-images.githubusercontent.com/2628259/46846144-e71c5080-cdb4-11e8-8a56-a32c4d89954b.png)

### Solution
An error message should appear with a not found file or directory warning.

**Comment by LOBsTerr** [comment]
Thank you for the report. I have added the check which will give more user friendly error

PR https://github.com/hechoendrupal/drupal-console/pull/3953

**Comment by GuidoRobertone** [comment]
> Thank you for the report. I have added the check which will give more user friendly error
> 
> PR #3953

Nice one! Sorry I didn't have time to send an update.

**Comment by LOBsTerr** [comment]
Merged
