### ISSUE TITLE
[generate:plugin:skeleton] Errors out after filling in interactive details when Interface is missing method documentation

### ISSUE THREAD

**Issue by dasginganinja** [hechoendrupal/drupal-console#3949]
### Problem/Motivation
When attempting to use the generate:plugin:skeleton command it errors out after each attempt to create my custom plugin type. It is expected that the script will generate changes within a module and that does not happen.

### How to reproduce
I generated a module using `drupal generate:module`. I then enabled the module. I then use `drupal generate:plugin:type:annotation` to generate a module named xyz_purge. In that method I also generated a service and a plugin manager. I then added a method to the plugin interface.

I then generated another module using `drupal generate:module` called xyz_purge_defplugin. I enabled that module and then ran `drush cr && drush cr`. After that I attempted to generate the plugin using `drupal generate:plugin:skeleton`. It found my xyz_purge module, the plugin type that was created, and it found the service defined by it, xyz_purge.default. When attempting to generate the files with the yes option this is the error I received:

````
In skeleton.php.twig line 95:
                                                                             
  Key "description" for array with keys "name, declaration" does not exist.  
                                                                             
````

**Details to include:**
- Drupal version - 8.6.1          
- Console version - 
drupal/console                             1.8.0              The Drupal CLI. A tool to generate boilerplate code, interact with and debug Drupal.
drupal/console-core                        1.8.0              Drupal Console Core
drupal/console-en                          1.8.0              Drupal Console English Language
drupal/console-extend-plugin               0.9.2              Drupal Console Extend Plugin
- Console Launcher version - 1.8.0

### Solution
I don't have a proposed fix for this, but [skeleton.php.twig on line 95](https://github.com/hechoendrupal/drupal-console/blob/912508f5465962877659480198802c43231e1057/templates/module/src/Plugin/skeleton.php.twig#L95) it is looking for the description key in the array.
This is populated by [PluginSkeletonCommand.php](https://github.com/hechoendrupal/drupal-console/blob/master/src/Command/Generate/PluginSkeletonCommand.php#L307) and is guarded by a check to see if there is a comment.

For this example it didn't set that key in the method data and that is why Twig is erring out.

In this situation it was helpful that it erred out, as I was able to get into the code and see what it was expecting.  At the same time since it would have been helpful to either be alerted that there weren't any method docs. Optionally, the default value for the description field could be set so that twig doesn't error out or the twig template could have a guard around it.  I just wanted to open discussion on this since I ran into the issue and was stumped for a little bit on it.

Thanks!

**Comment by LOBsTerr** [comment]
PR https://github.com/hechoendrupal/drupal-console/pull/3952

Thank you for the report. I have just removed unused variable.

**Comment by LOBsTerr** [comment]
It has been merged
