### ISSUE TITLE
[generate:entity:content] suggests a machine name too long to save

### ISSUE THREAD

**Issue by Eli-TW** [hechoendrupal/drupal-console#3954]
### Problem/Motivation
The generate:entity command can suggest an entity type ID too long to save. If this is accepted, the code generated by Drupal Console will error when the containing module is enabled.

Drupal Console shouldn't suggest IDs to the user that can be trivially predicted to fail.
Drupal Console shouldn't accept IDs from the user that can be trivially predicted to fail.

### How to reproduce
- Drupal version 8.6.x (commit fd4638ac0c1a45c570df779c1a250220a4f52ed5)
- Console version 1.8.0
- Console Launcher version 1.8.0

```
-> % drupal geco

 // Welcome to the Drupal Content Entity generator
 Enter the module name [scheduler]:
 >

 Enter the class of your new content entity [DefaultEntity]:
 > ScheduledPublishingEventEntity

 Enter the machine name of your new content entity [scheduled_publishing_event_entity]:
 >

 Enter the label of your new content entity [Scheduled publishing event entity]:
 > Scheduled publishing event

 Enter the base-path for the content entity routes [/admin/structure]:
 >

 Do you want this (content) entity to have bundles? (yes/no) [no]:
 > no

 Is your entity translatable? (yes/no) [yes]:
 > no

 Is your entity revisionable? (yes/no) [yes]:
 > no

-> % drush en scheduler -y

In EntityType.php line 300:

  Attempt to create an entity type with an ID longer than 32 characters: scheduled_publishing_event_
  entity.
```

### Solution
Trim to 32 characters when suggesting a machine name. Reject if the user submits more.

**Comment by LOBsTerr** [comment]
Drupal Console Core PR - https://github.com/hechoendrupal/drupal-console-core/pull/346
Drupal Console PR - https://github.com/hechoendrupal/drupal-console/pull/3962

I have added trimming and also additional validation when we execute command with interactive mode

**Comment by LOBsTerr** [comment]
Merged
