### ISSUE TITLE
[ generate:entity:content ] Clean up Entity Form Save method

### ISSUE THREAD

**Issue by AaronMcHale** [hechoendrupal/drupal-console#3956]
### Problem/Motivation
The `EntityForm::save` method that is generated could be cleaned up, it uses a case statement which is overkill for what is happening as well as having unnecessary code duplication.

### Solution

Instead of the following:

```php
    switch ($status) {
      case SAVED_NEW:
        drupal_set_message($this->t('Created the %label {{ label }}.', [
          '%label' => $entity->label(),
        ]));
        break;

      default:
        drupal_set_message($this->t('Saved the %label {{ label }}.', [
          '%label' => $entity->label(),
        ]));
    }
```

I propose using:

```php
    $this->messenger()->addMessage($this->t('%action the %label {{ label }}.', [
      '%action' => $status == SAVED_NEW ? 'Created' : 'Saved',
      '%label' => $entity->label(),
    ]));
```

Using the proposed approach makes the code much cleaner and easier for to understand.  The replacement of the case statement makes sense because using it instead of a simple inline if statement in the message parameters is overkill when there are only two possibilities.  It is also unlikely that there will ever be more than two possible messages here.

**Comment by GuidoRobertone** [comment]
Agree, MessengerInterface service should be included to show these messages.

**Comment by LOBsTerr** [comment]
Thanks for reporting it

PR https://github.com/hechoendrupal/drupal-console/pull/3957

**Comment by AaronMcHale** [comment]
Thanks for committing into the PR, I put `ENTITY_TYPE_LABEL` as the placeholder, not knowing exactly what it is, when I should have used `{{ label }}`, I noticed in your commit that it was using my placeholder instead of the actual one so you might want to recommit to fix that.

**Comment by LOBsTerr** [comment]
@AaronMcHale Fixed. yes, you are right. I missed it.

**Comment by LOBsTerr** [comment]
It has been merged
