### ISSUE TITLE
[generate:plugin:block] when this command runs, the annotations gets added right but their use statements are not( in MyModuleBlockPlugin.php), unlike other generate commands

### ISSUE THREAD

**Issue by Nickbahson** [hechoendrupal/drupal-console#3977]

**Comment by LOBsTerr** [comment]
I have just generated the command with default parameters and use statement is there. Can you provide more details what parameters did you use. You can also enable learning mode and provide the whole command
```
<?php

namespace Drupal\my\Plugin\Block;

use Drupal\Core\Block\BlockBase;
use Drupal\Core\Form\FormStateInterface;

```

**Comment by Nickbahson** [comment]
the use statements for the annotations:
`use Drupal\Core\Annotation\Translation;
use Drupal\Core\Block\Annotation\Block;`
for
`/***
 * @Block(
 *  id = "blockId",
 *  admin_label = @Translation("AdminBlockLabel"),
 * )
 */`

**Comment by LOBsTerr** [comment]
@Nickbahson For minimal work of the Block Plugin you actually don't need these use statements 
Please check official documentation https://www.drupal.org/docs/8/creating-custom-modules/create-a-custom-block

Block manager service uses necessary classes to perform annotation lookup. 

If you check other example from the core you we'll see that these annotations are not there.
Please provide more information or error message.

**Comment by Nickbahson** [comment]
I missed that part, I thought it was necessary ..turns out my error was from a different use statement..fixed it by adding all.

**Comment by LOBsTerr** [comment]
Closing it feel free to reopen if you find some other issues
