### ISSUE TITLE
[ database:dump ] The dump command should fail if connection is not resolved

### ISSUE THREAD

**Issue by CaptainQuirk** [hechoendrupal/drupal-console#3978]
### Problem/Motivation

Using the DumpDatabase command from within a [Symfony Process].

**Details to include:**

(https://symfony.com/doc/3.4/components/process.html), I expect the command to fail and return a non-zero code if the connection can not be found.

### How to reproduce

Launch the command with the a database name that is different from the connection information in a site's `settings.php`

**Details to include:**
- Drupal version 8.6.2
- Console version 1.8.0

### Solution

- throw an Exception in `DumpCommand` if `$databaseConnection` is null
- **OR** throw an exception directly in the trait

**Comment by LOBsTerr** [comment]
@CaptainQuirk if you check the code we throw an exception

```
https://github.com/hechoendrupal/drupal-console-core/blob/c897e0493de2a731743d87aab1d728aa0d5bb3f2/src/Utils/ShellProcess.php#L91
```

if I run the command
```
drupal database:dump 123123123213
```

I see error message plus it returns 1 error code

**Comment by CaptainQuirk** [comment]
I issue the following command : 

```
$ drupal --uri="mysite_uri" dbdu 1234 --file="mybackupfile.sql"
```

I get : 

```                                                                                                                       
 [ERROR] Database "1234" connection info wasn't found                                                                                                                                                                                   
 Working directory: /app/web
 Executing command:                                                                                                                         
 [OK] Database exported to: mybackupfile.sql      
 ```

The return code is : 

```
$ echo $? // 0
```

It's not the Shell Process call that causes an issue, it's the code at line `84`. If `$databaseConnection` is `null`, it should throw an `Exception` so that the return code is not 0.

**Comment by LOBsTerr** [comment]
@CaptainQuirk Ok, Thanks for information now I see it

**Comment by LOBsTerr** [comment]
PR https://github.com/hechoendrupal/drupal-console/pull/3979

**Comment by LOBsTerr** [comment]
Merged
