### ISSUE TITLE
[generate:event:subscriber] Generated EventSubscriber class does not honor coding standards

### ISSUE THREAD

**Issue by csegarra** [hechoendrupal/drupal-console#3983]
### Problem/Motivation

The code generated for the EventSubscriber has some errors regarding the Drupal coding standards:

- Expected 1 blank line before function; 2 found before the class constructor.
- Visibility must be declared on method "getSubscribedEvents".
- Doc comment short description must be on a single line, further text should be a separate paragraph on callback functions.
- Missing parameter comment on callback functions.
- Expected type hint "GetResponseEvent"; found "Event" for $event on callback functions.

### How to reproduce

Using Drupal Console 1.8 create a custom module:

```
drupal generate:module \
  --module "CS Test" \
  --machine-name cs_test \
  --module-path modules/custom \
  --description "Code Styling test module" \
  -q
```

And then add an EventSubscriber for some events:

```
drupal generate:event:subscriber \
  --module cs_test
```

### Solution

The EventSubscriber class should be modified to follow the Drupal coding standards.

**Comment by LOBsTerr** [comment]
@csegarra Can you create a PR I will review it? Thank you

**Comment by csegarra** [comment]
Hi @LOBsTerr !

Yesterday I have made the PR #3984 with the changes to the template.

Regards!

**Comment by LOBsTerr** [comment]
@csegarra Thank you for your contribution. I have merged the code.
I'm closing the issue, feel free to reopen it.
