### ISSUE TITLE
[cron:execute] Invalid check for or missing default value

### ISSUE THREAD

**Issue by DrColossos** [hechoendrupal/drupal-console#3987]
### Problem/Motivation
This is a follow up on #3126 and a response to #3951 that creates the use case. 

We are triggering the cron:execute via crontab. We are not using a module name or "all" but are simply calling "cron:execute"

### How to reproduce
On 1.8 simply run cron:execute

### Solution
\Drupal\Console\Command\Cron\ExecuteCommand needs to handle the defaults better OR provide the default via the 4th parameter of  `->addArgument(..., ['all'])`. This makes the null-check of the execute implementation obsolete (it didn't work anyways since the parameter is defined as an array from the arguments definition) and all implementations are picked up.

**Comment by DrColossos** [comment]
A pull reuqust is provided via #3988

**Comment by LOBsTerr** [comment]
@DrColossos Thank you for your contribution. Code was merged
