### ISSUE TITLE
[config:import] Memory leak?

### ISSUE THREAD

**Issue by hyperfocus1337** [hechoendrupal/drupal-console#3992]
### Config import always fails with memory leak

[ *config:import* ]

No matter how much memory I throw at my CI runner, config:import always fails with out of memory errors.

I increased PHP memory_limit to 12GB on a local machine CI runner yet command still fails

### Problem/Motivation
PHP always runs out of memory like this:
![2018-12-07_14-52_1](https://user-images.githubusercontent.com/24568457/49651536-c3316000-fa2f-11e8-8daf-a654cbd7614e.png)

### How to reproduce

- Create a clean Drupal 8.6.3 installation and export the configuration with ````drupal config:export````
- Run ````drupal config:import --directory=/var/www/html/config/sync/default --no-interaction````
- Command fails with above PHP memory issue on Drupal 8.6.3 clean config

**Versions**
- Drupal 8.6.3
- Console 1.8.0
- Drupal Console Launcher 1.8.0

### Solution
No clue how to fix.

**Comment by gilbertomangones** [comment]
Hi, I tried replay the error and the error is not generated.
Using
![2019-09-18_1725](https://user-images.githubusercontent.com/6983125/65273497-e15fdc80-dae6-11e9-85d4-7b0d08cdbc27.png)

![2019-09-19_1408](https://user-images.githubusercontent.com/6983125/65273577-0eac8a80-dae7-11e9-9abe-18725a440d6c.png)

Thank's
