### ISSUE TITLE
How do I install drupal console?

### ISSUE THREAD

**Issue by pentool** [hechoendrupal/drupal-console#4002]
Sorry, yes, I did read the docs.

I got stuck right after following the instruction on this page:
https://docs.drupalconsole.com/en/getting/launcher.html

After I did the curl command, went to terminal and typed `drupal`. I get `command not found`.

What am I missing? Thanks.

macOS Mojave 10.14.3
Drupal 8.x

**Comment by pingers** [comment]
`echo $PATH`
If you don't see `/usr/local/bin` in your path, then running `drupal` will not work... because the command cannot be found. I'm sure it should be there by default, but worth checking.
This article shows how to add paths to your path on OSX.
https://www.architectryan.com/2012/10/02/add-to-the-path-on-mac-os-x-mountain-lion/

**Comment by pentool** [comment]
Yes, the path is there. I have these in my $PATH:
```
/usr/local/bin
/usr/bin
/bin
/usr/sbin
/sbin
```

**Comment by pentool** [comment]
Ok. Got it working. Not sure what was the issue. I removed the original install, and did it again. Now it worked.

**Comment by pentool** [comment]
Now that I can execute `drupal` at the terminal, I was wondering why many of the commands are not available? I installed drupal manually (by downloading it from drupal), and I use mamp.

The drupal site is installed at `~/Sites/drupal`.
I installed drupal console globally and wanted to clear the site cache. So I typed `drupal cr all` in the terminal to which I got `"cr" is not a valid command name"`

So I tried adding the root: `drupal cr all --root=~/Sites/drupal` but I got the same error that a "cr" is not a valid command name.

What am I still missing? Thanks.

**Comment by jacksinn** [comment]
In case you still need an answer to this - if you install (require) drupal (console) as a dependency with Composer in the site docroot then after it installs you should see all of the options.

```
composer require drupal/console:~1.0 \
--prefer-dist \
--optimize-autoloader
```
