### ISSUE TITLE
[site:install] Incorrect error message when database can't be accessed

### ISSUE THREAD

**Issue by ericmorand** [hechoendrupal/drupal-console#4004]
When the database informations don't allow to access the database, the command `site:install` returns the following error:

>  [ERROR] Drupal is already installed, try dropping your database executing database:drop or install executing site:install --force --no-interaction      

To reproduce the issue, set an invalid user, database or password in the default database configuration and execute `vendor/bin/drupal site:install --force --no-interaction`.

The error message should explain that the database couldn't be accessed.

**Comment by enzolutions** [comment]
@ericmorand Solved with https://github.com/hechoendrupal/drupal-console/pull/4024 will be included in next release 1.9.0
