### ISSUE TITLE
[config:export:media:type] Export Media Type configuration

### ISSUE THREAD

**Issue by anuragshah17** [hechoendrupal/drupal-console#4007]
### Problem/Motivation
A brief statement describing why the issue was filed.
Wanted to export all the Media types configuration in custom module for multisite feature.

**Details to include:**
- Why are we doing this?
Helps in exporting media type configuration

### How to reproduce
Include steps related how to reproduce.

**Details to include:**
- Drupal version - 8.6.10
- Console version - 1.8.0
- Console Launcher version (you can obtain this by running outside of a drupal site `drupal --version`). - 
- Steps to reproduce
- Include screen-shot or video whenever necessary.

**Comment by LOBsTerr** [comment]
@anuragshah17 you can use dev version and the command 
```
drupal cee
```

or 

```
drupal config:export:entity
```
