### ISSUE TITLE
[console] Error when 'default' multisite is not set up

### ISSUE THREAD

**Issue by joachim-n** [hechoendrupal/drupal-console#4008]
### Problem/Motivation

I have a multisite installation in which the 'default' site isn't set up.

Even if I run a command against a specified site, I still get this error:

> [ERROR] The specified database connection is not defined: default

**Comment by GuidoRobertone** [comment]
Hi @joachim-n

I'm working on this issue trying to reproduce it locally, without lucky.

I created 2 multisite in my current project, then I removed the default directory. I can execute any drupal console command against any multisite. I 'm using specific uri (--uri) option but the default site broke up.

https://docs.drupalconsole.com/en/using/how-to-use-drupal-console-in-a-multisite-installation.html

I have to specific questions for you:
1. What is the way that you execute any command?
2. Why do you remove the default instance? and the way that you did it. 

With this information, I will try to reproduce and solve to include in the next Drupal Console release

Thank you
