### ISSUE TITLE
[database:dump] exclude cache data from dump file

### ISSUE THREAD

**Issue by MurzNN** [hechoendrupal/drupal-console#4010]
For minimize dump file size will be good to have an option to exclude cache data from it, so dumping only structure for all cache tables.

**Comment by enzolutions** [comment]
Hi @MurzNN 

Thanks for reporting this new feature.

This feature was implemented in PRs https://github.com/hechoendrupal/drupal-console/pull/4019  and https://github.com/hechoendrupal/drupal-console-en/pull/220 and will be included in this week release version 1.9.0
