### ISSUE TITLE
PHP Fatal error:  require()

### ISSUE THREAD

**Issue by knows1** [hechoendrupal/drupal-console#4014]
PHP Fatal error:  require(): Failed opening required 'drupal.php' (include_path='.:/usr/sh
are/php') in phar:///usr/local/bin/drupal/bin/drupal on line 3

**Comment by enzolutions** [comment]
Hi @knows1,

Thanks for reporting this issue.

I cannot reproduce this error, could you double check if this is still an issue, and provide a little more information about your environment.

**Comment by knows1** [comment]
Thanks :+1: enzolutions
Distributor ID:Ubuntu
Description:Ubuntu 16.04.6 LTS
Release:16.04
Codename:xenial
************************
7.3.4 FastCGI application
**********************************
Apache Web Server
-access_compat
-autoindex
-cgi
-cgid
-negotiation
-socache_shmcb
-userdir
-authn_core
-authz_core
-dir
-include
-rewrite
-setenvif
-bw
-filter
-status
-headers
-auth_basic
-suexec
-deflate
****************************
Plesk Onyx
Version 17.8.11
************************

**Comment by enzolutions** [comment]
@knows1  Did you tried with the latest version of Drupal, all commands of Drupal Console are failing?

**Comment by knows1** [comment]
Thank you, work on
Ubuntu 16.04.6 LTS
PRETTY_NAME="Debian GNU/Linux 9


$ curl https://drupalconsole.com/installer -L -o drupal.phar

$ composer require drupal/console:~1.0 --prefer-dist --optimize-autoloader


$ php drupal.phar
Drupal Console version 1.8.0

$ sudo mv drupal.phar /usr/local/bin/drupal

$ sudo chmod +x /usr/local/bin/drupal

$ drupal init

 Select destination to copy configuration:
  [0] /home/google/.console/
  [1] /var/www/example.com/html/drupal/console/
 > 1
