### ISSUE TITLE
generate:plugin:block throws errors on completion

### ISSUE THREAD

**Issue by jaydee18** [hechoendrupal/drupal-console#4016]
Drupal Version 8.6.14
Drupal Console version 1.8.0
Drupal Console Launcher 1.8.0
Database Version MySQL 8.0.1-dmr
PHP 7.2.15

I am trying to create a block in my custom module that includes a form. After running "drupal generate:plugin:block", using the following options: region not defined, load services from container: no, generate a form structure: yes (create from elements), proceed with operation: yes.

This does generate block plugin code in my module; however the code it outputs includes a malformed method in the class that extends BlockBase:

<pre>
public function defaultConfiguration() {
    return [
                                                      'response' => 0,
                                                                                        ] + parent::defaultConfiguration();
  }
</pre>

and this error is output repeatedly (perhaps for each form field):

[ERROR] <em class="placeholder">Warning</em>: array_flip(): Can only flip STRING and INTEGER values! in <em            
         class="placeholder">Drupal\Console\Core\Style\DrupalStyle-&gt;choiceNoList()</em> (line <em                    
         class="placeholder">62</em> of <em                                                                             
         class="placeholder">/path/to/site/drupal/vendor/drupal/console-core/src/Style/DrupalStyle.php< 
         /em>). <pre class="backtrace">Drupal\Console\Core\Style\DrupalStyle-&gt;choiceNoList(&#039;Enter the theme     
         region to render the Plugin Block.&#039;, Array, &#039;&#039;, 1) (Line: 273)                                  
         Drupal\Console\Command\Generate\PluginBlockCommand-&gt;interact(Object, Object) (Line: 240)                    
         Symfony\Component\Console\Command\Command-&gt;run(Object, Object) (Line: 978)                                  
         Symfony\Component\Console\Application-&gt;doRunCommand(Object, Object, Object) (Line: 255)                     
         Symfony\Component\Console\Application-&gt;doRun(Object, Object) (Line: 185)                                    
         Drupal\Console\Core\Application-&gt;doRun(Object, Object) (Line: 64)                                           
         Drupal\Console\Application-&gt;doRun(Object, Object) (Line: 148)                                               
         Symfony\Component\Console\Application-&gt;run() (Line: 89)                                                     
         require(&#039;/path/to/site/drupal/vendor/drupal/console/bin/drupal.php&#039;) (Line: 4)       
         </pre> 

Followed by this error twice:

[ERROR] <em class="placeholder">Warning</em>: call_user_func_array() expects parameter 1 to be a valid callback,       
         class 'SplFileInfo' does not have a method 'serialize' in <em                                                  
         class="placeholder">Drupal\Core\Extension\Extension-&gt;__call()</em> (line <em class="placeholder">160</em>   
         of <em class="placeholder">core/lib/Drupal/Core/Extension/Extension.php</em>). <pre                            
         class="backtrace">Drupal\Core\Extension\Extension-&gt;__call(&#039;serialize&#039;, Array) (Line: 314)         
         Drupal\Console\Extension\Manager-&gt;createExtension(Object) (Line: 251)                                       
         Drupal\Console\Extension\Manager-&gt;getModule(&#039;support_central_feedback&#039;) (Line: 353)               
         Drupal\Console\Extension\Manager-&gt;getPluginPath(&#039;support_central_feedback&#039;, &#039;Block&#039;)    
         (Line: 74)                                                                                                     
         Drupal\Console\Generator\PluginBlockGenerator-&gt;generate(Array) (Line: 206)                                  
         Drupal\Console\Command\Generate\PluginBlockCommand-&gt;execute(Object, Object) (Line: 255)                     
         Symfony\Component\Console\Command\Command-&gt;run(Object, Object) (Line: 978)                                  
         Symfony\Component\Console\Application-&gt;doRunCommand(Object, Object, Object) (Line: 255)                     
         Symfony\Component\Console\Application-&gt;doRun(Object, Object) (Line: 185)                                    
         Drupal\Console\Core\Application-&gt;doRun(Object, Object) (Line: 64)                                           
         Drupal\Console\Application-&gt;doRun(Object, Object) (Line: 148)                                               
         Symfony\Component\Console\Application-&gt;run() (Line: 89)                                                     
         require(&#039;/path/to/site/drupal/vendor/drupal/console/bin/drupal.php&#039;) (Line: 4)       
         </pre>

**Comment by LOBsTerr** [comment]
@jaydee18 It has been fixed https://github.com/hechoendrupal/drupal-console/issues/3860
I'm closing it.
