### ISSUE TITLE
update:execute: drupal updb does not perform updates

### ISSUE THREAD

**Issue by driskell** [hechoendrupal/drupal-console#4020]
### Problem/Motivation

After performing a drupal core update, running drupal updb reports no updates are available. We've been having to do this manually with update.php. We have now realised drush actually works.

```
$ drupal updb


 [WARNING] There aren't updates available


```

However, using drush, it works:

```
$ drush updb
 -------- ------------------- ------------- -----------------------------
  Module   Update ID           Type          Description
 -------- ------------------- ------------- -----------------------------
  system   fix_jquery_extend   post-update   Clear the library cache and
                                             ensure aggregate files are
                                             regenerated.
 -------- ------------------- ------------- -----------------------------


 Do you wish to run the specified pending updates? (yes/no) [yes]:
```

This specific example is the 8.6.14 to 8.6.15 update.

### How to reproduce
Install 8.6.14, update to 8.6.15, run drupal updb, no updates. Run drush updb, updates are available.

### Solution
Compare with drush updb

**Comment by danjdewhurst** [comment]
I can confirm I've have the same issue.

**Comment by lalop** [comment]
is there a way of accepting any update ? `-y` for exemple

**Comment by enzolutions** [comment]
@lalop could you create a new issue for that request to avoid losing track, due this issue is already closed

**Comment by lalop** [comment]
@enzolutions sure https://github.com/hechoendrupal/drupal-console/issues/4108
