### ISSUE TITLE
[config:export:view] option include-module-dependencies not working correctly

### ISSUE THREAD

**Issue by stefan-korn** [hechoendrupal/drupal-console#4021]
### Problem/Motivation
Running [config:export:view] with option [include-module-dependencies] set to yes does not work as expected.

What would be expected:
Module dependencies resulting from view will get added to info.yml file

What is actually happening:
info.yml gets overwritten and contains only dependencies resulting from view, everything else is lost from info.yml. This breaks the module effectively.

### How to reproduce
run drupal config:export:view and answer 'Include view module dependencies in module info YAML file" with yes

- Drupal version 8.6.15
- Console version 1.8.0

**Comment by harold20** [comment]
Hi @stefan-korn I made this PR https://github.com/hechoendrupal/drupal-console/pull/4026 that solve this issue

**Comment by enzolutions** [comment]
This change will be included in version 1.9.0
