### ISSUE TITLE
[config:export] IF a directory is set, it is not generated in the root dir

### ISSUE THREAD

**Issue by harold20** [hechoendrupal/drupal-console#4067]
### Problem/Motivation
If a directory is set, it is not generated in the root dir. It is generated where thes modules and themes are located.

### How to reproduce
drupal config:export  --directory=config.test 

**Details to include:**
- Drupal version 8.7.1.
- Console version 1.8.0.
- Console Launcher version 1.8.0.

**Comment by gilbertomangones** [comment]
Hi @harold20 

I added these LOC, generating the ```config:export``` in root Drupal 
https://github.com/hechoendrupal/drupal-console/pull/4150

Thanks
