### ISSUE TITLE
[console] Test statistics in Windows

### ISSUE THREAD

**Issue by enzolutions** [hechoendrupal/drupal-console#4068]
### Test statistics in Windows

We need to test the feature of statistics in Windows after release 1.9.0 to be included in 1.9.1

**Comment by nequeteme** [comment]
Hi @enzolutions, I enable the statistics on Windows 10 and it's working

**Environment:**
- Windows 10
- Cmder (Console emulator for Windows)
- XAMPP Version 7.3.9
- drupal/console 1.9.3

**Steep to enable the statistics:**
` drupal settings:set share.statistics true`
![2019-10-08_205139](https://user-images.githubusercontent.com/250047/66433093-2770d780-e9e5-11e9-8991-8f9a5ec91a81.png)

and I found the folder **.console** on my User Home Directory 
![2019-10-08_205356](https://user-images.githubusercontent.com/250047/66433209-73238100-e9e5-11e9-966a-48d38f0fa0a4.png)

**Comment by enzolutions** [comment]
thank for testing @nequeteme

**Comment by enzolutions** [comment]
Test if the send statistics works

**Comment by nequeteme** [comment]
Hi @enzolutions, the statistics send the data to the server
 
![image](https://user-images.githubusercontent.com/250047/66519153-5a31d300-eaac-11e9-80c3-790d3cd38d6b.png)

**Comment by enzolutions** [comment]
Thanks @nequeteme
