### ISSUE TITLE
Description about what it is

### ISSUE THREAD

**Issue by ugintl** [hechoendrupal/drupal-console#4082]
I trying to understand what is it exactly.

**Comment by enzolutions** [comment]
@ugintl what do you don't understand?

**Comment by ugintl** [comment]
I do not understand how this module can help me with my drupal site

**Comment by enzolutions** [comment]
@ugintl  this is not a module in a CLI application you could find a long description of the project on https://hechoendrupal.gitbooks.io/drupal-console/content/en/about/what-is-the-drupal-console.html

I hope that help you

**Comment by ugintl** [comment]
thanks
