### ISSUE TITLE
Escaping mysqldump breaks passwords

### ISSUE THREAD

**Issue by nvaken** [hechoendrupal/drupal-console#4089]
### Escaping mysqldump breaks passwords

[ *database:dump* ] Passwords with "dangerous" characters like `;` will be escaped into `database:dump`'s logic. This can cause errors on connecting since the password is invalid.

### Problem/Motivation
Not being able to dump a database with a password containing a semicolon (and probably other characters). 

### How to reproduce

- Use any random Drupal installation
- Use a password with a semicolon, eg `;123456`
- Try dumping the database and note that you will get a access denied error and note that the `mysqldump` command contains a `--password="\\;123456"` parameter. 

### Solution
Not really sure, I'm not _that_ familiar with shell escaping and security implications. My first insight would be not escaping the password and simply using single quotes around to password to prevent it from expanding into shell? Not sure though... 

I think this bug is introduced by https://github.com/hechoendrupal/drupal-console/issues/3888

**Comment by enzolutions** [comment]
Thanks for your report @nvaken
