### ISSUE TITLE
Can't install launcher due to redirect [docs]

### ISSUE THREAD

**Issue by lineape** [hechoendrupal/drupal-console#4104]
### Problem/Motivation
The launcher cannot be installed because https://drupalconsole.com/installer is redirecting to https://drupalconsole.com, causing curl and php readfile to download the html of the index page instead of the installer script.

**Details to include:**
The documentation for installing the launcher is here https://docs.drupalconsole.com/en/getting/launcher.html

### How to reproduce
run the command `curl https://drupalconsole.com/installer -L -o drupal.phar` and view the output (will be the html from the index page)

### Solution
Stop the redirect, or offer another way to install the launcher that doesn't require that url.

Or, update the docs if there is a different way to install it.

**Comment by harold20** [comment]
@lineape I just ran the curl line and this is my output
![image](https://user-images.githubusercontent.com/8105777/60284527-fe5e8800-98c8-11e9-8626-ad12b4fefe4a.png)

Everything is fine on my side.

**Comment by lineape** [comment]
Perhaps there is a DNS or a caching issue? 

These are the last few lines of the drupal.phar file that is created by the curl command when I run it:

```

<script id="mcjs">!function(c,h,i,m,p){m=c.createElement(h),p=c.getElementsByTagName(h)[0],m.async=1,m.src=i,p.parentNode.insertBefore(m,p)}(document,"script","https://chimpstatic.com/mcjs-connected/js/users/d0de8649943acda17c918fab2/193ae3988b8720e2de3d444b3.js");</script>
<script type="application/json" data-drupal-selector="drupal-settings-json">{"path":{"baseUrl":"\/","scriptPath":null,"pathPrefix":"","currentPath":"node\/73","currentPathIsAdmin":false,"isFront":true,"currentLanguage":"en"},"pluralDelimiter":"\u0003","data":{"extlink":{"extTarget":true,"extTargetNoOverride":null,"extNofollow":null,"extFollowNoOverride":null,"extClass":"0","extLabel":"(link is external)","extImgClass":false,"extSubdomains":false,"extExclude":"","extInclude":"","extCssExclude":"","extCssExplicit":"","extAlert":false,"extAlertText":"","mailtoClass":"0","mailtoLabel":"(link sends email)"}},"user":{"uid":0,"permissionsHash":"204d545bae38e5d248f4de279bee2d03ba09dadf836d4507bc47b39e573bd2c4"}}</script>
<script src="/sites/default/files/js/js_2Ur2RN6lSwngF5CCrSiu9DcisbBQa1HI_K-3R_EM7T4.js"></script>
<script src="https://maps.googleapis.com/maps/api/js?v=3&amp;sensor=false"></script>
<script src="/sites/default/files/js/js_13sN518uELZufvtl2iVO3IXdJQy2WHlFV84uuWJljWY.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/gist-embed/2.3/gist-embed.min.js" async></script>

</body>
</html>

<!-- END OUTPUT from 'themes/custom/drupalconsole_theme/templates/layout/html.html.twig' -->

```

**Comment by lineape** [comment]
Oh wait, @harold20 did you look at the contents of the drupal.phar file? Looking at the output from your console, the curl command received the same amount of bytes as mine. Does yours also have HTML in it?

**Comment by harold20** [comment]
Yes @lineape Now I get the error.

**Comment by harold20** [comment]
@lineape Could you try again?

**Comment by lineape** [comment]
@harold20 Yup, it's working now.

Was able to install the launcher and tested it on a drupal project.

Thanks!
