### ISSUE TITLE
[update:execute] Adding the ability to accept all updates via a command argument

### ISSUE THREAD

**Issue by lalop** [hechoendrupal/drupal-console#4108]
Since https://github.com/hechoendrupal/drupal-console/pull/4027 we have to explicitly accept updates before they are run.

When using drupal console in non interactive context this isn't possible, so I could be great to add an argument to accept by default all updates.

On most cli application `-y` is used for that.
Maybe this can become an option used more globally, like the verbosity one ?

**Comment by lalop** [comment]
I can work on this kind of feature

**Comment by enzolutions** [comment]
Awesome @lalop would be great to check if we could include in next week release 1.9.1
