### ISSUE TITLE
Error execute drupal console in drupal 8.7.4

### ISSUE THREAD

**Issue by Josemino** [hechoendrupal/drupal-console#4110]
PHP Fatal error:  Trait 'Drupal\Core\DependencyInjection\DeprecatedServicePropertyTrait' not found in /var/www/vhosts/coorporativa.base/httpdocs/web/core/modules/field_ui/src/Routing/FieldUiRouteEnhancer.php on line 16

**Comment by harold20** [comment]
@Josemino  Could provide more information how do you get this error?

DrupalConsole version
DrupalConsole launcher version
Command executed to get this error.

**Comment by Josemino** [comment]
Already solved. I was running the drupal console from another installation. Thank you.
