### ISSUE TITLE
1.9.1 memory leak 

### ISSUE THREAD

**Issue by csandanov** [hechoendrupal/drupal-console#4131]
### Running `drupal` leaks memory with the latest PHP

[ `console` ] 

### Problem/Motivation

Running `drupal` command from the shell hangs, leaks memory

### How to reproduce

1. Run `docker stats` on the host beforehand to see the container memory usage:
2. Pull image `docker pull wodby/drupal:8-7.3` (also happens on PHP 7.2):
3. Run container `docker run --rm -ti wodby/drupal:8-7.3 sh`
4. Run any command, (it will hang).
```shell
$ drupal --debug
Drupal Console Launcher version 1.9.1
Launcher path: /usr/local/bin/drupal
Drupal Console version 1.9.1
Per-Site path: /var/www/html/vendor/drupal/console/bin/drupal

✔ Creating request
✔ Creating Drupal kernel
✔ Registering dynamic services
➤ Rebuilding container
```
5. See `docker stats` to see how memory consumption growth

Drupal version: 8.7.6
PHP version:
```
PHP 7.3.8 (cli) (built: Aug  8 2019 21:37:23) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.8, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.8, Copyright (c) 1999-2018, by Zend Technologies
```

**Comment by AMDS** [comment]
I got the same error with 1.9.1 version.
Drupal 8.7.6
PHP 7.2

I turn off the XDdebug, the issue still remains.

**Comment by csandanov** [comment]
This issue is most likely due to some of the composer dependencies in drupal-composer project because I have an image (`wodby/drupal:8-7.3-4.14.6`) with the same PHP, drupal and drupal console versions and it works just fine. This issue started to happen on Aug 17th.

**Comment by AMDS** [comment]
New version of 1.9.2 is just released and it works for me.

Try 1.9.2

**Comment by enzolutions** [comment]
Thank mate @AMDS for testing
