### ISSUE TITLE
[database:add] add option to add settings to $databases['default']['default']

### ISSUE THREAD

**Issue by Kwadz** [hechoendrupal/drupal-console#4142]
The command `database:add` does not allow to create the first database defined by `$databases['default']['default']`. This can be useful in case a fresh install that you want to connect to an existing database. Currently the command only allows adding database in addition to the default one.

I suggest adding an option like `--default` to add the default database. The current template `add.php.twig` is:

```
$databases['{{ database }}']['default'] = [
  'database' => '{{ database }}',
  'username' => '{{ username }}',
  'password' => '{{ password }}',
  'host' => '{{ host }}',
  'port' => '{{ port }}',
  'driver' => '{{ driver }}',
  'prefix' => '{{ prefix }}',
];
```

I suggest adding `add-default.php.twig`:

```
$databases['default']['default'] = [
  'database' => '{{ database }}',
  'username' => '{{ username }}',
  'password' => '{{ password }}',
  'host' => '{{ host }}',
  'port' => '{{ port }}',
  'driver' => '{{ driver }}',
  'prefix' => '{{ prefix }}',
];
```

This new template would be called instead, when using `--default` option.

What do you think? I'd be pleased to do a pull request.

**Comment by enzolutions** [comment]
Hi @Kwadz I understand your suggestion and I like it, please do the PR the template should be located next to https://github.com/hechoendrupal/drupal-console/blob/master/templates/database/add.php.twig

**Comment by Kwadz** [comment]
@enzolutions, I tried too fork and do a pull request on https://github.com/hechoendrupal/drupal-console-book to upload but I realised this repo is read-only. Would you know how I can update the doc for this new command?

**Comment by enzolutions** [comment]
@Kwadz The docs for commands are generated based in command translations https://github.com/hechoendrupal/drupal-console-en

**Comment by enzolutions** [comment]
BTW last month we migrate the documentation to use [GatsbyJS](https://www.gatsbyjs.org/), so the repository [ https://github.com/hechoendrupal/drupal-console-book]( https://github.com/hechoendrupal/drupal-console-book) was declared **archived**.

In case you are interested in translate something else than commands.
