### ISSUE TITLE
Missing semicolon on generate:entity:content

### ISSUE THREAD

**Issue by mezuny** [hechoendrupal/drupal-console#4146]
Generating entity with generate:entity:content results in missing semicolon.

The issue title should comply with the following structure:

When creating a new module and entity through drupal-console, the entity file created is missing a semicolon on line 8. `use Drupal\Core\Entity\EditorialContentEntityBase`

* `generate:entity:content`

### Problem/Motivation
Problem results in fatal error when using freshly generated module and entity

**Details to include:**
Avoid creating a fatal error upon generating entiy.

### How to reproduce
Include steps related how to reproduce.

**Details to include:**
- Drupal version 8.7.7
- Console version 1.9.2
- Console Launcher version 1.9.2

**Steps to reproduce**
In bash:

1. Generate a entity with drupal generate:entity:content
-Say 'Yes' to any prompt with yes/no prompt
-Use the default value for any other prompt
2. Check entityname.php in module/src/Entity/entityname.php
3. On line 8 the semicolon should be missing. 

### Solution
Adjust the generate:entity:content to include a semicolon on line 8.

> // Welcome to the Drupal module generator
> 
>  Enter the new module name:
>  > social_gamification
> 
>  Enter the module machine name [social_gamification]:
>  > 
> 
>  Enter the module Path [modules/custom]:
>  > 
> 
>  Enter module description [My Awesome Module]:
>  > OpenSocial Gamification module
> 
>  Enter package name [Custom]:
>  > 
> 
>  Enter Drupal Core version [8.x]:
>  > 
> 
>  Do you want to generate a .module file? (yes/no) [yes]:
>  > yes
> 
>  Define module as feature (yes/no) [no]:
>  > no 
> 
>  Do you want to add a composer.json file to your module? (yes/no) [yes]:
>  > yes
> 
>  Would you like to add module dependencies? (yes/no) [no]:
>  > no 
> 
>  Do you want to generate a unit test class? (yes/no) [yes]:
>  > yes
> 
>  Do you want to generate a themeable template? (yes/no) [yes]:
>  > yes
> 
>  Do you want proceed with the operation? (yes/no) [yes]:
>  > 
> 
> 
>  // generate:composer
> Generated or updated files
>  Generation path: /var/www/html
>  1 - /modules/custom/social_gamification/social_gamification.info.yml
>  2 - /modules/custom/social_gamification/social_gamification.module
>  3 - /modules/custom/social_gamification/tests/src/Functional/LoadTest.php
>  4 - /modules/custom/social_gamification/social_gamification.module
>  5 - /modules/custom/social_gamification/templates/social-gamification.html.twig
>  6 - modules/custom/social_gamification/composer.json
> 
>                                                                                                           
>  Generated lines: 100                                                                                     
>                                                                                                           
> 
> root@776e7145b091:/var/www/html# drupal generate:entity:content
> 
>  // Welcome to the Drupal Content Entity generator
>  Enter the module name [activity_basics]:
>  > social_gamification
> 
>  Enter the class of your new content entity [DefaultEntity]:
>  > badge
> 
>  Enter the machine name of your new content entity [badge]:
>  > 
> 
>  Enter the label of your new content entity [Badge]:
>  > 
> 
>  Enter the base-path for the content entity routes [/admin/structure]:
>  > 
> 
>  Do you want this (content) entity to have bundles? (yes/no) [no]:
>  > yes
> 
>  Is your entity translatable? (yes/no) [yes]:
>  > 
> 
>  Is your entity revisionable? (yes/no) [yes]:
>  > 
> 
>  Do you want this (content) entity to have forms? (yes/no) [yes]:
>  > 
> 
>  Do you want this (content) entity to have an owner? (yes/no) [yes]:
>  > 
> 
>                                                                                                           
>  [WARNING] It looks like you have a hook_theme already declared                                           
>                                                                                                           
>            Please manually merge the two hook_theme() implementations in                                  
>                                                                                                           
>            modules/custom/social_gamification/social_gamification.module                                  
>                                                                                                           
> 
> 
>  // generate:entity:config
> 
>  Enter the base-path for the config entity routes [/admin/structure]:
>  > 
> 
> Generated or updated files
>  Generation path: /var/www/html
>  1 - modules/custom/social_gamification/social_gamification.permissions.yml
>  2 - modules/custom/social_gamification/src/badgeAccessControlHandler.php
>  3 - modules/custom/social_gamification/src/badgeTranslationHandler.php
>  4 - modules/custom/social_gamification/src/Entity/badgeInterface.php
>  5 - modules/custom/social_gamification/src/Entity/badge.php
>  6 - modules/custom/social_gamification/src/Entity/badgeViewsData.php
>  7 - modules/custom/social_gamification/src/badgeListBuilder.php
>  8 - modules/custom/social_gamification/src/badgeHtmlRouteProvider.php
>  9 - modules/custom/social_gamification/social_gamification.links.menu.yml
>  10 - modules/custom/social_gamification/social_gamification.links.task.yml
>  11 - modules/custom/social_gamification/social_gamification.links.action.yml
>  12 - modules/custom/social_gamification/src/Form/badgeSettingsForm.php
>  13 - modules/custom/social_gamification/src/Form/badgeForm.php
>  14 - modules/custom/social_gamification/src/Form/badgeDeleteForm.php
>  15 - modules/custom/social_gamification/templates/badge.html.twig
>  16 - modules/custom/social_gamification/badge.page.inc
>  17 - modules/custom/social_gamification/src/Form/badgeRevisionRevertTranslationForm.php
>  18 - modules/custom/social_gamification/src/Form/badgeRevisionDeleteForm.php
>  19 - modules/custom/social_gamification/src/Form/badgeRevisionRevertForm.php
>  20 - modules/custom/social_gamification/src/Controller/badgeController.php
>  21 - modules/custom/social_gamification/src/badgeStorage.php
>  22 - modules/custom/social_gamification/src/badgeStorageInterface.php
>  23 - modules/custom/social_gamification/templates//badge-content-add-list.html.twig
>  24 - modules/custom/social_gamification/social_gamification.module
>  25 - modules/custom/social_gamification/social_gamification.module
>  26 - modules/custom/social_gamification/config/schema/badge_type.schema.yml
>  27 - modules/custom/social_gamification/social_gamification.links.menu.yml
>  28 - modules/custom/social_gamification/social_gamification.links.action.yml
>  29 - modules/custom/social_gamification/src/Entity/badgeTypeInterface.php
>  30 - modules/custom/social_gamification/src/Entity/badgeType.php
>  31 - modules/custom/social_gamification/src/badgeTypeHtmlRouteProvider.php
>  32 - modules/custom/social_gamification/src/Form/badgeTypeForm.php
>  33 - modules/custom/social_gamification/src/Form/badgeTypeDeleteForm.php
>  34 - modules/custom/social_gamification/src/badgeTypeListBuilder.php
> 
>                                                                                                           
>  Generated lines: 2048

**Comment by LOBsTerr** [comment]
I have installed the latest stable version 1.9.3, it generates correctly Entity class. Can you please update your version and try again and let me know, if it is still broken

**Comment by mezuny** [comment]
Just checked, that seems to fix it. I'll close the issue. 
Thanks @LOBsTerr
