### ISSUE TITLE
[generate:cache:context] Typo in CacheContextGenerator 

### ISSUE THREAD

**Issue by manubing** [hechoendrupal/drupal-console#4157]
### [generate:cache:context] Typo in CacheContextGenerator 

Hi,

A typo in CacheContextGenerator prevents the generation of files.

### Problem/Motivation

When running `drupal generate:cache:context`, an `Undefined index: ache_context` warning is displayed and the command fails to complete.  

### How to reproduce

Just run the command and answer the generator questions:

![image](https://user-images.githubusercontent.com/249890/65238531-2252f380-dadd-11e9-9406-695b5ca1a3dd.png)

**Details to include:**
- Console version (1.9.3).
- Console Launcher version (1.9.3)

The following PR fixes the typo:

https://github.com/hechoendrupal/drupal-console/pull/4156

**Comment by LOBsTerr** [comment]
@manubing Thanks for your contribution, it has been merged
