### ISSUE TITLE
Drupal Console documentation has broken url links

### ISSUE THREAD

**Issue by bmartinez287** [hechoendrupal/drupal-console#4171]
Drupal Console documentation has broken URL link

- Every link under the FAQ seems to point to a broken markdown page.
- https://drupalconsole.com/docs/en/drupal_console_faq/faq

**Comment by enzolutions** [comment]
@jmolivas please add this to your queue for your review.

**Comment by jmolivas** [comment]
@bmartinez287 thanks for reporting it. @enzolutions sure I will take a look at this.

**Comment by jmolivas** [comment]
After quick scan of the main repo I found a related issue https://github.com/hechoendrupal/drupalconsole.com/issues/81

**Comment by jmolivas** [comment]
I will leave this open as reference and close as soon as the other issue on the main repo got fixed

**Comment by jmolivas** [comment]
@bmartinez287 new site deployed https://drupalconsole.com/docs/en/drupal_console_faq/faq
