### ISSUE TITLE
[config:export] Path is broken on windows

### ISSUE THREAD

**Issue by sylvainar** [hechoendrupal/drupal-console#4195]
### Problem/Motivation

I can't export my config because of broken path. That's a big issue since `config:export` / `config:import` are two of my most used commands.

```
In Filesystem.php line 104:

  Failed to create "D:\Profiles\myname\PhpstormProjects\myproject/D:\Profiles\myname\PhpstormProjects\myproject/../sync": mkdir(): No such file or directory.
```

### How to reproduce

Install module, then export config.

- OS: Windows 10
- Drupal version: 8.7.10
- Console version: 1.9.4
- Console Launcher version: 1.9.4
- Steps to reproduce: `drupal config:export`

![image](https://user-images.githubusercontent.com/9823286/68857104-654ad500-06e2-11ea-9b27-3dbd1e8a3e67.png)

![image](https://user-images.githubusercontent.com/9823286/68857193-95927380-06e2-11ea-8e96-68fcdc27593a.png)

### Solution

Dunno but it seems related to this issue: https://github.com/hechoendrupal/drupal-console/pull/4154

Quick fix for now has been to rollback to `1.9.2`.

**Comment by timotheemoulin** [comment]
I've looked into it (had the same issue) and fixed it in a small patch.

**Comment by LOBsTerr** [comment]
Thank you for your contribution
