### ISSUE TITLE
[generate:plugin:ckeditorbutton] Spelling error of variable in plugin.php.twig

### ISSUE THREAD

**Issue by ooneill547** [hechoendrupal/drupal-console#4203]
### Problem/Motivation
I was unable to generate the module files to install a CKEditor plugin in Drupal 8 due to a misspelled variable in _'console/templates/module/src/Plugin/CKEditorPlugin/plugin.php.twig'_. 

### How to reproduce
- Drupal version: 8.7.9
- Console version: 1.9.4
- Console Launcher version: 1.9.4

#### Steps to reproduce

- Run `drupal generate:plugin:ckeditorbutton`
- Follow instructions to enter appropriate values when requested. 
- Choose yes to proceed with the operation when prompted. 

An error, 'variable "pligins_id" does not exist' appears: 
![image](https://user-images.githubusercontent.com/52583631/69418234-34862380-0d12-11ea-88d6-4ddcd58d0da2.png)

### Solution
Edit the variable in line 8 of the file _'console/templates/module/src/Plugin/CKEditorPlugin/plugin.php.twig'_ from 
`CKEDITOR.plugins.add('{{ pligins_id }}', {`
to 
`CKEDITOR.plugins.add('{{ plugin_id }}', {`
as seen in #4202 

Rerun `drupal generate:plugin:ckeditorbutton` and the generator should complete successfully.

**Comment by ronaldmulero** [comment]
Thank you @ooneill547 
I had the same issue. Fixing the typo resolved it.

Drupal Console version 1.9.7
Drupal version 8.9.13

**Comment by vrwired** [comment]
thanks for reporting. Still exists.

Drupal Console version 1.9.7
Drupal version 8.9.17

**Comment by LOBsTerr** [comment]
It was fixed here https://github.com/hechoendrupal/drupal-console/pull/4339

Thank you for your contribution
