### ISSUE TITLE
Call to undefined method

### ISSUE THREAD

**Issue by jimrome** [hechoendrupal/drupal-console#4270]
### Issue title

The issue title should comply with the following structure:

[ *ISSUE-GROUP* ] Short description
_drupal site:mode dev -v_ throws fatal error
The *ISSUE-GROUP* should be one of:

* `command:name`
* `console`
* `helper`
* `standard`
* `template`
* `translation`
* `test`
* `docs`

### Problem/Motivation
A brief statement describing why the issue was filed.

**Details to include:**
` // cache:rebuild

 Rebuilding cache(s), wait a moment please.

Fatal error: Uncaught Error: Call to undefined method Drupal\Core\DrupalKernel::prepareLegacyRequest() in /srv/www/htdocs/bcc/vendor/drupal/console/src/Utils/DrupalApi.php:266
Stack trace:
#0 /srv/www/htdocs/bcc/vendor/drupal/console/src/Command/Cache/RebuildCommand.php(104): Drupal\Console\Utils\DrupalApi->drupal_rebuild(Object(Composer\Autoload\ClassLoader), Object(Symfony\Component\HttpFoundation\Request))
#1 /srv/www/htdocs/bcc/vendor/symfony/console/Command/Command.php(255): Drupal\Console\Command\Cache\RebuildCommand->execute(Object(Symfony\Component\Console\Input\ArrayInput), Object(Drupal\Console\Core\Style\DrupalStyle))
#2 /srv/www/htdocs/bcc/vendor/drupal/console-core/src/EventSubscriber/CallCommandListener.php(76): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArrayInput), Object(Drupal\Console\Core\Style\DrupalStyle))
#3 /srv/www/htdocs/bcc/vendor/symfony/event-dispatcher/EventDispatcher.php(264): Drupal\Console\Core\EventSubscriber\CallCommandListener->callCommands(Obje in /srv/www/htdocs/bcc/vendor/drupal/console/src/Utils/DrupalApi.php on line 266`

### How to reproduce
Include steps related how to reproduce.
see above
**Details to include:**
- Drupal version (you can obtain this by running `drupal site:status`).
- Console version (you can obtain this by running `composer show | grep drupal/console`).
- Console Launcher version (you can obtain this by running outside of a drupal site `drupal --version`).
- Steps to reproduce
- Include screen-shot or video whenever necessary.

### Solution
A brief description of the proposed fix.

**Details to include:**
- A short summary of the approach proposed or used in the PR.
- Approaches that have been tried and ruled out.
- Links to relevant API documentation or other resources.
- Known workarounds.

**Comment by tarekdj** [comment]
Had the same issue on Drupal 9. Here is a quick fix #4271
