### ISSUE TITLE
configImport method in ImportCommand and ImportSingleCommand classes fails on Drupal 9

### ISSUE THREAD

**Issue by sarcisal** [hechoendrupal/drupal-console#4303]
### Issue title
The configImport method in ImportCommand and ImportSingleCommand classes fails on Drupal 9

### Problem/Motivation
When configImport is invoked the following error is reported:

`ArgumentCountError: Too few arguments to function Drupal\Core\Config\ConfigImporter::__construct(), 9 passed in /var/www/html/vendor/drupal/console/src/Command/Config/ImportSingleCommand.php on line 149 and exactly 10 expected`

**Details to include:**
This method try to instance a new Drupal\Core\Config\ConfigImporter: 

```
    private function configImport(StorageComparer $storageComparer)
    {
        $configImporter = new ConfigImporter(
            $storageComparer,
            \Drupal::service('event_dispatcher'),
            \Drupal::service('config.manager'),
            \Drupal::lock(),
            \Drupal::service('config.typed'),
            \Drupal::moduleHandler(),
            \Drupal::service('module_installer'),
            \Drupal::service('theme_handler'),
            \Drupal::service('string_translation')
        );

        ...
}
```

**but starting from Drupal 9.0.x are required 10 mandatory parameters:**

`public function __construct(StorageComparerInterface $storage_comparer, EventDispatcherInterface $event_dispatcher, ConfigManagerInterface $config_manager, LockBackendInterface $lock, TypedConfigManagerInterface $typed_config, ModuleHandlerInterface $module_handler, ModuleInstallerInterface $module_installer, ThemeHandlerInterface $theme_handler, TranslationInterface $string_translation, **ModuleExtensionList $extension_list_module**) {`

**before the $extension_list_module parameter wasn't mandatory:**

`  public function __construct(StorageComparerInterface $storage_comparer, EventDispatcherInterface $event_dispatcher, ConfigManagerInterface $config_manager, LockBackendInterface $lock, TypedConfigManagerInterface $typed_config, ModuleHandlerInterface $module_handler, ModuleInstallerInterface $module_installer, ThemeHandlerInterface $theme_handler, TranslationInterface $string_translation, **ModuleExtensionList $extension_list_module = NULL**) {`

**Comment by m4olivei** [comment]
For some added context, the additional argument that is now needed for Drupal 9 was originally added to 8.8.x here https://www.drupal.org/project/drupal/issues/2926068. It was origianlly included with a default value of `NULL`. Since Drupal 9 though, that argument is requried, which was done as part of https://www.drupal.org/i/2926068.
Just adding the parameter should work for all versions of Drupal >= 8. Drupal < 8.8 will just ignore the argument presumably.

**Comment by LOBsTerr** [comment]
Thanks for your contribution
