### ISSUE TITLE
[console] Replace removed function Unicode::strtolower()

### ISSUE THREAD

**Issue by lazysoundsystem** [hechoendrupal/drupal-console#4314]
### Problem
Unicode::strtolower() was deprecated in D8 and isn't available in D9.
https://api.drupal.org/api/drupal/core%21lib%21Drupal%21Component%21Utility%21Unicode.php/function/Unicode%3A%3Astrtolower/8.6.x
https://www.drupal.org/node/2850048

### Solution
PR to come...

**Comment by lazysoundsystem** [comment]
https://github.com/hechoendrupal/drupal-console/pull/4315

**Comment by LOBsTerr** [comment]
Thanks for your contribution
