### ISSUE TITLE
[config:export] Call to undefined function Drupal\Console\Command\Config\config_get_config_directory()

### ISSUE THREAD

**Issue by PierreDeToulis** [hechoendrupal/drupal-console#4320]
With latest version from Drupal and Console, the command config:export return an error :

Drupal version : 9.2.5
Console version : 1.9.7

From documentation : https://api.drupal.org/api/drupal/core%21includes%21bootstrap.inc/function/config_get_config_directory/8.8.x
"Deprecated
in drupal:8.8.0 and is removed from drupal:9.0.0. Use \Drupal\Core\Site\Settings::get('config_sync_directory') instead."

Error: Call to undefined function Drupal\Console\Command\Config\config_get_config_directory() in /var/www/vendor/drupal/console/src/Command/Config/ExportCommand
.php on line 86 #0 /var/www/vendor/symfony/console/Command/Command.php(240): Drupal\Console\Command\Config\ExportCommand->interact(Object(Symfony\Component\Cons
ole\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#1 /var/www/vendor/symfony/console/Application.php(1027): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Obje
ct(Symfony\Component\Console\Output\ConsoleOutput))
#2 /var/www/vendor/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand(Object(Drupal\Console\Command\Config\ExportCommand)
, Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /var/www/vendor/drupal/console-core/src/Application.php(187): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput),
 Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /var/www/vendor/drupal/console/src/Application.php(64): Drupal\Console\Core\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symf
ony\Component\Console\Output\ConsoleOutput))
#5 /var/www/vendor/symfony/console/Application.php(149): Drupal\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Com
ponent\Console\Output\ConsoleOutput))
#6 /var/www/vendor/drupal/console/bin/drupal.php(89): Symfony\Component\Console\Application->run()
#7 /var/www/vendor/drupal/console/bin/drupal(4): require('/var/www/vendor...')
#8 {main}
Error: Call to undefined function Drupal\Console\Command\Config\config_get_config_directory() in Drupal\Console\Command\Config\ExportCommand->interact() (line 8
6 of /var/www/vendor/drupal/console/src/Command/Config/ExportCommand.php).

**Comment by LOBsTerr** [comment]
Should be fixed in 1.9.8
