### ISSUE TITLE
[console] ProcessBuilder is removed in Symfony 4, hence Drupal 9

### ISSUE THREAD

**Issue by yookoala** [hechoendrupal/drupal-console#4330]
### Problem/Motivation

Running `drupal database:client` will run into this error:

> Error: Class "Symfony\Component\Process\ProcessBuilder" not found in Drupal\Console\Command\Database\ClientCommand->execute() (line 66 of /home/foobar/public_html/vendor/drupal/console/src/Command/Database/ClientCommand.php).

This is because the [ProcessBuilder](https://api.drupal.org/api/drupal/vendor%21symfony%21process%21ProcessBuilder.php/class/ProcessBuilder/8.9.x) was deprecated in Symfony 3.4 and was removed in Symfony 4.0. Instead, [Process](https://api.drupal.org/api/drupal/vendor%21symfony%21process%21Process.php/class/Process/8.9.x) should be used directly.

### How to reproduce
1. Install a Drupal 9 site.
2. Install Drupal Console on it.
3. Run `drupal database:client`

### Solution
Replace the `ProcessBuilder` call with `Process`.
Example: https://github.com/pact-foundation/pact-php/pull/61

**Comment by yookoala** [comment]
Affected commands:

- `config:edit`
- `databsae:client`
- `database:query`
- `module:install`
- `server`

**Comment by LOBsTerr** [comment]
Thank you for your contribution. Fixed here https://github.com/hechoendrupal/drupal-console/pull/4335
