### ISSUE TITLE
[generate:form:config] Generate the config/MODULE_NAME.settings.yml file

### ISSUE THREAD

**Issue by rgoodie** [hechoendrupal/drupal-console#518]
(Perhaps a duplicate for or overlap to #171)

Would it be possible to have `generate:form` also build the schema? 

Great presentation at midcamp!

**Comment by esod** [comment]
I've built this and it works, but the test fails. https://github.com/hechoendrupal/DrupalAppConsole/pull/443

**Comment by jmolivas** [comment]
I will take a look to the test o/ during MidCamp

**Comment by esod** [comment]
Thanks. I'm still stuck. Here's the error:

![install-test-error](https://cloud.githubusercontent.com/assets/387576/6782430/8c234ba8-d14a-11e4-9197-9ae009666804.png)

It doesn't matter whether I remove offset 5 (or 4, or 3, or etc). Then the error message just reports undefined at that index (4, or 3 or etc.

**Comment by Sutharsan** [comment]
Creating forms is for me an iterative process. I start with a rough idea (at this point a generator can help), but during the building process, the order of fields changes, the labels change, the description is modified and default values (e.g. select list defaults) are added. If console would generate the initial config/install/ and config/schema files for me, I would probably have to re-do the files.

When I create a form, I make the settings and schema files when the form is (almost) finished. I would help me if console could generate settings and schema based on an existing form. Most of the decisions that make up these files have already been made and laid down in the form array.

So I propose to change the scope to: generate settings and schema files from an existing form definition.

**Comment by jmolivas** [comment]
@Sutharsan like the idea we can actually try both and include what @esod mentioned.

- Add a new command `config:export:form` and generate based on a form definition.
- Chain this new command on `generate:form:config` to generate the schema when the form is generated the first time.

NOTE: the command name `config:export:form` is just an example of the name we can use, feel free to propose a better name.

**Comment by Sutharsan** [comment]
I agree to generate both the config/install and the config/schema file(s). But reading the #443 file changes (... 'table', 'column', 'primary-key' 'hook_schema') this issue is about generating a database table.

**Comment by jmolivas** [comment]
True, how about `config:export:form` only generate the placeholder for default values at `config/install/module_name.settings.yml`
```
module_name:
  field_name: default_value
```
