### ISSUE TITLE
[generate:plugin:block] not allowed to add buttons to the form.

### ISSUE THREAD

**Issue by vacho** [hechoendrupal/drupal-console#551]
This feature is very important to block forms...

**Comment by vacho** [comment]
and I understood a little more. It is generating only form elements to block settings where perhaps no sense buttons. So what is missing to create form elements for graphical interface.

**Comment by jmolivas** [comment]
What will be the benefit of adding the buttons @vacho ?

**Comment by vacho** [comment]
is useful if you need to develop a block to enter information from the user interface.

**Comment by jmolivas** [comment]
so far you can add fields using console we need to add buttons do you like to add this feature @vacho ?

**Comment by vacho** [comment]
Yea

**Comment by jmolivas** [comment]
@vacho do you have a link to the documentation to take as example to add this functionality.

**Comment by Sutharsan** [comment]
The fields that can be adde to the block form are fields in the configuration form. These fields are added to the default configuration form. There are (normally) no buttons added by the plugin blockForm method.

Perhaps you are mistaken with a form placed in the content of the block (e.g. the user login block). Such a form is not coded in a block plugin. Create a form callback and include in the form in the build() method.
