### ISSUE TITLE
[console] Content staging export/import. 

### ISSUE THREAD

**Issue by jmolivas** [hechoendrupal/drupal-console#678]
Investigate best alternative to provide content staging export/import

Similar projects and links for inspiration:
http://wearepropeople.com/blog/a-content-staging-solution-for-drupal-8-and-more 
http://entitypilot.com/

**Comment by LOBsTerr** [comment]
Maybe we can use https://www.drupal.org/project/content_sync

**Comment by jmolivas** [comment]
I was researching about which modules we can use for content synchronization (import/export) and found:

Sync content
https://www.drupal.org/project/content_sync
https://www.drupal.org/project/content_synchronizer
https://www.drupal.org/project/yaml_content
https://www.drupal.org/project/demo_content
https://www.drupal.org/project/default_content
https://www.drupal.org/project/default_content_deploy
https://www.drupal.org/project/entity_share

Sync files:
https://www.drupal.org/project/stage_file_proxy

https://github.com/Ymbra/migrate_default_content

**Comment by enzolutions** [comment]
@LOBsTerr Do you think this is still an issue?

**Comment by enzolutions** [comment]
@jmolivas or @LOBsTerr we can close this issue?

**Comment by LOBsTerr** [comment]
@enzolutions yes, we can close it
