### ISSUE TITLE
[generate:rules:*] Add rules integration 

### ISSUE THREAD

**Issue by jmolivas** [hechoendrupal/drupal-console#704]
### Problem/Motivation

The main goal is this issue is to add commands to generate rules module components:
- [x] generete:rules:condition
- [x] generete:rules:action
- [x] generate:rules:dataprocessor
### Solution

Generate templates based on rules documentation:
http://thefubhy.gitbooks.io/rules/content/extending_rules/rules_action_plugins.html

**Comment by kevinquillen** [comment]
Looks like the generate rules action actually builds an Action plugin, not a RulesAction plugin. It should extend RulesActionBase.

See: http://thefubhy.gitbooks.io/rules/content/extending_rules/rules_action_plugins.html

**Comment by LOBsTerr** [comment]
PR https://github.com/hechoendrupal/drupal-console/pull/3824
PR Translations: https://github.com/hechoendrupal/drupal-console-en/pull/189

**Comment by LOBsTerr** [comment]
PR for generate:plugin:rules:condition https://github.com/hechoendrupal/drupal-console/pull/3827
PR for translation of generate:plugin:rules:condition https://github.com/hechoendrupal/drupal-console-en/pull/191

**Comment by LOBsTerr** [comment]
PR for generate:plugin:rules:dataprocessor https://github.com/hechoendrupal/drupal-console/pull/3828
PR for translation of generate:plugin:rules:dataprocessor https://github.com/hechoendrupal/drupal-console-en/pull/192

**Comment by LOBsTerr** [comment]
It has been merged
