### ISSUE TITLE
Add route_provider to ContentEntity generator

### ISSUE THREAD

**Issue by webflo** [hechoendrupal/drupal-console#705]

**Comment by jmolivas** [comment]
@webflo you may have the documentation page to take as example to add the required code.

**Comment by webflo** [comment]
I was to quick. The patch is not in core yet. https://www.drupal.org/node/2350509

**Comment by darol100** [comment]
The above issue have been split into two issue here is another relate issue - https://www.drupal.org/node/2596095

**Comment by LOBsTerr** [comment]
We have route_provider already for awhile in the Content Entity Generator command. I'm closing this issue
