### ISSUE TITLE
Discover annotation-based plugin types and offer to generate them.

### ISSUE THREAD

**Issue by wizonesolutions** [hechoendrupal/drupal-console#953]
Drupal Console includes some core plugin generation functions, e.g. `generate:plugin:block`.

What would be involved in expanding this to contrib plugins? In my case `generate:plugin:fillpdf_action` for example. Provided that the plugin's annotation class lists all its properties, presumably you could iterate over these and ask what each value should be and then generate a plugin implementation class with the appropriate annotation.

**Comment by jmolivas** [comment]
@wizonesolutions: At this point we have related to plugin generators:
```
Available commands for the "generate:plugin" namespace:
  generate:plugin:block            Generate a plugin block
  generate:plugin:condition        Generate a plugin condition.
  generate:plugin:field            Generate field type, widget and formatter plugins.
  generate:plugin:fieldformatter   Generate field formatter plugin.
  generate:plugin:fieldtype        Generate field type plugin.
  generate:plugin:fieldwidget      Generate field widget plugin.
  generate:plugin:imageeffect      Generate image effect plugin.
  generate:plugin:imageformatter   Generate image formatter plugin.
  generate:plugin:rest:resource    Generate plugin rest resource
  generate:plugin:rulesaction      Generate a plugin rule action
  generate:plugin:type:annotation  Generate a plugin type with annotation discovery
  generate:plugin:type:yaml        Generate a plugin type with Yaml discovery
  generate:plugin:views:field      Generate a custom plugin view field.
```

**Comment by wizonesolutions** [comment]
@jmolivas Yeah, that's for making new "plugin types." But if I want to implement a plugin type, I still have to do that myself if it's a custom one. Vs. for example `generate:plugin:block` or `generate:plugin:views:field` — those generate code that implement existing plugin types, no?

**Comment by enzolutions** [comment]
@jmolivas maybe something like generate:command:plugin ?

**Comment by darol100** [comment]
This is very interesting feature, any new update on this ?

**Comment by enzolutions** [comment]
@wizonesolutions a new command will be include in next release beta3 generate:plugin:skeleton https://github.com/hechoendrupal/DrupalConsole/pull/2432

**Comment by jmolivas** [comment]
Closing this one, since the `generate:plugin:skeleton` is included as part of the project
